### ISSUE TITLE
Autopilot Hardware Options - APM 2.8 supported?

### ISSUE THREAD

**Issue by vergissberlin** [ArduPilot/ardupilot_wiki#1010]
[Autopilot Hardware Options](http://ardupilot.org/copter/docs/common-autopilots.html) 
Please say something about the support for APM 2.8.

Thank you!
André

**Comment by hamishwillee** [comment]
No APM board is supported. The text says 2.6 which was the board at time of last support. I've changed that to 2.x in #1011
