### ISSUE TITLE
Rover: add setup demonstration videos

### ISSUE THREAD

**Issue by jungsoo50** [ArduPilot/ardupilot_wiki#1028]
[Rover Video Demonstrations](http://ardupilot.org/rover/docs/rover-video-demonstrations.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by rmackay9** [comment]
Hmm.. maybe this was a mistake.  I initially renamed it but now I see we already have some videos.

I do hope to add more Rover setup videos in the future but I'll close this issue for now anyway.
