### ISSUE TITLE
Autonomous Landing for a Fixed wing RC plane (like Skywalker)

### ISSUE THREAD

**Issue by dinesh286** [ArduPilot/ardupilot_wiki#1030]
I want to make a fixed wing plane(like skywalker) to do a autonomous landing using own algorithm.  I recently downloaded the arduplane code and compiled in ubuntu 16.04.  I want to know how and where to edit the arduplane code to put my own algorithm.   Is there any other better option to do this .

**Comment by magicrub** [comment]
Looks like you've posted a help question on the wiki Todo list. Closing. Please post help questions on the forum so the proper people can help you out! Http://discuss.ardupilot.org

**Comment by magicrub** [comment]
Please check this page before you make any new posts
http://ardupilot.org/plane/docs/automatic-landing.html

**Comment by peterbarker** [comment]
On Mon, 4 Dec 2017, dinesh286 wrote:

> I want to make a fixed wing plane(like skywalker) to do a autonomous
> landing using own algorithm. I recently downloaded the arduplane code and
> compiled in ubuntu 16.04. I want to know how and where to edit the
> arduplane code to put my own algorithm. Is there any other better option to
> do this .

All of what Tom said, but additionally - use SITL - and perhaps autotest - 
to develop your new algorithm.  That's also on the Wiki :-)

**Comment by dinesh286** [comment]
can u send me the link of wiki

**Comment by magicrub** [comment]
The link was already posted above. This is closed. Please use discuss.ArduPilot.org for help questions.
