### ISSUE TITLE
ESC calibration, alguien sabe donde se guardan los valores de calibración

### ISSUE THREAD

**Issue by max7573** [ArduPilot/ardupilot_wiki#1036]
`[ESC` calibration](http://ardupilot.org/plane/docs/quadplane-esc-calibration.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by hamishwillee** [comment]
This place is for bugs in the docs. Suggest you post on the discussion forums where more people will see them. In English "Where are ESC calibration values ​​are stored?"
