### ISSUE TITLE
Gazebo with SITL - problem Circle mode

### ISSUE THREAD

**Issue by monabf** [ArduPilot/ardupilot_wiki#1047]
Hi all,

I have been simulating a drone in Gazebo using Mavros with SITL and ArduCopter. Most modes work properly, but I have a problem with the Circle mode. From the [ArduCopter documentation](http://ardupilot.org/copter/docs/circle-mode.html), I understand that the nose of the drone should always be pointing towards the center of the circle, which is not the case for me. The drone is circling fine, I have no error messages anywhere, but its nose is always pointing forward instead of towards the center of the circle. I am not overwriting any yaw commands from the autopilot so it looks like this could be a bug in the Gazebo + mavros/SITL setup. [Here](https://gist.github.com/monabf/39ada6784216edc2d39fbf67cc450260) is my small script if you want to take a look. 

If anyone has ever tried using Circle mode with Gazebo I would be happy to know how it went! Any help is greatly appreciated!

**Comment by khancyr** [comment]
Gazebo plugin have largely change. I am closing this.
Please report on https://discuss.ardupilot.org/, if you still get issue with Circle mode, but that probably just a config error and not related to gazebo
