### ISSUE TITLE
Rangefinders (landing page)

### ISSUE THREAD

**Issue by patrick95470** [ArduPilot/ardupilot_wiki#1049]
[Rangefinders (landing page)](http://ardupilot.org/rover/docs/common-rangefinder-landingpage.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.
IT would be nice to have the sweep scanse lidar compatible

**Comment by auturgy** [comment]
I've moved this to here: https://github.com/ArduPilot/ardupilot/issues/7912 as it's a feature request, not an wiki issue.  I'd suggest contacting Scanse as well, as they may be in a better position to provide a driver.
