### ISSUE TITLE
Tilt Rotor Planes

### ISSUE THREAD

**Issue by g7g9g11** [ArduPilot/ardupilot_wiki#1051]
[QuadPlane Frame setup](http://ardupilot.org/plane/docs/quadplane-frame-setup.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by auturgy** [comment]
http://ardupilot.org/plane/docs/guide-tilt-rotor.html
What’s the issue?

Regards,

James

**Comment by auturgy** [comment]
Closing as no issue has been articulated.
