### ISSUE TITLE
Are the walkera D-Bus receivers compatible with the pixhawk either directly or through a ppm encoder

### ISSUE THREAD

**Issue by Deftroadrunner** [ArduPilot/ardupilot_wiki#1052]
[Compatible RC Transmitter and Receiver Systems](http://ardupilot.org/copter/docs/common-pixhawk-and-px4-compatible-rc-transmitter-and-receiver-systems.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by magicrub** [comment]
You've posted a help or HOWTO questions in the wiki docs updater. Please post in the forums at discuss.ardupilot.org
