### ISSUE TITLE
Copter Object Avoidance == please add Control-F option to show RADAR

### ISSUE THREAD

**Issue by patrickpoirier51** [ArduPilot/ardupilot_wiki#1062]
[Copter Object Avoidance](http://ardupilot.org/dev/docs/code-overview-object-avoidance.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

Lots of questions on the ''disapearing'' of the RADAR screen.
There is no information about CTRL-F to  invoque option screen and select the proximity display - RADAR

**Comment by rmackay9** [comment]
yes I totally agree on this one.  I just found out yesterday that the ctrl-f is required.  I'll add it to the wiki.

**Comment by rmackay9** [comment]
I've added some extra info on this at the bottom (changes should appear about 10min from the time I did this post).
