### ISSUE TITLE
FRAME_CLASS  where is it Set

### ISSUE THREAD

**Issue by GGGGGKK** [ArduPilot/ardupilot_wiki#1065]
[Boat Configuration](http://ardupilot.org/rover/docs/boat-configuration.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by rmackay9** [comment]
The FRAME_CLASS parameter can be set from any of the ground stations.  Personally I use the MP's "full parameter tree" screen.  Open MP Config/Tuning >> Planner and set "Layout" to "Advanced".

![mp-frame-class](https://user-images.githubusercontent.com/1498098/35252540-3ae79ab2-0024-11e8-8158-5598f09091c9.png)
