### ISSUE TITLE
Explain ArduPilot firmware architecture with diagrams?

### ISSUE THREAD

**Issue by k4kfh** [ArduPilot/ardupilot_wiki#1067]
As a new user, I'm a little overwhelmed by all the different pieces of a functioning Pixhawk running Ardupilot. Something to explain the different kinds of files (``.px4``, ``.apj``, and any others) and the different pieces of software (such as NuttX) that go into making all of this work would be a huge help.

If someone can explain that to me I will be happy to create some nice looking diagrams layer-cake style, as I think that will make more sense to newbies like myself.

**Comment by k4kfh** [comment]
Whoops...apparently I am just blind. Those seem to answer all my questions. Thank you! Sorry to waste time.

**Comment by rmackay9** [comment]
No troubles, thanks for your interest in ardupilot!
