### ISSUE TITLE
Rover: add list of known working motor drivers

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#1070]
In the Assembly section of the rover wiki, perhaps on the [motor-and-servo connections page ](http://ardupilot.org/rover/docs/rover-motor-and-servo-connections.html) we should add a list of known working motor drivers to allow the DIYers to pick a motor driver that we know works.

**Comment by Hwurzburg** [comment]
anyone have a list? I will add....

**Comment by rmackay9** [comment]
I know that these ones work:

- [RoboClaw 2x7a](https://www.pololu.com/product/3284) ([from this ArduRoller reference page](https://ardupilot.org/rover/docs/reference-frames-arduroller.html))
- [BlueRobotics Basic ESCs](https://bluerobotics.com/store/thrusters/speed-controllers/besc30-r3/) ([from the boogie board boat reference vehicle](https://ardupilot.org/rover/docs/reference-frames-boogieboard-boat.html))

**Comment by Hwurzburg** [comment]
closing
