### ISSUE TITLE
module load droneapi.module.api api start /home/odroid/GitHub/ardupilot-balloon-finder/scripts/balloon_strategy.py

### ISSUE THREAD

**Issue by moonsummer** [ArduPilot/ardupilot_wiki#1077]
[Communicating with ODroid via MAVLink](http://ardupilot.org/dev/docs/odroid-via-mavlink.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by rmackay9** [comment]
Not much info here about what the issue is so closing.
