### ISSUE TITLE
 SITL MAVPROXY and QGroundControl pymavlink srcSystem and srcComponent

### ISSUE THREAD

**Issue by alexx600** [ArduPilot/ardupilot_wiki#1078]
Hello,
Iam a litte bit confused with srcSystem and srcComponent value.
When i start simulation SITL srcSystem id is 1? and rscComponent is 1 also?
What about  MAVProxy that works in the backgroud? this id is also 1?

When i run pymavlink as an external program it's srcSystem is 255 and srcComponent is 0 ?
What about QGroundControl it system is 255, but what is component?

When i want to send Status Text message from pymavlink to MAVProxy should my tragetSystem and target Components be "1"?

I can't find any information about it.

**Comment by khancyr** [comment]
On ardupilot, system are default to 1:1 (system:component)
mavproxy is 1:255
Most GSC are 1:255 by default
On pymavlink connection, you need to set what system and component you are .
