### ISSUE TITLE
PX4FLOW Optical Flow Camera Board Overview == How to load from QGroundControl

### ISSUE THREAD

**Issue by patrickpoirier51** [ArduPilot/ardupilot_wiki#1081]
[PX4FLOW Optical Flow Camera Board Overview](http://ardupilot.org/copter/docs/common-px4flow-overview.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

Please change this:
Warning
QGroundControl currently defaults to an incompatible firmware for PX4Flow. Mission Planner defaults to the correct firmware, and supports setup of the device for Arducopter.

To this:
QGroundControl currently defaults to an incompatible firmware for PX4Flow.  In order to load the correct release, download px4flow-klt-06Dec2014.px4  from the link below and upload it by selecting  **custom firmware file**  on QGC the Firmware Upgrade Menu.

**Comment by rmackay9** [comment]
I've updated the wiki now... if it looks ok, we can close this issue I think.
