### ISSUE TITLE
Copter vs Plane: RTL mode differences

### ISSUE THREAD

**Issue by Naterater** [ArduPilot/ardupilot_wiki#1085]
The copter documentation on RTL is very detailed and good. Plane's RTL mode description is a bit vague, and if I'm not mistaken, the altitudes are handled differently. Plane will RTL and DESCEND to the RTL altitude. 

Items to clarify:
-at what point does the descent to RTL altitude begin?
-what altitude (absolute, relative, etc.) will be used for rally points?
-what loiter radius and direction are used?

**Comment by Hwurzburg** [comment]
#2214
