### ISSUE TITLE
Altitude Hold Mode Issue

### ISSUE THREAD

**Issue by Suntsan** [ArduPilot/ardupilot_wiki#1086]
[Altitude Hold Mode](http://ardupilot.org/copter/docs/altholdmode.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.
I encountered a weird issue when I flight my ArduCopter in Alt Hold Mode. The estimated hight by EKF2 does not correspond with altitude measured by barometer. The following picture shows the odd phenomena. Does anyone come across this problem? 
![alt_hold](https://user-images.githubusercontent.com/22390388/36009211-28f1a40a-0d86-11e8-83f2-6878c1221c89.png)

**Comment by rmackay9** [comment]
My guess is that the barometer is getting interference from the motion of the vehicle.  this is particularly evident when the vehicle is accelerating or decelerating and changes it's lean angle.  At these moments, the pressure over the barometer can change a lot and affect the barometer's reported altitude.  It might be good to try and compare the baro alt with the gps alt to determine if the EKF is correct or not.

The issues list is really not for support issues so I'm going to close this until it's determined to be an enhancement or bug report.
