### ISSUE TITLE
Add OS free F4Light to AutoPilot Hardware Options page

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#1087]
We've got a list of autopilot hardware options here: http://ardupilot.org/copter/docs/common-autopilots.html

.. but we need to add this new addition:
https://discuss.ardupilot.org/t/new-os-free-f4light-hal/25723

**Comment by Hwurzburg** [comment]
closing....this HAL abandoned due to license issues...
