### ISSUE TITLE
cd

### ISSUE THREAD

**Issue by spittma4** [ArduPilot/ardupilot_wiki#1094]

**Comment by rmackay9** [comment]
mistake?  no subject so closing..

**Comment by spittma4** [comment]
Hey Randy,

This was a mistake. I went was reading the thread, tried to alt tab into my virtual machine but it didn’t switch over and I didn’t realize until I mashed a cd enter in there.

Sorry about that. Thanks!

Samuel Pittman
Owner, Argos Dog Gear
Kent State University - Class of 2018
Computer Science Major
Spittma4@kent.edu
336.337.9548
