### ISSUE TITLE
Smart RTL is not listed in the Flight Modes section.

### ISSUE THREAD

**Issue by lordneeko** [ArduPilot/ardupilot_wiki#1099]
Need to add the Smart RTL mode to the Flight Modes section for Rover and Copter

**Comment by peterbarker** [comment]
On Tue, 27 Feb 2018, lordneeko wrote:

> Need to add the Smart RTL mode to the Flight Modes section for Rover and
> Copter

Thanks!  Bit of an oversight.

Do you think you might be able to add something?  You can edit the Wiki 
using the "Edit" button on the top right-hand-side of each page.  This 
creates a Pull Request which can then be approved...

**Comment by lordneeko** [comment]
I would be glad to...but I don't know anything about it! That's why I went
looking for it. :)

**Comment by lordneeko** [comment]
Suppose I could read the code and figure it out

**Comment by peterbarker** [comment]
On Tue, 27 Feb 2018, lordneeko wrote:

> Suppose I could read the code and figure it out

Or fly it and find out for real :-)

If you google a bit you should find the GSoC stuff including videos.

Peter
