### ISSUE TITLE
Mission Planner: Decouple MP/GCS and device setup walkthroughs

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/ardupilot_wiki#11]
There should also be some focus on decoupling the documentation of showing Mission Planner walk throughs on how to configure the device. At best the ardupilot docs should discuss in principal what needs to be configured and the walkthroughs should be a link to numerous GCS pages for the setup walkthrough. This is important as we also have tablet devices that also do the same job as the desktop GCSs.

(BILL B)

**Comment by auturgy** [comment]
This is still a relevant point imho, but it's a lot of work to provide setup guides for every GCS tool.  Thoughts?

**Comment by hamishwillee** [comment]
I agree. When I wrote this I owned this work, and this was a speculative todo list.

**Comment by auturgy** [comment]
MAVproxy has its own docs, as does APMPlanner2.  The QGC docs (https://docs.qgroundcontrol.com/en/SetupView/SetupView.html) cover both PX4 and ArduPilot, so would better linking to the QGC, MAVProxy and APMPlanner2 docs achieve the key outcome?

**Comment by hamishwillee** [comment]
Not sure. I didn't start the work so I didn't do much experimentation.

**Comment by brunoolivieri** [comment]
Would this issue still make sense to stay open?

**Comment by auturgy** [comment]
In my opinion we should make it easier to find instructions for the popular GCS packages, particularly QGC as it is the only actively supported free option for handheld devices at the moment.  I don't think we need to keep this issue open though.
