### ISSUE TITLE
Copter: explain AVOID_DIST_MAX parameter

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#1105]
Our user object avoidance pages don't mention this parameter or any other AVOID_* parameters as far as I can tell.  Really they should be explained along with the different behaviour of avoidance in AltHold vs Loiter.  The best way is probably to create a new "Object Avoidance" page in the "Advanced Configuration" area and then  have the sf40c, terrarange and even regular range finder pages link to this new page.

user wiki pages:

 - http://ardupilot.org/copter/docs/common-lightware-sf40c-objectavoidance.html
 - http://ardupilot.org/copter/docs/common-teraranger-tower-objectavoidance.html

dev wiki page: http://ardupilot.org/dev/docs/code-overview-object-avoidance.html

**Comment by Hwurzburg** [comment]
I think this has been covered now....reopen if there are remaining issues
