### ISSUE TITLE
Communicating with ODroid via MAVLink

### ISSUE THREAD

**Issue by jihadrahmawan** [ArduPilot/ardupilot_wiki#1121]
[Communicating with ODroid via MAVLink](http://ardupilot.org/dev/docs/odroid-via-mavlink.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

hi, i'w trying to mavproxy used in my odroid and it's work. there i'll make the mavproxy is run automaticly after startup of my odroid. i'm follow this step
1. editing ./bashrc file
2. write like : 
![3](https://user-images.githubusercontent.com/23419251/37240584-09535380-2480-11e8-9d71-0c2e594c495c.PNG)
3. and save and exit
4. i'm trying to reboot my odroid, and i'm open terminal and show message like bellow:
![1](https://user-images.githubusercontent.com/23419251/37240597-31f08d4e-2480-11e8-9537-6dfd9b4f1bc5.PNG)
5. i'm write screen-x in terminal and its not work:
![2](https://user-images.githubusercontent.com/23419251/37240599-4ffeddae-2480-11e8-8a65-d75cd1ba2f1d.PNG)

i'm trying manualy write mavproxy.py --master ...... like in .bashrc in my terminal its work, but why it's not work in startup with editing .bashrc in my odroid?
can anyone helping me to reslve that problem?

thanks

**Comment by auturgy** [comment]
Closing.  I hope the OP has resolved this: but it is a help queston that is best asked in discuss.ardupilot.org
If an issue is subsequently found with the wiki instructions, please raise a pull request with the necessary changes, or raise a new issue.
