### ISSUE TITLE
 Mission Planner Compass calibration

### ISSUE THREAD

**Issue by Supervvalrus** [ArduPilot/ardupilot_wiki#1122]
I have a problem with my compass calibration. There is no bad compass health yet it will not calibrate. I have attached a picture of the error i get.
Thanks for your help,
        
![exceptions](https://user-images.githubusercontent.com/37253333/37247291-17df9ac4-2487-11e8-8ca4-82828c2cc234.PNG)
Supervvalrus

**Comment by colmer** [comment]
The same error at windows 10

**Comment by rmackay9** [comment]
This is really a mission planner issue rather than a wiki documentation issue so I'll close this.  If this problem is still going on, could you report it in the [MP issues list](https://github.com/ArduPilot/MissionPlanner/issues)?

**Comment by rmackay9** [comment]
This is really a mission planner issue rather than a wiki documentation issue so I'll close this.  If this problem is still going on, could you report it in the [MP issues list](https://github.com/ArduPilot/MissionPlanner/issues)?
