### ISSUE TITLE
Program "g++" not found in PATH	

### ISSUE THREAD

**Issue by 1466207310** [ArduPilot/ardupilot_wiki#1126]
[Editing/Building with Eclipse on Windows](http://ardupilot.org/dev/docs/editing-the-code-with-eclipse.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by rmackay9** [comment]
This is not really the place to raise issues so I will close this.  This is the to-do list to improve the wiki.

I guess you've already seen [this wiki page](http://ardupilot.org/dev/docs/building-setup-windows.html#building-setup-windows) and have installed the pixhawk toolchain.
