### ISSUE TITLE
Beeper SoundByte downloads missing

### ISSUE THREAD

**Issue by Naterater** [ArduPilot/ardupilot_wiki#1129]
http://ardupilot.org/copter/docs/common-sounds-pixhawkpx4.html - all of the links on the page are to a site that cannot be reached.

**Comment by hamishwillee** [comment]
@jpkh These are hosted on http://download.ardupilot.org/downloads/wiki/pixhawk_sound_files/ and used to work. Is that server still live?

**Comment by Naterater** [comment]
Got the tones. Not sure when it was fixed.
