### ISSUE TITLE
Copter: add flip mode to list of flight modes

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#1132]
It seems out flight modes page is missing flip!
http://ardupilot.org/copter/docs/flight-modes.html

**Comment by lordneeko** [comment]
I'll work this. anyone have some good animations of their quad flipping? animated gifs are fun.

**Comment by lordneeko** [comment]
https://github.com/ArduPilot/ardupilot_wiki/pull/1144

**Comment by auturgy** [comment]
closed via https://github.com/ArduPilot/ardupilot_wiki/pull/1144
