### ISSUE TITLE
Copter: add RPM sensor setup page

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#1135]
Traditional helicopters often use RPM sensors to measure the main rotor speed. We should creat a wiki page which describes how to setup these sensors.

This was raised by @bzucak on Gitter as well.

**Comment by Gone4Dirt** [comment]
I have recently been going through the trials and tribulations of getting my rpm sensor working so am now more familiar with what is going on.  I will take on writing the Wiki.  Not 100% sure on everything so I am going to out a post to the community on the discourse to call for some knowledge share.  I will then compile it all into the wiki.

**Comment by rmackay9** [comment]
@Gone4Dirt, great!

**Comment by Gone4Dirt** [comment]
I have submitted the PR for this page.  It is here:
https://github.com/ArduPilot/ardupilot_wiki/pull/1914

**Comment by Hwurzburg** [comment]
pr merged...closing
