### ISSUE TITLE
ArduPilot Libraries

### ISSUE THREAD

**Issue by naveentrtumkur** [ArduPilot/ardupilot_wiki#1136]
[ArduPilot Libraries](http://ardupilot.org/dev/docs/apmcopter-programming-libraries.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

The hyperlink to Common in ArduPilot Libraries is wrongly pointing to AP_InertialNav https://github.com/ArduPilot/ardupilot/tree/master/libraries/AP_InertialNav

**Comment by magicrub** [comment]
fixed via https://github.com/ArduPilot/ardupilot_wiki/commit/b6a0b55aa86ddc8319c90c9f5b8bc382d24f16a2

thank you!
