### ISSUE TITLE
APSync intro should explain that there are two web configuration pages included

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#1147]
APSync intro: http://ardupilot.org/dev/docs/apsync-intro.html

These two web pages can be accessed to configure APsync:

http://10.0.1.128:8000 <-- video streaming on/off button
http://10.0.1.128 <-- apweb (cut down version of what's in a skyviper)

**Comment by brunoolivieri** [comment]
I did the simple PR #1785 to insert this information in the wiki.  Could this issue be closed?

**Comment by rmackay9** [comment]
yes, closing thanks!
