### ISSUE TITLE
Communicating with Raspberry Pi via MAVLink

### ISSUE THREAD

**Issue by DhruvaBansal00** [ArduPilot/ardupilot_wiki#1154]
[Communicating with Raspberry Pi via MAVLink](http://ardupilot.org/dev/docs/raspberry-pi-via-mavlink.html) - 
I am unable to perform communication between raspberry pi 3 (running Raspbian Jessie) and Pixhawk 2. I keep getting "waiting for heartbeat from /dev/ttyS0"

Thanks.

**Comment by auturgy** [comment]
Please use discuss.ardupilot.org for user support.
Good information on using raspberry pi with ArduPilot is in our wiki here: http://ardupilot.org/dev/docs/raspberry-pi-via-mavlink.html
