### ISSUE TITLE
Rover Detailed Wiring Diagram (Pixhawk)

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/ardupilot_wiki#118]
We have very basic Rover wiring diagrams mostly for the connections [to the autopilot board](http://rover.ardupilot.com/wiki/common-pixhawk-wiring-and-quick-start/#pixhawk_wiring_chart). 

It would be good to have a full diagram, showing all the connections for a typical build, including the controller board essential connections (power, safety switches, receiver) and optional hardware - telemetry, sonar etc etc.

A good example of the sort of thing we'd like is Copter's [Advanced Quadcopter Wiring Chart](http://copter.ardupilot.com/wiki/advanced-pixhawk-quadcopter-wiring-chart/).

This is spawned of #111

**Comment by gmorph** [comment]
I can do this.

**Comment by brunoolivieri** [comment]
I think that is cover by page http://ardupilot.org/rover/docs/rover-motor-and-servo-connections.html

Would this issue still make sense to stay open?

**Comment by rmackay9** [comment]
yes, i think we can close this now, txs
