### ISSUE TITLE
Building ArduPilot for APM2.x on Windows with Arduino

### ISSUE THREAD

**Issue by leminh1** [ArduPilot/ardupilot_wiki#1185]
[Building ArduPilot for APM2.x on Windows with Arduino](http://ardupilot.org/dev/docs/building-ardupilot-with-arduino-windows.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by hamishwillee** [comment]
Closing. Not a defect.
