### ISSUE TITLE
Attopilot 180A Voltage and Current Sensor

### ISSUE THREAD

**Issue by auturgy** [ArduPilot/ardupilot_wiki#1186]
[Attopilot 180A Voltage and Current Sensor](http://ardupilot.org/copter/docs/common-using-a-current-sensor.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

Pages should probably be removed in favour of the Mauch modules.

**Comment by Hwurzburg** [comment]
topic archived...closing
