### ISSUE TITLE
Visually following

### ISSUE THREAD

**Issue by ghdmmbyd** [ArduPilot/ardupilot_wiki#1196]
Does everyone have an open-source visual follow-up plan, and when does the ArduPilot add visual follow-up?

**Comment by rmackay9** [comment]
This isn't really a wiki item so I think I will close this item.

I'm not sure there really is a robust **open source** visual-follow-me feature available.  FlytOS is closed source I think.  I really question whether the dronekit visual-followme works, I don't think I've seen it in action.

As @auturgy suggests, ArduPilot can certainly do the flying part, it is best that it's left to a companion computer to do the vision processing stuff so perhaps that could go into APSync.

**Comment by ghdmmbyd** [comment]
Thinks！ The visual module is definitely using a coprocessor. What I want is a goal-based follow-up control strategy.

**Comment by rmackay9** [comment]
i don't fully understand what "goal based follow-up control strategy" means but perhaps the red-balloon-finder is a decent example of something similar to what you're looking for.  https://github.com/rmackay9/ardupilot-balloon-finder
