### ISSUE TITLE
Build and install Ignition Maths for Gazebo

### ISSUE THREAD

**Issue by mohand150** [ArduPilot/ardupilot_wiki#1198]
hello 
when I execute this code [http://ardupilot.org/dev/docs/using-gazebo-simulator-with-sitl.html#compiling-and-installing-gazebo-from-source](url)
it shows me these errors
![capture du 2018-04-13 11-24-18](https://user-images.githubusercontent.com/34864889/38727959-bd68b29a-3f0e-11e8-93ee-0469cb787ee5.png)

then I can not continue installing gazebo
thanks for any help !

**Comment by auturgy** [comment]
I'm not sure there is an issue with the wiki specifically here, as you're using 14.04, not 16.04 (which the instructions were created to support).
Try swiftgust's build (which also assumes Ubuntu 16.04), or check the Gazebo wiki to see if the dependencies and packages are available for 14.04. Sorry!
If you come up with a way to make things work with 14.04, feel free to make a PR to share what you leanr.

**Comment by khancyr** [comment]
instructions have been updated and cleaned.
