### ISSUE TITLE
installing Gazebo From Source

### ISSUE THREAD

**Issue by mohand150** [ArduPilot/ardupilot_wiki#1200]
Hello,
I tried Gazebo Installation on my new laptop with Ubuntu 14.04 LTS
followed as document here : [http://ardupilot.org/dev/docs/using-gazebo-simulator-with-sitl.html#using-gazebo-simulator-with-sitl](url)
it show me this error 
![capture du 2018-04-13 14-05-31](https://user-images.githubusercontent.com/34864889/38733912-009e154a-3f24-11e8-96ec-eea9f85e3d8a.png)

thaks for any help !

**Comment by auturgy** [comment]
The wiki instructions are for Ubuntu 16.04.
This is related to https://github.com/ArduPilot/ardupilot_wiki/issues/1198 so closing to avoid duplication.

**Comment by peterbarker** [comment]
On Sat, 14 Apr 2018, auturgy wrote:

> The wiki instructions are for Ubuntu 16.04.
> This is related to #1198 so closing to avoid duplication.

With @khancyr's help I've got a couple of branches which provide a Vagrant 
virtual machine for ROS.

I'd put these in the "barely working" state at the moment - but they did 
seem to be working...

This one compiles everything from source - these are basically the 
instructions you've been following:
https://github.com/peterbarker/ardupilot/tree/vagrant-ros

This one does things the easy way - packages are provided for modern 
Ubuntus:

https://github.com/peterbarker/ardupilot/tree/recursion-vagrant-ros

They might provide some hints to your problems.

**Comment by mohand150** [comment]
@peterbarker excuse but I use the version 16.4.4 TLS
![capture du 2018-04-15 11-23-37](https://user-images.githubusercontent.com/34864889/38776952-fbb5baf6-409f-11e8-9046-398c0f8a5037.png)

that's why I can not find the solution to my problem

**Comment by auturgy** [comment]
When you opened the issue, you said you were using 14.04.
I see you’ve edited it now.
Please try what peter has suggested above, or try this: https://github.com/SwiftGust/ardupilot_gazebo/blob/master/README.md
which is also intended for 16.04 (happens to work on my machine (Ubuntu 17.10) to).
