### ISSUE TITLE
EKF Update

### ISSUE THREAD

**Issue by Naterater** [ArduPilot/ardupilot_wiki#1205]
EKF3 is now default, but there's a lot of old information in the EKF overview. Somebody with an in-depth knowledge of EKF should put some updates here, http://ardupilot.org/plane/docs/common-apm-navigation-extended-kalman-filter-overview.html

**Comment by rmackay9** [comment]
EK2 is still the default actually..

**Comment by Naterater** [comment]
Gotcha. But it is default for tailsitter planes. I think a page or at least a section should be dedicated to EKF3 parameters and applications -- why it's better/not in certain scenarios at least.

**Comment by Naterater** [comment]
Will EKF3 ever make it to the limelight?

**Comment by Hwurzburg** [comment]
Its getting closer....closing this, wiki will be updated when it does indeed occur
