### ISSUE TITLE
Copter: ver 3.6 updates

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#1215]
Wiki updates we should do before the official Copter-3.6 release:

- [x] SmartRTL page needs info on what happens when it runs out of points (answer: vehicle can't be switched into SmartRTL).  Also mention SmartRTL can be used for various failsafes.
- [x] battery failsafe update
- [ ] clarify GPS_TYPE must be set specifically to "5" (NMEA) if GPS only provides the NMEA protocol messages
- [x] add dodecahexa copter output to motor mapping
- [ ] how to run per-motor compass mot?  https://discuss.ardupilot.org/t/implementing-per-motor-calibration/30199
- [x] new loiter tuning parameter info should be added to loiter page
- [ ] add info about how compasses are chosen and how to disable some drivers (COMPASS_TYPE_MASK)
- [ ] add info about supporting two external compasses
- [x] flowhold mode page
- [x] follow mode page
- [x] ChibiOS-only OSD. http://ardupilot.org/copter/docs/common-osd-boards-on-screen-display.html
- [x] baro temperature calibration.  aka TCAL_ENABLED.  https://discuss.ardupilot.org/t/tcal-enabled-parameter/34982
- [x] ICE engine integration (https://discuss.ardupilot.org/t/petrol-boosted-tricopter/17823)
- [x] replace references to RC_FEEL_RP with ATC_INPUT_TC on stabilize mode and autotune pages

**Comment by al3xst** [comment]
Also I guess this chapter has to be adapted to ArduCopter: http://ardupilot.org/dev/docs/code-overview-adding-a-new-mavlink-message.html since commands_logic.cpp and control_auto.cpp don't exist. (restructured? content moved?)

**Comment by lordneeko** [comment]
rmackey9, list in the current SmartRTL wiki (linked from the parameters page), I had put parameter references for
SRTL_ACCURACY and SRTL_POINTS, but in AP_SmartRTL.cpp, I see parameters
SMARTRTL_ACCURACY_DEFAULT and SMARTRTL_POINTS_DEFAULT

I don't see the ones listed in the wiki in the code, now in a search. Am I missing something?

**Comment by rmackay9** [comment]
two new items should appear at the bottom of the list:

- [ ] add info about how compasses are chosen and how to disable some drivers (COMPASS_TYPE_MASK)
- [ ] add info about supporting two external compasses

**Comment by rmackay9** [comment]
Moved remaining issues to the Copter-4.0 wiki list: https://github.com/ArduPilot/ardupilot_wiki/issues/2110
