### ISSUE TITLE
Pixhawk Eclipse : fatal Not a git repository 

### ISSUE THREAD

**Issue by emretuncay** [ArduPilot/ardupilot_wiki#1227]
Hello Everyone
I'm working on custom octocopter using pixhawk FC. And Im trying to customize ardupilot code on eclipse px4 toolchain.When I make px4-v2,px4-v2-octo or any make command I receive some fatal like below.
![image](https://user-images.githubusercontent.com/38782255/39419038-6b4db784-4c66-11e8-9884-edbe46d4eebf.png)
Why this fatal occurs and How can I solve this.
Thank you.

**Comment by khancyr** [comment]
Hello, 
Did you clone ArduPilot repo or download the zip archive ? You need to clone the depot ..
This is the documentation section for user support please use http://discuss.ardupilot.org/.
Thanks
