### ISSUE TITLE
Setting up SITL on Windows

### ISSUE THREAD

**Issue by kangxiaojie** [ArduPilot/ardupilot_wiki#1228]
$ make px4-v2
fatal: 有歧义的参数 'HEAD'：未知的版本或路径不存在于工作区中。
使用 '--' 来分隔版本和路径，例如：
'git <命令> [<版本>...] -- [<文件>...]'
/bin/sh: 第 0 行:cd: /home/kang/ardupilot/modules/PX4NuttX/nuttx/: No such file                          or directory
fatal: 不是一个 git 仓库：/home/kang/ardupilot/modules/PX4Firmware/../../.git/mo                         dules/modules/PX4Firmware
// BUILDROOT=/home/kang/ardupilot/Build.ArduCopter HAL_BOARD=HAL_BOARD_PX4 HAL_B                         OARD_SUBTYPE= TOOLCHAIN=NATIVE EXTRAFLAGS=-DGIT_VERSION="HEAD" -I/home/kang/ardu                         pilot/libraries/AP_Common/missing -DMAVLINK_PROTOCOL_VERSION=2 -DNUTTX_GIT_VERSI                         ON="" -DPX4_GIT_VERSION="" -DUAVCAN=1 -D__STDC_FORMAT_MACROS -DHAVE_STD_NULLPTR_                         T=0 -DHAVE_ENDIAN_H=0 -DHAVE_BYTESWAP_H=0 -DHAVE_OCLOEXEC=0 -I/home/kang/ardupil                         ot/Build.ArduCopter/libraries/GCS_MAVLink/include/mavlink -I/home/kang/ardupilot                         /modules/uavcan/libuavcan/include -I/home/kang/ardupilot/modules/uavcan/libuavca                         n/include/dsdlc_generated
Checking modules
modules/mavlink/pymavlink/.git missing - need module init
+ git submodule init
+ for m in $MODULE_LIST
+ '[' -f modules/gbenchmark/.gitmodules ']'
+ for m in $MODULE_LIST
+ '[' -f modules/gtest/.gitmodules ']'
+ for m in $MODULE_LIST
+ '[' -f modules/mavlink/.gitmodules ']'
+ cd modules/mavlink
+ git submodule init
fatal: not a git repository: /home/kang/ardupilot/modules/mavlink/../../.git/mod                         ules/modules/mavlink
+ echo 'init of mavlink failed'
init of mavlink failed
+ git submodule status --recursive
+ exit 1
make: *** [D:/cygwin64/home/kang/ardupilot/mk/modules.mk:22：CHECK_MODULES] 错误                          1

How can i solve this problem? thanks.

**Comment by khancyr** [comment]
on the root of ardupilot directory, do 
git submodule update --init --recursive
