### ISSUE TITLE
Normal/Elevon/VTail Mode 

### ISSUE THREAD

**Issue by Mephios** [ArduPilot/ardupilot_wiki#1244]
I have a problem with selecting the right set-up for delta wings (c1-chaser) HELP! the servo from channel 1 goes upwards, channel 2 is fine. any help? using apm 2.8 and latest version of MP for the 2.8 version. I can't find the old documentation for it :( 
![maxresdefault](https://user-images.githubusercontent.com/38970473/39824990-605a969e-53b9-11e8-9f18-597a90bbc397.jpg)

**Comment by rmackay9** [comment]
support really belongs on the forums I'm afraid so I'll close this issue, sorry!  If we're not strict about this then the issues list just becomes another support forum and we lose track of our to-do list.
