### ISSUE TITLE
A failure of Building ArduPilot for APM2.x on Windows with Arduino

### ISSUE THREAD

**Issue by embracehjx** [ArduPilot/ardupilot_wiki#1245]
I'm trying to compile the source code based on the following tutorial.
[Building ArduPilot for APM2.x on Windows with Arduino]
(http://ardupilot.org/dev/docs/building-ardupilot-with-arduino-windows.html) 
However, the IDE recommended for this tutorial has been unable to open the source code downloaded using git-scm, because the type of code is.cpp, and the IDE can only open.
I'm a novice, I don't know how to solve this problem, I hope someone can help me.
Thanks very much!!

**Comment by rmackay9** [comment]
We don't support the APM boards any more I'm afraid.  It really is best to upgrade to one of the other [supported flight controllers](http://ardupilot.org/copter/docs/common-autopilots.html).  They are quite close in price (sometimes cheaper I think) and far more powerful.
