### ISSUE TITLE
Benewake TFmini lidar

### ISSUE THREAD

**Issue by chris669** [ArduPilot/ardupilot_wiki#1251]
[Benewake TFmini lidar](http://ardupilot.org/copter/docs/common-benewake-tfmini-lidar.html) - Appreciate they started to document this lidar, but the parameters written there are not reliable:
RNGFND_MIN_CM = 5
as this lidar with the actual firmware is **not able to read with accuracy ranges under 50CM**. For example, if you continue reading distances and the drone is approaching from the landing place, the distance indicated by the lidar increase.

Example
Real distance/ Lidar reported distance (CM): 80/80, 70/70, 60/60, 50/50, 40/55, 30/60, 20/70...

Benewake indicates this as a Blind Range, but for them starting at 30cm.

![blindrange](https://user-images.githubusercontent.com/15046400/40127262-435a91b8-592f-11e8-9c32-6bb5a90fc7ae.jpg)

So today this lidar **is not usable for landing, and even could be dangerous**, unless Benewake provides a new firmware to correct this.

OR one solution would be to provide the right values for RNGFND_MIN_CM. For example, what will happen in a landing phase with a Copter if RNGFND_MIN_CM = 50? Will EKF or something give the hand to the Baro? How will this be managed? Maybe a short explanation in the Wiki could also be the solution. Thanks.

**Comment by Hwurzburg** [comment]
Wiki has been changed to 30 for min...closing
