### ISSUE TITLE
Error building Ardupilot on windows with make

### ISSUE THREAD

**Issue by RIUM17** [ArduPilot/ardupilot_wiki#1258]
Hi,

I’m following instructions here http://ardupilot.org/dev/docs/building-px4-with-make.html#building-px4-with-make to build the ardupilot code.
After I entering the “make px4-v2” it end up something like this:

LINK: /d/NaijiaWang/ardupilot-master/ardupilot/modules/PX4Firmware/Build/px4io-v2_default.build/firmware.elf
/bin/sh: -c: line 0: syntax error near unexpected token (' 
/bin/sh: -c: line 0:arm-none-eabi-ld --warn-common --gc-sections -T/d/NaijiaWang/ardupilot-master/ardupilot/modules/PX4Firmware/Build/px4io-v2_default.build/nuttx-export/build/ld.script -L/d/NaijiaWang/ardupilot-master/ardupilot/modules/PX4Firmware/Build/px4io-v2_default.build/nuttx-export/libs -Map /d/NaijiaWang/ardupilot-master/ardupilot/modules/PX4Firmware/Build/px4io-v2_default.build/firmware.elf.map -o /d/NaijiaWang/ardupilot-master/ardupilot/modules/PX4Firmware/Build/px4io-v2_default.build/firmware.elf --start-group /d/NaijiaWang/ardupilot-master/ardupilot/modules/PX4Firmware/Build/px4io-v2_default.
build//d/NaijiaWang/ardupilot-master/ardupilot/modules/PX4Firmware/Build/px4io-v2_default.build/empty.c.o /d/NaijiaWang/ardupilot-master/ardupilot/modules/PX4Firmware/Build/px4io-v2_default.build//d/Naijia
Wang/ardupilot-master/ardupilot/modules/PX4Firmware/src/drivers/boards/px4io-v2/module.pre.o /d/NaijiaWang/ardupilot-master/ardupilot/modules/PX4Firmware/Build/px4io-v2_default.build//d/NaijiaWang/ardupilo
t-master/ardupilot/modules/PX4Firmware/src/drivers/stm32/module.pre.o /d/NaijiaWang/ardupilot-master/ardupilot/modules/PX4Firmware/Build/px4io-v2_default.build//d/NaijiaWang/ardupilot-master/ardupilot/modu
les/PX4Firmware/src/modules/px4iofirmware/module.pre.o /d/NaijiaWang/ardupilot-master/ardupilot/modules/PX4Firmware/Build/px4io-v2_default.build//d/NaijiaWang/ardupilot-master/ardupilot/modules/PX4Firmware
/src/platforms/common/module.pre.o /d/NaijiaWang/ardupilot-master/ardupilot/modules/PX4Firmware/Build/px4io-v2_default.build//d/NaijiaWang/ardupilot-master/ardupilot/modules/PX4Firmware/src/platforms/nuttx
/px4_layer/module.pre.o -lapps -lnuttx d:/program files (x86)/gnu tools arm embedded/4.9 2015q3/bin/…/lib/gcc/arm-none-eabi/4.9.3/…/…/…/…/arm-none-eabi/lib/armv7-m/libm.a d:/program files (x86)/gnu t
ools arm embedded/4.9 2015q3/bin/…/lib/gcc/arm-none-eabi/4.9.3/armv7-m/libgcc.a --end-group’
make[2]: *** [/d/NaijiaWang/ardupilot-master/ardupilot/modules/PX4Firmware/Build/px4io-v2_default.build/firmware.elf] Error 2
make[2]: Leaving directory /d/NaijiaWang/ardupilot-master/ardupilot/modules/PX4Firmware/Build/px4io-v2_default.build' make[1]: *** [/d/NaijiaWang/ardupilot-master/ardupilot/modules/PX4Firmware/Build/px4io-v2_default.build/firmware.px4] Error 2 make[1]: Leaving directory/d/NaijiaWang/ardupilot-master/ardupilot/modules/PX4Firmware’
make: *** [px4-io-v2] Error 2

What might be the problem?

Thanks

**Comment by khancyr** [comment]
Hello,
This is the documentation section for user support please use http://discuss.ardupilot.org/.
Thanks
