### ISSUE TITLE
Couple of comments of"Testing the connection" section

### ISSUE THREAD

**Issue by pzxz** [ArduPilot/ardupilot_wiki#1262]
when i enter the floowing , it doesn’t run properly
param show ARMING_CHECK
param set ARMING_CHECK 0
arm throttle

**Comment by khancyr** [comment]
hello,
What doesn't work ?
This is the documentation section if it is link to some documentation please give us a link where you suspect it is false. Otherwise for use support please use http://discuss.ardupilot.org/.
Thanks

**Comment by Califboy1986** [comment]
In full GPS mode it did a flyway on me and to this day no drone and the company will not do a thing about it

**Comment by khancyr** [comment]
No answer so closing
