### ISSUE TITLE
FlightDeck FrSky Taranis App

### ISSUE THREAD

**Issue by servoman1** [ArduPilot/ardupilot_wiki#1266]
[FlightDeck FrSky Taranis App](http://ardupilot.org/copter/docs/common-frsky-flightdeck.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by servoman1** [comment]
Can't reset flight timer.

**Comment by auturgy** [comment]
The Flightdeck app is a product from Craft&Theory. I’m going to close this as it isn’t an ArduPilot issue, but perhaps @tomlauzon can help.

**Comment by tomlauzon** [comment]
resolved. thanks!
