### ISSUE TITLE
LightWare SF40c for Object Avoidance

### ISSUE THREAD

**Issue by NedClark** [ArduPilot/ardupilot_wiki#1269]
[LightWare SF40c for Object Avoidance](http://ardupilot.org/copter/docs/common-lightware-sf40c-objectavoidance.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by NedClark** [comment]
Does this system now work in Auto?
Is there any work on making this available such that Auto missions can be safer?

**Comment by proficnc** [comment]
Support questions belong in discuss.ardupilot.org

This is just for proven issues.

**Comment by proficnc** [comment]
A fault in the code etc...
