### ISSUE TITLE
Plane - RTL behavior

### ISSUE THREAD

**Issue by JeyPi** [ArduPilot/ardupilot_wiki#1287]
My today's FPV experience:
I took off from a  spot 280 meters AMSL (altitude above mean sea level)
I was remotely landing the plane while in the stabilized mode at an RC field that was a 1000 meters away from me and a bit lower - 240 AMSL.
I was gliding in for landing. All was great. Just before touch down, the plane lost RC link and the RTL mode kicked in. I was no longer in control. The ardupilot software took a right turn towards the Take off position without any climb. Just a turn. That of course was followed by a crush as the plane was so low and the tip of the wing touched the ground. My RTL altitude was set to 100 meters.
I suggest the code should be adjusted to climb the plane to a safe altitude before turning to the home position. I understand this could not suite to all platforms so at least this behavior could be user pick able.
The only data that survived was the camera footage. The flight deck data card was destroyed.
Video of the event here:
https://drive.google.com/open?id=1M_ZMg-GumfTnKhr5usVDDcZS5AaffCR2

As you can see, the only thing needed was a little climb before the turn and plane would had been saved.

**Comment by magicrub** [comment]
This is the behavior that copter does. I've never heard of it being a problem with plane before but I can understand this use case.

**Comment by magicrub** [comment]
I just noticed you posted this on the wiki. This is not a documentation thing, you've posted a feature request. Please repost in github.com/ArduPilot/ArduPilot
