### ISSUE TITLE
Terrain Following

### ISSUE THREAD

**Issue by maaz1113** [ArduPilot/ardupilot_wiki#1290]
Hello everyone.
I am using a Lidar LW20 with Pixhawk cube on my Hexacopter for terrain following. It is working fine, but the problem is that the response is too slow. the copter hovers for a few seconds over the roof top before changing its altitude.I am experiencing a delay of about 2-3 seconds. Can someone help me in solving this problem?
-thanks

**Comment by WickedShell** [comment]
This is a support issue, please take it to https://discuss.ardupilot.org
