### ISSUE TITLE
Opening Ardupilot Source Code in Arduino IDE

### ISSUE THREAD

**Issue by pranavdeep** [ArduPilot/ardupilot_wiki#1293]
I tried all the steps mentioned on the website but I'm not able to see the "Copter" in the sketch folder. I want to build a drone that can autonomously take off and hover at a particular height. It should take off,hover at a particular height for some time and land to base. This should happen without GPS. There is no navigation needed. But the take off and landing should happen autonomously. 
Could anyone please help me?

**Comment by proficnc** [comment]
Ardupilot no longer builds for aurdino 

Please follow the wiki in building for STM32 based boards

If you have questions, please ask on discuss.ardupilot.org, or the Ardupilot.org Facebook page.

This is only for issues

Thanks
