### ISSUE TITLE
Parameter number missing from parameter lists

### ISSUE THREAD

**Issue by sgofferj** [ArduPilot/ardupilot_wiki#1296]
In all parameter lists for the different platforms the numerical representation of the parameter itself is missing, making it very VERY hard to e.g. use MAV_CMD_DO_SET_PARAMETER. The information is also not easily found from the code.

**Comment by sgofferj** [comment]
Learned that parameters are enumerated at boot time, not compile time, so impossible to document.

**Comment by WickedShell** [comment]
Just as a note `MAV_CMD_DO_SET_PARAMETER` is not supported. If you want to set a parameter you must do it by name. You must set parameters with [PARAM_SET](http://mavlink.org/messages/common#PARAM_SET) and they are set by name.
