### ISSUE TITLE
Missing Image for dji-f330-flamewheel page

### ISSUE THREAD

**Issue by huttonsoftware** [ArduPilot/ardupilot_wiki#1324]
I need to upload an image, MOTORS_QuadX.jpg, for an edit I made to dji-f330-flamewheel.html, but I do not have upload rights to the images folder. How do I upload it?

![motors_quadx](https://user-images.githubusercontent.com/35647716/42728883-ef4e6e80-877a-11e8-8b47-42fdb03f0b45.jpg)

**Comment by Hwurzburg** [comment]
archived page...closing
