### ISSUE TITLE
Error cannot find glog !!

### ISSUE THREAD

**Issue by zubair123khan** [ArduPilot/ardupilot_wiki#1344]
Hello guys

I am trying to compile my workspace using instruction https://github.com/wilselby/ROS_quadrotor_simulator and its giving me error "**Project 'rotors_control' tried to find library 'glog'.  The library is neither a target nor built/installed properly**".
Although in this tutorial it said that this glog will not interrupt catkin_make. 

Any suggestions !
Thanks

**Comment by auturgy** [comment]
This isn’t related to the ArduPilot wiki.
Our instructions for setting up ROS are here: http://ardupilot.org/dev/docs/ros.html
Give them a go.
