### ISSUE TITLE
Typo in documentation of LAND_DS_V_DWN parameter

### ISSUE THREAD

**Issue by Kelly-Foster** [ArduPilot/ardupilot_wiki#1346]
Typo:  LAND_DS_V_DWN: Deepstall **veloicty** down

**Comment by WickedShell** [comment]
Thanks, I've pushed a fix into https://github.com/ArduPilot/ardupilot/pull/9000

**Comment by WickedShell** [comment]
And merged, docs will auto rebuild shortly.
