### ISSUE TITLE
mavesp8266 wiki should mention WiFi password is "ardupilot"

### ISSUE THREAD

**Issue by Kelly-Foster** [ArduPilot/ardupilot_wiki#1356]
Followed the wiki instructions for flashing on Windows with NodeMcu tool, and all that went well.  Upon reboot of the esp8266 board, the "ArduPilot" WAP appears, but it requires a security key.  @tridge was kind enough to respond on gitter that key is "ardupilot".  I think that should be added to the wiki.

Kelly

EDIT:  just noticed the wiki describes WAP name as possibly "ardupilot".  Note that WAP name (currently on mine) came up "ArduPilot", password "ardupilot".   E.g., title case WAP, lower case password.

**Comment by Hwurzburg** [comment]
fixed
