### ISSUE TITLE
typo in RC_OPTIONS description

### ISSUE THREAD

**Issue by Kelly-Foster** [ArduPilot/ardupilot_wiki#1365]
typo in "Ignore RC Reciever"
i before e, except after c

**Comment by khancyr** [comment]
hello,
could you point out in which page or the code ? 
Or, if you want you should have a button :  Edit on GitHub, that will allow you to submit directly a modification !

**Comment by WickedShell** [comment]
@khancyr It's param docs, soo it can't be edited on the wiki. I'm afraid I have to fess up to this being my bad spelling (again).

**Comment by khancyr** [comment]
that what I feared ... 
That is here : https://github.com/ArduPilot/ardupilot/blob/master/libraries/RC_Channel/RC_Channels_VarInfo.h#L89
@Kelly-Foster want to correct it ?

**Comment by hamishwillee** [comment]
> i before e, except after c

Apparently they've stopped teaching that in schools in Victoria, Australia now. Too many exceptions!

**Comment by auturgy** [comment]
Unacceptable!

**Comment by khancyr** [comment]
close with https://github.com/ArduPilot/ardupilot/pull/10334
