### ISSUE TITLE
Advanced MultiCopter Design - needs serious update

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/ardupilot_wiki#1368]
[Advanced MultiCopter Design](http://ardupilot.org/copter/docs/advanced-multicopter-design.html) - this references a whole bunch of vehicles and components that are no longer available (not surprising - updates are from around 2013)

@rmackay9 I'm not attempting to fix this because I don't know enough. Can you pull in the right people to help?

Known broken links and redirects are:

(line  291) broken    http://www.rctigermotor.com/html/2013/Efficiency-Type_1219/176.html - [Errno 104] Connection reset by peer
(line  145) broken    http://curtisyoungblood.com/V2/products/quadcopters/stingray-500 - HTTP Error 404: Not Found
(line  332) broken    http://www.rctigermotor.com/html/2013/Professional_0912/52.html - [Errno 104] Connection reset by peer
(line   81) broken    http://www.estesrockets.com/helis-quads/quadcopters/004606-proto-x - HTTP Error 404: Not Found
(line  380) broken    http://www.rctigermotor.com/html/2013/Navigator_0910/36.html - HTTP Error 404: Not Found
(line  172) redirect  http://www.ecalc.ch/xcoptercalc.php?ecalc&lang=en - permanently to https://www.ecalc.ch/xcoptercalc.php?ecalc&lang=en
(line  456) redirect  http://www.ebay.com/itm/like/231128616387?lpid=82 - permanently to https://www.ebay.com/itm/231128616387?lpid=82
(line  396) broken    http://www.rctigermotor.com/html/2013/Professional_0912/49.html - [Errno 104] Connection reset by peer
(line  685) broken    http://www.acpsales.com/Carbon-Fiber.html - HTTP Error 404: Not Found
(line  682) redirect  http://www.rockwestcomposites.com/ - with Found to https://www.rockwestcomposites.com/
(line  686) redirect  http://multimedia.3m.com/mws/mediawebserver?6666660Zjcf6lVs6EVs666GGfCOrrrrQ- - permanently to http://multimedia.3m.com/mws/media/153955O/3mtm-scotch-weldtm-epoxy-adhesive-2216-b-a.pdf
(line  689) redirect  http://www.amazon.com/Loctite-9340%C3%A2-Hysol-Adhesive-Temperature/dp/B000WXL1YE/ref=sr_1_1?s=industrial&ie=UTF8&qid=1392508821&sr=1-1&keywords=loctite+9340 - permanently to https://www.amazon.com/Loctite-9340%C3%A2-Hysol-Adhesive-Temperature/dp/B000WXL1YE/ref=sr_1_1?s=industrial&ie=UTF8&qid=1392508821&sr=1-1&keywords=loctite+9340
(line  709) broken    http://www.hoverthings.com/fliparmblack - HTTP Error 404: Not Found
(line  686) redirect  http://www.amazon.com/3M-Scotch-Weld-Epoxy-Adhesive-EC-2216/dp/B000WXL090/ref=sr_1_2?ie=UTF8&qid=1392508104&sr=8-2&keywords=3m+2216 - permanently to https://www.amazon.com/3M-Scotch-Weld-Epoxy-Adhesive-EC-2216/dp/B000WXL090/ref=sr_1_2?ie=UTF8&qid=1392508104&sr=8-2&keywords=3m+2216
(line  740) redirect  http://makezine.com/projects/wavecopter-a-waterproof-quadcopter/ - permanently to https://makezine.com/projects/wavecopter-a-waterproof-quadcopter/
(line  888) redirect  http://diydrones.com/forum/topics/build-your-own-copter-part-iii?xg_source=activity - permanently to https://diydrones.com/forum/topics/build-your-own-copter-part-iii?xg_source=activity
(line  897) redirect  http://diydrones.com/group/arducopterusergroup/forum/topics/building-copters-with-round-tubes-stronger-lighter-easier-to - permanently to https://diydrones.com/forum/topics/building-copters-with-round-tubes-stronger-lighter-easier-to?groupUrl=arducopterusergroup&
(line  898) redirect  http://diydrones.com/forum/topics/build-your-own-copter-part-ii - permanently to https://diydrones.com/forum/topics/build-your-own-copter-part-ii
(line  899) redirect  http://diydrones.com/forum/topics/build-your-own-copter-part-iii - permanently to https://diydrones.com/forum/topics/build-your-own-copter-part-iii
(line  875) redirect  http://www.ecalc.ch/xcoptercalc.php?ecalc - permanently to https://www.ecalc.ch/xcoptercalc.php?ecalc
(line  902) redirect  http://diydrones.com/profiles/blogs/octocopter-scratch-build - permanently to https://diydrones.com/profiles/blogs/octocopter-scratch-build
(line  900) redirect  http://diydrones.com/forum/topics/build-your-own-copter-part-iv - permanently to https://diydrones.com/forum/topics/build-your-own-copter-part-iv

**Comment by Hwurzburg** [comment]
topic archived...closing issue
