### ISSUE TITLE
Elevon Planes, mixing_gain mixing_offset 

### ISSUE THREAD

**Issue by Saxin** [ArduPilot/ardupilot_wiki#1384]
[Elevon Planes](http://ardupilot.org/plane/docs/guide-elevon-plane.html#mixing-gain),

Background: Typically a proper throws setup for flying wings calls for different amount of throw for elevator  / ailerons inputs, usually the authority needed for elevator is much more than needed for ailerons due to massive difference in distance of surfaces vs. COG on roll vs. pitch axis.

This mixing_gain parameter and associated formulas don't guide how to achieve this, it will help to see example and range of this parameter. On top of this I wasn't able to achieve different throws with only this parameter, I needed also to use mixing_offset parameter which isn't mentioned in the wiki.

It can be found in full parameters list - http://ardupilot.org/plane/docs/parameters.html#mixing-offset-mixing-offset, it's even described that it should be used along with mixing_gain - but again it's not clear how to do it correctly and systematically.

**Comment by Hwurzburg** [comment]
this has been updated...please feel free to point out anything that still needs work....closing
