### ISSUE TITLE
Connecting with SkyRocket SkyViper using a Wifi access point.

### ISSUE THREAD

**Issue by SubMishMar** [ArduPilot/ardupilot_wiki#1414]
I am trying to use the wifi in station mode as mentioned in the last part of this page: http://ardupilot.org/dev/docs/skyviper.html

I have followed the given instructions and put the required WIFI.TXT file in the SD card onboard my skyviper drone. And also connected my desktop to the access point. How can I now connect to skyviper? What exactly is the fcu_url that I must pass to mavros to connect to the drone? And what address will open the html interface to check the status of the drone?

**Comment by khancyr** [comment]
User question should be asked on https://discuss.ardupilot.org/
