### ISSUE TITLE
OpenPilot Revolution and RevoMini

### ISSUE THREAD

**Issue by MFlghts** [ArduPilot/ardupilot_wiki#1418]
[OpenPilot Revolution and RevoMini](http://ardupilot.org/plane/docs/common-openpilot-revo-mini.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

Please add BATT_VOLT_PIN and BATT_CURR_PIN numbers to set up for Revo!

**Comment by auturgy** [comment]
Closed by https://github.com/ArduPilot/ardupilot_wiki/pull/1424
Thanks for raising and fixing this!
