### ISSUE TITLE
Add Here+ GNSS Compass orientation issue to the documentation

### ISSUE THREAD

**Issue by splenkingforth** [ArduPilot/ardupilot_wiki#1433]
For Here+ GPS produced after OCT 2017 the compass orientation has to be set to pitch180yaw90 therefore a standard Arduplane install as per the wiki will not work. I believe Arducopter has resolved this.
This is still not mentioned in the documentation and is creating a lot of problems for end users.

Details here... 
https://discuss.ardupilot.org/t/copter-3-5-5-released-take-care-re-new-hex-gps-compass-orientation/25373

**Comment by rmackay9** [comment]
I think this is fixed now so closing.
