### ISSUE TITLE
Debian 9 APM Planner 2 Installation Error Solutions

### ISSUE THREAD

**Issue by CanadianEngineer** [ArduPilot/ardupilot_wiki#1467]
Hey Everyone!

I came across some issues installing apmplanner2 on Debian 9. From the [download page](http://firmware.ardupilot.org/Tools/APMPlanner/), I tried installing `apm_planner_2.0.23_debian_stretch.deb` and `apm_planner_2.0.24_xenial64.deb`; however, I was getting the following error messages:

```
$ sudo dpkg -i apm_planner_2.0.23_debian_stretch.deb
...
Errors were encountered while processing:
apmplanner2:i386
```

```
$ sudo dpkg -i apm_planner_2.0.24_xenial64.deb
...
Errors were encountered while processing:
apmplanner2:i386
```

For each, I tried running `sudo apt-install -f`, which resulted in:
```
$ apmplanner2
-bash: apmplanner2: command not found
```

I reran the installer for `apm_planner_2.0.23_debian_stretch.deb` and immediately tried running `apmplanner2` which this was the result:
```
$ apmplanner2
apmplanner2: error while loading shared libraries: libsndfile.so.1: cannot open shared object file: No such file or directory
```

I tried looking up `libsndfile.so.1` and came across an article saying I should create a symbolic link to it from my `/usr/local/lib` folder (or something along those lines). **Didn't work for me**.

### Solution

1. Run the installer for `apm_planner_2.0.24_xenial64.deb`.
```
$ sudo dpkg -i apm_planner_2.0.24_xenial64.deb
```

2. Confirm the following error message, specifically it complaining about `libQt5SerialPort.so.5`.
```
$ apmplanner2
apmplanner2: error while loading shared libraries: libQt5SerialPort.so.5: cannot open shared object file: No such file or directory
```

3. Download the appropriate version of `libQt5SerialPort.so.5` from [here](https://rpmfind.net/linux/rpm2html/search.php?query=libQt5SerialPort.so.5()(64bit)). `lib64qt5serialport5-5.11.2-1.mga7.x86_64.rpm` worked for me.

4. Install alien to be able to install rpm packages:
```
sudo apt-get install alien
```

5. Install the rpm package using alien:
```
sudo alien -i lib64qt5serialport5-5.11.2-1.mga7.x86_64.rpm
```

6. Launch APM Planner. From terminal: `apmplanner2`.

Hope this helps!

**Comment by khancyr** [comment]
thanks for the solution. I am closing this
