### ISSUE TITLE
Mateksys F405-STD and variants

### ISSUE THREAD

**Issue by davidbitton** [ArduPilot/ardupilot_wiki#1488]
[Mateksys F405-STD and variants](http://ardupilot.org/copter/docs/common-matekf405.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

This article shows the original UART layout before it was changed to 1 to 1 -- UART1 is Serial1.

**Comment by davidbitton** [comment]
@vierfuffzig I must be. I assumed (wrongly) that it was the same. Never mind then! Thanks.

**Comment by Hwurzburg** [comment]
Closing since this is a non issue
