### ISSUE TITLE
RC Transmitter and Receiver Systems errors

### ISSUE THREAD

**Issue by WickedShell** [ArduPilot/ardupilot_wiki#1517]
http://ardupilot.org/copter/docs/common-pixhawk-and-px4-compatible-rc-transmitter-and-receiver-systems.html is overall rather stale.

Significant errors of note:
 - Spektrum Satellite Rx's do not speak PPM-SUM, it's DSM http://ardupilot.org/copter/docs/common-pixhawk-and-px4-compatible-rc-transmitter-and-receiver-systems.html#spektrum-satellite-receivers-operate-on-ppm-sum )
 - FrSky link's are all 404 (the list of the recievers, the X8R, XSR direct links for example)
 - Futaba receiver links are all 404

**Comment by Hwurzburg** [comment]
#2445 addresses this....have added a must do for myself to redo the page and make it more protocol oriented and less product oriented
