### ISSUE TITLE
Full parameter tree - too long

### ISSUE THREAD

**Issue by Naterater** [ArduPilot/ardupilot_wiki#1531]
OSDn_, BATTn_, RCn_, and SERVOn_ are all parameters that have multiple instances and really only require one description per for all instances. The tree is getting out of hand with its length, and the OSD parameters have at least doubled the size of the tree.

Is there any way to automatically shrink down this menu on the left or condense the repetitive items?
![image](https://user-images.githubusercontent.com/35429159/50377851-aaf24100-05ea-11e9-9066-804698dc474b.png)

**Comment by vierfuffzig** [comment]
+1
collapsing OSD params would add massive convenience

**Comment by khancyr** [comment]
We could add something on the parser to shrink the osd parameters

**Comment by vierfuffzig** [comment]
is it /Tools/autotest/param_metadata/htmlemit.py that generates the param page? this scripting is quite a bit beyond my scope, can't figure how exactly the toc depth is generated. seems the parser's depth is limited to 1 while the OSDn params have 2 subgroups actually...

**Comment by Hwurzburg** [comment]
this seems to be fixed...OSD parameters are collapsed unless expanded...
