### ISSUE TITLE
Benewake TFmini lidar

### ISSUE THREAD

**Issue by arcdragon1** [ArduPilot/ardupilot_wiki#1532]
[Benewake TFmini lidar](http://ardupilot.org/copter/docs/common-benewake-tfmini-lidar.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

This page should be updated to reflect that the Benewake TFmini now has an I2C version and hooking it up to the serial port is still an option.

**Comment by Hwurzburg** [comment]
this has been updated
