### ISSUE TITLE
Add drotek airspeed sensor to airspeed page

### ISSUE THREAD

**Issue by arcdragon1** [ArduPilot/ardupilot_wiki#1533]
Please add this different species of airspeed sensor to the page:  https://drotek.com/shop/en/airspeed/848-sdp3x-airspeed-sensor-kit-sdp33.html

**Comment by Hwurzburg** [comment]
does not seem to exist....@arcdragon1 please provide more info if it does exist before we close this request

**Comment by Hwurzburg** [comment]
closing
