### ISSUE TITLE
Copter: move quick wiring diagrams to ardupilot hardware pages

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#1560]
The [Copter's Assembly section](http://ardupilot.org/copter/docs/assembly-instructions.html) includes a few "quick wiring" pages for a very limited number of autopilots.

These should be moved to the specific flight controller pages under [AutoPilot Hardware Options](http://ardupilot.org/copter/docs/common-autopilots.html).

The only exception should be the Pixhawk1 page because I think this is our default reference flight controller.

**Comment by rmackay9** [comment]
After this is done I think we should promote the contents of the "Assembly Instructions" area (i.e. Mounting the Flight Controller, ESCs and Motors, GPS+Compass, Vibration Damping, Magnetic interference) up one level so it's under "First Time Setup'

**Comment by Hwurzburg** [comment]
personally I am in favor of the hierarchical approach....I agree with the specific wiring diagram comment, but would like to keep a base wiring and required component subsytem assembly as a grouped topic....long lists are hard to select from...I am working to group things in the long TOC lists into logical , navigable groups...

**Comment by Hwurzburg** [comment]
think this is in better shape now...
