### ISSUE TITLE
Loading ChibiOS firmware onto Pixhawk

### ISSUE THREAD

**Issue by Elmeerkat** [ArduPilot/ardupilot_wiki#1561]
[Loading ChibiOS firmware onto Pixhawk](http://ardupilot.org/copter/docs/common-loading-chibios-firmware-onto-pixhawk.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by rmackay9** [comment]
mistake I guess so closing
