### ISSUE TITLE
RC Input and Output

### ISSUE THREAD

**Issue by auturgy** [ArduPilot/ardupilot_wiki#1569]
[RC Input and Output](http://ardupilot.org/dev/docs/learning-ardupilot-rc-input-output.html) - Needs to be completey redone.  Misleading to users

**Comment by Hwurzburg** [comment]
can you comment a bit more about what is wrong and what is needed?thanks

**Comment by Hwurzburg** [comment]
closing...unless some details can be provided on what is lacking/needed since those pages have already been reworked
