### ISSUE TITLE
MP commands - remove Condition_Change_Alt

### ISSUE THREAD

**Issue by jace26** [ArduPilot/ardupilot_wiki#1577]
Condition_Change_Alt command is no longer supported by any frame (why? @WickedShell it sounds like a nice command I'd like to use for an L/D test)

please remove.

**Comment by auturgy** [comment]
I hope that closiyis what you were asking in the end. If not, ping me and I’ll reopen

**Comment by jace26** [comment]
@auturgy Nope, I need this pulled from the wiki, it's not supported anymore by any version of ardupilot:
http://ardupilot.org/copter/docs/common-mavlink-mission-command-messages-mav_cmd.html#mav-cmd-condition-change-alt

**Comment by rmackay9** [comment]
yes, we should remove that section from the wiki..

**Comment by vierfuffzig** [comment]
ok to close this, subject to PR approval?

basti.

**Comment by rmackay9** [comment]
fixed thanks!
