### ISSUE TITLE
Copter: add Terrain failsafe page

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#1579]
We should probably add the terrain failsafe to the [list of possible failsafes](http://ardupilot.org/copter/docs/failsafe-landing-page.html).  It's quite rare actually but [here is an issue](https://github.com/ArduPilot/ardupilot/issues/10255) (which is really a support call) where it's happened.  Having extra documentation might help reduce support calls.

Update: we have some [information on this failsafe here](http://ardupilot.org/copter/docs/terrain-following.html#failsafe-in-case-of-no-terrain-data).

**Comment by Hwurzburg** [comment]
added....will need to update more once master changes are in beta...
