### ISSUE TITLE
C.H.U.C.K Autopilot (for Parrot Disco)

### ISSUE THREAD

**Issue by MEXICO-PARIS** [ArduPilot/ardupilot_wiki#1601]
[C.H.U.C.K Autopilot (for Parrot Disco)](http://ardupilot.org/plane/docs/common-CHUCK-overview.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by proficnc** [comment]
What is the actual issue?

**Comment by rmackay9** [comment]
perhaps a mistake so closing..

**Comment by auturgy** [comment]
http://firmware.ardupilot.org/Plane/stable/disco/

Regards,

James

**Comment by MEXICO-PARIS** [comment]
bonjour Jame

le firmware et il pour la sequoia du parrot disco pro

**Comment by auturgy** [comment]
Bonjour,

Je ne sais pas si le Pro avec séquoia est le même.
Pierre parle français. J'espère qu'il peut aider davantage. @khancyr



Regards,

James

**Comment by MEXICO-PARIS** [comment]
ok merci James

**Comment by khancyr** [comment]
Bonjour,

Normalement, le disco pro est sur le firmware de Parrot pas ArduPilot. Malheuresement, nous n'avons pas d'API pour le control de la camera sequoia. Le mieux est de vous tourner vers le service client de Parrot.
