### ISSUE TITLE
In mp and wiki, rssi_ana_pin is missing tags

### ISSUE THREAD

**Issue by cuhome** [ArduPilot/ardupilot_wiki#1619]
I tested it on my v5_nano board (it is based on fmu v5), I found that my board rssi is not working, I found the wiki and mp, I didn't find what my board should set rssi_ANA_PIN to, I saw the firmware Code, found that it should be set to 8. I have tested it, rssi is normal. Please add tags to let more people know.
![Uploading v5_nano.png…]()
![rssi_pin](https://user-images.githubusercontent.com/31507501/51962345-c6c6ed80-249a-11e9-9072-2bf01ed36900.png)

**Comment by auturgy** [comment]
G’day Hongle,
the parameter values are auto-generated from comments in the source code, so we’ll have to fix it there. Thanks for finding the solution though!

Regards,

James

**Comment by Hwurzburg** [comment]
fixed in code already
