### ISSUE TITLE
Rover-3.5 updates

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#1629]
A list of wiki updates we need to do related to the Rover-3.5 release

- [x] follow mode setup instructions
- [x] simple mode setup instructions
- [ ] wheel encoder for rate control (WRC_ parameters)

**Comment by Hwurzburg** [comment]
Need information on WRC_ parameters in order to add to wiki....who to ask?

**Comment by rmackay9** [comment]
moved the final item to Rover-4.0 list
