### ISSUE TITLE
Dead link in Wiki page: Tips For New Pilots

### ISSUE THREAD

**Issue by apache405** [ArduPilot/ardupilot_wiki#1643]
[Tips For New Pilots](http://ardupilot.org/copter/docs/ac_tipsfornewpilots.html) - Dead link: http://www.hobbyking.com/hobbyking/store/RC_PRODUCT_SEARCH.asp?strSearch=Battery+Monitor gives a 404 on hobby king's site.

**Comment by stephendade** [comment]
Fix has been applied. This can be closed now.

**Comment by rmackay9** [comment]
closed!
