### ISSUE TITLE
COLLISION AVOIDANCE

### ISSUE THREAD

**Issue by boristobi** [ArduPilot/ardupilot_wiki#1653]
[Search](http://ardupilot.org/copter/search.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by boristobi** [comment]
SOME PEOPLE HAVE PROJECY WIT BENEWAKE TF MINI AND PIXHAWK. Thanks

**Comment by rmackay9** [comment]
looks like a support issue which belongs in the forums so I'll close this.
