### ISSUE TITLE
SiK Radio — Advanced Configuration

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/ardupilot_wiki#1657]
[SiK Radio — Advanced Configuration](http://ardupilot.org/copter/docs/common-3dr-radio-advanced-configuration-and-technical-information.html) 
says:
"The radio firmware supports both the MAVLink 0.9 and the MAVLink 1.0 transmission formats."

MAVLink 2.0 deserves a mention as well.

**Comment by brunoolivieri** [comment]
Hi, 

Thanks for the observation. Indeed I got updated information on forums [1], and I did the PR #1780

Could we close this issue?

[1] https://discuss.ardupilot.org/t/sik-radios-vs-mavlink-versions/43282/2?u=brunoolivieri

**Comment by AndKe** [comment]
yes, thank you.
