### ISSUE TITLE
DShot and BLHeli ESC Support

### ISSUE THREAD

**Issue by nooa** [ArduPilot/ardupilot_wiki#1664]
[DShot and BLHeli ESC Support](http://ardupilot.org/copter/docs/common-dshot.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant. 

04 March 2019 01:02 
This link is not functioning: http://www.blheli32.com/list-of-blheli_32-escs/

**Comment by rmackay9** [comment]
Indeed it seems to be down.. not sure there's much we can do about it though.  Hopefully it'll be back up later..

**Comment by Hwurzburg** [comment]
no longer exists as link
