### ISSUE TITLE
No sub Wiki ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [ArduPilot/ardupilot_wiki#1666]
I have been around for couple of weeks on ardupilot and still can't find the sub Wiki ... is there anything wrong ?

**Comment by khancyr** [comment]
Hello,
ArduSub got its own wiki at https://www.ardusub.com
I will note to make a link to it

**Comment by auturgy** [comment]
It’s a slight anomaly, but Blue Robotics and the ArduSub community maintain the sub wiki here: https://www.ardusub.com/

Regards,

James

**Comment by MohamedAliRashad** [comment]
> Hello,
> ArduSub got its own wiki at https://www.ardusub.com
> I will note to make a link to it

This is strange ..... it doesn't work with me, Does it require a VPN or something ?
