### ISSUE TITLE
ImportError: No module named serialSearch

### ISSUE THREAD

**Issue by pinepinepine** [ArduPilot/ardupilot_wiki#1667]
[Search](http://ardupilot.org/dev/search.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by rmackay9** [comment]
Not quite clear what this is asking for.. is it asking for a search field?

**Comment by pinepinepine** [comment]
I have solved it. when I upload firmware to pixhawk using Cygwin，it reports this error.because that I forget to install Python2-pip package(i cant find this package when installing cygwin) ，I  cant use pyserial。I install Python27-pip and intall pyserial，and no error appears .
