### ISSUE TITLE
Add pwm output group info (aka rate limitation info) to all flight controllers

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#1669]
As mentioned in [this discussion on the forums](https://discuss.ardupilot.org/t/copter-3-6-7-released/39352/7), most hardware does not support independent output rates (i.e. 400hz for motors, 50hz for servos) for each output channel.  For example on a Pixhawk1 channels 1 ~ 4 must use the same output rate.  channels 5 and 6 must similarly use the same output rate.  We should document these groups on the wiki pages for all flight controllers.

**Comment by Hwurzburg** [comment]
#2211
