### ISSUE TITLE
Altitude Hold Mode  -mentioned parameter INAV_TC_Z does not exist.

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/ardupilot_wiki#1678]
[Altitude Hold Mode](http://ardupilot.org/copter/docs/altholdmode.html) -

INAV_TC_Z  does not exist, please update with proper solution.

**Comment by rmackay9** [comment]
@AndKe, the equivalent parameter in the EKF is the EK2_ALT_M_NSE.  It's mentioned on [this user focused EKF wiki page](http://ardupilot.org/copter/docs/common-apm-navigation-extended-kalman-filter-overview.html) but I'll update the AltHold page in the near-ish future.

**Comment by brunoolivieri** [comment]
Hi @rmackay9	

I understood that the parameter INAV_TC_Z is for EKF1 and EK2_ALT_M_NSE for EKF2. Am I correct?

If so, could I update the information?

**Comment by rmackay9** [comment]
@brunoolivieri, yes, that's right.  I'm pretty sure the scaling is not the same but it is the equivalent..

**Comment by brunoolivieri** [comment]
@rmackay9 Thanks! :-)

@AndKe I created the PR #1793 to fix that. Are you ok to close the PR?

**Comment by AndKe** [comment]
Yes, thank you
