### ISSUE TITLE
Septentrio AsteRx-m UAS and AsteRx-m2 UAS RTK GPS

### ISSUE THREAD

**Issue by aresesss** [ArduPilot/ardupilot_wiki#1685]
[Septentrio AsteRx-m UAS and AsteRx-m2 UAS RTK GPS](http://ardupilot.org/plane/docs/common-gps-septentrio.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by rmackay9** [comment]
Looks like a mistake so closing
