### ISSUE TITLE
Combine training centers and school pages

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#1704]
We apparently have separate training centers and school wiki pages.  we should combine these.

**Comment by auturgy** [comment]
Originally they were intended for different things: flight/operations training centres, and code/development schools.
I think the distinction made sense, until we cross merged and messed it up.
Up to you though.

Regards,

James

**Comment by brunoolivieri** [comment]
I can see the Training Centers in plane/copter wikis but Schools only in dev wiki. None of the others have those links. It is correct? Should be updated?

**Comment by rmackay9** [comment]
@brunoolivieri, yes, they should all be consistent I think.

**Comment by Hwurzburg** [comment]
It would seem that code schools and flight training should be separated... and both pages listed in all wikis...I will do that if you guys agree...

**Comment by rmackay9** [comment]
I think we should just put them together on a single page with some way to see what each school offers.  Otherwise I think we will end up with duplicates as some schools offer both... and i think from the user's point of view they are all schools.

**Comment by Hwurzburg** [comment]
PR #2066 combines

**Comment by Hwurzburg** [comment]
closing
