### ISSUE TITLE
Connecting with ROS to Ardupilot Over Radio Telemetry Module (Or BeagleBone Blue)

### ISSUE THREAD

**Issue by BraytonL** [ArduPilot/ardupilot_wiki#1707]
[Connecting with ROS](http://ardupilot.org/dev/docs/ros-connecting.html)
I see that there are plenty of instructions for connecting to the PIXHAWK (or ArduPilot I assume) with ROS and on board compute module such as the Rasperry Pi or Jetson. However, is it possible to run ROS on an Ubuntu computer as a ground station and receive data through an USB telemetry relay module such as [this one ](https://www.amazon.com/dp/B074V6FKZR/ref=cm_sw_em_r_mt_dp_U_iU5RCb1PFV068 ). I'm currently using this to get data into MissionPlanner and it works great. 

As a side not I'm looking to build a BeagleBone Blue quadcopter to help with my student research. Are there any packages that supports this kind of connection between ROS and ArduPilot running on the same computer?

I assume there is some way to tell mavros to connect to a USB device as a serial port, but I'm currently at a loss. Any help would be greatly appreciated. Thanks in advance!

**Comment by rmackay9** [comment]
Txs for the feedback.  It's probably best to ask questions in the support forums or in the [ArduPilot/VisionProjects gitter chat](https://gitter.im/ArduPilot/VisionProjects).

To clarify the terminology, Pixhawk is a type of hardware and ArduPilot is the software.  Maybe that's already clear but just in case 'cuz lots of people mix them up.

Normally we reserve this issues list for recording enhancement requests or mistakes in the wiki so I'll close this issue if that's OK.
