### ISSUE TITLE
SkyRocket Hardware

### ISSUE THREAD

**Issue by 4ishops** [ArduPilot/ardupilot_wiki#1709]
Hello,

Do you have internal flash layout for Sonix board?
I have similar board on MJX Bugs 2 B2W drone and looking for firmware.

mtdparts=snx-spi:320k(uboot),2304k(kernel),4608k(rootfs),512k(etc),64k(key),384k(config)

Creating 6 MTD partitions on "snx-spi":
0x000000000000-0x000000050000 : "uboot"
0x000000050000-0x000000290000 : "kernel"
0x000000290000-0x000000710000 : "rootfs"
0x000000710000-0x000000790000 : "etc"
0x000000790000-0x0000007a0000 : "key"
0x0000007a0000-0x000000800000 : "config"

[SkyRocket Hardware](http://ardupilot.org/copter/docs/skyrocket-hardware.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by auturgy** [comment]
This isn’t an ArduPilot issue, so closing.
It’s best to ask the manufacturer or perhaps a forum for your copter.
