### ISSUE TITLE
Companion Computers few page out of date

### ISSUE THREAD

**Issue by bys1123** [ArduPilot/ardupilot_wiki#1710]
1. Disable bluetooth on RPi3 should use `dtoverlay=pi3-disable-bt` in /boot/config.txt instead of `dtoverlay=pi-disable-bt` descripted in wiki.
http://ardupilot.org/dev/docs/raspberry-pi-via-mavlink.html#testing-the-connection
2. Look like Config page is work on 80 port with apweb, (8000 port is only for video?)
http://ardupilot.org/dev/docs/apsync-intro.html#simple-configuration-web-page

**Comment by bys1123** [comment]
I saw Randy mentioned apweb on #1147

**Comment by brunoolivieri** [comment]
Hi @bys1123 

I did the simple PR #1786 to fix the BT command and PR #1785 to insert item "2" in the Wiki.

Could this issue be closed?

**Comment by rmackay9** [comment]
@brunoolivieri, thanks for all your efforts on the wiki, txs!  i'll close this now.

**Comment by bys1123** [comment]
Thanks!
