### ISSUE TITLE
Using Gazebo Simulator with SITL

### ISSUE THREAD

**Issue by ankitgc1** [ArduPilot/ardupilot_wiki#1714]
[Using Gazebo Simulator with SITL](http://ardupilot.org/dev/docs/using-gazebo-simulator-with-sitl.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

sim_vehicle.py: command not found

**Comment by brunoolivieri** [comment]
Hi, you could try to refer the entire path: ../Tools/autotest/sim_vehicle.py  OR add it on your $Path.

In any case, I did a PR to insert the path on the documentation.

I believe that this issue could be closed.

Regards,

**Comment by Hwurzburg** [comment]
closing...resolved
