### ISSUE TITLE
Building for Bebop on Linux

### ISSUE THREAD

**Issue by malfonsoNeoris** [ArduPilot/ardupilot_wiki#1719]
[Building for Bebop on Linux](http://ardupilot.org/dev/docs/building-for-bebop-on-linux.html) 
Hi.. i would like no know if there are updates regarding the bebop or bebop 2 ardupilot.

- [ ] Optical Flow. or at list stable indoor hover like in the original autopilot
- [ ] Camera streaming.. or a way to get frontal camera from python program

thanks

**Comment by brunoolivieri** [comment]
Hi @malfonsoNeoris , I believe that should be a question to discuss in the forums (https://discuss.ardupilot.org). Could you try it?

I believe that this issue could be closed due to the fact that is not a wiki issue.

Regards,

**Comment by rmackay9** [comment]
I think camera streaming is supported on the Disco but I'm less sure if the Bebop2 has the correct library.  In any case, as @brunoolivieri says, it's not a wiki issue so closing.

**Comment by malfonso0** [comment]
sorry for the misplaced question
i will ask in the forum
