### ISSUE TITLE
Rover Assembly Instructions

### ISSUE THREAD

**Issue by BMCstudio** [ArduPilot/ardupilot_wiki#1723]
I have my boat in auto mode .but I find that only servo work.the motor still stop.what is wrong.it would be grateful if you can solve my question.thanks

**Comment by rmackay9** [comment]
@BMCstudio, could you create a new discussion in the Rover-3.5 forum? https://discuss.ardupilot.org/c/ardurover/rover-35

It would be best to include a dataflash log as well if possible.  Thanks for using AP!
