### ISSUE TITLE
DroneKit Tutorial

### ISSUE THREAD

**Issue by nurafifah29** [ArduPilot/ardupilot_wiki#1729]
Thanks ardupilot for references, worth it for me. I have some issues to open this link: http://python.dronekit.io/ about The official DroneKit Python documentation,  a quick start guide. I opened it in chrome browser. Do you have a suggestion to help my problem?

**Comment by hamishwillee** [comment]
Currently there are hosting issues. These will likely be fixed in the current month.

You can browse the docs on wayback: https://web.archive.org/web/20181225071243/http://dronekit.io/

**Comment by nurafifah29** [comment]
Thank you for your suggestion and information, you had helped me a lot.
