### ISSUE TITLE
Compass Calibration

### ISSUE THREAD

**Issue by prabhuhalady** [ArduPilot/ardupilot_wiki#1735]
[Compass Calibration] (http://ardupilot.org/copter/docs/common-compass-calibration-in-mission-planner.html) -  "bad compass health" APM 2.6 with external compass(neo 7m gps+ compass)

**Comment by auturgy** [comment]
APM 2.X was deprecated several years ago.
This issue will not be investigated.
Please see http://ardupilot.org/copter/docs/common-autopilots.html for supported hardware.
