### ISSUE TITLE
Issue with "Testing the Connection" due to Telem2 being disabled on battery power

### ISSUE THREAD

**Issue by mcavolowsky** [ArduPilot/ardupilot_wiki#1750]
[Communicating with Raspberry Pi via MAVLink](http://ardupilot.org/dev/docs/raspberry-pi-via-mavlink.html)

Following the instruction provided, I was unable to successfully complete the "Testing the Connection" section with my Pixhawk 4.  When trying to connect, I would get a "source_system=255" message and there would be no response when issuing commands such as "param set "ARMING_CHECK".

Based on a Google search, I was able to identify the problem.  Apparently, the Telem1 and Telem2 ports are disabled when connecting to the Pixhawk 4 via USB power.  It would help if this were mentioned in the tutorial.

Credit goes to this post by Cyclops:

https://discuss.ardupilot.org/t/raspberrypi3-and-apm2-6-via-mavproxy/17341/19

**Comment by Hwurzburg** [comment]
@mcavolowsky sorry its taking so long to get to this...but this is not correct...the TELEM ports are unaffected with USB power.....if you are still having an issue, post in the https://discuss.ardupilot.org/c/hardware-discussion/companion-computers
