### ISSUE TITLE
Communicating with Raspberry Pi via MAVLink

### ISSUE THREAD

**Issue by auturgy** [ArduPilot/ardupilot_wiki#1751]
[Communicating with Raspberry Pi via MAVLink](http://ardupilot.org/dev/docs/raspberry-pi-via-mavlink.html) - Diagram and text needs to be changed to remove suggestion you can power the Pi from the FC.

**Comment by brunoolivieri** [comment]
Hi @auturgy,

I will be glad to edit that. However, are you sure that you can not to that? Or you should not do that? 

Please, note that the page encourage to power RPI throught USB: "Powering via USB is recommended as it is typically safer."

**Comment by Hwurzburg** [comment]
done a while ago
