### ISSUE TITLE
Mission Commands

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/ardupilot_wiki#1752]
[Mission Commands](http://ardupilot.org/planner/docs/common-mavlink-mission-command-messages-mav_cmd.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

The Param1 description, "1" or "2" in http://ardupilot.org/planner/docs/common-mavlink-mission-command-messages-mav_cmd.html#mav-cmd-do-set-home
does not match 
https://mavlink.io/en/messages/common.html#MAV_CMD_DO_SET_HOME
with "0" and "1"

**Comment by brunoolivieri** [comment]
Hi,

Thanks for the finding. Indeed, we did the PR #1781 to fix that.

May you close the issue?

regards,

**Comment by AndKe** [comment]
yes, thank you.
