### ISSUE TITLE
Firmware Website down (http://firmware.ardupilot.org)

### ISSUE THREAD

**Issue by MpxFlyer** [ArduPilot/ardupilot_wiki#1754]
I just wanted to update my cube. However I just got error messages like "no firmware availiable". I then wanted to download the FW manually via http://firmware.ardupilot.org 
However I cannot seem to access the website. Is it possible that it is down?

**Comment by auturgy** [comment]
Yes. Firmware.ardupilot.org is currently down. It’s being looked at right now.

Regards,

James

**Comment by peterbarker** [comment]
On Fri, 31 May 2019, MpxFlyer wrote:

> However I cannot seem to access the website. Is it possible that it is down?

Fixed!

Our bad.

**Comment by MpxFlyer** [comment]
Awesome thanks for your quick reply. I just wanted to make sure it was not an error with my network or whatsoever. please keep us updated - looking forward to finally beeing able to try my pixhawk!
