### ISSUE TITLE
Wiki Issues cleanup status list #1

### ISSUE THREAD

**Issue by vierfuffzig** [ArduPilot/ardupilot_wiki#1761]
as discussed on wiki gitter. will be updated. trying my best to sort, adress and implement suggestions, thanks everyone pinged for looking into these:

**done:**
<s>https://github.com/ArduPilot/ardupilot_wiki/issues/1469 implemented by https://github.com/ArduPilot/ardupilot_wiki/pull/1757 @rmackay9 </s>
<s>https://github.com/ArduPilot/ardupilot_wiki/issues/1467 solved, please close</s>
<s>#1461 implemented by https://github.com/ArduPilot/ardupilot_wiki/pull/1758 @rmackay9 merged, please close issue</s>
<s>#1433 implemented by https://github.com/ArduPilot/ardupilot_wiki/pull/1760 pretty specific, merge or close both ping @rmackay9 </s>
<s>#1428 implemented by https://github.com/ArduPilot/ardupilot_wiki/pull/1765 @khancyr merged, please close issue</s>
<s>#1420 implemented by https://github.com/ArduPilot/ardupilot_wiki/pull/1767 </s>
<s>#1414 support request, close</s>
<s>#1375 ready to close </s>
<s>#1342 full site rework https://github.com/ArduPilot/ardupilot_wiki/pull/1774  ready to close</s>

**issues to close:**
<s>#1366 implemented by https://github.com/ArduPilot/ardupilot_wiki/pull/1772</s> ready to close
<s>#1356 implemented by https://github.com/ArduPilot/ardupilot_wiki/pull/1773</s> ready to close
#1419 ready to close
<s>#1426 implemented by https://github.com/ArduPilot/ardupilot_wiki/pull/1766 </s> ready to close

**needs decision:**
#1435 fix https://github.com/ArduPilot/ardupilot_wiki/pull/1759 rejected ping @rmackay9 close issue too?
#1432 see https://github.com/ArduPilot/ardupilot_wiki/pull/1764 @khancyr WIP

**Comment by vierfuffzig** [comment]
updated, thanks everyone for your effort! 
can't close issues, got no permission, ping @Hwurzburg maybe...?

thanks, basti.

**Comment by Hwurzburg** [comment]
will do

**Comment by vierfuffzig** [comment]
thx henry!

**Comment by vierfuffzig** [comment]
closing list with just the SITL diagram update left as WIP. thanks everyone!
