### ISSUE TITLE
Complete Parameter List Versioning

### ISSUE THREAD

**Issue by Naterater** [ArduPilot/ardupilot_wiki#1763]
This is a formal request for the Complete parameter list to be versioned by release. People are asking today where features and parameters are when they haven't yet made it to stable releases. The current complete parameter lists are auto generated from master, and I think it should be generated from the most recent stable release if there is only one version.

**Comment by brunoolivieri** [comment]
Hi @Naterater , would not this be the case of a discussion in the forum?

I believe that this issue could be closed.

Cheers.

**Comment by rmackay9** [comment]
I think I'll leave this one open.  It's a bit of a mix of flight code and wiki changes but it makes sense to track it here.

**Comment by brunoolivieri** [comment]
ok

**Comment by brunoolivieri** [comment]
The versioning for parameters is running. You can check it out: https://ardupilot.org/copter/docs/parameters.html  (it is a listbox of versions...)

I will close that, please feel free to reopen if necessary.
