### ISSUE TITLE
firmware.ardupilot.org is down (servers are not available from June 8)

### ISSUE THREAD

**Issue by dzotov2** [ArduPilot/ardupilot_wiki#1788]
firmware.ardupilot.org is down (servers are not available from June 8)
I watched another similar issue (1754). But it's now closed.

**Comment by auturgy** [comment]
It’s available for me. Can you check again and paste the error message?

Regards,

James

**Comment by dzotov2** [comment]
tracert (upper) and browser message (bottom).  I'm connecting from Russia Federation (tryed from separate machines and providers)

![image](https://user-images.githubusercontent.com/51694627/59252432-bf77d380-8c34-11e9-8852-d50cb53df8b6.png)

**Comment by tridge** [comment]
definitely working from here

**Comment by dzotov2** [comment]
strange behavior. Some devices have access to the site, some do not have it... Other resources working fine (http://www.ardupilot.org/, https://discuss.ardupilot.org/ )

**Comment by auturgy** [comment]
It’s possible that a dns server somewhere along line is pointing to the old firmware server (due to caching). We upgraded to a more powerful build server last week, so the underlying IP address has changed (although the URL hasn’t).
Unfortunately firmware.ardupilot.org isn’t directly reachable via the server IP.
The website is definitely up and working from other places around the world.
I’m not a guru on this stuff so can’t really help more than that.
If you need a specific firmware, perhaps open a post on the forum asking for it.

I’d like to close this issue, but we’ve noted that changing the server hasn’t properly propagated everywhere.

Thanks for reporting this.

James

**Comment by peterbarker** [comment]
That IP address that @dzotov2 reported is the current one.

So... has that IP address been blacklisted by something/someone?  I guess we'll have to keep an eye on this.

**Comment by dzotov2** [comment]
> That IP address that @dzotov2 reported is the current one.
> 
> So... has that IP address been blacklisted by something/someone? I guess we'll have to keep an eye on this.

Checked from different machines, stations, providers and conditions. Local\regional blocking of the IP \ domain http://firmware.ardupilot.org was also not detected. Some devices have access to the site, some do not have it.

**Comment by peterbarker** [comment]
Are the traceroutes the same from different networks?

Paste a working traceroute, perhaps?

**Comment by dzotov2** [comment]
for example, working tracert

![image](https://user-images.githubusercontent.com/51694627/59271393-66bc3100-8c5c-11e9-9fe6-bd82eb6cf4af.png)

+ second another

Трассировка маршрута к mega2.ardupilot.org [159.65.186.182]
с максимальным числом прыжков 30:

  1    <1 мс    <1 мс    <1 мс  serv.office2.naumen.ru [192.168.212.1]
  2    <1 мс    <1 мс    <1 мс  10.0.12.254
  3     5 ms     5 ms     5 ms  62.181.37.17
  4    19 ms    12 ms     5 ms  mow-b4-link.telia.net [62.115.161.120]
  5   122 ms   122 ms   121 ms  s-bb3-link.telia.net [62.115.116.232]
  6   121 ms   120 ms   123 ms  kbn-bb3-link.telia.net [62.115.139.169]
  7   117 ms   117 ms   118 ms  nyk-bb3-link.telia.net [213.155.134.50]
  8   122 ms   119 ms   118 ms  nyk-b3-link.telia.net [62.115.140.223]
  9                     *     Превышен интервал ожидания для запроса.
 10                     *     Превышен интервал ожидания для запроса.
 11   117 ms   120 ms   117 ms  159.65.186.182
