### ISSUE TITLE
reset

### ISSUE THREAD

**Issue by elgato41** [ArduPilot/ardupilot_wiki#1790]
[RC Input Channel Mapping (RCMAP)](http://ardupilot.org/copter/docs/common-rcmap.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by brunoolivieri** [comment]
Hi @elgato41 

The issue in empty. Please, what is wrong on such page? 

If this was a mistake, could you close the issue?

regards,

**Comment by rmackay9** [comment]
probably a mistake, i'll close this one.
