### ISSUE TITLE
No such file or directory Linux VM 

### ISSUE THREAD

**Issue by zwadzinski** [ArduPilot/ardupilot_wiki#1791]
Hi, so I am following this guide to setup SITL/MAVProxy on a Linux VM. I am also using this for a plane while the video is using a copter. I can get to here: https://www.youtube.com/watch?time_continue=4&v=pJGFkZmGV6o 19:20 before an error occurs saying: 
<<<bash: cd: /home/zwadzinski/ardupilot/Ardoplane: No such file or directory.>>>

![ubuntu troubleshoot](https://user-images.githubusercontent.com/46848582/59290078-5052ad00-8c3d-11e9-8995-dc3cd8e89f0c.PNG)

I’m assuming its because I am using a plane but have no idea. Also I am very new to this whole thing so dumbing it down may be a good idea. Any ideas on what to do? thanks

**Comment by magicrub** [comment]
> cd: /home/zwadzinski/ardupilot/Arduplane: No such file or directory.

Linux is case sensitive, path is "ardupilot/ArduPlane". He even says that in the video at the time mark.

This video is very nice, I did not know about it until now, thank you!. However, the make system has been replaced with waf so you won't be able to build but you can still run the simulator with the commands he uses.. although he does a lot of Export stuff that is all unnecessary, the install script does it all for you. Please use the wiki installation instructions, they're kept up to date where this video is 2 years old and has not (and can not) change.
