### ISSUE TITLE
Adding a new MAVLink Message (Code Overview): No generate.sh script found

### ISSUE THREAD

**Issue by Senthilkumarl** [ArduPilot/ardupilot_wiki#1805]
There is no generate.sh script in libraries/GCS_MAVLink folder in the latest version.

**Comment by brunoolivieri** [comment]
Hello @Senthilkumarl 

Please, could you provide the page that cites that?

**Comment by Senthilkumarl** [comment]
http://ardupilot.org/dev/docs/code-overview-adding-a-new-mavlink-message.html

Please update the documentation.

**Comment by rajat2004** [comment]
Issue #354 is related to this, from [this comment](https://github.com/ArduPilot/ardupilot_wiki/issues/354#issuecomment-209002489), Step 4 isn't required, as mentioned in the Wiki, compiling the project should be enough
Maybe remove the `generate.sh` line if it's no longer applicable?

**Comment by Senthilkumarl** [comment]
http://ardupilot.org/dev/docs/code-overview-scheduling-your-new-code-to-run-intermittently.html
Ok, I got it. But where is ArduCopter.cpp. It seems that, ArduCopter.cpp has been renamed as Copter.cpp.
Is there any updated documentation ?

**Comment by rajat2004** [comment]
@Senthilkumarl Thanks for pointing out this! I've opened #1806 for the renaming.

**Comment by brunoolivieri** [comment]
@Senthilkumarl The change has been applied.  The issue could be closed?

**Comment by rmackay9** [comment]
great. closing..
