### ISSUE TITLE
OmnibusF7V2 doc page need some corrections

### ISSUE THREAD

**Issue by ninja-zx11** [ArduPilot/ardupilot_wiki#1819]
Docs page of OmnibusF7V2 needs some more info added and need some corrections.Current doc is found here:[http://ardupilot.org/copter/docs/common-omnibusf7.html](url)

I am attaching the corrected text.I am new and don't know how it works.So could anyone update the current doc with the text found in the attached file?Thanks.
[wiki.txt](https://github.com/ArduPilot/ardupilot_wiki/files/3346194/wiki.txt)

**Comment by Hwurzburg** [comment]
I have created a PR #1820....corrected formatting and spelling.... thanks....we may need to change the FRsky stuff until the capability is released in all vehicle stable versions...then re-update the wiki...

...you might try to setup GIT on your computer, and clone the wiki....you can make changes directly on the web origin repository then...you do not have to do most of them locally...just get a repo clone on Github
