### ISSUE TITLE
Install Firmware

### ISSUE THREAD

**Issue by godesady** [ArduPilot/ardupilot_wiki#1826]
Critical message: "MAVLink Version or Baud Rate Mismatch" "Your MAVLink device seems to use the deprecated version 0.9, while APM Planner only supports version 1.0+. Please upgrade the MAVLink version of your autopilot. If your autopilot is using version 1.0, check if the baud rates of APM Planner and your autopilot are the same."

**Comment by magicrub** [comment]
try Mission Planner
