### ISSUE TITLE
Learning the ArduPilot Codebase

### ISSUE THREAD

**Issue by xinshaou** [ArduPilot/ardupilot_wiki#1828]
[Learning the ArduPilot Codebase](http://ardupilot.org/dev/docs/learning-the-ardupilot-codebase.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by khancyr** [comment]
Hello,

you didn't add issue description. I am closing this until you add some description.
Thanks for
