### ISSUE TITLE
Plane 3.4 updates

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/ardupilot_wiki#183]
Plane 3.4 et al have added some new functionality that may need to be documented. Action to go through [release notes](https://github.com/diydrones/ardupilot/blob/master/ArduPlane/release-notes.txt) and check. Also to talk to Tridge.
- [ ] [common-Lightware SF02 Rangefinder](http://plane.ardupilot.com/wiki/common-rangefinder-sf02/) 
  -  Support for both serial and i2c in plane 3.4.0. I2C is not documented. priseborough is investigating - chase up to see if got working
- [x]  [TRAINING Mode](http://plane.ardupilot.com/wiki/training-mode/) adds support for stall prevention. 
  - Addressed by #175

**Comment by hamishwillee** [comment]
@tridge @gmorph If there are any specific issues you know about with the docs for Plane 3.4, please add them here.

**Comment by auturgy** [comment]
overtaken by events (aka now at AP3.8.x)
