### ISSUE TITLE
Add missing boards to AutoPilot Hardware Options page

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#1844]
We are missing a number of boards from our [AutoPilot Hardware Options](http://ardupilot.org/copter/docs/common-autopilots.html).  We should go through and make sure all supported boards are listed on this page.

**Comment by auturgy** [comment]
Pixhawk 4 mini is in the list

**Comment by rmackay9** [comment]
Ah, right, I'll change the title to make it more clear that we should just check that we have all boards listed on the wiki

**Comment by Hwurzburg** [comment]
Can we close this now?

**Comment by rmackay9** [comment]
Yes, we probably need to be more specific when an issue is raised like this so we know when it's complete.  Txs,closing!
