### ISSUE TITLE
Document the --no-mavproxy option for SITL

### ISSUE THREAD

**Issue by WickedShell** [ArduPilot/ardupilot_wiki#1851]
MAVProxy can cause a problem with other GCS's when it is participating in mission uploads and forwarding telemetry. In general if using a different GCS invoking SITL directly, or using the `--no-mavproxy` option with sim_vehicle.py will result in more success. This addresses https://github.com/ArduPilot/ardupilot/issues/11814

**Comment by Hwurzburg** [comment]
done...closing
