### ISSUE TITLE
Resolve wiki page build issues

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#1869]
When building the wiki pages if seems like there are many issues displayed and some of them are new-ish.

Just one example:

common-appendix.rst:11: WARNING: toctree contains reference to nonexisting document u'docs/common-training-centers'

**Comment by brunoolivieri** [comment]
I hope that I can try to help with those warnings from next week.

**Comment by khancyr** [comment]
Ideally, we should add travis to check for new warning

**Comment by brunoolivieri** [comment]
I understood that it would be a task to find errors in pages and fix them based on the warnings.

**Comment by khancyr** [comment]
To have the warning, you just have to build the wiki, the warning will be displayed on the terminal.

**Comment by brunoolivieri** [comment]
Yes, I was wondering to build, grep some warnings to try fix on the .rst files: https://pastebin.com/X8DFYCmp.

I did not get how Travis could help in this case.

**Comment by brunoolivieri** [comment]
I did a quick check, and there were 466 warnings while building the wiki:

1) 324 warnings from "undefined labels"  (~70%)
2) 93 warnings from documents that are not in any toctree (~20%)
3) 35 warnings from parameters.rst regarding "duplicate explicit"  (~8%)

Regarding 1) This look hard to crosscheck. Is there an easy way to find the missed reference?

I mean: ACRO_EXPO is missing on copter/accro_mode.rst. Would be the better solution to remove such :ref:?

Regarding 2) Does it needs to check one by one? Is it just an alarm do try to show lost pages? I am asking it because of lots of files in this situation are easily accessible.

Regarding 3)  I believe that could be removed at once on the build scripts?

**Comment by rmackay9** [comment]
ACRO_EXPO has been split into ACRO_RP_EXPO, ACRO_Y_EXPO

**Comment by brunoolivieri** [comment]
I did a draft to investigate the parameters that may have had their names changed. So, the 324 pages can be summarized to the 66 labels below. Before read each page I compared the list with [parameters page](http://ardupilot.org/copter/docs/parameters.html) to get some clues. 

@rmackay9 Please, could you check if this is what you mentioned?

| Missing label                                                    | Looks like a parameter?                                                                          | TO-DO                                                                                       |
|------------------------------------------------------------------|--------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------|
| _atc_rate_ff_enab                                                | Is it ATC_RATE_FF_ENAB?                                                                          |                                                                                             |
| acro_expo                                                        | Yes!                                                                                             | Change the label. Note: "we have split it into two parameters ACRO_RP_EXPO and ACRO_Y_EXPO" |
| adsb_list_size                                                   | Is it ADSB_LIST_MAX?                                                                             |                                                                                             |
| avd_f_action                                                     | Is it AVD_F_RCVRY?                                                                               |                                                                                             |
| brd_safety_enable                                                | Is it BRD_SAFETYENABLE?                                                                          |                                                                                             |
| channel-output-functions_flaperon1_and_flaperon2                 | no?                                                                                              |                                                                                             |
| checking the motor numbering with the mission planner motor test | no?                                                                                              |                                                                                             |
| connect-escs-and-motors                                          | no?                                                                                              |                                                                                             |
| elevon_output                                                    | no?                                                                                              |                                                                                             |
| fs_batt_enable                                                   | Is the BATT_FS_LOW_ACT (set as zero) the newer vesion of this parameter?                         |                                                                                             |
| fs_batt_mah                                                      | Is the BATT_LOW_MAH the newer versions of this parameter?                                        |                                                                                             |
| fs_batt_voltage                                                  | Are the BATT_LOW_VOLT, BATT_CRT_VOLT, and BATT_FS_VOLTSRC the newer versions of this parameter?  |                                                                                             |
| guide-flaperons                                                  | no?                                                                                              |                                                                                             |
| invertedflt_ch                                                   | Are optinals channels used with value 43 the newer approach for this parameter?                  |                                                                                             |
| lgr_servo_deploy                                                 | Is the LGR_STARTUP the newer parameter?                                                          |                                                                                             |
| lgr_servo_rtract                                                 | Is the  LGR_STARTUP the newer parameter?                                                         |                                                                                             |
| manual tuning of roll and pitch                                  | no?                                                                                              |                                                                                             |
| mission-command-list#do-mount-control                            | no?                                                                                              |                                                                                             |
| mnt_angmi_til                                                    | Is it MNT_ANGMIN_TIL?                                                                            |                                                                                             |
| mot_spin_armed                                                   | Is the MOT_SPIN_ARM the newer approach for that?                                                 |                                                                                             |
| mot_yaw_sv_max                                                   | Could be related to MOT_SPIN_MAX?                                                                |                                                                                             |
| mot_yaw_sv_min                                                   | Could be related to MOT_SPIN_MIN?                                                                |                                                                                             |
| mot_yaw_sv_rev                                                   | Could be related to MOT_YAW_SV_ANGLE?                                                            |                                                                                             |
| mot_yaw_sv_trim                                                  | ?                                                                                                |                                                                                             |
| pos_xy_p                                                         | Related fo Wheel Encoder? FLOW_POS? FOLL_POS? Visual Odometry?                                   |                                                                                             |
| px4-rover-build-with-brushless-traxxas-stampede-4wd-truck        | no?                                                                                              |                                                                                             |
| pxfmini                                                          | no?                                                                                              |                                                                                             |
| q_m_spin_armed                                                   | Is the MOT_SPIN_ARM the newer approach for that?                                                 |                                                                                             |
| q_thr_mid                                                        | Is the PILOT_THR_BHV or ACRO_THR_MID the newer approach for that?                                |                                                                                             |
| q_wp_speed_dn.                                                   | ?                                                                                                |                                                                                             |
| rc10_function                                                    | Is it the old approach to RC10_ Parameters?                                                      |                                                                                             |
| rc5_function                                                     | Is it the old approach to RC5_ Parameters?                                                       |                                                                                             |
| rc7_rev                                                          | Is is RC7_REVERSED?                                                                              |                                                                                             |
| rc9_function                                                     | Is it the old approach to RC9_ Parameters?                                                       |                                                                                             |
| rngfnd_addr                                                      | Is it the RNGFND1_PIN? Maybe RNGFND1_ADDR?                                                       |                                                                                             |
| rngfnd_debounce                                                  | Is it the                                                                                        |                                                                                             |
| rngfnd_gndclear                                                  | Is it the RNGFND1_GNDCLEAR?                                                                      |                                                                                             |
| rngfnd_max_cm                                                    | Is it the RNGFND1_MAX_CM?                                                                        |                                                                                             |
| rngfnd_min_cm                                                    | Is it the RNGFND1_MIN_CM?                                                                        |                                                                                             |
| rngfnd_orient                                                    | Is it the RNGFND1_ORIENT?                                                                        |                                                                                             |
| rngfnd_pin                                                       | Is it the RNGFND1_PIN?                                                                           |                                                                                             |
| rngfnd_pos_x                                                     | Is it the RNGFND1_POS_X?                                                                         |                                                                                             |
| rngfnd_pos_z                                                     | Is it the RNGFND1_POS_Z?                                                                         |                                                                                             |
| rngfnd_rmetric                                                   | Is it the RNGFND1_RMETRIC?                                                                       |                                                                                             |
| rngfnd_scaling                                                   | Is it the RNGFND1_SCALING?                                                                       |                                                                                             |
| rngfnd_triggr_cm                                                 | ?                                                                                                |                                                                                             |
| rngfnd_turn_angl                                                 | ?                                                                                                |                                                                                             |
| rngfnd_turn_time                                                 | Is it the RNGFND1_SETTLE?                                                                        |                                                                                             |
| rngfnd_type                                                      | Is it the RNGFND1_TYPE?                                                                          |                                                                                             |
| rover-motor-and-servo-connections_skid-steering                  | no?                                                                                              |                                                                                             |
| sail_no_go_angle                                                 | no?                                                                                              |                                                                                             |
| speed_turn_dist                                                  | ?                                                                                                |                                                                                             |
| speed_turn_gain                                                  | ?                                                                                                |                                                                                             |
| sr2_positioin                                                    | Looks like a typo from: SR2_POSITION                                                             |                                                                                             |
| vel_xy_p                                                         | Something related to FHLD_XY_P?                                                                  |                                                                                             |
| vtail_output                                                     | ?                                                                                                |                                                                                             |
| wp_overshoot                                                     | ?                                                                                                |                                                                                             |
| wp_speed                                                         | ?                                                                                                |                                                                                             |
| wpnav_loit_jerk                                                  | Is it the LOIT_BRK_JERK? Maybe something from WPNAV_ Parameters?                                 |                                                                                             |
| wpnav_loit_maxa                                                  | Maybe something from WPNAV_ Parameters?                                                          |                                                                                             |
| pnav_loit_mina                                                   | Maybe something from WPNAV_ Parameters?                                                          |                                                                                             |
| wpnav_loit_speed                                                 | Maybe something from WPNAV_ Parameters?                                                          |                                                                                             |
| connect-escs-and-motors                                          | no?                                                                                              |                                                                                             |
| learn_ch                                                         | Compass learn? Throttle learn? Temperature learn?                                                |                                                                                             |
| mag_enable                                                       | Would be COMPASS_ORIENT or COMPASS_EXTERNAL?                                                     |                                                                                             |

**Comment by Hwurzburg** [comment]
Bruno. I am working on the errors for plane specific stuff right now...
fyi, many labels are deprecated but still need to be there to support older versions, so they wont have valid refs....I just eliminate the ref, but keep the param label if its obsolescence isn't horribly ancient....like INVERTEDFLT_CH

**Comment by brunoolivieri** [comment]
Hi Henry,

Nowadays the wiki just present last Ardupilot repo parameters list. There is an Issue asking to maintain a version for each stable release, but I believe that will not be done short.

I am afraid to maintain some old parameters listed by removing the refs without any leave any documentation or indicative of a deprecated information. 

I guess that the build warnings are the only indicative of old information about parameters that we have. Without this warning in the build I am afraid that could be lost. 

Maybe would be better flag it to next wiki call that we will be present. Let me know your thoughts.

**Comment by brunoolivieri** [comment]
@rmackay9 , please, 

MAG_ENABLE used to be an old parameter?

**Comment by rmackay9** [comment]
@brunoolivieri, yes, it's been zapped somewhat recently (in the last few months) so it probably still exists in the stable versions but it will be gone in the next stable versions which should go out over the next few months.

**Comment by Hwurzburg** [comment]
Closing now....all wiki build problems (except the code block error which I will continue to work on, and the delayed merge items) are now resolved....
