### ISSUE TITLE
Common: add SPL telemetry link to our Telemetry landing page

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#1896]
I think we should add a link to our Telemetry landing page that points users to the SPL solution for 3G/4G (or whatever it is!) telemetry.  [There is a blog post here about it](https://discuss.ardupilot.org/t/stretching-comm-links-from-indoors-to-the-globe/45896) and we've already done the same for a competing product called UAVCast.

**Comment by auturgy** [comment]
Yup. FYI SPL is an Iridium satcom datalink

**Comment by adnan-ulhaque** [comment]
NAT Traversal through telecomm / sattelite service provider is the key here. I believe this an extremly important topic to connect telemetry+fpv over bvlos (beyond visual line of sight). UAVcast and other alternatives are not free . There are free public cloud services where Raspberry Pi (with Pixhawk) can be connected to MP on TCP via any data cellular SIM e.g. below...

https://discuss.ardupilot.org/t/fpv-over-internet-via-rpi3/22597?u=adnan_ul_haque

**Comment by Hwurzburg** [comment]
PR# 2178 addresses this
