### ISSUE TITLE
Job Openings in Dev Team

### ISSUE THREAD

**Issue by auturgy** [ArduPilot/ardupilot_wiki#1909]
[Job Openings in Dev Team](http://ardupilot.org/dev/docs/job-openings.html) - Noting @IamPete1 and @peterbarker are looking after Tracker now, and the wiki efforts of Henry, Bruno et al, we may wish to edit this page.

**Comment by rmackay9** [comment]
yes i agree.

**Comment by rmackay9** [comment]
@Hwurzburg, yes, I agree.  We always welcome new developers of course but we've got the maintainers now that we were looking for.

**Comment by Hwurzburg** [comment]
Will leave the page but modify...ie nothing now, but check back every quarter or so

**Comment by Hwurzburg** [comment]
done...closing
