### ISSUE TITLE
Wrong BRD_RTC_TYPES value on some ROS pages

### ISSUE THREAD

**Issue by anbello** [ArduPilot/ardupilot_wiki#1932]
On following wiki pages:
http://ardupilot.org/dev/docs/ros-timesync.html
http://ardupilot.org/dev/docs/ros-aruco-detection.html
http://ardupilot.org/dev/docs/ros-aruco-detection.html
it is written to set the value of BRD_RTC_TYPES to 1 but the correct value to have MAVLINK_SYSTEM_TIME is 2.

**Comment by tridge** [comment]
fixed, thanks!
