### ISSUE TITLE
Building ArduPilot for APM2.x on Windows with Make - verify for Plane

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/ardupilot_wiki#199]
[Building ArduPilot for APM2.x on Windows with Make](http://dev.ardupilot.com/wiki/building-ardupilot-for-apm2-x-on-windows-with-make/) -has not been verified for Plane - needs to at least find a "known good version" for which this works.

Some [discussion here](https://groups.google.com/forum/#!topic/drones-discuss/KfV6pv-w0qw)

**Comment by davidbuzz** [comment]
For developers whishing to build the ( now quite old ) code for APM 2.x you'll need the branch master-AVR and the tags from there.  see: https://github.com/ArduPilot/ardupilot/tree/master-AVR
