### ISSUE TITLE
SkyRocket parts for 2450 gps

### ISSUE THREAD

**Issue by hoppey** [ArduPilot/ardupilot_wiki#2032]
[SkyRocket](http://ardupilot.org/copter/docs/skyrocket.html) -. Need pinion gears for v2450gps

**Comment by rmackay9** [comment]
This is the wiki to-do list.  Probably best to post questions in the forums.  https://discuss.ardupilot.org/c/arducopter/skyviper

**Comment by hoppey** [comment]
Sky Viper parts discontinued? Unbelievable! One Hell of a company...I really liked them, But about time to change to a better company that has parts available for More than 2 years...I can still get parts for my 1980 Harley (AMF).........

**Comment by hoppey** [comment]
Closed issue?  WTF?
