### ISSUE TITLE
SkyRocket Hardware

### ISSUE THREAD

**Issue by hoppey** [ArduPilot/ardupilot_wiki#2035]
[SkyRocket Hardware](http://ardupilot.org/copter/docs/skyrocket-hardware.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by hoppey** [comment]
All I want is 2450 pinion gears!!!

**Comment by auturgy** [comment]
Hi @hoppey 
As per the other issue you opened on this: please ask support questions in the forum discuss.ardupilot.org
