### ISSUE TITLE
Attopilot 180A Voltage and Current Sensor

### ISSUE THREAD

**Issue by auturgy** [ArduPilot/ardupilot_wiki#2041]
[Attopilot 180A Voltage and Current Sensor](http://ardupilot.org/copter/docs/common-using-a-current-sensor.html) - Discontinued product.  Need to mark as such.  Perhaps refer to the Mauch high current sensors, which are available.

**Comment by Hwurzburg** [comment]
I cant find anything to replace the atto pilot sensors....perhaps we should just archive the page...plenty of other hardware options are listed in its parent page...

**Comment by rmackay9** [comment]
@Hwurzburg, yes, sounds good to me.  I think this was a very old option in the early days where there was nothing else.

**Comment by Hwurzburg** [comment]
Merged #2069
