### ISSUE TITLE
rename "VIO tracking camera to "Intel RealSense"

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#2044]
I think this page's title is a bit too generic.  http://ardupilot.org/copter/docs/common-vio-tracking-camera.html

The setup is (I think) specific to the IntelRealSense 265.  Perhaps some portions of it work for other types of 3D cameras but still, I think we should make the title more specific.  I think most people are more likely to read the page if it has "Intel RealSense" in the page.

**Comment by auturgy** [comment]
It might be better to split it: a vio page, then link specific implementations under.
Particularly as there is both python and mavros implementations, plus T265, plus undoubtedly more to follow

**Comment by rmackay9** [comment]
.. but for now we only have one sensor that it works with.. so.. for now I'd just rename it.. but that's only one opinion.

**Comment by Hwurzburg** [comment]
done...closing this
