### ISSUE TITLE
Non approvers should still be able to review changes

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/ardupilot_wiki#205]
Currently only approvers can see the changes to wiki articles. It would be much better if anyone could "see" proposed changes and comment ... even if they can't approve them.

**Comment by gmorph** [comment]
This process has changed now that we have gone to github and PRs for wiki changes and we are using the PR review process so I'm going to close this.  If I've got this wrong just let me know.
Thanks, Grant.

**Comment by hamishwillee** [comment]
Agreed. Thanks.
