### ISSUE TITLE
GCS Failsafe

### ISSUE THREAD

**Issue by Sir-Lamba** [ArduPilot/ardupilot_wiki#2058]
[GCS Failsafe](http://ardupilot.org/copter/docs/gcs-failsafe.html) - 
Hello ardupiloters :grin:
I'm a new bee, carrying out a research on UAV failsafe systems.
Can GCS Failsafe be set on other GCS softwares aside Mission Planner?
How can I get access to the GCS Failsafe or any other Failsafe code? I've checked the Ardupilot master code but don't know which it is or if its there

**Comment by brunoolivieri** [comment]
Hi there,

This is the wiki to-do list. Probably best to post questions in the forums. https://discuss.ardupilot.org/

Regarding the failsafes, did you checked the parameters list? http://ardupilot.org/copter/docs/parameters.html

**Comment by Hwurzburg** [comment]
every vehicle has different code/behaviour for handling the various failsafes....first find the parameter like  FS_GCS_ENABLE and then search for that params variable name...like " failsafe_gcs" in Copter...then examine the code...

am closing this since its not a Wiki issue...
