### ISSUE TITLE
Building ArduPilot for Pixhawk/PX4 on Mac with Make

### ISSUE THREAD

**Issue by lvale** [ArduPilot/ardupilot_wiki#206]
Hi @hamishwillee 

The table on point 6 of this page:
http://dev.ardupilot.com/wiki/building-px4-with-make/
could be also used here,
http://dev.ardupilot.com/wiki/building-px4-with-make-on-mac/

 as IMHO it's clearer than the current text.

Also I believe that the build process as described is also generating the ELF Ardu* files

<img width="1074" alt="screen shot 2015-11-06 at 22 25 04" src="https://cloud.githubusercontent.com/assets/3130363/11010241/53e7af7e-84d5-11e5-83d4-bf4b97ee4acc.png">

**Comment by hamishwillee** [comment]
@lvale Agreed! I've updated http://dev.ardupilot.com/wiki/building-px4-with-make-on-mac/ - please check it.

Not sure what you mean by "Also I believe that the build process as described is also generating the ELF Ardu* files" (and if so, what changes this would imply are needed to the docs)
