### ISSUE TITLE
Add warning to DrotagX page

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#2067]
We should add a warning to the [DrotagX wiki page](http://ardupilot.org/copter/docs/common-geotagging-drotagx.html#common-geotagging-drotagx) that some developers have had difficulty getting it to work.  So we know of 3 people who say they could never get it to work, 1 who says they did get it to work.

The warning should be something like:

warning::

     ArduPilot development team members report mixed results with this product.  Some report it worked easily, others were unable to get it to work despite their best efforts.

**Comment by Hwurzburg** [comment]
#2070 merged...closing
