### ISSUE TITLE
ERLE Robitics

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot_wiki#2081]
Apparently this company no longer exists...should we archive and remove the numberous references to it?

**Comment by rmackay9** [comment]
@Hwurzburg, yes, I think that's probably fine. thanks!

**Comment by Hwurzburg** [comment]
Are there ANY Linux flight controllers being made? no Navio no ERLE...if not, should LINUX stuff be archived also?

**Comment by Hwurzburg** [comment]
PR #2084 addresses this

**Comment by proficnc** [comment]
I’d personally prefer this stayed... as the designer of the PXF, I see it as an important step in our journey.

With the new BB out, I’m actually considering another revision of the PXF

**Comment by Hwurzburg** [comment]
merged
