### ISSUE TITLE
QuadPlane Simulation no longer functions as documented

### ISSUE THREAD

**Issue by nmcobb** [ArduPilot/ardupilot_wiki#2085]
I am attempting to start a QuadPlane simulation, however when running _sim_vehicle.py -j4 -f quadplane --console --map_ as described [here](http://ardupilot.org/plane/docs/quadplane-simulation.html), I am getting a key error: KeyError: 'quadplane'.

**Comment by Hwurzburg** [comment]
did you run it from the ArduPlane directory? if not, you need to add -v ArduPlane option

**Comment by nmcobb** [comment]
Yeah, I am passing that as well...

**Comment by Hwurzburg** [comment]
Runs fine for me

**Comment by nmcobb** [comment]
Hmm, do I need to do any setup / compilation? Should I be running off of something other than master?

**Comment by peterbarker** [comment]
On Sun, 13 Oct 2019, Miles Cobb wrote:

> I am attempting to start a QuadPlane simulation, however when running sim_vehicle.py -j4 -f quadplane --console --map as described here, I am getting a
> key error: KeyError: 'quadplane'.

Almost certainly a case-sensitivity issue.
