### ISSUE TITLE
Compatible RC Transmitter and Receiver Systems

### ISSUE THREAD

**Issue by brunoolivieri** [ArduPilot/ardupilot_wiki#2097]
[Compatible RC Transmitter and Receiver Systems](http://ardupilot.org/copter/docs/common-pixhawk-and-px4-compatible-rc-transmitter-and-receiver-systems.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

I was updating Google groups old references and I am not sure with this page. Someone have a clue?

**Comment by Hwurzburg** [comment]
which one are you referring to?

**Comment by Hwurzburg** [comment]
@brunoolivieri  Bruno,update??

**Comment by brunoolivieri** [comment]
It should be closed by now...
