### ISSUE TITLE
Optitrack for Non-GPS Navigation

### ISSUE THREAD

**Issue by mareschn** [ArduPilot/ardupilot_wiki#2101]
[Optitrack for Non-GPS Navigation](http://ardupilot.org/copter/docs/common-optitrack.html) - This Tutorial is incomplete, and needs some updates.  We have identified some basic items, but I still have not succeeded in making it work.  

In order to use the stopwatch function and networking, we need to include these:
.. code-block:: c#
using System.Diagnostics;
using System.Net;
using System.Net.Sockets;

Also, @chobitsfan has helped to confirm that there is a missing line in this code:
.. code-block:: c#
public class SampleClientML {
    private static IPEndPoint drone_ep = new IPEndPoint(IPAddress.Parse("192.168.99.1"), 14550); //assume your drone is connected to PC running SampleClientML through wifi and its ip is 192.168.99.1
    private static Socket mavSock = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp);
    private static Stopwatch stopwatch;
    static void Main() {
        stopwatch = new Stopwatch();
        stopwatch.Start();

Should be this:
.. code-block:: c#
public class SampleClientML {
    private static IPEndPoint drone_ep = new IPEndPoint(IPAddress.Parse("192.168.99.1"), 14550); //assume your drone is connected to PC running SampleClientML through wifi and its ip is 192.168.99.1
    private static Socket mavSock = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp);
    private static MAVLink.MavlinkParse mavlinkParse = new MAVLink.MavlinkParse()
    private static Stopwatch stopwatch;
    static void Main() {
        stopwatch = new Stopwatch();
        stopwatch.Start();

If anyone has succeeded in making this work, please share.  The autopilot does not seem to be receiving/recognizing the mocap packets.

**Comment by prem48science** [comment]
thank you @chobitsfan, I figured out by myself. yes the above fix works and better if it's updated on the ardupilot website.
