### ISSUE TITLE
Add (Archived) note to some boards

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#2122]
We should add a note at the top of these pages to say that they're "archived"

- Qualcomm Snapdragon: http://ardupilot.org/copter/docs/common-qualcomm-snapdragon-flight-kit.html

also check the pages for other discontinued boards and make sure they've got Archived written on them

Thanks!

**Comment by rmackay9** [comment]
This article is not archived actually so we should move it out of the Archived list:

- http://ardupilot.org/copter/docs/common-tarot-gimbal.html

**Comment by Hwurzburg** [comment]
done in PR #2130
