### ISSUE TITLE
"Forum" link on left menu bar of index page

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#2132]
I'm not sure if it's new or old but I noticed a "Forum" link is on the left side of the ardupilot wiki (http://ardupilot.org/ardupilot/).  Perhaps i'm being picky instead of practical but I think this breaks the underlying rule that external links are in the upper menu and internal links are on the left bar.  Of course, if @Hwurzburg prefers it this way then I'm happy with it.

As a side note I think that AntennaTracker and Developer should be moved up under "Sub" and above "Firmware Downloads"... or maybe we should keep the same order as appears in the "Home" menu..

I also wonder if we should archive "APM Planner 2".  Perhaps it needs a team discussion but I think it's not being maintained.

**Comment by auturgy** [comment]
Last commit to apm planner was only a month ago: not hugely active, but ticking along.

Regards,

James

**Comment by Hwurzburg** [comment]
Re-ordered menu to match top menu for sites....removed forum link

**Comment by rmackay9** [comment]
I think @auturgy is right that we can leave APM Planner 2 because there is still activity there.
