### ISSUE TITLE
AMP Planner 2 Simulate

### ISSUE THREAD

**Issue by szjenter** [ArduPilot/ardupilot_wiki#2133]
[Search](http://ardupilot.org/planner2/search.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by Hwurzburg** [comment]
Closing, this issue has no information

**Comment by szjenter** [comment]
Greetings to everyone!
My question is: APM Planner 2, can I use simulation? How to get started?
Thanks for the reply!
