### ISSUE TITLE
Fix DroneKit-python links

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#2140]
We should update the links on this ArduPilot page: http://ardupilot.org/dev/docs/droneapi-tutorial.html

DroneKit Python documentation: https://github.com/dronekit/dronekit-python/blob/master/README.md

quick start guide: https://dronekit-python.readthedocs.io/en/latest/guide/quick_start.html

**Comment by Hwurzburg** [comment]
Done

**Comment by rmackay9** [comment]
Great, thanks very much!
