### ISSUE TITLE
APM Planner 2 Simulation

### ISSUE THREAD

**Issue by szjenter** [ArduPilot/ardupilot_wiki#2141]
Greetings to everyone!
My question is: APM Planner 2, can I use simulation? How to get started?
Thanks for the reply!

**Comment by brunoolivieri** [comment]
Hi @szjenter,

I am not sure that APM Planner 2 can perform a stand-alone simulation, but Mission Planner does. You could check it out.

This is a Wiki to-do list. Would be better to ask questions in the forums (https://discuss.ardupilot.org/). I am closing this issue.
