### ISSUE TITLE
Add note re Cube Orange's ADS-B on Serial5

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#2148]
I think that on this page: http://ardupilot.org/copter/docs/common-ads-b-receiver.html

We should add a note that the ADS-B sensor is attached to Serial5 on a CubeOrange.  An alternative would be to have it listed on the [product page for the CubeOrange](http://www.proficnc.com/all-products/188-the-cube.html) (that we don't control)

**Comment by proficnc** [comment]
All of our documentation is moving to the docs.cubepilot.org which is editable on github 

We just trained up a bunch of our staff, so expect edits soon :)

**Comment by Hwurzburg** [comment]
the cube orange carrier board docs indicate Serial5 is attached to ADS-B....I think we can close this now..
