### ISSUE TITLE
AP_RangeFinder: add uLanding radar page

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#2175]
We don't have a lot of info on how to connect this uLanding lidar but we should add what we can.  https://aerotenna.com/shop/%CE%BClanding-lite/

We should provide a link to the manufacturers datasheet: https://aerotenna.com/datasheets/AerotennauLandingLiteDatasheet.pdf

We support the Serial/UART form only (not the CAN yet although it is coming)

It apparently has a serial connection so I guess the setup is:

SERIALx_PROTOCOL = 9 (RangeFinder)
RNGFNDx_TYPE = 11
RNGFNDx_BAUD = 38400
RNGFNDx_MAX_CM = 4000 (40m which is slightly less than the sensor's claimed maximum range of 45m)
RNGFNDx_MIN_CM = ?

We should add a warning that the lidar may give inaccurate readings when less than 50cm from the surface.

**Comment by Hwurzburg** [comment]
addressed by #2229 
the device is no longer refered to by uLanding but rather US-D1
