### ISSUE TITLE
Auxiliary Function Switches (3.6 and earlier)

### ISSUE THREAD

**Issue by GustavoBritodeLima** [ArduPilot/ardupilot_wiki#2179]
[Auxiliary Function Switches (3.6 and earlier)](http://ardupilot.org/copter/docs/channel-7-and-8-options.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

I am using an Omnibus F4 Pro and a Kakute F7 Mini to ship the latest version of Arducopter.  Both Channel 7 and 8 (extended configuration) functions are disabled.  Any suggestion?

**Comment by Hwurzburg** [comment]
discuss.ardupilot.org is for support questions....this is for wiki issues....CHx_OPT have been replaced by RCx_OPTION in 4.0 and latest...
