### ISSUE TITLE
APSync for px4

### ISSUE THREAD

**Issue by crisdeodates** [ArduPilot/ardupilot_wiki#2190]
[APSync](http://ardupilot.org/dev/docs/apsync-intro.html) - Is there an APSync module for PX4 flight stack? Couldn't find any.

**Comment by khancyr** [comment]
Hello, 
Px4 and ArduPilot are two separated project so we won't put much work force on supporting px4 firmware (and to be honest, most of us don't know how to use it).
In case of apsync the solution would b3 quite simple, you need to change the mavlink repo from Ardupilot/mavlink to mavlink/mavlink and you will have full support of px4 mavlink.
