### ISSUE TITLE
Missing video of biwing quad tailsitter

### ISSUE THREAD

**Issue by peterbarker** [ArduPilot/ardupilot_wiki#2199]
https://youtu.be/cfqP9-2IWtQ

Differential thrust for roll/pitch.

Also has control surfaces.

http://ardupilot.org/copter/docs/common-all-vehicle-types.html

**Comment by peterbarker** [comment]
Also, perhaps this one deserves an entry?

https://www.youtube.com/watch?v=ed6Et6ENU-g&feature=youtu.be

**Comment by peterbarker** [comment]
This is a X vs + configuration for the motors.

**Comment by kd0aij** [comment]
copter tailsitters (quad+) by Pierre Losa
jetwing: https://www.youtube.com/watch?v=TtF8WSfgQhI
https://www.youtube.com/watch?v=wMVBBoANOyw
hacker wing: https://www.youtube.com/watch?v=ed6Et6ENU-g&t=2s

**Comment by kd0aij** [comment]
It appears that the only link to "all supported vehicles" is in the copter sub-wiki, yet it includes quadplanes and rovers?

**Comment by Hwurzburg** [comment]
no its in every vehicle...just not  obvious...its on each intro page as a link

**Comment by kd0aij** [comment]
maybe it would be better to have a link below "Home" on this page: http://ardupilot.org/ardupilot/

**Comment by Hwurzburg** [comment]
certainly could be added there....even  restricted once in a sub-wiki from their intro pages....and maybe should be on the home subwiki page left menu also...

**Comment by kd0aij** [comment]
This is a SITL demo of the "manual forward throttle" PR for quadplanes: https://youtu.be/QDexNUvDX0I

**Comment by Hwurzburg** [comment]
#2200

**Comment by Hwurzburg** [comment]
maybe on the Ardupilot channel...have any others besides this or from others ? otherwise if you want feedback, post it on the blog?
