### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by brunoolivieri** [ArduPilot/ardupilot_wiki#2221]
[Brushed Motors](http://ardupilot.org/copter/docs/common-brushed-motors.html) 

There is a link to Roboteq and its site seems down. Instead of remove the link, I suggest wait some time before remove the broken link.

link: https://www.roboteq.com/index.php/roboteq-products-and-services/brushless-dc-motor-controllers

**Comment by Hwurzburg** [comment]
seems to work now

**Comment by brunoolivieri** [comment]
Still preseting 403 error to me.

**Comment by khancyr** [comment]
the link is working on my side

**Comment by Hwurzburg** [comment]
me too

**Comment by brunoolivieri** [comment]
It is working here right now.  Probably something on my side. :-s
