### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by brunoolivieri** [ArduPilot/ardupilot_wiki#2222]
[Camera Gimbal with Servos](http://ardupilot.org/copter/docs/common-camera-gimbal.html)

There is a broken link*, and I do not have a suggestion good enough to update it.

*link: http://www.draganfly.com/blog/rc-aerial-photography-get-great-pictures-tutorial/

**Comment by Hwurzburg** [comment]
I think we should just remove the link...

**Comment by brunoolivieri** [comment]
I agree, PR #2264 removes that.
