### ISSUE TITLE
History of ArduPilot

### ISSUE THREAD

**Issue by auturgy** [ArduPilot/ardupilot_wiki#2231]
[History of ArduPilot](http://ardupilot.org/ardupilot/docs/common-history-of-ardupilot.html) - needs a refresh, and addition of the 4.0 releases

**Comment by rmackay9** [comment]
In particular I think we should add a link to that blog post of the person who flew it on the north or south pole..  I'm pretty sure that AP has flown in the Artic but not quite at one of the poles.

**Comment by brunoolivieri** [comment]
I guess these are the links you mentinoned:

https://discuss.ardupilot.org/t/ardupilot-flew-on-the-north-pole/47418

https://www.youtube.com/watch?v=Ar-kL-wY0qg

**Comment by rmackay9** [comment]
@brunoolivieri, yes, that's it, thanks!

**Comment by Hwurzburg** [comment]
#2442
