### ISSUE TITLE
FrSky Telemetry

### ISSUE THREAD

**Issue by maciek01** [ArduPilot/ardupilot_wiki#2262]
[FrSky Telemetry](http://ardupilot.org/copter/docs/common-frsky-telemetry.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

suggestion to add the following mentions:

-Cube Orange (will the same cable work as with black?)
-JumperTX T16 with multi protocol module

**Comment by Hwurzburg** [comment]
#2352 added T16.....dont think we need to mention every autopilot/cable....C&T has cables that fit every  one even if they dont mention them all by name....you can figure which one is needed by its connector, which they do show...thanks for the suggestions!
