### ISSUE TITLE
UAVCAN Setup

### ISSUE THREAD

**Issue by auturgy** [ArduPilot/ardupilot_wiki#2267]
[UAVCAN Setup](http://ardupilot.org/copter/docs/common-uavcan-setup-advanced.html) - Needs a refresh to describe/link expanded UAVCAN sensor options.

**Comment by tridge** [comment]
we support:
 - airspeed
 - baro
 - compass
 - rangefinder
 - LED
 - buzzer
 - safety switch
 - GPS
 - batt monitor

**Comment by Hwurzburg** [comment]
Wiki PR #2273
