### ISSUE TITLE
Let's Encrypt SSL certificate on website

### ISSUE THREAD

**Issue by tenten8401** [ArduPilot/ardupilot_wiki#2276]
I don't know if this is the right repository, but it'd be extremely nice to have SSL support on the main website, especially since most browsers now have a "not secure" badge next to the URL. https://letsencrypt.org/ gives out certificates for free, is completely automated and takes like 5 minutes to set up.

I know we aren't really transferring anything sensitive, but it'd be nice to have to prevent MiTM attacks among other things.

**Comment by khancyr** [comment]
Hello, 

That something we discuss from some time already but that have, to my knowledge, more implications than just use let's encrypt : SEO, wildcard support, etc.
Anyways, some of us are already working on this. It should come fast.

Thanks for pointing it out !

**Comment by auturgy** [comment]
@tridge i think we can close this

**Comment by jpkh** [comment]
I can add certs on wiki. We are using LE certs on many of our other websites but not  in wiki

**Comment by auturgy** [comment]
LE certs have been implemented.
