### ISSUE TITLE
Add description of how to setup multiple RC receivers

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#2301]
It came up in the Dec 2019 partners call that we should add documentation on how to setup multiple receivers.

Some points include:

- the 2nd receiver must use a serial protocol and can be connected to any serial port
- the ranges used for both receivers will be the same (i.e. held in the RCx_ parameters) so users need to be careful that the output from the transmitter/receiver is the same for both
- receivers need to be setup to output "no pulses" during a failsafe because we can't use the low-throttle method to failover to the second receiver
- if using frsky (which is a popular choice), some kind of frsky converter-thingmy is required OR users should use an autopilot with an STMF7 (or H7?) chip that supports making some config change to the serial port that is required (sorry I don't know what this is)

**Comment by Hwurzburg** [comment]
PR #2327

**Comment by Hwurzburg** [comment]
done
