### ISSUE TITLE
Mateksys F405-Wing:WS2812 leds

### ISSUE THREAD

**Issue by auturgy** [ArduPilot/ardupilot_wiki#2310]
[Mateksys F405-Wing](https://ardupilot.org/copter/docs/common-matekf405-wing.html) - Need to identify that output groups are relevant for LEDs too.
Ref: https://discuss.ardupilot.org/t/matek-f405-wing-neopixel/49955/3
This will apply to all boards obviously but might as well start here.

**Comment by Hwurzburg** [comment]
#2314

**Comment by Hwurzburg** [comment]
done...thanks
