### ISSUE TITLE
Website 404 on root page

### ISSUE THREAD

**Issue by ThisIsTheOnlyUsernameAvailable** [ArduPilot/ardupilot_wiki#2311]
Hi,
I googled 'arduplane' and followed the first provided hit, which directs to http://plane.ardupilot.org/.  This 404's, with no redirect to the correct landing page.

The same issue happens with 'arducopter', which directs to http://copter.ardupilot.org/.

I'd suggest you need to either mirror the root page to this URL, or offer a redirect to catch people googling and getting stuck.

**Comment by auturgy** [comment]
Thanks for the report. Fix in progress.

Regards,

James

**Comment by peterbarker** [comment]
Should be fixed.  Please test.

**Comment by ThisIsTheOnlyUsernameAvailable** [comment]
Looks great.  Thanks for the speedy fix.
