### ISSUE TITLE
Wheel Encoders

### ISSUE THREAD

**Issue by adalta87** [ArduPilot/ardupilot_wiki#2318]
Please change the ground testing from MP status screen RPM 1 and RPM 2 to make sure wheel encoders are working please Crtl-F within MP and select mavlink inspector, scroll to the bottom of the status messages to wheel_distance. The values will change if wheel encoders are working correctly.
![wheel_encoder](https://user-images.githubusercontent.com/22821839/70407787-e015c000-1a02-11ea-919f-f74aac7b884a.JPG)

**Comment by rmackay9** [comment]
Yes, I think this is a good change to make, 4.0 users should check the WHEEL_DISTANCE.distance vlaues instead of RPM.

**Comment by Hwurzburg** [comment]
done...closing

**Comment by adalta87** [comment]
henry your the shit! You shouldn't be working on Christmas eve hahahah!
Happy Holidays!
