### ISSUE TITLE
Loading MP on Windows 7Pro

### ISSUE THREAD

**Issue by GROO254** [ArduPilot/ardupilot_wiki#2320]
[Loading Firmware onto ChibiOS-only boards](https://ardupilot.org/plane/docs/common-loading-firmware-onto-chibios-only-boards.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by proficnc** [comment]
Please raise technical problems in the discussion forums

**Comment by GROO254** [comment]
Thank you. Groo is new to the MP world and having the software go Gump, is a bit perplexing and annoying. Thanks again.
