### ISSUE TITLE
Create Xracer build instructions in dev wiki

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/ardupilot_wiki#233]
New feature [discussed here](https://groups.google.com/forum/#!msg/drones-discuss/IUlLAKVZBr0/JpimC_hdCQAJ).

**Comment by rmackay9** [comment]
let's put a video in there like this one (until a better one arrives): https://www.youtube.com/watch?v=YNlDeSOwWi0

**Comment by rmackay9** [comment]
we can also mention that the reason that it's smaller is that it is different from the Pixhawk in that it does not have the I/O chip on it.  This also slightly reduces lag between the control and pwm outputs.

**Comment by davidbuzz** [comment]
AFAIK the Xracer was released as the "pixracer", which is now well documented, so this issue can be closed.  see https://github.com/ArduPilot/ardupilot_wiki/search?utf8=%E2%9C%93&q=pixracer
