### ISSUE TITLE
Antenna Tracking

### ISSUE THREAD

**Issue by fishworx** [ArduPilot/ardupilot_wiki#2340]
please see youtube link below.... I'm using an adrupilot for the tracker. It's powered via a 2s battery. The servo on ch2 buzzes (disconnected).

Am I doing this right? The documentation doesn't really describe how to setup or operate?

https://youtu.be/2mg4l-uS_Vc

**Comment by brunoolivieri** [comment]
Hi @fishworx , 

This is the Wiki to-do list, it is not the right place to post questions. I will close the issue for this reason.

Regarding your antennatracker, the best place to ask for questions is the forum: https://discuss.ardupilot.org/c/antennatracker . I suggest you read old questions and post new questions there. The community is very helpfull.
