### ISSUE TITLE
arspd-fbw-max-maximum-airspeed, possibly wrong definition

### ISSUE THREAD

**Issue by teodoryantcheff** [ArduPilot/ardupilot_wiki#2393]
https://ardupilot.org/plane/docs/parameters.html#arspd-fbw-max-maximum-airspeed

I think stating **ARSPD_FBW_MAX** needing to be "..._at least 50% above **ARSPD_FBW_MAX**_..." is wrong.
I think it should read "...50% above **ARSPD_FBW_MIN**..."

**Comment by Hwurzburg** [comment]
thanks....#13153 addresses this
