### ISSUE TITLE
Tidy CLI pages in Dev Wiki

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/ardupilot_wiki#24]
All CLI content was moved to dev wiki as part of #15 . This task is to tidy those remaining documents. 

```
Mission Planner Terminal
    common-CLI Setup Test modes
    common-Mission Planner Command Line Interface (CLI)
    Mission Planner Command Line Interface (CLI)
    Using the Command Line Interface
    Setting up flight modes with the CLI
    Using the Command Line Interface to Configure APM:Copter
```

**Comment by auturgy** [comment]
@peterbarker is the CLI dead yet?  Can the pages be removed and this issue closed?

**Comment by peterbarker** [comment]
On Sun, 15 Oct 2017, auturgy wrote:

> @peterbarker is the CLI dead yet? Can the pages be removed and this issue
> closed?

CLI is dead.

**Comment by auturgy** [comment]
thanks: I'll dig through and kill the CLI pages tomorrow.

**Comment by Hwurzburg** [comment]
@auturgy can this be closed now?

**Comment by Hwurzburg** [comment]
all pages are archived...closing this
