### ISSUE TITLE
Holybro Kakute F7 wrong orinetation

### ISSUE THREAD

**Issue by mafrmt00** [ArduPilot/ardupilot_wiki#2410]
When using Kakuten F7 with ardupilot.
Setup Steps:
- Replace bootloader via DFU
- Flash firmware through Misson Planner

For roll, left and right is swapped.

When changing the board orientation, so that OSD works, powering up leads to a instant flip of the copter.

Using it with the default orientation (As it is mountet) the copter also intsantly flips on throtteling up.

The board/copter works with default board orienation(As it is mounted) in betaflight.

**Comment by rmackay9** [comment]
Thanks for the report.  This should really go onto the main flight code issues list: https://github.com/ArduPilot/ardupilot/issues but in any case, I'm surprised this hasn't come up before.  I think we have numerous KakuteF7 users including @andyp1per.

**Comment by andyp1per** [comment]
@mafrmt00 lot's of people using this without issues. Can you specify which exact board you are using? How are you determining that left and right are swapped? The OSD horizon should move in the opposite direction to your roll

**Comment by mafrmt00** [comment]
Sorry,misinterpreted the OSD.
