### ISSUE TITLE
LEDs: split external LEDs into two pages (or maybe three if we want a landing page)

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#2423]
I think we should split the [External LEDs](https://ardupilot.org/copter/docs/common-external-leds.html) page into a landing page and then under this have separate ToshibaLED and NeoPixel LED pages.

The landing page should perhaps keep a link to the other wiki page that describes the meaning of the lights and perhaps there's other general information about LEDs that could also remain on the landing page.

The key reason I bring this up is that I think we need more detailed information on how to setup the NeoPixel LEDs at least based on what I see in this discussion: https://discuss.ardupilot.org/t/ws2812b-neopixel-integration/48580

**Comment by Hwurzburg** [comment]
I would need info on all the LED types, since there are many more than Toshiba and Neopixel supported, and how each one is connected.....who can explain that to me?

**Comment by Hwurzburg** [comment]
#2423 addresses this, I hope...but #2424 must be merged first since it has an image required...
rather than splitting into multiple pages now, I think this is sufficient, I think that we need to also update the servo outputs page and I have put it on my list...

**Comment by Hwurzburg** [comment]
@rmackay9 okay to close?

**Comment by Hwurzburg** [comment]
closing
