### ISSUE TITLE
reduce whitespace around BiCopter image

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#2429]
Great to see the bicopter info on the wiki. https://ardupilot.org/copter/docs/connect-escs-and-motors.html.

It's a really small thing but I think we should reduce the white space especially at the top of the bi-copter image.  I'd do this myself but I don't have a good picture editing software.  Windows Paint seem to turn transparent pixels white which isn't good.

**Comment by Hwurzburg** [comment]
done
