### ISSUE TITLE
Archived:Connecting the Radio Receiver (APM2)

### ISSUE THREAD

**Issue by Super4rover** [ArduPilot/ardupilot_wiki#2448]
[Archived:Connecting the Radio Receiver (APM2)](https://ardupilot.org/rover/docs/common-connecting-the-radio-receiver-apm2.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

hi, recently i have bought this sonar sensor MB1240, i want to make my rover to do a distance avoidance or the rover will stop when there is obstacle, but i think there are some problems that i had encountered. can you help me with it?  there is no box to enable the sonar sensor and no option to select my sonar type as well. but there are reading on the mission planner but no correct.

**Comment by rmackay9** [comment]
It's best to report support issues in the forums: https://discuss.ardupilot.org/c/ardurover

But as mentioned in other context, we don't support the APM boards anymore.

I'm going to close this issue, sorry to be strict but other wise our to-do list turns into a support forum (and we already have one of those).

Txs for using AP!
