### ISSUE TITLE
Task function requirements

### ISSUE THREAD

**Issue by kenking2536** [ArduPilot/ardupilot_wiki#2463]
1.At present, the way to change the position of waypoint is too simple, only by modifying the direct input longitude and latitude to let the coordinates or the mouse directly drag the waypoint to move the position coordinates. The position of this waypoint cannot be moved by modifying the parameters of distance and azimuth.
2.If the position of the waypoint cannot be moved by modifying the parameters of the distance and azimuth, and the exact position of the waypoint cannot be effectively controlled, for example, I need to execute an UAV take-off and fly to the first waypoint, which is 100 meters from the north of the H point, the way of manually dragging the waypoint with the mouse will be very inaccurate, and there will always be a deviation of one or two degrees in the azimuth, and the distance will also be With the corresponding deviation, it's basically difficult to achieve exactly the same.
3.In order to improve the way of coordinate modification, you can input the corresponding parameters in the distance and azimuth to make the waypoint change, and automatically calculate the lat (latitude) and long (longitude), and display them in the command bar.

### How to add or modify specific code in source code?

**Comment by Hwurzburg** [comment]
@kenking2536 Sorry, but this is not the place to enter a code enhancement request for mission planner...this is for code documentation issues only....please copy this over to https://github.com/ArduPilot/MissionPlanner/issues
closing this here...sorry
