### ISSUE TITLE
Update wiki for circle mode rate/radius control

### ISSUE THREAD

**Issue by Pedals2Paddles** [ArduPilot/ardupilot_wiki#2478]
The wiki needs to be updated to reflect the recent changes to circle mode from https://github.com/ArduPilot/ardupilot/pull/13188.  I'll do it, hopefully this week. This issue is mostly because I keep forgetting and need the reminder.

**Comment by Hwurzburg** [comment]
#2481

**Comment by Pedals2Paddles** [comment]
Well you guys move faster than me! I made two comments, one for a spelling error and one for the reversing of the up and down. Other than that, LGTM! Thanks!

**Comment by Hwurzburg** [comment]
closding
