### ISSUE TITLE
Add kakutef7 mini to Autopilot Hardware Options page

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#2486]
At some point we've added support for the kakutef7 mini but missed adding new pages under the [Autopilot Hardware options page](https://ardupilot.org/copter/docs/common-autopilots.html).

- [manufacturer page](http://www.holybro.com/product/kakute-f7-mini-tekko32-f3-4in1-45a-mini-esc-stack/)
- [firmware](https://firmware.ardupilot.org/Copter/stable/KakuteF7Mini/)

**Comment by Hwurzburg** [comment]
#2491
