### ISSUE TITLE
Create Rover Introduction/Features page and move current intro to "what you'll need"

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/ardupilot_wiki#249]
Rename the current [Rover Introduction](http://rover.ardupilot.com/wiki/gettit/) to "What you'll need" and create a new Introduction, modeled on [Copter Introduction](http://copter.ardupilot.com/wiki/introduction/) which provides a high level feature overview and positioning of Rover.

**Comment by Hwurzburg** [comment]
I think this is pretty well done now....closing
