### ISSUE TITLE
Controlling Input Throw, Trim and Reversal

### ISSUE THREAD

**Issue by lynnmaeu** [ArduPilot/ardupilot_wiki#2496]
[Controlling Input Throw, Trim and Reversal](https://ardupilot.org/plane/docs/rc-throw-trim.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by auturgy** [comment]
Closing. No issue articulated.
Feel free to reopen if you have details of the issue. If you’re after user assistance, please post on discuss.ardupilot.org
