### ISSUE TITLE
Common: add documentation for moving baseline (yaw from two GPSs)

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#2509]
AP-4.0.x (for all vehicles) supports "moving baseline" which involves using two RTK GPSs (normally Ublox F9 GPS) to calculate yaw.

The setup under 4.0 is quite difficult but it will be much easier for the 4.1 releases.  We should document the setup for the 4.1 releases even before they are available because a significant number of people want to test this even before it goes out.

**Comment by Hwurzburg** [comment]
think this is closed now
