### ISSUE TITLE
Landing Gear: typo for when plane retracts gear

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#2510]
I think that this page has a typo. https://ardupilot.org/copter/docs/common-landing-gear.html

> For Plane, it will **deploy** after a Takeoff is completed in AUTO mode, during the final glide phase of a LAND in AUTO mode, or final descent phase of a VTOL landing.

Surely it **retracts** after a Takeoff is completed no?  @tridge

**Comment by Hwurzburg** [comment]
fixed #2532

**Comment by rmackay9** [comment]
@Hwurzburg, thanks very much!
