### ISSUE TITLE
EPM Gripper doc out of date for Copter 3.3

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/ardupilot_wiki#252]
[EPM Gripper](http://copter.ardupilot.com/wiki/common-electro-permanent-magnet-gripper/) doc is out of date as of Copter 3.3. Need @rmackay9 help to find out how integration has changed.

**Comment by brunoolivieri** [comment]
The file history shows updates from 2016 to last December. 

I think that the original intention of the issue is complete and the issue could be closed. Otherwise, what should be added on the page?

**Comment by rmackay9** [comment]
yes, I think it's up to date..
