### ISSUE TITLE
BLHeli: mention AP's does not support bi-directional DShot

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#2521]
AP does not support all BLHeli features according to the discussion with @tridge here: https://discuss.ardupilot.org/t/pixhawk-4-holybro-arducopter-3-6-9-4-0-1rc3-no-control-over-two-motors-in-an-x8-with-dshot/51480/71

We should make clear which DShot/BLHeliTelemetry features AP supports:

- ArduPilot does not implement bi-directional DShot
- ArduPilot does not support the non-DShot mechanism of sending a low-throttle value to the ESC to trigger the ESC to send telemetry data.  Do we have a better name for this method?

**Comment by Hwurzburg** [comment]
added to pending PR 2502

**Comment by Hwurzburg** [comment]
merged, closing
