### ISSUE TITLE
Rangefinders (landing page)

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/ardupilot_wiki#2533]
[Rangefinders (landing page)](https://ardupilot.org/copter/docs/common-rangefinder-landingpage.html) 
The page fails to mention what the old RNGFND_ parameters translate to in ver 4.0   is it RNGFND1_ or any other number, or RNGFNDA_ ?

**Comment by Hwurzburg** [comment]
added a note on https://ardupilot.org/copter/docs/common-rangefinder-setup.html
