### ISSUE TITLE
Duplicate Node com.hex.here../125!

### ISSUE THREAD

**Issue by coptrdr2** [ArduPilot/ardupilot_wiki#2551]
[Search](https://ardupilot.org/copter/search.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by Hwurzburg** [comment]
without detailed information, this will be closed tomorrow

**Comment by coptrdr2** [comment]
When attempting to fly a quadcopter with  Arducopter 4.02 firmware and CAN GPS firmware 1.3.19 we keep getting duplicate node com.hex.here../125! prearm error.  The GPS is configured with the switch in the CAN position and the pixhawk is set to GPS_Type to 9 UVCAN.. We have built several (75+) machines without any problems.

**Comment by Hwurzburg** [comment]
Sorry you are having an issue...setup and support issues and questions should be entered in the appropriate support forum: discuss.ardupilot.org...
this area (GitHub) is for corrections or additions to the Wiki documentation...
closing
