### ISSUE TITLE
Automatic rudder control

### ISSUE THREAD

**Issue by uavengine** [ArduPilot/ardupilot_wiki#2558]
[Flight Features](https://ardupilot.org/plane/docs/flight-features.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by khancyr** [comment]
hello,

Without question or pointing what is wrong, we will close this issue

**Comment by uavengine** [comment]
Thank you for the notification:

I have a question Mission planner(It contains so many parameters) about the parameter for Takeoff mode.
I was not clearabout the servomotor control.

In manual mode,AILRON and Rudder move independently,

But if we setTakeoff mode, FBWA or Takeoff mode, Auto,

If we move lever (Ail)of Prop, then both AILRON and Rudder move simultaneously that motioncaused instability during Taxiing.

If it moved AILRONand Elevator upward, it will be stable.   How we can set thecombination of servo

(AIL,RUDDER)-->(AIL, Elev upward)

 

This is myquestion

 


 
    On Friday, February 21, 2020, 12:47:08 PM UTC, Pierre Kancir <notifications@github.com> wrote:  
 
 
hello,

Without question or pointing what is wrong, we will close this issue

**Comment by Hwurzburg** [comment]
@uavengine Sorry but this is for issues with the Wiki documentation, not support questions. Please ask those in the discuss.ardupilot.org forums for assistance with your application. However, in non-Manual modes, the parameter KFF_RDDRMIX is used to mix rudder with aileron input.
