### ISSUE TITLE
Copter references to THR_MAX and THR_MIN

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot_wiki#2577]
Many references to these non-existent parameters throughout the wiki....many common param descriptions use these references which only apply to plane now,evidently....like ARMING_REQUIRE, THROW in copter, all the BATT WATT params...

**Comment by rmackay9** [comment]
I've fixed the THROW parameter descriptions so they don't mention THR_MIN.  Not a complete solution to this issue but one step.

**Comment by Hwurzburg** [comment]
What do you suggest we do for ARMING_REQUIRE and the BATT_WATT params....also, shouldnt I add the BATT_WATT params to a section on the current limiting wiki page?

**Comment by Hwurzburg** [comment]
fixed in wiki
