### ISSUE TITLE
Plane inconsistencies with ARSPD_FBW_MAX definition

### ISSUE THREAD

**Issue by disgruntled-patzer** [ArduPilot/ardupilot_wiki#2587]
See thread here: https://discuss.ardupilot.org/t/arspd-fbw-max-definitions-inconsistent-across-documentation/42603

- The complete parameter list states that ARSPD_FBW_MAX should be slightly less than level flight speed at THR_MAX (see https://ardupilot.org/plane/docs/parameters.html#arspd-fbw-max-maximum-airspeed)
- The TECS tuning page states that ARSPD_FBW_MAX should be set to the highest level flight speed at THR_MAX (see https://ardupilot.org/plane/docs/tecs-total-energy-control-system-for-speed-height-tuning-guide.html#complete-parameter-list)

**Comment by Hwurzburg** [comment]
fixed in #2589 closing
