### ISSUE TITLE
Hott Telemetry image has wires reversed?

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#2600]
[This discussion in the Copter-4.0 forums](https://discuss.ardupilot.org/t/graupner-hott-telemetry-doesnt-work-at-all/52995/9) suggests that we've got the wiring backwards for the Hott Telemetry connection.

Let's confirm whether the user is right and if "yes" let's update the image (the user has supplied a corrected image that we could use).

**Comment by Hwurzburg** [comment]
resolved
