### ISSUE TITLE
Link to Parrot's version of linaro arm-linux-gnueabihf toolchain is broken

### ISSUE THREAD

**Issue by rahulghangas** [ArduPilot/ardupilot_wiki#2603]
The given [link](https://github.com/Parrot-Developers/toolchains/blob/master/parrot-tools-linuxgnutools-2016.02-linaro_1.0.0-2_amd64.deb) at [Building ArduCopter for Bebop 2](https://ardupilot.org/dev/docs/building-for-bebop-2.html) returns a 404 error

**Comment by Hwurzburg** [comment]
fixed

**Comment by auturgy** [comment]
I messed up the path on the last change in this: was just about to fix it.

Regards,

James

**Comment by auturgy** [comment]
Done now (I merged it myself: just a single char change)

Regards,

James
