### ISSUE TITLE
LightWare SF10, not connecting to Arduplane on I2c, ADC or Serial

### ISSUE THREAD

**Issue by LynxGhee** [ArduPilot/ardupilot_wiki#2606]
[LightWare SF10 and SF11 Lidar](https://ardupilot.org/copter/docs/common-lightware-sf10-lidar.html) I have been trying to connect the rangefinder onto the Arduplane latest firmware, issue would be that i have tried all connections including I2C, Serial and ADC. None of them output any sonarrange, although i know its not a hardware issue, since connecting to the lightware terminal via Serial FTDI, it reads the measurement properly.

One consideration is that when attempting this on Arducopter, the I2C seemed to work fine, serial and ADC wont connect. 
Running out of ideas on what to do.

**Comment by Hwurzburg** [comment]
You should ask in the support forum: discuss.ardupilot.org...carefully read all the rangefinder docs in the wiki including the specific hardware ones for those LIDARs...
this is for documentation errors and additions....
