### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by gregoryberry** [ArduPilot/ardupilot_wiki#2607]
[Search](https://ardupilot.org/copter/search.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant. WITH FLYSKY FS-I6X TX AND FS-IA6B DO I NEED THE PPM ENCODER TO SETUP DIY 500 QUADCOPTER AND FLY

**Comment by Hwurzburg** [comment]
Please direct support questions to discuss.ardupilot.org....this is for errors in the wiki documentation....thanks
but to answer your question: that reciever has both iBus and PPM outputs, which can be directly connected to the receiver input on any Ardupilot autopilot controller

**Comment by gregoryberry** [comment]
SORRY, THANK YOU FOR YOUR TIME.
