### ISSUE TITLE
add new motoor thrust calculation

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot_wiki#2642]
in this page:
https://ardupilot.org/copter/docs/motor-thrust-scaling.html
change to use this google sheet to calculate expo:
https://docs.google.com/spreadsheets/d/1_75aZqiT_K1CdduhUe4-DjRgx3Alun4p8V2pt6vM5P8/edit?usp=sharing

**Comment by Hwurzburg** [comment]
#2643
