### ISSUE TITLE
Marco-Ublox_M8N.txtSearch

### ISSUE THREAD

**Issue by Espenf** [ArduPilot/ardupilot_wiki#2668]
[Search](https://ardupilot.org/copter/search.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by Hwurzburg** [comment]
need complete information....will close if not provided...

**Comment by Espenf** [comment]
Please close, just a mistake. Thought i searched.  Sorry.




Skaff deg Outlook for Android







On Sat, Apr 11, 2020 at 11:30 PM +0200, "Henry Wurzburg" <notifications@github.com> wrote:















need complete information....will close if not provided...
