### ISSUE TITLE
Indoor Flying Guidelines

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/ardupilot_wiki#2685]
[Indoor Flying Guidelines](https://ardupilot.org/copter/docs/indoor-flying.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

The documentation should be updated with FS_EKF_THRESH instead  GPS_FAILSAFE

**Comment by Hwurzburg** [comment]
thanks....no change to EKF_THESH is needed, I'll just remove the GPS FS mention...
