### ISSUE TITLE
update hwdef docs for SERIAL_ORDER

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot_wiki#2692]
This PR replaces UART_ORDER with SERIAL_ORDER:
https://github.com/ArduPilot/ardupilot/pull/14182
once merged we need to update the wiki for the change.
The SERIAL_ORDER option specifies uarts in the SERIALn_ parameter order, which should be a lot easier for developers to understand

**Comment by Hwurzburg** [comment]
Pretty easy, it only appears  two times in the wiki....we never really explained the funky ordering, users had to figure it out themselves....

**Comment by Hwurzburg** [comment]
merged
