### ISSUE TITLE
Pozyx for Non-GPS Navigation

### ISSUE THREAD

**Issue by Hil00091** [ArduPilot/ardupilot_wiki#2698]
[Pozyx for Non-GPS Navigation](https://ardupilot.org/copter/docs/common-pozyx.html) 

I use ArduCopter v4.0.3 in mission Planner, CU is Holybro pixhawk 4, everything is connected to Arduino UNO R3 and configured as instructed but unfortunately I get an error all the time:

V1.0
Assertion failed in function: setTxPower
Filename: C:\Users\qwerf\Documents\Arduino\libraries\Pozyx-Arduino-library-master\Pozyx_lib.cpp
Line number: 337

What a mistake I'm making, Please help.

![IMG_20200429_215526](https://user-images.githubusercontent.com/51081608/80640977-7905b000-8a64-11ea-8a1e-74b37c3c2668.jpg)
![arduino uno anchor id](https://user-images.githubusercontent.com/51081608/80640989-7dca6400-8a64-11ea-85d0-168de5db1fa2.jpg)
![arduino uno error](https://user-images.githubusercontent.com/51081608/80640999-802cbe00-8a64-11ea-9db8-883255798c23.jpg)

![pozyx anchors and tag](https://user-images.githubusercontent.com/51081608/80641444-2d9fd180-8a65-11ea-9d87-93ffd8e3aeed.jpg)

![mission planner](https://user-images.githubusercontent.com/51081608/80641779-a7d05600-8a65-11ea-94fe-4d9ffc613629.jpg)

Arduino sketch :
[pozyx_drone_mission_planner.zip](https://github.com/ArduPilot/ardupilot_wiki/files/4554262/pozyx_drone_mission_planner.zip)

**Comment by Hwurzburg** [comment]
sorry, but this if for documentation issues, not support questions....please move the content over to discuss.ardupilot.org where people who can provide will see this....thanks

however, if this is a result of a documentation error, please reopen with the specific errors...
