### ISSUE TITLE
Bootloader docs link to a 404 on github

### ISSUE THREAD

**Issue by WickedShell** [ArduPilot/ardupilot_wiki#2717]
https://ardupilot.org/dev/docs/bootloader.html has a link to `README.txt` (points at https://github.com/ArduPilot/ardupilot/blob/master/Tools/bootloaders/README.txt ) which is 404 on github. I'm pretty sure this should be swapped to be `README.md` at this point.

**Comment by WickedShell** [comment]
As an additional note the mavlink command for flashing the bootloader should probably point out that it has to be a command long. (Just saying MAVLink command is ambiguous as it could be a command_int)

**Comment by Hwurzburg** [comment]
fixed..thanks
