### ISSUE TITLE
SITL Simulator (Software in the Loop)

### ISSUE THREAD

**Issue by KevinHarper786** [ArduPilot/ardupilot_wiki#2718]
[SITL Simulator (Software in the Loop)](https://ardupilot.org/dev/docs/sitl-simulator-software-in-the-loop.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

I'm having trouble running this program. i have followed the steps for installing it on windows 10 but still no luck. Mavproxy and Cygwin are not working together , the map on Mavproxy just freezes when i start to zoom out

Can someone help ?? or give some advice

**Comment by Hwurzburg** [comment]
you should try asking on the support forum instead of this documentation update/errors repo issues list: discuss.ardupilot.org
