### ISSUE TITLE
Using SITL for ArduPilot Testing - add EKF failsafe tests

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/ardupilot_wiki#277]
Update [Using SITL for ArduPilot Testing](http://dev.ardupilot.com/wiki/using-sitl-for-ardupilot-testing/#testing_rc_failsafe) with information from [here
](https://gist.github.com/mrpollo/f307fc13bc55028723a4) - in particular how to simulate EFK fail.

**Comment by khancyr** [comment]
already donc
