### ISSUE TITLE
dev/source/docs/building-setup-linux.rst

### ISSUE THREAD

**Issue by auturgy** [ArduPilot/ardupilot_wiki#2776]
We should re-order this, so that users run the install script as the first step.
Also need to add meat to the Docker instructions - they're very light.

**Comment by Hwurzburg** [comment]
#2799 but I cant help with Docker

**Comment by Hwurzburg** [comment]
closing until someone complains of error in Docker instructions, since I cant expand them and no complaints so far...help there is alwasys welcome
