### ISSUE TITLE
CUAVv5 RC in note

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot_wiki#2784]
we should have a note on SBUS input on the CUAVv5 board. I've tested and this is how it works:

 - for the original (no longer sold) CUAVv5, SBUS input works on either the RC pin on the servo rail or on the SBUS/RSSI connector on the side
 - for the CUAVv5+, SBUS input only works on the SBUS/RSSI connector on the side, it does not work on the RC pin on the servo rail

When using the connector on the side (the 5 pin JST-GH marked as SBUS/RSSI) you must use the right cable. The following image shows the right cable in a CUAVv5+

![image](https://user-images.githubusercontent.com/831867/82852689-ed8a1c80-9f46-11ea-8655-54eb177368f5.png)

**Comment by Hwurzburg** [comment]
@tridge I put that note in the doc in Feb.....and the doc has the pinout shown for the SBUS/RSSI port....James had seen the note and raised the question (which I answered) in the dev thread just before you noticed it? and did the bench test....
