### ISSUE TITLE
Links for old parameters files.

### ISSUE THREAD

**Issue by brunoolivieri** [ArduPilot/ardupilot_wiki#2822]
The script that makes multiple parameters files enables links for each parameter in each file in an individual a manner. 

It makes the wiki build slower and uses more memory due to the huge toctree (thousands of (un)used links).

IFF we do not link old parameters would be nice remove such links and enable linking only for the latest firmware of each vehicle.

What do you think?

**Comment by Hwurzburg** [comment]
we dont link any old rev params I beleive, if they are not in master, they would throw errors, if that happens, I unlink them (on archived pages,etc.) so I dont think links to other than the master set are required...

**Comment by Hwurzburg** [comment]
any progress Bruno?is this still an issue?

**Comment by brunoolivieri** [comment]
I guess we could close it now.
