### ISSUE TITLE
Misleading Description of Parameter THR_MAX in Parameter List

### ISSUE THREAD

**Issue by Rolf-G** [ArduPilot/ardupilot_wiki#2841]
The description of [THR_MAX](https://ardupilot.org/plane/docs/parameters.html#thr-max-maximum-throttlel) is: 

"Maximum throttle percentage used in **automatic throttle** modes."

After that you have to assume that THR_MAX is not used in FBWA, because FBWA is not one of the automatic throttle modes . That was annoying when there wasn't enough power to throw the plane in FBWA. (I've found another way to use THR_MAX only in auto throttle modes by enabling THR_PASS_STAB). But either you should adapt the description to the functionality or vice versa.

**Comment by vierfuffzig** [comment]
this likely just slipped through when THR_MIN was in focus last year, see https://github.com/ArduPilot/ardupilot/pull/11059 for reference.

**Comment by vierfuffzig** [comment]
https://github.com/ArduPilot/ardupilot/pull/14586

**Comment by vierfuffzig** [comment]
fix merged, can be closed

**Comment by rmackay9** [comment]
Txs!
