### ISSUE TITLE
Using SITL with RealFlight](https://ardupilot.org/dev/docs/sitl-with-realflight.html) -

### ISSUE THREAD

**Issue by marcelvdkellen** [ArduPilot/ardupilot_wiki#2842]
[Using SITL with RealFlight](https://ardupilot.org/dev/docs/sitl-with-realflight.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by brunoolivieri** [comment]
Empty issue, so closing.
