### ISSUE TITLE
FPort Receivers

### ISSUE THREAD

**Issue by LitterBugs** [ArduPilot/ardupilot_wiki#2843]
[FPort Receivers](https://ardupilot.org/copter/docs/common-FPort-receivers.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

The parameter listing for the F765-wing is slightly incorrect.  There are  multiple users that commented in the F.Port beta testing thread, including myself that have found that RC_OPTIONS =8 should not be set.  F.port does not work with it set, and works correctly when unset / =0

https://discuss.ardupilot.org/t/frsky-fport-support-testers-wanted/50669

Regards,
Karl Litterer

**Comment by Hwurzburg** [comment]
it apparently  depends on the RC receiver and what firmware revision....note added to wiki page
