### ISSUE TITLE
Shaw we remove HITL pages?

### ISSUE THREAD

**Issue by brunoolivieri** [ArduPilot/ardupilot_wiki#2849]
Based on [discord chat](https://discordapp.com/channels/674039678562861068/674039678982422579/722426629426511933), should we remove [HITL pages](https://ardupilot.org/dev/docs/hitl-simulators.html)?   

Maybe insert a flag of non updated page?

**Comment by Hwurzburg** [comment]
I will archive them

**Comment by Hwurzburg** [comment]
done
