### ISSUE TITLE
SITL Simulator (Software in the Loop)

### ISSUE THREAD

**Issue by albcem** [ArduPilot/ardupilot_wiki#2883]
[SITL Simulator (Software in the Loop)](https://ardupilot.org/dev/docs/sitl-simulator-software-in-the-loop.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

The figure for the communication architecture for SITL is outdated; the Port numbers and the pairs of software that communicate are wrong. I found the following figure online that correctly represents the current state of the communications. The owner of the figure proposed it to update the affected page but no change has been made.

![157b5fbb2737be331ba48dbedef08f1c56a17157](https://user-images.githubusercontent.com/31510084/86008954-efd11200-b9ef-11ea-8775-e22c5a2d5991.png)

**Comment by brunoolivieri** [comment]
Link to PR #1764

**Comment by peterbarker** [comment]
@Hwurzburg it does address my comments.

**Comment by Hwurzburg** [comment]
closed by #2983
