### ISSUE TITLE
Connecting Telemetry to Auvidea J120

### ISSUE THREAD

**Issue by Deepakgthomas** [ArduPilot/ardupilot_wiki#2919]
I'm looking to get a connection between my Pixhawk and Onboard GPU using telemetry. However, it doesn't seem to be connecting for some reason. I followed the instructions given on this page - https://ardupilot.org/dev/docs/companion-computer-nvidia-tx2.html

I'm able to get a signal when I connect using USB, therefore I doubt that there is a problem with my device. I'd appreciate it if anyone could come up with suggestions to debug this issue.

**Comment by Hwurzburg** [comment]
you should ask in a support forum, like  discuss.ardupilot.org....this is for confirmed wiki errors or additions...if the instructions were incorrect, then an issue can be raised here...but at this point, it could be any number of issues or setup/connection errors....so am closing this....feel free to reopen if you can confirm a wiki error and not some other cause....technical help should be available in the support questions forum....thanks
