### ISSUE TITLE
HOTT Telemetry not working

### ISSUE THREAD

**Issue by Huege** [ArduPilot/ardupilot_wiki#2986]
Dear all,

was trying to activate HOTT telemetry on ArduPlane and failed while following this setup guide: [HOTT Telemetry](https://ardupilot.org/copter/docs/common-hott-telemetry.html). Also tried out different ports. No sensors showing up at all.
My setup is F765 wing, GR12 + MZ 18 transmitter.

Thanks in advance for your support.

**Comment by Hwurzburg** [comment]
please report this in the discuss.ardupilot.org forum.....if it turns out to be something missing or inaccurate in the wiki, we can change it...but the issue must be resolved first to assure that is the case...thanks

**Comment by Huege** [comment]
done: https://discuss.ardupilot.org/t/graupner-hott-telemetry-doesnt-work-at-all/52995/22?u=guidohuelsmann

**Comment by Hwurzburg** [comment]
closing
