### ISSUE TITLE
Add video to GPS-for-Yaw page

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#2997]
I think this might be a good video to put at the top (or bottom I guess) of the [GPS-for-yaw page](https://ardupilot.org/rover/docs/common-gps-for-yaw.html):
https://www.youtube.com/watch?v=NjaIKyrInpg

**Comment by Hwurzburg** [comment]
done

**Comment by rmackay9** [comment]
oh great, thank you very much!
