### ISSUE TITLE
yaapuConfiguring a Telemetry Radio using Mission Planner

### ISSUE THREAD

**Issue by mosfetman** [ArduPilot/ardupilot_wiki#2999]
[Configuring a Telemetry Radio using Mission Planner](https://ardupilot.org/copter/docs/common-configuring-a-telemetry-radio-using-mission-planner.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by brunoolivieri** [comment]
s is empty, so I am closing it.

Please, feel free to reopen it with more details.
