### ISSUE TITLE
Sitl Opens but with " Link Down " on the Console

### ISSUE THREAD

**Issue by drnayeem** [ArduPilot/ardupilot_wiki#3012]
Hello 

Need some help 
I have installed SITL and Mavproxy with Cygwin . 
i am able to fire up and Arduplane in SITL but the Console shows an error of Link Down 

Could someone help me resolve the error 
Regards

**Comment by Hwurzburg** [comment]
try discuss.ardupilot.org to get support help on this...this is for wiki doc issues and suggestions...you probably have a setup problem of some kind....
