### ISSUE TITLE
Learning ArduPilot — Introduction

### ISSUE THREAD

**Issue by kschoos** [ArduPilot/ardupilot_wiki#3030]
[Learning ArduPilot — Introduction](https://ardupilot.org/dev/docs/learning-ardupilot-introduction.html) 

The section "Vehicle Code" says:
"Along with the *.cpp files, each vehicle directory contains a make.inc file which lists library dependencies."

However, I can't make out such make.inc files. Does this need updating?

**Comment by Hwurzburg** [comment]
@peterbarker bump!
