### ISSUE TITLE
Connect ESCs and Motors

### ISSUE THREAD

**Issue by 9friday** [ArduPilot/ardupilot_wiki#3032]
[Connect ESCs and Motors](https://ardupilot.org/copter/docs/connect-escs-and-motors.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

The article mentions that Pixhawk has issues with EMAX ESCs, but this [issue](https://github.com/ArduPilot/ardupilot/issues/2094) has a reply stating the issue has been resolved for new EMAX SimonK ESCs. 
Now has that issue been resolved for all EMAX ESCs or only specific models?

Regards.

**Comment by rmackay9** [comment]
Responded on the issue, thanks.
