### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by KI4KKT** [ArduPilot/ardupilot_wiki#3053]
New Copter Firmware will not download.  I have tried Downloading over 6 different times.
![Firmware Failed DL](https://user-images.githubusercontent.com/44986458/94374264-a8cae980-00d0-11eb-9460-2baea577083c.PNG)

**Comment by Hwurzburg** [comment]
try posting in the support forum....discuss.ardupilot.org    this is for documentation issues....
and this would be a Mission Planner Support question
