### ISSUE TITLE
SITL Simulator (Software in the Loop)

### ISSUE THREAD

**Issue by brunoolivieri** [ArduPilot/ardupilot_wiki#3055]
[SITL Simulator (Software in the Loop)](https://ardupilot.org/dev/docs/sitl-simulator-software-in-the-loop.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

@Hwurzburg : The youtube video needs to be renamed: "Ardupilot's" instead "ArdudPilot's"

link: https://www.youtube.com/watch?v=Ewh0fKGEJL4&t=476s

(I cannot fix there)

**Comment by Hwurzburg** [comment]
fixed...thanks
