### ISSUE TITLE
MSP OSD parameters missing on Cube Black & Pixhawk4

### ISSUE THREAD

**Issue by hawkairborne** [ArduPilot/ardupilot_wiki#3063]
[MSP OSD](https://ardupilot.org/plane/docs/common-msp-osd-overview.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

I am trying to use the MSP OSD on both a Cube Black and Pixhawk4. I have been speaking with Alex Apostoli(Yaapu) on the forum (https://discuss.ardupilot.org/t/msp-protocol-support/57944) and he has mentioned that the build server is not adding the OSD parameters to both of these latest firmwares. I am trying it with 4.1.0-FIRMWARE_VERSION_TYPE_DEV. Can you please update the build so that these option are present from the usual download area (https://firmware.ardupilot.org/Copter/latest/CubeBlack/)

Kind Regards,

Perry

**Comment by Hwurzburg** [comment]
not a wiki issue.....this is actually being addressed with a PR to the code.... #15495....closing this....thanks
