### ISSUE TITLE
Parachute: add documentation re CHUTE_CRT_SINK parameter

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#3066]
This parameter didn't function in Copter-4.0 but does work in Copter-4.1.  In short users should change this parameter to a reasonable maximum sink rate for their application.  For example 5m/s.

**Comment by Hwurzburg** [comment]
so did the feature just not work if there was enough motor authority to keep it level while falling? is that what the new param addresses?

**Comment by rmackay9** [comment]
yes, the parachute would not deploy if the vehicle descended while maintaining attitude control.

**Comment by Hwurzburg** [comment]
so we need to add this param to the wiki since its in stable, but note that it does not work and but has been fixed in master...

**Comment by Hwurzburg** [comment]
closing
