### ISSUE TITLE
Motor and Servo Configuration

### ISSUE THREAD

**Issue by Theunen** [ArduPilot/ardupilot_wiki#3069]
hello, 
I'm bulding a rover project with a pixhawk.
When i'm configuring the motor and steering in ardupilot it go's wrong,.
On the screen mandatory harware=> radio callibration, the signals of roll and throttle com in and give a reaction on the reading bar, so the signals come in to the right connections,...
But when i configure the servo outputs and set position 1 to ground steering and position 3 to throttle, there is no reaction of servo and motor, when i set is to RCIN 1 and RCIN 3 the motor and servo are activated, and working as expected...(so the conections of the motor and servo seems ok)
I think the rover does not want to drive autonomously because of this, the references to throttle and steering are not right

Does anyone have an idea what i'm doing wrong?
Many Thanks 
M

**Comment by rmackay9** [comment]
It's probably best to raise this in the Rover forum https://discuss.ardupilot.org/c/ardurover/rover-4-0/154

This issues list is really for to-do items to add to the wiki
