### ISSUE TITLE
Holybro Kakute F7 Mini

### ISSUE THREAD

**Issue by brad112358** [ArduPilot/ardupilot_wiki#3070]
[Holybro Kakute F7 Mini](https://ardupilot.org/copter/docs/common-holybro-kakutef7mini.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

Motor (PWM) output order is incorrect in the table below the installation guide heading.  Perhaps this was an error in the board hwdef file, but at this point, I think it's easier to fix in the documentation.  I tested this in V4.0.4 on V2.0 of the Kakute F7 Mini.

Plug pin 5 is M4, pin 6 is M1, pin 7 is M2, pin 8 is M3

**Comment by Hwurzburg** [comment]
thanks...fixed
