### ISSUE TITLE
ArduPilot Pre-Built Binaries

### ISSUE THREAD

**Issue by FlyEnjoy** [ArduPilot/ardupilot_wiki#3076]
[ArduPilot Pre-Built Binaries](https://ardupilot.org/dev/docs/pre-built-binaries.html) - F-765 RSSI Analog input
Hello community, 
I have a F-765 flashed with “arduplane_with_bl.hex” latest Version of Oct 2, 2020. 
F-765 is connected to GPS Matek MBQ-5883, AirSpeed ASPD 4525, Scherrer RX700 NR (running on PPM connected to Rx6). GPS is connected to Tx2Rx2, AirSpeed to DA2 CL2.
DJI FPV is connected to Tx1RX1. OSD is correctly shown.
I observe a systematic hang-up of the F-765  when I activate the RSSI in MissionPlanner: if I set the RSSI_TYPE = 1 (i.e. analogous) RSSI_PIN_HIGH,1.8 RSSI_PIN_LOW,1.25 and have Scherrer analogous voltage connected to the RSSI pin on F-765, write the parameters everything works fine. The RSSI is correctly shown in the OSD of DJI FPV.
However, if I repower the F-765 it crashes and the only way to get it to life is to flash the firmware and load the parameters again.
The F-765 only crashes if RSSI_TYPE=1, otherwise (for example RSSI_Type = 0, or RSSI_Type=2)  I can repower w/o trouble. This is 100% reproducible with two identical F-765 setups. 
Finally, I flashed the F-765 with the stable firmware version 4.0.6 and the RSSI_type = 1 works fine, also when repowered.
Does anyone know why this hangup occurs, and can fix it? 
Many thanks,
Rainer

**Comment by Hwurzburg** [comment]
for support issues try discuss.ardupilot.com....this is for documentation errors or additions...just copy this over there under ArduPlane4.0 topic...
