### ISSUE TITLE
Mission Planning

### ISSUE THREAD

**Issue by reduxdj** [ArduPilot/ardupilot_wiki#3086]
[Mission Planning](https://ardupilot.org/copter/docs/common-mission-planning.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

On parallels, UI overlaps and is obscured
<img width="1520" alt="Screen Shot 2020-10-17 at 6 37 26 PM" src="https://user-images.githubusercontent.com/322547/96356750-076bfd80-10a8-11eb-9eba-f196856f9597.png">

**Comment by Hwurzburg** [comment]
sorry, not a wiki issue....you can open an issue here for a Mission  Planner issue: https://github.com/ArduPilot/MissionPlanner/issues
