### ISSUE TITLE
common-Power Modules (landing page)

### ISSUE THREAD

**Issue by bujiebuhuo** [ArduPilot/ardupilot_wiki#309]
[common-Power Modules (landing page)](http://copter.ardupilot.com/wiki/common-powermodule-landingpage/) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant
Hello  I want to know where can get the the schematic of this Modules.

**Comment by hamishwillee** [comment]
Check each of the module pages. If they aren't there we don't have them - and you should ask for support from the forums.
