### ISSUE TITLE
Extended Kalman Filter (EKF)

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/ardupilot_wiki#3105]
[Extended Kalman Filter (EKF)](https://ardupilot.org/copter/docs/common-apm-navigation-extended-kalman-filter-overview.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

Image says EKF3 is WIP , in fact, it is in stable releases now..

**Comment by rmackay9** [comment]
I've fixed up the wording now in the image.  So below EKF3 it now says "Copter 4.1~".  This is more an indication of whether it's the default or not but in any case I think it is better.
