### ISSUE TITLE
How to change the default map of the simulator?

### ISSUE THREAD

**Issue by mariofaragalla** [ArduPilot/ardupilot_wiki#3110]
Hi! I am using Gazebo with the sim_vehicle.py file to simulate my quadcopter. Everything works fine, but I would like to change the default map that appears in the Map window. So could you please tell me how to do it? and with which file extension? Thank you very much.

**Comment by brunoolivieri** [comment]
This is the Wiki to-do list, you please ask questions in the forums: https://discuss.ardupilot.org/

Btw, there is a flag "-L" for the  sim_vehicle.py which you can set the home point. You can check https://ardupilot.org/dev/docs/using-sitl-for-ardupilot-testing.html#setting-vehicle-start-location

cheers
