### ISSUE TITLE
Complete Parameter List

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/ardupilot_wiki#3111]
[Complete Parameter List](https://ardupilot.org/plane/docs/parameters.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

https://ardupilot.org/copter/docs/parameters.html#arming-check-arm-checks-to-perform-bitmask says "Parameters check - (unused)"
This is contradicted by https://ardupilot.org/plane/docs/common-prearm-safety-checks.html#parameter-checks

**Comment by Hwurzburg** [comment]
you give two identical links

**Comment by AndKe** [comment]
Thank you, I fixed it now.
Short version: parameters lists (for any platform) says the "parameters check" is unused, the other page, and source, contradicts it.

**Comment by Hwurzburg** [comment]
that is not a wiki issue....there is an error in the codes metadata for that param.....when they actually started using it in Plane (for Quadplane params for ATT and POS control), they forgot to removed the unused tag...will open an issue in code side...then close this...thanks

**Comment by Hwurzburg** [comment]
since you entered a code PR, closing this one
