### ISSUE TITLE
HereFlow Optical Flow Sensor mounted on pixhawk 2.1 but there is still some drift

### ISSUE THREAD

**Issue by gryphoon-sx** [ArduPilot/ardupilot_wiki#3125]
Hello, i mounted the hereflow optical flow on my quadcopter with a pixhawk 2.1 running on the 4.0.5 firmware, i made all the necessary settings and calibrations, and the flowX is identical to bodyX, same for Y axis along with gyros, however, it seems like the pixhawk isen't taking taking into considerations the values from the sensor properly, there's still a drift on loiter and flowhold mode, however, if rotate the orientation of the sensor, the quadcopter behaves crazy which indicates that the sensor is working fine. any solution please?

**Comment by rmackay9** [comment]
This is really a support issue and I've answered in the forums so closing
