### ISSUE TITLE
Ambiguity in `TUNE_PARAM` description

### ISSUE THREAD

**Issue by arikrupnik** [ArduPilot/ardupilot_wiki#3132]
https://ardupilot.org/plane/docs/parameters.html#tune-param says about `TUNE_PARAM`:

> Parameters less than 50 are for QuadPlane vertical lift motors only.

Does this mean that these parameters do not apply to q-plane configurations without "vertical lift motors," e.g., tail sitters, or does the language simply date from the time before q-plane supported tailsitters?

**Comment by Hwurzburg** [comment]
tailsitters have vertical lift motors otherwise there is no VTOL..doesn't mater if its one, two, or more motors or copter tailsiters...the fact that in fixed wing modes they are forward motors has no bearing on VTOL pid tuning...
