### ISSUE TITLE
Compass calibration should recommend doing with GPS lock

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#3137]
We should add advice to the compass calibration page that if possible compass calibration should be done outdoors so that the "earth magnetic tables" can be used to scale the compass sensor's output to match the expected magnetic field for the user's location

**Comment by Hwurzburg** [comment]
Due to gps lock?

**Comment by rmackay9** [comment]
@Hwurzburg yes.  It's not really necessary to do the calibration outdoors, it's just necessary that the vehicle has a position estimate which it should have if the GPS has a good 3D lock.

**Comment by Hwurzburg** [comment]
done

**Comment by rmackay9** [comment]
Thank you very much!
