### ISSUE TITLE
Nooploop for Non-GPS Navigation

### ISSUE THREAD

**Issue by bcfdkl-150** [ArduPilot/ardupilot_wiki#3146]
[Nooploop for Non-GPS Navigation](https://ardupilot.org/copter/docs/common-nooploop.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.
I've download the latest coptor4.1 from https://firmware.ardupilot.org/Copter/latest/fmuv2/
But still cannot find the parameter PCN_TYPE(which is need according to the tutor: https://ardupilot.org/copter/docs/common-nooploop.html)
Is there anything wrong with the latest coptor 4.1? or there's some problem with my APM or MissionPlaner?

**Comment by rmackay9** [comment]
fmuv2 is for boards with the 1M flash limit which unfortunately don't have the code space to fit many new features including the noop loop code.  You can try loading fmuv3 instead of better yet switch to the Pixhawk1 firmware. https://firmware.ardupilot.org/Copter/latest/Pixhawk1/
