### ISSUE TITLE
Installing APM Planner for Mac : unable to proceed installation, it is not compatible with Catalina.

### ISSUE THREAD

**Issue by KK1203** [ArduPilot/ardupilot_wiki#3151]
[Installing APM Planner for Mac](https://ardupilot.org/planner2/docs/mac-install.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by alteman** [comment]
APM Planner is outdated, the only up to date app is Windows-only Mission Planner. Try running it in VirtualBox I guess..

**Comment by Hwurzburg** [comment]
asked and answered...closing

**Comment by KK1203** [comment]
Thks for reply,  I have Win10 in Mac bootcamp, mission planner now
installed there.

KK
