### ISSUE TITLE
Firmware for HCLRC  Zeus F722

### ISSUE THREAD

**Issue by Stevowonder** [ArduPilot/ardupilot_wiki#3152]
Hi 

Is there an .hex file for the HCLRC Zeus F722 flightcontroller?

**Comment by brunoolivieri** [comment]
Hello, this is the Wiki to-do list. You should post questions in discussion forum.

BTW,
Firmwares can be found here: https://firmware.ardupilot.org/
I guess the board H**G**LRC has not enough flash to use with ArduPilot.
