### ISSUE TITLE
[HKLM \ Software \ Microsoft \ Fusion! EnableLog] (DWORD) su 1Loading Firmware

### ISSUE THREAD

**Issue by aldoliana** [ArduPilot/ardupilot_wiki#3188]
[Loading Firmware](https://ardupilot.org/copter/docs/common-loading-firmware-onto-pixhawk.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by Hwurzburg** [comment]
no info....closing
