### ISSUE TITLE
common-Planning a Mission with Waypoints and Events

### ISSUE THREAD

**Issue by mrpreciado** [ArduPilot/ardupilot_wiki#320]
hey guys im having this issue with my hexa it has apm2.6 as soon as it enters to mission (auto) it drifts away with no direction in particular the other flight modes seem to respond well ,i dont know what to do any suggestions .it wont even do a waypoint

**Comment by hamishwillee** [comment]
Hi @mrpreciado 
This area is for issues with the wiki, not technical support. Can you please repost on the APM forums.
