### ISSUE TITLE
Editors and IDEs - adding Atom editor wiki

### ISSUE THREAD

**Issue by mounalbaccouch** [ArduPilot/ardupilot_wiki#3206]
https://ardupilot.org/dev/docs/code-editing-tools-and-ides.html
In this page of WIKI, I want to add the Atom editor to the list. Atom supports collaboration by sharing workspace and editing the code in the same workspace using Teletype package, and it supports working with Git and GitHub directly with the GitHub package. So, it is suitable for Ardupilot community.

**Comment by khancyr** [comment]
hello,
feel free to open a PR to add instruction for Atom

**Comment by Hwurzburg** [comment]
closing this since the PR is merged
