### ISSUE TITLE
UAVCAN GUI

### ISSUE THREAD

**Issue by auturgy** [ArduPilot/ardupilot_wiki#3253]
[UAVCAN GUI](https://ardupilot.org/copter/docs/common-uavcan-gui.html) - The download link is now a redirect to the UAVCAN forum.  We need to provide a better download link.  Noting the current state of UAVCAN, and lack of maintenance of the GUI, it might be best to host the tool ourselves.
@tridge

**Comment by Hwurzburg** [comment]
fixed link....for now...
