### ISSUE TITLE
Missing yaw torque image files

### ISSUE THREAD

**Issue by Gone4Dirt** [ArduPilot/ardupilot_wiki#3254]
Getting this warning message on build of wiki:

![image](https://user-images.githubusercontent.com/34512430/103642455-1053c900-4f4b-11eb-8923-7fd8a8d0e8c1.png)

Checked the images folder and they aren't there.  They just need adding and the file path updating I think.

**Comment by Hwurzburg** [comment]
actually they are there...but in the plane wiki...links for the common based page need to be changed...currently reflect path when moved into main wiki at 4.1 release...
#3255
