### ISSUE TITLE
Dangerous advice?

### ISSUE THREAD

**Issue by fnoop** [ArduPilot/ardupilot_wiki#326]
http://ardupilot.org/copter/docs/ac_tipsfornewpilots.html

There was a post recently on diydrones where a novice was trying to build a meter size (T960) hex with 16" CF props.  It was flipping initially and when esc order was sorted it was then leaning significantly when trying to take off.  This wiki page was cited by several people as advice to proceed and what they had done in the past.
```
" Hold the copter firmly in your hand and level in the air and with the props clear of your body, advance the throttle a bit to get a feel for what’s going on. "
```
Is this not potentially incredibly dangerous advice for newbies?  I wouldn't like to think of the potential harm that could come from large CF props if a copter tried to flip while throttle raised above someone's head.  Perhaps I'm just being silly/unreasonable, but thought I would raise it for discussion.

**Comment by hamishwillee** [comment]
Thanks @fnoop 

While I'd hope readers might have a little common sense, I've put this suggestion inside a warning. You can see it at the link now.

**Comment by rmackay9** [comment]
I agree that we could remove the advice about holding the copter.  I personally never do that.  I think it's not necessary especially now that we have a feature that allows the user to spin each motor individually to test it's direction.

**Comment by hamishwillee** [comment]
@rmackay9 So where's the information on how to do that (individual spin motor) thing.

**Comment by fnoop** [comment]
@hamishwillee here it is
http://ardupilot.org/copter/docs/connect-escs-and-motors.html#testing-motor-spin-directions

**Comment by hamishwillee** [comment]
Thanks very much @fnoop @rmackay9 - I've fixed this up in #367

**Comment by rmackay9** [comment]
nice, thanks.

**Comment by siliconalchemy** [comment]
Thanks :)
