### ISSUE TITLE
Building Sitl in Windows error

### ISSUE THREAD

**Issue by GRS26** [ArduPilot/ardupilot_wiki#3284]
Hello,
I followed :
https://ardupilot.org/dev/docs/building-setup-windows-cygwin.html#building-setup-windows-cygwin
https://ardupilot.org/dev/docs/sitl-native-on-windows.html
to the letter, but I seem to be getting a error every time I try to build this error occur:
![Untitled](https://user-images.githubusercontent.com/48105412/105350319-b9e0be80-5bc9-11eb-9ee2-54720b762a34.png)

**Comment by Hwurzburg** [comment]
sorry, this is not a wiki issue...you are having a build error....I suggest you post in the discss.ardupilot.org support forum...
you may also want to run git status to make sure your modules are up to data , if not git submodule update --init --recursive again
