### ISSUE TITLE
Ready-To-Use --  Makeflyeasy

### ISSUE THREAD

**Issue by patrickpoirier51** [ArduPilot/ardupilot_wiki#3292]
Looking at Aliexpress , most of VTOL Planes are using Ardupilot

Example:
https://www.aliexpress.com/store/5630181

Makeflyeasy Fighter (VTOL Version)  
https://www.aliexpress.com/item/4001113285374.html
https://www.aliexpress.com/item/1005001858282219.html

Including a ''always free'' Ground Station...

![MP](https://user-images.githubusercontent.com/12484190/105576824-790cb500-5d43-11eb-9d24-adbbbafb7d64.jpg)

**Comment by Hwurzburg** [comment]
actually I see nothing that indicates these are ArduPilot based rather than PX4 or some custom firmware...only that they seem to have MAVLink telem....until this is confirmed we should not list them...

**Comment by rmackay9** [comment]
If it's mission planner then it's almost guaranteed to be AP (although I have bumped into one example where a custom firmware used MP).

**Comment by patrickpoirier51** [comment]
Thanks for updating @makeflyeasy  :-)

**Comment by Hwurzburg** [comment]
MakeFlyEasy vehicles added to wiki...closing
