### ISSUE TITLE
Sphynx site's "Developer Chat" is pointing towards gitter

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#3332]
![image](https://user-images.githubusercontent.com/1498098/108034398-ce08c600-7078-11eb-9835-8e5995aca291.png)

The "Community" >> "Developer Chat" link on the main ardupilot.org page's menu's should be updated to point to Discord.  

Note that the "Developer Voice Chat" menu option already points to discord so perhaps we could just have a single link and call it "Developer Chat"

**Comment by Hwurzburg** [comment]
believe concrete would need the change

**Comment by Hwurzburg** [comment]
points to discord now

**Comment by rmackay9** [comment]
fantastic, thanks!
