### ISSUE TITLE
Mateksys F405-SE/WSE

### ISSUE THREAD

**Issue by omesen55** [ArduPilot/ardupilot_wiki#3342]
[Mateksys F405-SE/WSE](https://ardupilot.org/plane/docs/common-matekf405-se.html) - 
On the Matek f405w board, the matek M8Q-5883 GPS is connected to its SH1.0_6pin connector (4V5 / G / TX4 / RX4 / DA2 / CL2) can the Mission Planner of AP ver1.3.74 recognize this GPS, what should I do to achieve it (Matekf405Wing firmware)? My screen shows GPS: noGPS

**Comment by MATEKSYS** [comment]
set serial3_protocol  -1

**Comment by Hwurzburg** [comment]
adding notes in wiki
