### ISSUE TITLE
Manual availability

### ISSUE THREAD

**Issue by HFATL** [ArduPilot/ardupilot_wiki#3347]
Just would like to ask if there is any Ardupilot Manual for Plane that gather all the information in one single document to be easily printed.

Thank you and best regards

**Comment by Hwurzburg** [comment]
no...sorry....but if you are looking for a quick setup guide, try following this: https://ardupilot.org/plane/docs/fpv-plane.html

and in the future, please make support requests/questions in discuss.ardupilot.org forums...this is for errors in documentation

**Comment by HFATL** [comment]
Sorry for posting in wrong place and thanks for your kindly reply!

Thank you
