### ISSUE TITLE
HC-SR04 Sonar Rangefinder

### ISSUE THREAD

**Issue by ujjwalk450** [ArduPilot/ardupilot_wiki#3350]
[HC-SR04 Sonar Rangefinder](https://ardupilot.org/copter/docs/common-rangefinder-hcsr04.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

The sonar does not work as being described with pixhawk and also no other clear instruction available online.

**Comment by rmackay9** [comment]
I suspect the issue is that support for this sonar is not in the stable release.  It will be released with 4.1.
