### ISSUE TITLE
Button to remove highlight in wiki after search

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/ardupilot_wiki#336]
Because it is a pain.

**Comment by gmorph** [comment]
What is this?  What highlight in wiki after search?

**Comment by hamishwillee** [comment]
Yes, that is what we're talking about. Yes it's a feature, but often if you just want to find a topic about something (e.g. APM2.x) you then want to read the doc without having all the highlights.

**Comment by brunoolivieri** [comment]
The feature still there, but I do not know if it is a problem issue. It still a desirable issue that worth to maintain on issue list? Would someone work on it? Alternatively, we could close it?

**Comment by rmackay9** [comment]
I might just close this 'cuz it's not that big a deal really..
