### ISSUE TITLE
Plane Failsafe Function

### ISSUE THREAD

**Issue by jacques-eloff** [ArduPilot/ardupilot_wiki#3365]
[Plane Failsafe Function](https://ardupilot.org/plane/docs/apms-failsafe-function.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

I believe there is a typo in the section on Long failsafe action. Sentence reads "In a QuadPlane, if in VTOL operation in modes others than AUTO or GUIDED, the action taken will be either a QRTL or QLAND, depending on the Q_RTL_MODE bit mask setting for bit 5."

I believe "Q_RTL_MODE" in the sentence should instead be "Q_OPTIONS".

**Comment by Hwurzburg** [comment]
thanks...good catch...will change..

done...thanks
