### ISSUE TITLE
Plane Failsafe Function

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/ardupilot_wiki#3366]
[Plane Failsafe Function](https://ardupilot.org/plane/docs/apms-failsafe-function.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

Please make describe the difference between THR_FAILSAFE=0 and 2

**Comment by Hwurzburg** [comment]
keep reading.... https://ardupilot.org/plane/docs/apms-failsafe-function.html#configuring-for-ground-control-station-control-beyond-rc-range
