### ISSUE TITLE
MAVLink Basics

### ISSUE THREAD

**Issue by brunoolivieri** [ArduPilot/ardupilot_wiki#3373]
[MAVLink Basics](https://ardupilot.org/dev/docs/mavlink-basics.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

Hi there,

There is a text: "Other MAVLink capable device on the vehicle (i.e. companion computer, gimbal) should use the same System ID as the flight controller but use a different Component ID." 

However, the second image shows the opposite:  "same Component ID as the flight controller but uses a different System  ID."

I think the text is correct, but I am kinda confused here.

ping @khancyr @rmackay9

**Comment by khancyr** [comment]
On the second image that a GCS, that isn't part of the vehcile, so you need a different SYSID !
