### ISSUE TITLE
min_gndspd_cm

### ISSUE THREAD

**Issue by bordiga7** [ArduPilot/ardupilot_wiki#3374]
[Search](https://ardupilot.org/plane/search.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by bordiga7** [comment]
Hi there 

What exactly is the effect of "min_gndspd_cm" on auto modes in the case of not using airspeed sensor? 
I'm using arduplane 4.05 with an airframe with no airspeed sensor

**Comment by Hwurzburg** [comment]
read the wiki entry: https://ardupilot.org/plane/docs/common-mavlink-mission-command-messages-mav_cmd.html#mav-cmd-do-change-speed
