### ISSUE TITLE
Build of single page as PDF

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/ardupilot_wiki#338]

**Comment by FLYBYME** [comment]
Yeah I would like this!

**Comment by jpkh** [comment]
I will be really big pdf but shortly we should be able to do that. Sphinx allows it on some level

**Comment by hamishwillee** [comment]
The really big PDF is trivially easy, but I think what people want to do is take away any arbitrary page offline.

**Comment by gmorph** [comment]
They could just print it out of their browser to PDF - CTRL+P normally works.  I don't think there is a huge demand for this.

**Comment by hamishwillee** [comment]
The PDF print from browser is rubbish because it includes lots of things you don't need in a PDF context (e.g. sidebar) and layout is bad. BUT I see this as "too hard" to do easily/not sufficient value for effort - and I agree the need isn't hug. 

So, closing for now.
