### ISSUE TITLE
Using SITL

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/ardupilot_wiki#3385]
[Using SITL](https://ardupilot.org/dev/docs/using-sitl-for-ardupilot-testing.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

Please observe that Rangefinder configuration fails in current Plane:

MANUAL> param set SIM_SONAR_SCALE 10
MANUAL> param set RNGFND1_TYPE 1
MANUAL> param set RNGFND1_SCALING 10
MANUAL> param set RNGFND1_PIN 0
MANUAL> param set RNGFND1_MAX_CM 5000
MANUAL> param set RNGFND1_MIN_CM 0Unable to find parameter 'RNGFND1_SCALING'
Unable to find parameter 'RNGFND1_PIN'
Unable to find parameter 'RNGFND1_MAX_CM'

and 
param set RPM_TYPE 1
Does not produce MAVlink RPM data.

Finally: 
there is no SIM_ACC_RND   (but  SIM_ACC2_RND and  SIM_ACC3_RND  exists )

**Comment by JalilAfkhami** [comment]
> [Using SITL](https://ardupilot.org/dev/docs/using-sitl-for-ardupilot-testing.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.
> 
> Please observe that Rangefinder configuration fails in current Plane:
> 
> MANUAL> param set SIM_SONAR_SCALE 10 MANUAL> param set RNGFND1_TYPE 1 MANUAL> param set RNGFND1_SCALING 10 MANUAL> param set RNGFND1_PIN 0 MANUAL> param set RNGFND1_MAX_CM 5000 MANUAL> param set RNGFND1_MIN_CM 0Unable to find parameter 'RNGFND1_SCALING' Unable to find parameter 'RNGFND1_PIN' Unable to find parameter 'RNGFND1_MAX_CM'
> 
> and param set RPM_TYPE 1 Does not produce MAVlink RPM data.
> 
> Finally: there is no SIM_ACC_RND (but SIM_ACC2_RND and SIM_ACC3_RND exists )


I was facing same "Unable to find parameter 'RNGFND1_SCALING" error. restarting SITL solved my issue.
