### ISSUE TITLE
PDF Guides are missing

### ISSUE THREAD

**Issue by yasek** [ArduPilot/ardupilot_wiki#339]
[PDF Guides](http://ardupilot.org/copter/docs/pdf-guides.html)
Links on this page are broken and return 404:
http://firmware.ardupilot.org/downloads/wiki/pdf_guides/APM2_Quad_Setup_3.pdf
http://firmware.ardupilot.org/downloads/wiki/pdf_guides/APM2_Flamewheel_Quad_Setup1.pdf
http://firmware.ardupilot.org/downloads/wiki/pdf_guides/APM2_Quad_Stabilize_1.pdf
http://firmware.ardupilot.org/downloads/wiki/pdf_guides/APM2_Quad_AltHold_Loiter_1.pdf
http://firmware.ardupilot.org/downloads/wiki/pdf_guides/APM2_PID_MAP_4.pdf

**Comment by jpkh** [comment]
Links are fixed now and files are back online.
