### ISSUE TITLE
Flaperon Configuration

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/ardupilot_wiki#3411]
[Flaperon Configuration](https://ardupilot.org/plane/docs/flaperons-on-plane.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

FLAP_IN_CHANNEL is mentioned, should be corrected to RC*_OPTION=208

**Comment by Hwurzburg** [comment]
only in master....will add to upcoming features page
