### ISSUE TITLE
RPLidar A2 not showing data in proximity window

### ISSUE THREAD

**Issue by vanarp0915** [ArduPilot/ardupilot_wiki#3428]
Hello all,

I am working on 360-degree obstacle avoidance in a quadcopter. I connected my lidar to the TELEM1 port of Cube black and followed all the procedures in the actual ardupilot documentation. I am finding trouble in getting the data from RPLidar into the proximity window. I have even tried powering RPLidar first and then Cube and vice versa, still no data. RPLidar’s (Vcc, Motoctrl) is powered with 5V BEC.

These are the parameters I have used to set up the lidar

SERIAL1_PROTOCOL = “11”
SERIAL1_BAUD = “115”
PRX_TYPE = “5”
PRX_ORIENT = “0”
BRD_SER1_RTSCTS = “0”

Can anyone please help me with this issue?
Thank you.

**Comment by Hwurzburg** [comment]
please move to support forum.... discuss.ardupilot.org
