### ISSUE TITLE
Telem 2

### ISSUE THREAD

**Issue by AttieP** [ArduPilot/ardupilot_wiki#3436]
Good day , 

I am having issues getting Telemetry 2 to work on Pixhawk 4 with firmware from mission planner 4.0.7, 
All works on Telemetry 1 , 

I am trying to get the FR-SKY telemetry to work on TELEM2 even tried MAV@ on the TELEM2 port and does not work . 

SERIAL_PASS1,0
SERIAL_PASS2,-1
SERIAL_PASSTIMO,15
SERIAL0_BAUD,115
SERIAL0_PROTOCOL,2
SERIAL1_BAUD,57
SERIAL1_OPTIONS,0
SERIAL1_PROTOCOL,2
SERIAL2_BAUD,57
SERIAL2_OPTIONS,0
SERIAL2_PROTOCOL,10
SERIAL3_BAUD,38
SERIAL3_OPTIONS,0
SERIAL3_PROTOCOL,5
SERIAL4_BAUD,38
SERIAL4_OPTIONS,8
SERIAL4_PROTOCOL,23
SERIAL5_BAUD,57
SERIAL5_OPTIONS,0
SERIAL5_PROTOCOL,-1
SERIAL6_BAUD,115200
SERIAL6_OPTIONS,0
SERIAL6_PROTOCOL,2

**Comment by Hwurzburg** [comment]
please move to a support forum: discuss.ardupilot.org
