### ISSUE TITLE
Rover: document recent sailboat features

### ISSUE THREAD

**Issue by arikrupnik** [ArduPilot/ardupilot_wiki#3461]
@Hwurzburg : listening to your DevCon talk inspired me to send you some bullet points.

Sailboat support has grown since the last Wiki update.

* Sailboat supports auxiliary motor propulsion (`RCx_OPTION=74 Sailboat motoring 3pos`)
  *  `USE_MOTOR_NEVER`
  * `USE_MOTOR_ASSIST`
    * for tacking
    * for low wind
  * `USE_MOTOR_ALWAYS`
* Throttle input can be used to control sails, or the dedicated `RCx_OPTION=207 MainSail`. It would be helpful to explain the difference between them.
* Throttle input controls sails directly in manual mode. In Acro mode, throttle controls speed, in the sense that below a certain throttle value, the boat will depower the sails to remain stationary. It may be worth explaining that in Acro mode, rudder input controls the rate of turn rather than servo output directly.
* Wiki describes only "traditional" sail control with a sheet and a winch.
  * An additional configuration is supported in release code--wing sail with elevator-style AoA control (`SERVOx_FUNCTION=128 Wing Sail Elevator`) https://discuss.ardupilot.org/t/sailboat-support/32060/321
  * A third configuration is WIP, direct servo control of rotating mast: https://github.com/ArduPilot/ardupilot/pull/17066/

**Comment by Hwurzburg** [comment]
super...I may ask for more details when I get to this...

**Comment by arikrupnik** [comment]
Thank you, @Hwurzburg. I'm sure you know this, but @IamPete1 is the authority on sailboat support. I'm just figuring things out.

Another aspect you may want to document is land sailing. The Wiki notes, "Only sail boats have been tested so far, although there is no reason land based vehicles wouldn’t work." Since this statement, @srmainwaring has had significant, documented success with land yachts.
