### ISSUE TITLE
GPS for Yaw (aka Moving Baseline)

### ISSUE THREAD

**Issue by ktrussell** [ArduPilot/ardupilot_wiki#3512]
[GPS for Yaw (aka Moving Baseline)](https://ardupilot.org/rover/docs/common-gps-for-yaw.html) - According to the comments in Mission Planner for the EK3_MAG_CAL parameter, setting 5 has been deprecated in version 4.1.0 and later. Instead we are to use EK3_SRC1_YAW, EK3_SRC2_YAW and EK3_SRC3_YAW. So I believe the article should be changed to reflect that.

I had success using EK3_SRC1_YAW = 2.

**Comment by rmackay9** [comment]
I think I've fixed this now. https://ardupilot.org/rover/docs/common-gps-for-yaw.html

Thanks for the reminder.
