### ISSUE TITLE
Credits and Contributors

### ISSUE THREAD

**Issue by islemhm** [ArduPilot/ardupilot_wiki#3514]
hello i have a problem in APMplanner, i use ubuntu 18.04 and this version of apm planner "apm_planner_2.0.26_bionic64.deb"This is my 'install firmware' screen which is blank in both disconnected & connected state (I'm trying to configure my pixhawk1 for the first time)
Any ideas why this is occuring and how do I fix this?
![image](https://user-images.githubusercontent.com/79261716/117585639-5f815480-b10b-11eb-98ee-4c4609a29ac5.png)

**Comment by khancyr** [comment]
Hello,

Please ask questions on https://discuss.ardupilot.org/ . This is the wiki issues tracker. Thanks
