### ISSUE TITLE
clarification requested on the filtering wiki page

### ISSUE THREAD

**Issue by mattdholmes00** [ArduPilot/ardupilot_wiki#3523]
@andyp1per and @Hwurzburg much thanks for improving the [filtering wiki page](https://github.com/ArduPilot/ardupilot_wiki/blob/master/common/source/docs/common-imu-notch-filtering.rst), however as I go through it I'm not sure which sections apply to which modes.  Specifically, I have ESC telemetry and have set my INS_HNTCH_MODE, 3.  But then I cannot figure out which other parameters are also applicable when using that mode.  E.g. _ENABLE, _REF, _ FREQ, _BW, are any of those relevant with mode 3?   I think a simple sentence or two in key spots would clarify that, e.g. "this section only pertains to those using INS_HNTCH_MODE __".  I would fix it if I knew, but the reason I'm posting this is because I don't know...

**Comment by Hwurzburg** [comment]
I have re-org'd the notch filter pages...if something still is unclear, let me know...closing
