### ISSUE TITLE
Valid range of ACRO_RP_EXPO

### ISSUE THREAD

**Issue by KimHyungSub** [ArduPilot/ardupilot_wiki#3541]
ACRO_RP_EXPO's valid range is from -0.5 to 1.0 based on documentation (https://ardupilot.org/copter/docs/parameters-Copter-stable-V4.0.7.html). However, ArduPilot source code forces the parameter to have a value from 0 to 1; g.acro_rp_expo = constrain_float(g.acro_rp_expo, 0.0f, 1.0f)
It would be nice if the documentation will be updated according to the range check in source code.

**Comment by Hwurzburg** [comment]
@rmackay9 bug or doc error?

**Comment by rmackay9** [comment]
@Hwurzburg looks like a bug in the param description as @KimHyungSub says.  Thanks for this!

**Comment by Hwurzburg** [comment]
closed by #17486
