### ISSUE TITLE
Archive Eclipse with Make page

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#3549]
We should archive this page: https://ardupilot.org/dev/docs/editing-the-code-with-eclipse.html

... and then we can remove, "These instructions replace the older method which relied on Make." from this page: https://ardupilot.org/dev/docs/building-setup-windows-eclipse.html

**Comment by Hwurzburg** [comment]
done

**Comment by rmackay9** [comment]
@Hwurzburg great, thanks very much!
