### ISSUE TITLE
Advanced Configuration

### ISSUE THREAD

**Issue by govsux** [ArduPilot/ardupilot_wiki#356]
[Advanced Configuration](http://ardupilot.org/copter/docs/common-advanced-configuration.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

I could be looking right at it but I don't see anything on the entire new ardupilot 'copter' pages regarding the various modes and what they do. aka RTL.... Stabilize.... Auto etc.. I know it's a work in progress.

**Comment by CraigElder** [comment]
http://ardupilot.org/copter/docs/flight-modes.html
