### ISSUE TITLE
Precision Docking

### ISSUE THREAD

**Issue by Cadify** [ArduPilot/ardupilot_wiki#3585]
[Search](https://ardupilot.org/dev/search.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by nkruzan** [comment]
Hello do you have some information to add why there is an issue? I see you are interested in Precision Docking, but what is missing or needing clarification?

**Comment by Cadify** [comment]
Hello,

 

Sorry, that was just a clumsy click by me, not intentional, other than that that I am running an open source project with ArduBoat where precision docking and maneuvering is very interesting, so I am looking into anything that may be relevant.

 

Actually, I was looking for some status update about how the Precision Docking is going. 

 

Regards

Joern Watvedt

RC boat joystick piloting project manager.

 

Fra: nkruzan ***@***.***> 
Sendt: mandag 31. mai 2021 20:26
Til: ArduPilot/ardupilot_wiki ***@***.***>
Kopi: Cadify ***@***.***>; Author ***@***.***>
Emne: Re: [ArduPilot/ardupilot_wiki] Precision Docking (#3585)

 

Hello do you have some information to add why there is an issue? I see you are interested in Precision Docking, but what is missing or needing clarification?

**Comment by nkruzan** [comment]
I see it on the roadmap under @rmackay9 he may be able to give status update.

**Comment by khancyr** [comment]
We are working on releasing the version v4.1, so it would surely happen after the release. If that isn't an issue with the wiki, I am closing this.

**Comment by rmackay9** [comment]
Yes, I'd like to get precision docking working but I can't promise when yet I'm afraid..
