### ISSUE TITLE
FlyWoo F745 AIO BL_32

### ISSUE THREAD

**Issue by kingasa47** [ArduPilot/ardupilot_wiki#3591]
[FlyWoo F745 AIO BL_32](https://ardupilot.org/plane/docs/common-flywoo-f745.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

Will the dji digital fpv system work with this?

**Comment by Hwurzburg** [comment]
this is really a support question, not wiki issue...try moving it to discuss.ardupilot.org if still unanswered
