### ISSUE TITLE
Installing APM Planner for Mac

### ISSUE THREAD

**Issue by djwalko** [ArduPilot/ardupilot_wiki#3598]
[Installing APM Planner for Mac](https://ardupilot.org/planner2/docs/mac-install.html) - Unable to install this on a new MacBook Pro with the M1 chip :(. Any plans to update the software to make it compatible??

**Comment by Hwurzburg** [comment]
this is not for Planner issues....open an issue here: https://github.com/ArduPilot/apm_planner/issues...thanks
