### ISSUE TITLE
Loiter Mode

### ISSUE THREAD

**Issue by trondhindenes** [ArduPilot/ardupilot_wiki#360]
[Loiter Mode](http://ardupilot.org/copter/docs/loiter-mode.html) - The Loiter Tuning screen doesn't correspond with the explained values. It would be great if the documentation would call out what each value is called in Mission Planner.

**Comment by brunoolivieri** [comment]
I believe that 00ceaf0 fixed that. Moreover, there were at least five other updates since this Issue have been opened.

Could we close this issue?

**Comment by Hwurzburg** [comment]
yes closing
