### ISSUE TITLE
Wizard Servo output page function list not clik

### ISSUE THREAD

**Issue by Zzeytinci** [ArduPilot/ardupilot_wiki#3611]
Hi
Mandatory page -> servo output -> position -> function list  is not select. 
never clicked. 
why not click.
Please help me.

**Comment by Hwurzburg** [comment]
sorry but dont understand your question....and that question should be asked in discuss.arudpilot.org forums (Mission Planner support question area) not this....this if for issues with the wiki directly...not support questions...thanks
