### ISSUE TITLE
VS Code Debugging: add how to debug startup tasks

### ISSUE THREAD

**Issue by hendjoshsr71** [ArduPilot/ardupilot_wiki#3629]
Here: https://ardupilot.org/dev/docs/debugging-with-gdb-on-linux.html#vs-code

We should add how to "Launch" debugging in VSCode so users can debug object construction, SITL parameters. 

We may also want to create a new header in the Debugging tree that lists "Debugging with an IDE" new users seem not be seeing those directions.

**Comment by Hwurzburg** [comment]
@hendjoshsr71 Josh, I know nothing on this topic....someone else will have to write a rough draft and I can polish, if needed....

**Comment by khancyr** [comment]
Simple trick to debug initial sequence : put your breakpoint in HAL constuctor or any init phase you want, and reboot !

**Comment by hendjoshsr71** [comment]
> Simple trick to debug initial sequence : put your breakpoint in HAL constuctor or any init phase you want, and reboot !

@khancyr Oh nice! That is a lot easier then the launch option for my normal usage. Definitely needs to get added to the wiki.

@Hwurzburg  But I will also include a launch option, autotest, unit test, and more profiles in a PR. 
How would you like to structure this? I was thinking about adding a page under Debugging with GDB -> Debugging SITL Using VSCode

**Comment by Hwurzburg** [comment]
@hendjoshsr71 a new page sounds like the best way
