### ISSUE TITLE
Add note re non-GPS to Copter's flight mode page

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#3640]
The [Copter flight mode summary page](https://ardupilot.org/copter/docs/flight-modes.html) has a "GPS" column and a "GPS Dependency" section and I've found at least one user who took this literally and thought that Loiter couldn't be used with OpticalFlow+Rangefinder ([see discussion](https://discuss.ardupilot.org/t/issues-of-flow-fxscaler/73292/9)).

We should clarify the "GPS Dependency" section so users know that it is not actually a hard dependency on the GPS but rather a requirement for a good position estimate which includes GPS and Non-GPS sources listed here https://ardupilot.org/copter/docs/common-non-gps-navigation-landing-page.html (we should provide this link too).

**Comment by Hwurzburg** [comment]
I think this has been addressed...closing
