### ISSUE TITLE
Option of “HC-SR04 sonar” cannot be found in the configuration menu of RNGFND1_TYPE

### ISSUE THREAD

**Issue by BUAAxiaobaige** [ArduPilot/ardupilot_wiki#3676]
Hello,

I want to use HC-SR04 sonar for indoor flying, but when I tried to configure it referring the guide of [this page](https://ardupilot.org/copter/docs/common-rangefinder-hcsr04.html), I cannot find the option of “HC-SR04 sonar” in the menu of RNGFND1_TYPE(neither in QGroundControl nor Mission Planner).

I have tried several versions of ardupilot firmware but none of them works.

Can anyone help me? Thanks a lot in advance.

**Comment by hendjoshsr71** [comment]
Hi @BUAAxiaobaige ,

Please post your hardware type, firmware version and Mission Planner version.

I found it in Mission Planner using DEV firmware. I have feeling it is not in your firmware as it first appeared in 4.1.0-beta3 it looks like. If you are comfortable using beta firmware you could use the latest 4.1.0-beta

See below.

![image](https://user-images.githubusercontent.com/69225461/127697051-219261d7-e49a-4257-8e05-1e923dfa35f3.png)

**Comment by Hwurzburg** [comment]
its been in the code since June of last year

**Comment by BUAAxiaobaige** [comment]
> Hi @BUAAxiaobaige ,
> 
> Please post your hardware type, firmware version and Mission Planner version.
> 
> I found it in Mission Planner using DEV firmware. I have feeling it is not in your firmware as it first appeared in 4.1.0-beta3 it looks like. If you are comfortable using beta firmware you could use the latest 4.1.0-beta
> 
> See below.
> 
> ![image](https://user-images.githubusercontent.com/69225461/127697051-219261d7-e49a-4257-8e05-1e923dfa35f3.png)

oh it works, I kept trying firmware of versions lower than 4.1 and now change it to 4.1.0 and I can find the option of "sr04"

thanks a lot !

Regard.
