### ISSUE TITLE
MAV FTP not working

### ISSUE THREAD

**Issue by gugpilot** [ArduPilot/ardupilot_wiki#3681]
After last stable update when I try to download from MAV FTP some log files, I got an error
<img width="840" alt="Schermata 2021-08-05 alle 14 44 46" src="https://user-images.githubusercontent.com/30938700/128352574-80fa7c8d-f49a-4fa0-8705-a385feda71ed.png">

**Comment by Hwurzburg** [comment]
closing....support issues can be posted on discuss.ardupilot.org
