### ISSUE TITLE
Dev: SITL: gimbals instructions completely out of date

### ISSUE THREAD

**Issue by IamPete1** [ArduPilot/ardupilot_wiki#3690]
Caused https://github.com/ArduPilot/ardupilot/issues/15179

https://ardupilot.org/dev/docs/using-sitl-for-ardupilot-testing.html#adding-a-gimbal

Is just completely wrong, we don't even have those params anymore.

It might be better to just delete them until someone get to re-wring....

**Comment by Hwurzburg** [comment]
@IamPete1 Pete I am kinda at a loss on this....I can run SITL fine with the -M option...all the parameters mentioned in the section for mnt_type and servo functions are valid....so dont quite understand the issue here...

**Comment by IamPete1** [comment]
It looks to me that `-M` simulates a mavlink gimbals not a servo one. At the least we should update `RC6_FUNCTION` to `SERVO6_FUNCTION`. I should add that I have not actually tested the correct way to set this up.

**Comment by Hwurzburg** [comment]
fixed.....was just looking at function numbers when I checked....if you find something wrong with this in SITL (I dont know how to test other than it runs) or how to setup a servo gimbal in SITL, open a new issue please...thanks
