### ISSUE TITLE
mRobotics UAVCAN Adapter Node

### ISSUE THREAD

**Issue by yuri-rage** [ArduPilot/ardupilot_wiki#3711]
[mRobotics UAVCAN Adapter Node](https://ardupilot.org/copter/docs/common-mro-uavcan-adapter-node.html)

CAN_D1_PROTOCOL (and/or CAN_D2_PROTOCOL) must be set to 1 (UAVCAN) for the node to work.  That parameter is not mentioned in the setup section.

**Comment by Hwurzburg** [comment]
fixed
