### ISSUE TITLE
ardupilot pixhavk 248

### ISSUE THREAD

**Issue by zup555777** [ArduPilot/ardupilot_wiki#3712]
[Search](https://ardupilot.org/dev/search.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by Hwurzburg** [comment]
No info closing

**Comment by zup555777** [comment]
Dear
I started set up Pixavk 2.4.8 a few months ago and stopped on compass calibration.
I recently wanted to continue but can't find the GSC Ardupilot I worked with!
I want to reinstall but I don't know which GSC, I mean 2.3? Or can someone else?
Thanks Peter

**Comment by rmackay9** [comment]
@zup555777,

It was probably Mission Planner. https://ardupilot.org/copter/docs/common-install-gcs.html
