### ISSUE TITLE
Long words don't wrap onto multiple lines, and page can not be panned right.

### ISSUE THREAD

**Issue by WickedShell** [ArduPilot/ardupilot_wiki#372]
Long descriptions like the last word of http://ardupilot.org/plane/docs/parameters.html#log-bitmask-log-bitmask doesn't fit on a single screen width, and the last part of the bit description is not readable.

**Comment by hamishwillee** [comment]
@WickedShell Thanks, this is a known issues.

@peterbarker Your latest update to the parameters on plane fixes this rather nicely. Did you submit the patch?

**Comment by peterbarker** [comment]
On Tue, 12 Apr 2016, Hamish Willee wrote:

> @WickedShell Thanks, this is a known issues.
> 
> @peterbarker Your latest update to the parameters on plane fixes this rather
> nicely. Did you submit the patch?

Not yet.  Soon.

**Comment by hamishwillee** [comment]
Thanks!

**Comment by brunoolivieri** [comment]
It seems like the words in parameters file are wrapping correctly in multiple lines now. Right?

If so, I believe that this issue could be closed.

**Comment by Hwurzburg** [comment]
Confirmed..closing
