### ISSUE TITLE
How to make Robotis Servos work in multi-turn mode (4-5 turns)?

### ISSUE THREAD

**Issue by sitnikov2020** [ArduPilot/ardupilot_wiki#3740]
[Robotis Servos](https://ardupilot.org/copter/docs/common-servo-robotis.html)

Robotis Servos and pixhawk (fmuv3) work properly in standart 1 turn mode (OPMODE_POS_CONTROL). 

What i need to do to make them work in multi-turn mode? I need 4-5 turns.

I tried to make custom firmware- changed library AP_RobotisServo.cpp in this way:
- changed mode to multi-turn here http://joxi.ru/MAjbBE9fj9EaKA
- changed Position maximum to 4 turns here http://joxi.ru/RmzboEVfYgQOnm

Library has such code in the end:
uint32_t value = pos_min + v * (pos_max - pos_min);
send_command(i+1, REG_GOAL_POSITION, value, 4); 

But it doesn't work, i have only 1 turn (360 degrees)

So how to make Robotis Servos work in multi-turn mode (4-5 turns)?

**Comment by Hwurzburg** [comment]
this really belongs in the developer discord chat under hardware.....since you are trying to change the code to get a new feature, not the documentation issues....please move it to ardupilot.org/discord in the hardware chat...thanks
