### ISSUE TITLE
GPIOs "h" missing form "https" on a link to hwdef.dat

### ISSUE THREAD

**Issue by kniuk** [ArduPilot/ardupilot_wiki#3749]
[GPIOs](https://ardupilot.org/plane/docs/common-gpios.html)
Link to hwdef.dat is:
ttps://github.com/ArduPilot/ardupilot/tree/master/libraries/AP_HAL_ChibiOS/hwdef
and should be
https://github.com/ArduPilot/ardupilot/tree/master/libraries/AP_HAL_ChibiOS/hwdef
"h" is missing. Therefore link does not open.

**Comment by Hwurzburg** [comment]
fixed..thanks
