### ISSUE TITLE
Where can I get firmware support Optical Flow work on APM2.

### ISSUE THREAD

**Issue by Jasonsiu** [ArduPilot/ardupilot_wiki#375]
I was download AC 3.2.1 on APM 2.6 by Mission planner, when I changed flight mode to OF_Loiter, APM doesn't work to change OF_Loiter that it keeps the flight mode before changed. My hardware is ADNS3080.

**Comment by hamishwillee** [comment]
Try the forums: http://discuss.ardupilot.org/
