### ISSUE TITLE
GPIOs needs adding new way of repurposing single PWM/SERVO output to GPIO

### ISSUE THREAD

**Issue by kniuk** [ArduPilot/ardupilot_wiki#3750]
[GPIOs](https://ardupilot.org/plane/docs/common-gpios.html) 
New way of repurposing PWM to GPIO is more flexible since 4.2dev (maybe 4.1beta?) 
Instead of using limiting BRD_PWM_COUNT and regaining GPIO control over higher PWMs it uses SERVOx_FUNCTION value of -1 to redirect this pin for GPIO control

**Comment by Hwurzburg** [comment]
issue already captured in Wiki 4.2 list

**Comment by kniuk** [comment]
Excuse me, but I must be dumb. How do I view DOCS/WIKI for 4.2  ?

**Comment by Hwurzburg** [comment]
most have not been created yet, but there is a running list I keep of needed documentation https://github.com/ArduPilot/ardupilot_wiki/issues/3688
