### ISSUE TITLE
FlyWoo F745 AIO BL_32

### ISSUE THREAD

**Issue by DinoHassio** [ArduPilot/ardupilot_wiki#3766]
[FlyWoo F745 AIO BL_32](https://ardupilot.org/rover/docs/common-flywoo-f745.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by DinoHassio** [comment]
Buona sera a tutti. Domanda, quale firmware ardupilot copter scaricare, non trovo riferimento della scheda  dal sito firmware.ardupilot.org .Se qualcuno sa ringrazio

**Comment by Hwurzburg** [comment]
page updated
