### ISSUE TITLE
mission planner for windows xp

### ISSUE THREAD

**Issue by massimobernabei** [ArduPilot/ardupilot_wiki#377]
[](http://ardupilot.org/planner/search.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by magicrub** [comment]
Huh?

**Comment by hamishwillee** [comment]
@massimobernabei This area is for commenting on issues with articles. Support questions should be raised on the discussion boards (and worded as questions - which this is not): http://discuss.ardupilot.org/

I am closing.
