### ISSUE TITLE
Benewake TF02 / TF03 lidar/ TF-Luna

### ISSUE THREAD

**Issue by Edekheh** [ArduPilot/ardupilot_wiki#3777]
[Benewake TF02 / TF03 lidar/ TF-Luna](https://ardupilot.org/rover/docs/common-benewake-tf02-lidar.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

Wrong wiring : For TF03 it's Blue(lidars RX) and Brown(lidars TX) instead of white and Green.

**Comment by Hwurzburg** [comment]
I will add a note
