### ISSUE TITLE
Copter Commands in Guided Mode

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/ardupilot_wiki#3778]
[Copter Commands in Guided Mode](https://ardupilot.org/dev/docs/copter-commands-in-guided-mode.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

I think 
MAV_CMD_GUIDED_CHANGE_HEADING
MAV_CMD_GUIDED_CHANGE_ALTITUDE
MAV_CMD_GUIDED_CHANGE_SPEED  
works too..

Thank you.

**Comment by Hwurzburg** [comment]
@rmackay9 confirm and I will update...thanks

**Comment by rmackay9** [comment]
These are only supported by Plane it seems..

**Comment by AndKe** [comment]
- sorry , my bad.
