### ISSUE TITLE
Edit tabaction on flightdata

### ISSUE THREAD

**Issue by danilopmaciel** [ArduPilot/ardupilot_wiki#3779]
Where is the action tab designer file? 
![image](https://user-images.githubusercontent.com/30030866/134358881-9aef2cd2-58be-4173-8be3-ee11f6130541.png)

**Comment by khancyr** [comment]
Hello, please see on Mission Planner repository. Thanks https://github.com/ArduPilot/MissionPlanner

**Comment by danilopmaciel** [comment]
> Hello, please see on Mission Planner repository. Thanks https://github.com/ArduPilot/MissionPlanner

https://github.com/danilopmaciel/xmission
I want to know which file is responsible for such a visual structure. I'm already editing the original repository, but through flightdata.cs I can't adjust the designer.
