### ISSUE TITLE
Communicating with Raspberry Pi via MAVLink

### ISSUE THREAD

**Issue by sgh055** [ArduPilot/ardupilot_wiki#380]
[Communicating with Raspberry Pi via MAVLink](http://ardupilot.org/dev/docs/raspberry-pi-via-mavlink.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

Companion computer can do add new sensors like temperature sensor, IR camera etc...

I want to use the sensor data for my GCS.

Raspberry-pi can do it?

**Comment by hamishwillee** [comment]
@sgh055 This section is for issues with the wiki and enhancements - you should ask support questions on the forums http://discuss.ardupilot.org/
