### ISSUE TITLE
Publish logos compatible to wikipedia

### ISSUE THREAD

**Issue by Matthias84** [ArduPilot/ardupilot_wiki#3852]
Hi there, I would love to share your logo at wikipedia to illustrate articles and wikidata objects
https://commons.wikimedia.org/wiki/File:Ardu_-_logos.jpg

Unfortunatly there is currently no attribution nor license available which is compatible with wikicommons. Could you redistribute the logo, or give us further information?

**Comment by Hwurzburg** [comment]
@auturgy can you help on this or point me to someone who can?

**Comment by auturgy** [comment]
The logos are available under CC3.0 BY SA which is a Wikipedia/WikiCommons compatible license.

**Comment by Hwurzburg** [comment]
@Matthias84 does this resolve your issue?

**Comment by Matthias84** [comment]
Sorry for the delay. Yes I think this final declaration will be enough. Thanks for clarification! :smile:
