### ISSUE TITLE
QuadPlane Simulation quadplane example

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/ardupilot_wiki#3889]
[QuadPlane Simulation](https://ardupilot.org/plane/docs/quadplane-simulation.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

The command example does not seem to be valid anymore, and produces this output:
```
andre@loke:~$ sim_vehicle.py -j4 -f quadplane --console --map
SIM_VEHICLE: Start
SIM_VEHICLE: 
** Is (andre) really your vehicle type?
Perhaps you could try -v ArduCopter|Helicopter|Blimp|ArduPlane|Rover|ArduSub|AntennaTracker
You could also try changing directory to e.g. the ArduCopter subdirectory

SIM_VEHICLE: Killing tasks

```

**Comment by Hwurzburg** [comment]
updated in wiki...thanks...closing
