### ISSUE TITLE
Building ArduPilot for APM2.x with Eclipse on Windows

### ISSUE THREAD

**Issue by liaorongfan** [ArduPilot/ardupilot_wiki#391]
[Building ArduPilot for APM2.x with Eclipse on Windows](http://ardupilot.org/dev/docs/building-apm2-with-eclipse-on-windows.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by rmackay9** [comment]
we should totally remove this wiki page actually.  We don't support the APM2.x boards anymore.

**Comment by liaorongfan** [comment]
How about the earlier branches of codes for ArduCopter based on an APM2.X,such as V2.8 or V2.5, I mean ,does it works for building on Arduino1.0.3? Looking forward to hearing from you. Thank you!

发自我的 Kevin

**Comment by rmackay9** [comment]
@liaorongfan, yes, the instructions should still work for very old builds.

**Comment by hamishwillee** [comment]
FYI @rmackay9 I've archived this as #406

**Comment by rmackay9** [comment]
great, thanks!

**Comment by liaorongfan** [comment]
@rmackay9  Got it, thanks a lot

**Comment by liaorongfan** [comment]
@rmackay9 Excuse me, I am still working on Building ArduPilot for APM2.x with Eclipse on Windows,since the artical says "They have been tested on Windows 10 to build the ArduCopter-3.2.1 branch."  But after I type "make apm2" in the px4 console,it responded "Can not find Arduino in this system", though I specified the path in config.mk  like this "ARDUINO=C:/APM_program/ArduPilot-Arduino-1.0.3-windows". could you give me some advice?

**Comment by rmackay9** [comment]
@liaorongfan, I'm sorry, I just can't keep supporting the AVR boards.  I get so many requests each day for support and new features, I'm afraid I have to prioritise those that help move the project forward.
