### ISSUE TITLE
Connect ESCs and Motors

### ISSUE THREAD

**Issue by paulnferri** [ArduPilot/ardupilot_wiki#3952]
[Connect ESCs and Motors](https://ardupilot.org/copter/docs/connect-escs-and-motors.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

So the picture that describes the Quad "X" configuration shows the motor order being 1 and 2 ccw, and 3 and 4 cw. Yet the code clearly shows that 1 and 3 are ccw and 2 and 4 are cw (this is always the configuration I remember). 

void AP_MotorsMatrix::setup_motors(motor_frame_class frame_class, motor_frame_type frame_type)
{
    // remove existing motors
    for (int8_t i = 0; i < AP_MOTORS_MAX_NUM_MOTORS; i++) {
        remove_motor(i);
    }
    set_initialised_ok(false);
    bool success = true;

    switch (frame_class) {

        case MOTOR_FRAME_QUAD:
            _frame_class_string = "QUAD";
            _mav_type = MAV_TYPE_QUADROTOR;
            switch (frame_type) {
                case MOTOR_FRAME_TYPE_PLUS:
                    _frame_type_string = "PLUS";
                    add_motor(AP_MOTORS_MOT_1,  90, AP_MOTORS_MATRIX_YAW_FACTOR_CCW, 2);
                    add_motor(AP_MOTORS_MOT_2, -90, AP_MOTORS_MATRIX_YAW_FACTOR_CCW, 4);
                    add_motor(AP_MOTORS_MOT_3,   0, AP_MOTORS_MATRIX_YAW_FACTOR_CW,  1);
                    add_motor(AP_MOTORS_MOT_4, 180, AP_MOTORS_MATRIX_YAW_FACTOR_CW,  3);
                    break;
                case MOTOR_FRAME_TYPE_X:
                    _frame_type_string = "X";
                    add_motor(AP_MOTORS_MOT_1,   45, AP_MOTORS_MATRIX_YAW_FACTOR_CCW, 1);
                    add_motor(AP_MOTORS_MOT_2, -135, AP_MOTORS_MATRIX_YAW_FACTOR_CCW, 3);
                    add_motor(AP_MOTORS_MOT_3,  -45, AP_MOTORS_MATRIX_YAW_FACTOR_CW,  4);
                    add_motor(AP_MOTORS_MOT_4,  135, AP_MOTORS_MATRIX_YAW_FACTOR_CW,  2);

Here is the picture on ardupilot.org

https://ardupilot.org/copter/_images/motororder-quad-x-2d.png

Which one is correct, and can we fix the incorrect one? Or am I making a mistake?

**Comment by Hwurzburg** [comment]
sorry you are reading the code wrong...in type x motor 1 and 2 are CCW and at the 45 deg and -135 deg positions as shown in the figure...the last numbers are TESTING ORDER....not motor order.....motor1 is first then 4, then 2, and then 3
