### ISSUE TITLE
Holybro GPS compass orientation

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot_wiki#3994]
The IST8310 compass in the Holybro GPS modules are oriented 90 degrees out. The compass dance produces the right result, detecting COMPASS_ORIENT=6 (Yaw270) when the GPS arrow is pointing forward, but we should note this somewhere in the pages for these GPS modules.
Affected modules include the following:

- https://shop.holybro.com/holybro-m8n-gps_p1094.html
- https://shop.holybro.com/holybro-m9n-gps_p1280.html

See this report for an example of this issue:
https://docs.google.com/document/d/1G7CbwGhScHzVzVKTTHknnljIN88NffWr1f2Fvr-lP7w/edit?usp=sharing

**Comment by vincentpoont2** [comment]
@tridge I have put a note on Holybro GPS product webpage.
It looks like the RTK GPS are also affected. I have created this put request to include this information on the Ardupilot wiki.
https://github.com/ArduPilot/ardupilot_wiki/pull/4010/files
