### ISSUE TITLE
Complete Parameter List

### ISSUE THREAD

**Issue by mech-thkoeln** [ArduPilot/ardupilot_wiki#3999]
[Complete Parameter List](https://ardupilot.org/copter/docs/parameters.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

NTF_BUZZ_TYPES: Buzzer Driver Types seems wrong in the wiki

in the table it is stated:
0 | Built-in buzzer
1 | DShot

however for an OmnibusF4 

setting NTF_BUZZ_TYPES=1 uses the built-in buzzer pin.  NTF_BUZZ_TYPES=0 switches off all buzzers.
Thanks!

**Comment by Hwurzburg** [comment]
it is correct...its a BITMASK.....so value 0 is no bits set.....value 1 is bit 0 set for the built-in buzzer.....closing
