### ISSUE TITLE
Object Avoidance with Bendy Ruler

### ISSUE THREAD

**Issue by kcee454** [ArduPilot/ardupilot_wiki#4009]
[Object Avoidance with Bendy Ruler](https://ardupilot.org/copter/docs/common-oa-bendyruler.html) - I tried using blendy ruler with parameters as mentioned in tutorial with cube black and RPLidar A2M8 as obstacle sensor....it works fine in manual flight without enabling OA_TYPE...but when I enable OA_Type, Drone doesn't fly well and it crashes.... what might be the issue?

**Comment by Hwurzburg** [comment]
support question should be entered at discuss.ardupilot.org...this is for documentation issues....closing
