### ISSUE TITLE
Small typo in "Starting up and calibrating Plane"

### ISSUE THREAD

**Issue by cjmssmd** [ArduPilot/ardupilot_wiki#4012]
[Starting up and calibrating Plane](https://ardupilot.org/plane/docs/starting-up-and-calibrating-arduplane.html)

Minor nit.  But probably worth fixing:

In this page, the text " If the plane you arm is not a good return point" should say " If the place you arm is not a good return point"

Chris

**Comment by Hwurzburg** [comment]
thanks...fixed...
