### ISSUE TITLE
RFD900 page: replace links back to DIYDrones

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#4024]
We should replace the link to diydrones from the bottom of this page https://ardupilot.org/copter/docs/common-rfd900.html

**Comment by Hwurzburg** [comment]
remove or replace?if replace...with what?

**Comment by rmackay9** [comment]
Sorry I didn't provide that extra info.  I think it should point to our Hardware section of discuss.

https://discuss.ardupilot.org/c/hardware-discussion/radios-hardware/101

I see other discussions re the RFD900 in this area.

**Comment by Hwurzburg** [comment]
done

**Comment by rmackay9** [comment]
thanks very much!
