### ISSUE TITLE
Stores: remove jester drones from stores page

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#4033]
We should remove jester drones (https://www.jestersdrones.org/store/) from the stores page (https://ardupilot.org/ardupilot/docs/common-stores.html)

sky-drones and jdrones also look like they may be broken but I'm not sure if these two are permanently broken or not.

**Comment by nkruzan** [comment]
As of March 2 2022:
Jester Drones page is currently working, but has https certificate error
Sky-Drones appears functional
jDrones is alive but returning http error 500

**Comment by Hwurzburg** [comment]
Done
