### ISSUE TITLE
RC Transmitter Flight Mode Configuration

### ISSUE THREAD

**Issue by Frief84** [ArduPilot/ardupilot_wiki#404]
[RC Transmitter Flight Mode Configuration](http://ardupilot.org/copter/docs/common-rc-transmitter-flight-mode-configuration.html) - Is it possible to make the channel assignment changeable
 like in the microkopter-System ... that would make the Pixhawk easily adaptable!

![capture](https://cloud.githubusercontent.com/assets/10880983/14769382/5e65e648-0a57-11e6-9861-d3f22886ede4.JPG)

**Comment by magicrub** [comment]
I'd this a feature request to the firmware? You've posted an issue to the
documentation page...

**Comment by Frief84** [comment]
Oh sorry ... yes... i gues it's more a Firmwareissue

especially the changeability of the Flight Mode Chanel would be important!!!
for me ;-)

2016-04-24 21:46 GMT+02:00 Tom Pittenger <notifications@github.com>:

> I'd this a feature request to the firmware? You've posted an issue to the
> documentation page...
> On Apr 24, 2016 11:02 AM, "Frief84" <notifications@github.com> wrote:
>
> > RC Transmitter Flight Mode Configuration
> > <
> http://ardupilot.org/copter/docs/common-rc-transmitter-flight-mode-configuration.html
> >
> > - Is it possible to make the channel assignment changeable
> > like in the microkopter-System ... that would make the Pixhawk easily
> > adaptable!
> >
> > [image: capture]
> > <
> https://cloud.githubusercontent.com/assets/10880983/14769382/5e65e648-0a57-11e6-9861-d3f22886ede4.JPG
> >
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ArduPilot/ardupilot_wiki/issues/404>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ArduPilot/ardupilot_wiki/issues/404#issuecomment-214027770>
>



-- 
------------------------------------------------------------------------------------------------------------------------------------------------
Frieder Knabe
Gregor-Mendel-Str.38
14469 Potsdam

Tel: 0173/9103383

**Comment by magicrub** [comment]
Would you mind closing this issue and opening one in /ardupilot/ardupilot?
Thx.

**Comment by WickedShell** [comment]
There are already issues tracking flight channel (and I believe the other
ones as well). The flight mode issue is here:
https://github.com/ArduPilot/ardupilot/issues/3819

**Comment by davidbuzz** [comment]
as noted, not a wiki issue.  :-)
