### ISSUE TITLE
SearcharduIMO

### ISSUE THREAD

**Issue by walgla** [ArduPilot/ardupilot_wiki#4040]
[Search](https://ardupilot.org/copter/search.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by walgla** [comment]
> [Search](https://ardupilot.org/copter/search.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

ardupilot

**Comment by Hwurzburg** [comment]
no info...closing
