### ISSUE TITLE
Sounds (Pixhawk)

### ISSUE THREAD

**Issue by phelix001** [ArduPilot/ardupilot_wiki#4042]
https://ardupilot.org/copter/docs/common-sounds-pixhawkpx4.html  
Sounds don't load.

**Comment by rmackay9** [comment]
I've just tested and the .wav files do play for me on my machine.  So I can click on any of the links on the page and it downloads a .wav file and then I can play it.

**Comment by Hwurzburg** [comment]
it was broken...Tridge just fixed...
