### ISSUE TITLE
The SWAG Shop link is broken.

### ISSUE THREAD

**Issue by muramura** [ArduPilot/ardupilot_wiki#4046]
The SWAG Shop link is broken.

This link is incorrect.
https://shop.ardupilot.org/

The correct URL is as follows
https://www.redbubble.com/people/ArduPilot/shop

**Comment by rmackay9** [comment]
@muramura, thanks for the report.  Which page did you find the broken link on?

**Comment by Hwurzburg** [comment]
@brunoolivieri can you fix?

**Comment by muramura** [comment]
Yes, that's right.

**Comment by tridge** [comment]
the correct link is https://ardupilot.redbubble.com/

**Comment by tridge** [comment]
fixed
