### ISSUE TITLE
Copter: add info on PILOT_SPEED_UP/DN

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#4059]
We should document that the user can set different maximum speeds up and down on the pages for [Loiter](https://ardupilot.org/copter/docs/loiter-mode.html#loiter-mode), AltHold, PosHold, etc.  The parameters are PILOT_SPEED_UP/DN.  We should also mention that the acceleration can be set using PILOT_ACCEL_Z.

**Comment by Hwurzburg** [comment]
#4101 closes this
