### ISSUE TITLE
Gazebo 11 has built-in support for ArduPilot

### ISSUE THREAD

**Issue by chobitsfan** [ArduPilot/ardupilot_wiki#4060]
https://ardupilot.org/dev/docs/using-gazebo-simulator-with-sitl.html

Gazebo 11 now has built-in support for ArduPilot. I have tested it and it seems work fine. Maybe I could help to update wiki?

**Comment by khancyr** [comment]
the plugin is old and only support copter. That is why we got an external plugin

**Comment by chobitsfan** [comment]
@khancyr  Thank you for explaining it. 

By the way, I found plugin from https://github.com/khancyr/ardupilot_gazebo works well with gazebo-9, but it do not work with gazebo-11.
