### ISSUE TITLE
Why can't I see the first video

### ISSUE THREAD

**Issue by A-Xiaojun** [ArduPilot/ardupilot_wiki#4061]
When I tried to set up SITL on Linux, I found that the first video did not load

**Comment by nkruzan** [comment]
The creator has made the video private. It can be viewed here https://web.archive.org/web/20170720201656/https://www.youtube.com/embed/pJGFkZmGV6o

looks like we need a new video.

**Comment by nkruzan** [comment]
the instructions here get you same result https://ardupilot.org/dev/docs/building-setup-linux.html#building-setup-linux

**Comment by Hwurzburg** [comment]
> looks like we need a new video.
Not needed...link has videos....have removed dead link
