### ISSUE TITLE
auto grid & drawing polygon for survey mission in python

### ISSUE THREAD

**Issue by montathar111** [ArduPilot/ardupilot_wiki#4063]
Dear sir 
I hope you are doing well. I am working in drone programming by python. I am using dronekit and mavlink commands. I want to draw a polygon using python is it possible ? I mean I want to give 4 coordinates as an input then apply the polygon command to draw the path for survey. How can I do in in python. or what are the other alternatives ?
regards

**Comment by Hwurzburg** [comment]
please ask support questions in discuss.ardupilot.org forums....this is for wiki errors and additions...
