### ISSUE TITLE
Spektrum Satellite RX Bind Failure

### ISSUE THREAD

**Issue by s-mason4** [ArduPilot/ardupilot_wiki#4068]
Hi there, running a Pixhawk 1 on ArduPlane. TX is a Spektrum DX6 which appears to be compatible on existing documentation.

I am attempting to bind a spektrum dsmx satellite rx (PN #SPM9745) via the SPKT/DSM port on the front of the board. 

There is a brief LED flash when connecting the 3 wire cable, then nothing. I have confirmed the wiring as several other issues have been traced to this.

When pressing Bind DSMX under the Setup>Radio Calibration there is no indication anything occurs and the bind fails.

In MP the Param are set to default, then I have added the following from 
[https://ardupilot.org/copter/docs/common-spektrum-rc.html](url)

    Set SERIAL4_PROTOCOL = 23
    Set SERIAL4_OPTIONS = 4
    Set RSSI_TYPE = 3

Here is a photo of the FC connected to USB and the satellite rx. 
https://imgur.com/a/hW821qf

Next step will be purchasing an RX to bind, then connecting to the FC. This is something I would prefer to avoid.

**Comment by Hwurzburg** [comment]
please move this support question to the discuss.ardupilot.org forum....these issues are for documentation issues and requests...thanks
