### ISSUE TITLE
Discord invite drops new user into General Voice Channel

### ISSUE THREAD

**Issue by acxz** [ArduPilot/ardupilot_wiki#4076]
The link for the discord invite: https://ardupilot.org/discord sends the user directly to the voice channel for General. This isn't a good idea since it can be very awkward for new users to just pop into a voice chat. I think it is a good idea to change the invite link to point to the `general` or `social` text channel.

**Comment by tridge** [comment]
thanks! i've fixed it to redirect to general text chat
