### ISSUE TITLE
Iflight beast h7 page - possible useful information to add

### ISSUE THREAD

**Issue by payor-ma** [ArduPilot/ardupilot_wiki#4099]
Hey not sure if this is worth putting up on the wiki.  

On this page https://github.com/ArduPilot/ardupilot_wiki/blob/master/common/source/docs/common-iflight-beasth7AIO.rst
It is stated that the iflight beast h7 board does not support i2c for a compass.  Whilst this is correct, I found it to be a desirable target and figured out a relatively accessible way to break out i2c for compass and other sensor support.  Unsure whether such a modification belongs on the wiki but maybe others may find it useful.

![example](https://user-images.githubusercontent.com/42142608/152468715-75b2f108-4efe-46f9-af0d-8bcecfb656de.png)

Next to the barometer, which is hooked up via i2c there are two resistors which are 2.2k pull ups for the SDA and SCL.  tacking wires onto the right side of these resistors based on the orientation in the diagram, allows expansion of the i2c bus.  Here's evidence:

![image](https://user-images.githubusercontent.com/42142608/152468853-c509f6e1-3b18-4aa4-92b0-735555bf694a.png)
![image](https://user-images.githubusercontent.com/42142608/152468873-ea4b7ed9-f24d-4e3e-a5cc-a9331a5de66d.png)
![image](https://user-images.githubusercontent.com/42142608/152468887-4615f01a-67fb-4652-acff-85256b477b92.png)
![image](https://user-images.githubusercontent.com/42142608/152468901-0a91d485-3be1-4505-abb2-4ba28de1b613.png)

Availability of i2c for compass and other sensors may be of high value to other people looking to use this board with autopilot.

**Comment by payor-ma** [comment]
I'm happy to produce some clear documentation and put in a pull request but I'm unsure if this kindof stuff belongs on the wiki.

**Comment by Hwurzburg** [comment]
yes,we do put this kind of into in....see  https://ardupilot.org/plane/docs/common-furiousfpv-f35.html
however, since this is directly to components rather than solder pads I would have warnings about potential circuit damage to the components...ie requires skilled soldering techniques....

**Comment by payor-ma** [comment]
I'll close this issue and just put in a pull request when I have some time to do a write up.
