### ISSUE TITLE
Throttle Based Dynamic Notch Setup

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/ardupilot_wiki#4117]
[Throttle Based Dynamic Notch Setup](https://ardupilot.org/copter/docs/common-throttle-based-notch.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

The MP button described as “new DF log” is renamed to "IMU Batch Sample" 

![Screenshot from 2022-02-10 11-17-18](https://user-images.githubusercontent.com/1468842/153386446-b5880a9d-aad1-46f1-bd9d-2fe6606a683f.png)

**Comment by Hwurzburg** [comment]
done
