### ISSUE TITLE
Missing DataFlash Log Documentation about CAND and COFS

### ISSUE THREAD

**Issue by mustafa-gokce** [ArduPilot/ardupilot_wiki#4123]
In the [Onboard Message Log Messages](https://ardupilot.org/copter/docs/logmessages.html#onboard-message-log-messages) wiki page, documentation for CAND and COFS logs is missing.
This issue was created for a request in a [forum topic](https://discuss.ardupilot.org/t/documentation-for-cand-parameter-in-dataflash-log/81778).

**Comment by Hwurzburg** [comment]
COFS no longer exists....CAND needs docs....in progress

**Comment by Hwurzburg** [comment]
PR submitted to add log metadata
