### ISSUE TITLE
how to build Rover 

### ISSUE THREAD

**Issue by vaibhavngp1204** [ArduPilot/ardupilot_wiki#4126]
can anyone share idea or video which will give me idea how to build rover based on pixhawk 2.4.8

**Comment by Hwurzburg** [comment]
ask in discuss.ardupilot.org...this is for documentation errors and updates...

**Comment by rmackay9** [comment]
Some hopefully helpful links:

wiki's first time setup: https://ardupilot.org/rover/docs/apmrover-setup.html
some reference frames: https://ardupilot.org/rover/docs/reference-frames.html
Rover-4.1 discusion area: https://discuss.ardupilot.org/c/ardurover/rover-41/158

Welcome to AP!
