### ISSUE TITLE
Rover: fixup the Sonar and Rangefinder Doco

### ISSUE THREAD

**Issue by gmorph** [ArduPilot/ardupilot_wiki#413]
Need to review the Sonar/Rangefinder doco for Rover as lots has changed since it was originally written.

**Comment by hamishwillee** [comment]
YOu're added to this one. I think you need to request to join https://github.com/orgs/ArduPilot/teams/documentation

**Comment by davidbuzz** [comment]
@gmorph  - update pls.

**Comment by gmorph** [comment]
We can close this as the documentation is consistent now.
