### ISSUE TITLE
EKF & VIBE Failsafe charts not displaying when selected

### ISSUE THREAD

**Issue by Periwink1e** [ArduPilot/ardupilot_wiki#4132]
[EKF Failsafe](https://ardupilot.org/copter/docs/ekf-inav-failsafe.html) - When I open mission planner all functions seem to work fine except when trying to use the EKF and VIBE charts. When I click on these buttons nothing comes up. A window in the background does seem to get generated what is properly named but it is not something that does anything when selected. I did not have this problem when I first started using mission planner but for reasons I'm not sure it has arisen. I have tried getting a fresh install but this has not resolved the issue. 
Thanks for any feedback, Logan

**Comment by Hwurzburg** [comment]
this should be a Mission Planner issue https://github.com/ArduPilot/MissionPlanner/issues  or a support question discuss.ardupilot.org....this area is for documentation issues...you will get more attention from users who could help you with the problem...
