### ISSUE TITLE
Move multiple receivers to advanced configuration (from Peripheral hardware)

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#4143]
I think the multiple receivers setup (https://ardupilot.org/copter/docs/common-multiple-rx.html) is more of an advanced feature than a Peripheral.

It's similar to our RC Options or RCMAP pages which are also under the Advanced Configuration category.

**Comment by Hwurzburg** [comment]
done

**Comment by rmackay9** [comment]
Thanks very much!
