### ISSUE TITLE
Downloading and Analyzing Data Logs in Mission Planner

### ISSUE THREAD

**Issue by CraigElder** [ArduPilot/ardupilot_wiki#417]
Parsing of tables is broken in the second half of this page.

**Comment by jpkh** [comment]
you mean this: http://ardupilot.org/planner/docs/common-downloading-and-analyzing-data-logs-in-mission-planner.html
Can you post full url with link to internal headers on the area where you found this.

**Comment by hamishwillee** [comment]
That's the one - search on "Compass"

**Comment by davidbuzz** [comment]
fixed with commit: https://github.com/ArduPilot/ardupilot_wiki/commit/66f87ab6f42d1b48af5e39902e38cfbd10c97575   which turns all thenon-rendering html table artifacts into proper rendering tables.

**Comment by hamishwillee** [comment]
@davidbuzz Very nice. FMI only, How did you generate the proper tables from the "html"?

**Comment by davidbuzz** [comment]
@hamishwillee  - I used a two stage process: 
1 - past it into here: https://domchristie.github.io/to-markdown/  ( with the github tickbox ticked )
2 - manually fix everything that's broken, which is everything.

**Comment by billbonney** [comment]
@davidbuzz nice, was marvelling at how bad that page had got on formatting just the other day (while trying to glean some useful info)
