### ISSUE TITLE
explanation required for SITL locations.txt file

### ISSUE THREAD

**Issue by HuguesD** [ArduPilot/ardupilot_wiki#418]
Hello,
The ardupilot/Tools/autotest/locations.txt file allows to define starting home positions for the vehicles in SITL. A default locations.txt file exists with different locations. However there are no explanations to be found about what are the last numbers on each line (the first two numbers seem to be GPS coordinates) ?

**Comment by WickedShell** [comment]
Altitude and starting heading, but it should be better documented, you're
right.

IIRC the order is Lat,Lng,Alt,Heading where alt is MSL and in meters, and
heading is degrees

**Comment by HuguesD** [comment]
Thx, very clear now. Should be added to this doc page:http://ardupilot.org/dev/docs/using-sitl-for-ardupilot-testing.html#using-sitl-for-ardupilot-testing

**Comment by magicrub** [comment]
Pending change to the wiki
https://github.com/ArduPilot/ardupilot_wiki/pull/422

**Comment by peterbarker** [comment]
The referenced ticket has already been closed.

I've just pushed a change to sim_vehicle.py to ignore (shell-style) comments in locations.txt, and added a comment at the top of locations.txt giving the format.
