### ISSUE TITLE
Advanced Compass Setup

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/ardupilot_wiki#4205]
[Advanced Compass Setup](https://ardupilot.org/copter/docs/common-compass-setup-advanced.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

This page deserves a description on how to use COMPASS_AUTO_ROT 2   - what to do to make it fix orientation.

**Comment by Hwurzburg** [comment]
#4226 done
