### ISSUE TITLE
Relay LUA Scripting Documentation Error

### ISSUE THREAD

**Issue by mustafa-gokce** [ArduPilot/ardupilot_wiki#4243]
In the [documentation](https://ardupilot.org/copter/docs/common-lua-scripts.html#relay-relay), it says 

> enabled(relay_num) - Returns true if the requested relay is currently turned on.

But in the code, it only returns the relay is enabled or not.
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Relay/AP_Relay.h#L36

I raised this for a [forum discussion](https://discuss.ardupilot.org/t/solved-lua-relay-enabled-and-relay-toggle-issues/83238).

**Comment by rmackay9** [comment]
yes, I agree the documentation is incorrect. txs!

**Comment by Hwurzburg** [comment]
fixed
