### ISSUE TITLE
[Update] Frontpage banner and use-case

### ISSUE THREAD

**Issue by supercrazysam** [ArduPilot/ardupilot_wiki#4248]
Referred by @Hwurzburg here to create this issue:

Mentioned this to @IamPete1 and @rishabsingh3003 as well.  

=====
We posted our "autonomous drone with collision avoidance" project blog here:
https://discuss.ardupilot.org/t/cmu-nrec-falco-drone-safe-flights-by-agile-collision-avoidance/83300

We also submitted PR for listing our project as one of the ardupilot_wiki example use-case. 
#4244  [merged]
#4247  [merged]

=====
Following this, we would like to:

1.  Have our use-case added to the bottom section of Ardupilot home page (https://ardupilot.org/) , similar to how we added use-case to ardupilot_wiki
2. Have this banner_picture below added as one of the frontpage sliding banner (https://ardupilot.org/), linked to our blog post when clicked.

![site_banner](https://user-images.githubusercontent.com/25998453/159780768-8c9c8338-8e3d-4a49-93af-d742ba907391.png)

( link to our blog post: https://discuss.ardupilot.org/t/cmu-nrec-falco-drone-safe-flights-by-agile-collision-avoidance/83300 )

Thank you for your time and help.

Sincerely,
Sam

**Comment by Hwurzburg** [comment]
#4277 addresses....
