### ISSUE TITLE
GLIDE_SLOPE_THR parameter definition issue on docs

### ISSUE THREAD

**Issue by HarunBerk16** [ArduPilot/ardupilot_wiki#4269]
https://ardupilot.org/plane/docs/parameters-Plane-stable-V4.1.7.html#glide-slope-thr-glide-slope-threshold 

The "autotakeoff" word at the end of the paragraph confused me. I know the glide slope term is about landing. I think it should replaced with "auto-landing".

![glide_slope_thr_issue](https://user-images.githubusercontent.com/57728727/161147260-dd9d2ba6-830b-4149-9ca9-db020a83c5d6.jpg)

**Comment by Hwurzburg** [comment]
This is indeed to fix an issue that was with autotakeoff of having to dive after an autotakeoff as it moved to a waypoint afterward...only  used for planes with more power to climb at max angle and airspeed at takeoff throttle....they climb over the slope between the takeoff altitude and the next waypoint during the takeoff climb, resulting in an immediate dive back down to the waypoint glide(climb) slope...this forces recalcuation of the slope to the waypoint from the current altitude/position...
