### ISSUE TITLE
Update building setup for Windows 11 

### ISSUE THREAD

**Issue by RuffaloLavoisier** [ArduPilot/ardupilot_wiki#4279]
https://github.com/ArduPilot/ardupilot_wiki/blob/master/dev/source/docs/building-setup-windows10.rst

Can't i run `WSL2` on `Windows 11` ? I think we need to update.

related issue :

* https://github.com/ArduPilot/ardupilot_wiki/issues/3911

**Comment by hendjoshsr71** [comment]
Certainly can.  Just the setup it less convoluted so I think it would benefit from its own page. 

This issue seems like a duplicate though.

**Comment by Hwurzburg** [comment]
it is...closing in favor of yours Josh....its on my to-do-list
