### ISSUE TITLE
USB connection and upload from WSL2

### ISSUE THREAD

**Issue by RuffaloLavoisier** [ArduPilot/ardupilot_wiki#4280]
A way to connect USB on WSL2 has been officially developed. This will further enhance the performance of the development environment. I think this part needs to be reflected in the [document](https://github.com/ArduPilot/ardupilot_wiki/blob/master/dev/source/docs/building-setup-windows10.rst#wsl1-vs-wsl2) and updated.

**Comment by Hwurzburg** [comment]
its not actually part of official windows but a third party open source project...it does work however....the docs do need updating for  Win11 since it integrates LINUX WSL2 fully except for USB, which needs that add-on...

**Comment by RuffaloLavoisier** [comment]
It's not an official method, but I think we need to let others know that we can improve the development environment. how about you?

**Comment by Hwurzburg** [comment]
its on my list to add a Win11 page...the comment was that its not an official Microsoft release...third party open source

**Comment by Hwurzburg** [comment]
added
