### ISSUE TITLE
Add X-Plane data in and out settings to sitl-with-xplane.rst 

### ISSUE THREAD

**Issue by radiohound** [ArduPilot/ardupilot_wiki#4295]
There was a step left out of the instructions for sitl-with-xplane.rst . When I used the additional instructions below (from x-plane-hardware-in-the-loop-simulation.rst) sitl with xplane worked. With X-Plane's initial default settings, no data will go in or out of X-Plane.

These are the screen shots that show the necessary settings you need to set in the Settings Menu – Data Input and Output:
![image](https://user-images.githubusercontent.com/1838777/163529182-fed1f26f-d986-4c8c-91c6-3cddd63941bd.png)
![image](https://user-images.githubusercontent.com/1838777/163529262-c76f3968-13c8-4e92-8b76-cb0d3a7665fe.png)

**Comment by TunaLobster** [comment]
I reviewed the X-Plane SITL code and retested this. With ArduPilot running and no X-Plane data being output (none of the boxes checked), ardupilot SITL waits for data to show up. Once the first packet shows up, ArduPilot sends commands to set the rest of the data output settings and then SITL continues on like normal.

I do understand the issue though. There are 2 X-Plane pages with complimentary information. Lets leave this open and I will consolidate the information down and update for X-Plane 11 where needed.

**Comment by Hwurzburg** [comment]
closed by above
