### ISSUE TITLE
Calibration PX4Flow

### ISSUE THREAD

**Issue by quentin1002** [ArduPilot/ardupilot_wiki#432]
Hi everybody, 

I followed this [tutorial](http://ardupilot.org/copter/docs/common-px4flow-overview.html) in order to calibrate my PX4Flow, used along with a pixhawk PX4 board. Neverless the consistency check is not giving me a relevant result. Here is what I get performing the x-gyro test. In white is the HIGH_RES_IMU_xgyro and in pink is the OPTICAL_FLOW_RAD_Integrated_xgyro. As you can see there is a scaling effect that I can't solve...
![screenshot from 2016-05-04 16 15 03](https://cloud.githubusercontent.com/assets/15336020/15008621/2339d948-1214-11e6-8a4f-743d050db935.png)

Thanks in advance for your help,
Quentin

**Comment by hamishwillee** [comment]
Hi Quentin

Sorry for the delay. Best place to ask this question is the forums: http://discuss.ardupilot.org/

If this discussion should show a flaw in the tutorials, then of course we'd love to fix it - let us know.

Regards
Hamish
