### ISSUE TITLE
Ainstein US-D1 Radar Altimeter

### ISSUE THREAD

**Issue by Prathapremo** [ArduPilot/ardupilot_wiki#4330]
[Ainstein US-D1 Radar Altimeter](https://ardupilot.org/copter/docs/common-aerotenna-usd1.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by Prathapremo** [comment]
Which firmware is supportable for USD1 radar for CAN port please let me know if someone could get output from CAN Port

**Comment by Hwurzburg** [comment]
support is in the current stable release...support questions should be posted in discuss.ardupilot.org, not here
