### ISSUE TITLE
About > Roadmap should point to https://github.com/orgs/ArduPilot/projects/1

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#4348]
We should probably archive the [older roadmap page](https://ardupilot.org/dev/docs/roadmap.html) and instead point ardupilot.org's Roadmap page to here: https://github.com/orgs/ArduPilot/projects/2

**Comment by Hwurzburg** [comment]
done

**Comment by rmackay9** [comment]
Thanks so much!
