### ISSUE TITLE
Copter: fixup Autotune instructions to specify setting up RC aux switch or flight mode

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#4372]
There was some confusion in [this 4.2 discussion](https://discuss.ardupilot.org/t/autotune-with-a-6-channel-radio/86186) because the user though they must use an auxiliary switch.  AutoTune is a flight mode now though so the flight mode channel can be used instead.

**Comment by Hwurzburg** [comment]
#4374 closes this
