### ISSUE TITLE
Rover: add L298N motor driver connection instructions to Motors/ESCs category

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#4375]
There are numerous requests from users (like [here](https://discuss.ardupilot.org/t/connecting-pixhawk-2-4-8-and-motor-driver-l298n/68503) and [here](https://github.com/ArduPilot/ardupilot/issues/20637)) about how to use a L298n motor driver.  Yesterday [jazzl0ver provided these instructions](https://github.com/jazzl0ver/ardupilot-rover-l298n) so we should migrate these instructions to the [Rover wiki's Motors and ESCs section](https://ardupilot.org/rover/docs/common-escs-and-motors.html).

P.S. I'm adding this issue so that we don't forget about it.

**Comment by Hwurzburg** [comment]
added to brushed motors page
