### ISSUE TITLE
Package "gflags_catkin" is required in page "Using ROS/Gazebo Simulator with SITL"

### ISSUE THREAD

**Issue by glody** [ArduPilot/ardupilot_wiki#439]
In page "http://ardupilot.org/dev/docs/using-rosgazebo-simulator-with-sitl.html", error "glog_catkin: Cannot locate rosdep definition for [gflags_catkin]" shows while runing "rosdep install --from-paths src --ignore-src --rosdistro indigo -y".

Pull request had created to fix this issue: https://github.com/ArduPilot/ardupilot_wiki/pull/438

Error message:
$ rosdep install --from-paths src --ignore-src --rosdistro indigo -y
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
glog_catkin: Cannot locate rosdep definition for [gflags_catkin]

**Comment by kiti1013** [comment]
Hello, do you solve this problem？

**Comment by khancyr** [comment]
Can be close
