### ISSUE TITLE
Setup Guide for MakeFlyEasy Believer

### ISSUE THREAD

**Issue by invictus2010** [ArduPilot/ardupilot_wiki#4417]
[Setup Guide for MakeFlyEasy Believer](https://ardupilot.org/plane/docs/airframe-believer.html) - The link to buy a RTF kit for this plane throws a 404 error. This may be a better link: https://www.aliexpress.com/item/2281799816065887.html?gatewayAdapt=4itemAdapt

**Comment by Hwurzburg** [comment]
I will contact our partner for his preference...thanks

**Comment by Hwurzburg** [comment]
updated
