### ISSUE TITLE
GPS / Non-GPS Transitions

### ISSUE THREAD

**Issue by patrickpoirier51** [ArduPilot/ardupilot_wiki#4430]
[GPS / Non-GPS Transitions](https://ardupilot.org/plane/docs/common-non-gps-to-gps.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

Does this really applies to PLANE ?

**Comment by Hwurzburg** [comment]
I dont see why not.....a quadplane approaching and landing in its hanger, for example

**Comment by patrickpoirier51** [comment]
OK , your scenario is working.
The problem is users are expecting it to work on plane as of here:
https://discuss.ardupilot.org/t/px4flow-without-lidar-for-non-gps-navigation/87773

Could I suggest You add some additional explanation/restriction as your quadplane example above ?

btw Thanks for your excellent work  Henry @Hwurzburg

**Comment by Hwurzburg** [comment]
added note
