### ISSUE TITLE
Yaapu initializing loading layout error

### ISSUE THREAD

**Issue by DarioHxC** [ArduPilot/ardupilot_wiki#4468]
As you can see in the video, that error is super annoying. Everytime I flip the arm or mode switches, lua goes nuts. Any help would be really appreciated.

https://youtu.be/2YAY7X4GNIE

**Comment by Hwurzburg** [comment]
wrong group....try opening an issue in https://github.com/yaapu/FrskyTelemetryScript

**Comment by DarioHxC** [comment]
Thank you and sorry for being such a n00b.
