### ISSUE TITLE
AutoTune

### ISSUE THREAD

**Issue by adalta87** [ArduPilot/ardupilot_wiki#4469]
[AutoTune](https://ardupilot.org/copter/docs/autotune.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

Could we include a playback of what arducopter plays once autotune is complete in the autotune instructions page? Some users are tuning without a GCS (although not ideal) and it would be benifical for them to hear or be able to hear the sound that is played once complete. I recently tuned 4 mini quads and had GCS but I always relied on the sound to key me into autotune success, then would confirm in GCS it completed. It is very hard with one individual to stare at GCS during autotune and easier to hear tune if successful then confirm in GCS.

**Comment by Hwurzburg** [comment]
please make a feature request issue in the code section of ArduPilot....closing...not a doc issue
