### ISSUE TITLE
Unable to use vagrant

### ISSUE THREAD

**Issue by khancyr** [ArduPilot/ardupilot_wiki#447]
Hi,

I try to use vagrant to build and see results of my modification but I got the same error you report here : https://github.com/sphinx-doc/sphinx/issues/2429
Did you have a fix ?

**Comment by hamishwillee** [comment]
The problem was in the conf.py file. If you update to the latest version of the documentation source it should work fine.

**Comment by khancyr** [comment]
OK ! thanks, my fork was up to date !

**Comment by hamishwillee** [comment]
Hi @khancyr 
That's odd - so have you got this working now?

**Comment by khancyr** [comment]
*wasn't ...
Yes it works ! So I see that my PR isn't working well ! Need some time to correct and continue it!

**Comment by hamishwillee** [comment]
:-) Thanks for the clarification
