### ISSUE TITLE
Advanced In-Flight FFT Setup

### ISSUE THREAD

**Issue by adalta87** [ArduPilot/ardupilot_wiki#4481]
[Advanced In-Flight FFT Setup](https://ardupilot.org/copter/docs/common-imu-fft-advanced-setup.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

under the [Harmonic Notch Throttle Configuration Using Data from an In-Flight FFT Test Flight](https://ardupilot.org/copter/docs/common-imu-fft-advanced-setup.html) third bullet is this "Perform a stable lengthy hover as you might do for learning the hover throttle with the ." What is suppose to be at the very end where it states with the . then ends?

**Comment by Hwurzburg** [comment]
wiki corrections made
