### ISSUE TITLE
ArduRover for Pixhawk 6C Flight Controller

### ISSUE THREAD

**Issue by jakobjackson2016** [ArduPilot/ardupilot_wiki#4492]
Is there an ETA for a `stable` ArduRover release for HolyBro Pixhawk 6C?  I have been seeing a `latest` release of Pixhawk 6C for a long time but it has been failing `test.Rover` Autotest: https://autotest.ardupilot.org/ 

Also, has anyone deployed ArduRover on Pixhawk 6C successfully?  Pixhawk 6C is the only HolyBro board available for purchase in the market since I have GPS modules that can work only with HolyBro flight controllers.

**Comment by Hwurzburg** [comment]
wiki issues is not the right place for this....the main repo is....and the Rover version of latest is being built successfully and is avialable for download from the firmware server...if there was an issue, it would not be in there (ie would not build)....dont know exactly what those autotest results really indicate

the Pixhawk6's have not been back ported to the Stable releases yet....dont know if they will or will only be in the 4.3 beta soon to be released
