### ISSUE TITLE
Mandatory Hardware Configuration

### ISSUE THREAD

**Issue by adalta87** [ArduPilot/ardupilot_wiki#4495]
[Mandatory Hardware Configuration](https://ardupilot.org/copter/docs/configuring-hardware.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

Where on this page does it include a link to the initial setup feature that is now under mandatory setup, I clicked through the (next) button but never ever came upon a page that shows that feature or explains it? I actually cannot find a page anywhere for this feature and have been seeing it pushed heavily by dev and the likes in the forums. It is also missing from the hierarchal structure that fit with how the wiki is setup. If this is going to be a mandatory setup it should be included in the wiki somewhere.

**Comment by Hwurzburg** [comment]
sorry I have no idea of what "initial setup" page you are refering to

**Comment by Hwurzburg** [comment]
@adalta87 please provide more information as requested, or I will need to close this issue...thanks
