### ISSUE TITLE
pixracer quick start?

### ISSUE THREAD

**Issue by warmwater** [ArduPilot/ardupilot_wiki#453]
It will be nice to have pixracer quick start or detailed instruction

**Comment by hamishwillee** [comment]
Yes it would - at the moment all we've got is the [pixracer overview](http://ardupilot.org/copter/docs/common-pixracer-overview.html). If you have any expertise in creating something similar to the [Pixhawk Quickstart](http://ardupilot.org/copter/docs/common-pixhawk-wiring-and-quick-start.html) we'd be happy to take it :-)

@rmackay9 Anyone else you might suggest we could get on board to create a quickstart?

**Comment by davidbuzz** [comment]
No movement on this suggestion  for ~6 months, closing it, but I encourage the original submitter to rais a PR for the wiki with this suggestion.
