### ISSUE TITLE
PRX_ to PRX1_ changes have created warnings in the wiki 

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#4537]
[Yesterday's multiple proximity sensor PR](https://github.com/ArduPilot/ardupilot/pull/21521) has broken some links in the wiki
![image](https://user-images.githubusercontent.com/1498098/186614098-9567a4e0-f51c-41a4-9442-ab766c493a0c.png)

In general the fix is just to replace PRX_ with PRX1_.  Note that some parameters remain as PRX_ (those that apply to all sensors).

**Comment by Hwurzburg** [comment]
a bit more than that, but I will update ASAP

**Comment by Hwurzburg** [comment]
shouldnt we add the exclusion and yaw params to the rplidar and terarange tower pages?

**Comment by Hwurzburg** [comment]
and something is wrong with your build errors due to this....there are several more pages with errors....that makes me wonder why you do not see them in your test build

**Comment by Hwurzburg** [comment]
fixed....let me know about the added params to the other prox sensors pages

**Comment by rmackay9** [comment]
awesome, thanks very much!
