### ISSUE TITLE
CAN Bus Setup

### ISSUE THREAD

**Issue by nojiratz** [ArduPilot/ardupilot_wiki#4542]
[CAN Bus Setup](https://ardupilot.org/copter/docs/common-canbus-setup-advanced.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.
The parameter CAN_Px_PROTOCOL should be changed to CAN_Dx_PROTOCOL

**Comment by Hwurzburg** [comment]
done..thanks
