### ISSUE TITLE
Flymaple based content should be removed from the docs

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/ardupilot_wiki#458]
Flymaple support was recently removed from ArduPilot

> flymaple removal (#4191)

Any content on the topic should be removed from the docs

**Comment by magicrub** [comment]
I think this has been fixe dalready

**Comment by hamishwillee** [comment]
No. I didn't do it and haven't seen anyone else doing it. There are at least two hits here: http://ardupilot.org/dev/search.html?q=flymaple&check_keywords=yes&area=default

We should also update the history (http://ardupilot.org/copter/docs/common-history-of-ardupilot.html?highlight=flymaple) to show removal of support.

**Comment by davidbuzz** [comment]
I've removed references to the flymaple except for https://github.com/ArduPilot/ardupilot_wiki/blob/master/dev/source/docs/building-apm-for-flymaple.rst  , as it explicitly mentions the board is no longer supported.     I've also added the "removal of support" to the history document.   issue can now be closed.
