### ISSUE TITLE
Searchflight mode

### ISSUE THREAD

**Issue by denjohn** [ArduPilot/ardupilot_wiki#4593]
[Search](https://ardupilot.org/dev/search.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by denjohn** [comment]
what's the issue with all flight modes under config in mission planner disappearing? had them there 2 days ago.
how do I reset all from the quad copter drone to mission planner?

**Comment by Hwurzburg** [comment]
this is not a wiki issue.... discuss.ardupilot.org for support questions please
