### ISSUE TITLE
The search does not work

### ISSUE THREAD

**Issue by LanoAstur** [ArduPilot/ardupilot_wiki#4605]
For a few days the web search tool does not work. In my case it is a serious disorder since I use it abundantly to locate query topics in the documentation.

![image](https://user-images.githubusercontent.com/90454231/190015097-dd4f5a0e-958f-4c5c-90bf-a8c851ed5144.png)

It's always the same, it says "searching" but never returns results.

**Comment by Hwurzburg** [comment]
working on fix...might take a day or two

**Comment by LanoAstur** [comment]
Thank you very much for the reply

**Comment by Hwurzburg** [comment]
working now
