### ISSUE TITLE
4.4 Wiki (Should be in Upcoming features asap)

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot_wiki#4665]
- [x] 16677 TKOF_GND_PITCH (@magicrub )
- [x] 19381 Log disarmed only with battery (@priseborough )
- [x] 197332 FBWB Min Alt(@khanasif786 )
- [x] 19860 Add radius to DO_REPOSITION (@magicrub )
- [x] 20399 Add Currawong ECU support (@reilly-callaway)
- [x] 20541 Reset target airspeed (@WickedShell )
- [x] 20669 Trajectory scripting (@MatthewHampsey )
- [x] 20780 TradHeli P tuning(@bnsgeyer )
- [x] 21366 Throttle Gain Boost (@andyp1per )
- [x] 21510 Add Optical Flow to Rover (@stephendade )
- [x] 21609 Copter weathervaning (@IamPete1 )
- [x] 21643 EFI scripting backend (@hendjoshsr71 )
- [x] 21662 Add Temp Sensor peripheral  (@magicrub )
- [x] 21739 VTX control lookup tables (@andyp1per )
- [x] 21780 FFT postfilter (@andyp1per )
- [x] 21787 SIYI Gimbal driver (@rmackay9 )
- [x] 21829 Disable SLCAN when armed (@tridge)
- [x] 21865 ARKV6X flight controller(@AlexKilmaj)
- [x] 21883 RTL inside RTL_RAD in VTOL (@IamPete1 )
- [ ] 21899 SimuLink model for Copter (@fbredeme)
- [x] 21911 SLCAN AP_Periph support (@magicrub )
- [x] 21975 IMU3 kill aux sw(@muramura )
- [x] 22016 Turtle mode features (@andyp1per )
- [x] 22032 EFI CAN Scripting (@tridge )
- [x] Add gimbal commands for #4749 into commands list (@rmackay9 )
- [x] 22051 Change brd safety switch(@peterbarker )
- [x] 22056 New Tricks on a Switch (@tridge)
- [x] 22086 ACRO_LOCKING mode 2 (@tridge)
- [x] 22096 AUTOTUNE_AXES (@Hwurzburg )
- [x] 22147 DO_LAND_START alt (@magicrub )
- [x] 22140 CAM_MIN_INTERVAL (@tridge )
- [x] 22172 Autotest for aerobatics(@tridge)
- [x] 22175 new AEROM params (@tridge)
- [x] 22178 MANUAL_STR_EXPO (@rmackay9 )
- [x] 22174 THR_MIN in disarm (@tridge )
- [x] 22188 PixPilotV6 board (@Cedric0489)
- [x] 22191 Improve TECS (@priseborough )
- [x] 22197 Synth Curr Batt Monitor (@Hwurzburg )
- [x] 22199 Aerobatics scripts (@tridge)
- [x] 22200 FS timeouts (@rmackay9 )
- [x] 22227 ARK RTK GPS (@AlexKilmaj)
- [x] 22258 Payload Place (@lthall )
- [x] 22261 ARGICA GPS Message (@tridge )
- [x] 22262 DroneCAN option (@IamPete1 )
- [x] 22266 ELRS baud rate option (@andyp1per )
- [x] 22267 BARO Z-axis improvement (@andyp1per )
- [x] 22287 Y4 Qframe type (@jmoroso8)
- [x] 22292 Aerobatics scripts (@tridge)
- [x] 22297 ARSPD_ENABLE param (@IamPete1 )
- [x] 22301 Aerobarics scripts(@tridge)
- [x] 22307 ESC CAN timeout (@joshanne )
- [x] 22315 Yaw coordination in AUTOUNE (@tridge)
- [x] 22325 MAvlink force reboot (@peterbarker )
- [x] 22328 QSTAB RC Aux function (@IamPete1 )
- [x] 22332 MambaF405-2022B board (@andyp1per )
- [x] 22378 LAND_WIND_COMP (@rbeall )
- [x] 22382 MatekL431 Batt mon (@tridge )
- [x] 22412 Peach autopilot (@ThePeach-kr)
- [x] Holybro G4 GPS (@tridge)
- [x] 22421 JUMP_TAG mission item(@magicrub )
- [x] 22429 Copter tuning option (@lthall )
- [x] 22431 Corner accel limit (@lthall )
- [x] 22436 ReaperF475 update (@Hwurzburg )
- [x] 22437 BT WindVane (@IamPete1 )
- [x] 22461 Heli yaw comp (@bnsgeyer )
- [x] 22474 SITL on hdwr improvements (@tridge )
- [ ] 22479 SITL file connection via UART (@peterbarker )
- [x] 22488 VectorNAV100 support (@IamPete1 )
- [x] 22584 TKOFF_THR_MAX_T param (@tridge)
- [x] 22626 Emerg status in OpenDroneID(@tridge)
- [x] 22631 Dont allow same low and crt batt setting (@IamPete1 )
- [x] 22636 QRTL alt cone (@IamPete1 )
- [x] 22651 New Webots docs (@IamBurwell)
- [x] 22673 Qplane payload script applet(@tridge )
- [x] 22697 Add MAX31865 temp sensor(@magicrub )
- [x] 22712 TradHeli manual autorotate(@bnsgeyer )
- [x] 22714 EFI battery monitor(@tridge )
- [x] 22742 Change QRTL radii(@IamPete1 )
- [x] 22748 Runcam 2 4K option(@Cam84Fr)
- [x] 22750 Yaw autotune in other modes(@Hwurzburg )
- [x] 22763 BRD_PWM_VOLT_SEL(@tridge )
- [ ] 22765 SITL Xplane(@tridge )
- [x] 22819 PixPilotV3 and PixSurveyA2 (@Cedric0489 )
- [x] 22843 OSD avg resting cell volt panel(@Hwurzburg )
- [x] 22882 rFCU H743 board (@tridge ) **awaiting README.md**
- [x] 22794 FS_GCS_TIMEOUT for Rover(@khancyr )
- [x] 22921 Mission on SD(@tridge )
- [x] 22924 Mag Cal RC switch (@Hwurzburg )
- [x] 22955 CAM params rename (@rmackay9 )
- [x] 22965 MPPT_ENABLE (@magicrub )
- [x] 23072 BDShot Pixhawk6C and ZealotH743(@andyp1per )
- [x] 23084 Diawa Winch baud rate update(@rmackay9 )
- [x] 23097 SURFTRAK_TC (@lthall )
- [x] 23139 Payload Place abort (@hwurzburg)
- [ ] YAW D autotune (@andyp1per) **wiki delayed until fully tested by users per Leonard**
- [x] 23200 Landing Abort SW (@magicrub )
- [x] 23233 Dead Reckoning Applet (@rmackay9 )

updated 03/18/2023

**Comment by andypiper** [comment]
likely typo, should be @andypiper -> @andyp1per above
