### ISSUE TITLE
Add how we use  fund  in donation page

### ISSUE THREAD

**Issue by khancyr** [ArduPilot/ardupilot_wiki#4697]
This https://ardupilot.org/copter/docs/common-partners-program.html#how-are-collected-funds-spent should  be linked  on donation page. That  would make  it  clear  for  even communauty  how  we  spend money

**Comment by Hwurzburg** [comment]
not sure how to do that on the paypal page....but could add a link below the donate button "How are donations spent?"

**Comment by mohit-marathe** [comment]
Hey @Hwurzburg! I have made a PR for this issue here: https://github.com/ArduPilot/ardupilot_wiki/pull/4768
Please see to it. Thanks!

**Comment by Hwurzburg** [comment]
closed by above
