### ISSUE TITLE
CAN bus and UAVCAN protocol

### ISSUE THREAD

**Issue by steamfoundry** [ArduPilot/ardupilot_wiki#4698]
[CAN bus and UAVCAN protocol](https://ardupilot.org/dev/docs/can-bus.html) - To match [PR 3983](https://github.com/ArduPilot/ardupilot_wiki/pull/3983) This page needs a rewrite to correct the naming to the current DroneCan project name.

**Comment by Hwurzburg** [comment]
thanks...updated

**Comment by steamfoundry** [comment]
Thanks!

(Team McFly, #Hovergames 2022)
