### ISSUE TITLE
Glossary : add the meaning of "ATC".

### ISSUE THREAD

**Issue by batzkass** [ArduPilot/ardupilot_wiki#470]
[Glossary](http://ardupilot.org/copter/docs/common-glossary.html)
I see the ATC acronym in many stabilisation parameters but I can't find its exact meaning. Maybe a new entry here could help ?
Thanks.

**Comment by magicrub** [comment]
added

**Comment by batzkass** [comment]
Thanks for this fast reaction. But I'm not sure "Air Traffic Control" is the right acronym here, as I thought about : http://ardupilot.org/copter/docs/parameters.html#atc-parameters

**Comment by rmackay9** [comment]
So in the case of the Copter parameters, "ATC" is for ATitude Control.
