### ISSUE TITLE
Add time delay to GUIDED mode

### ISSUE THREAD

**Issue by fdndimon** [ArduPilot/ardupilot_wiki#4712]
How can I add a time delay option to GUIDED mode?
So that the vehicle is not always in it, but only for the specified time. And when it expires, switch back to AUTO mode.

**Comment by Hwurzburg** [comment]
this is not a wiki issue...better to ask in the discuss.ardupilot.org support forrums....

**Comment by rmackay9** [comment]
@fdndimon,

I think the best way is probably to use a Lua script.  https://ardupilot.org/copter/docs/common-lua-scripts.html
