### ISSUE TITLE
Testing with Replay

### ISSUE THREAD

**Issue by priseborough** [ArduPilot/ardupilot_wiki#476]
[Testing with Replay](http://ardupilot.org/dev/docs/testing-with-replay.html) - Documentation is out of date

**Comment by hamishwillee** [comment]
Hi @priseborough - I believe you :-) Is this something you can/will fix, or is there someone else you'd nominate? Can you expand on where the issues in this are?

**Comment by priseborough** [comment]
The console command examples no longer work since the replay was updated several weeks ago. I am happy to fix, but have raised this issue so I don't forget.

**Comment by hamishwillee** [comment]
Thanks very much. Assigned to you!

**Comment by gmorph** [comment]
@peterbarker - as the Tools guy do you think you can update this?

**Comment by peterbarker** [comment]
Done.
