### ISSUE TITLE
Plugin versioning

### ISSUE THREAD

**Issue by mitarpol** [ArduPilot/ardupilot_wiki#477]
Hello.
I made plugin for MP 1.3.37. 
This plugin works on .37 and .38 but not working on previous (i checked 1.3.30, 1.3.20) 
How plugin versioning works?

**Comment by hamishwillee** [comment]
Hi 
This area is for ardupilot wiki bugs. Probably best place to raise this question is the mission planner discussion area: http://discuss.ardupilot.org/c/ground-control-software/mission-planner

Regards
