### ISSUE TITLE
Advanced Compass Setup

### ISSUE THREAD

**Issue by davidbitton** [ArduPilot/ardupilot_wiki#478]
[Advanced Compass Setup](http://ardupilot.org/copter/docs/common-compass-setup-advanced.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

There are weird line breaks near the top. See pic.

![screenshot](https://cloud.githubusercontent.com/assets/277207/16238638/2930855c-37af-11e6-8589-f70fb95b43ec.png)

**Comment by davidbuzz** [comment]
fixed.  :-)
