### ISSUE TITLE
Document new AirMode arming behavior

### ISSUE THREAD

**Issue by arikrupnik** [ArduPilot/ardupilot_wiki#4781]
https://ardupilot.org/plane/docs/airmode.html describes older, pre-4.2 behavior WRT AirMode arming. It refers to `RCx_OPTION` 41. 4.2 introduced two new options, 153 and 154. This page seems like the place to describe the new behavior.

**Comment by shashwat-chawla** [comment]
Can you please elaborate the issue?
I can't understand it .

**Comment by Hwurzburg** [comment]
the wiki was updated to the new behavior a while back...this issue should be closed....4.1 and prior firmware activated airmode differently
