### ISSUE TITLE
If ACRO mode uses rudder now, update acro-mode.html

### ISSUE THREAD

**Issue by arikrupnik** [ArduPilot/ardupilot_wiki#4787]
https://ardupilot.org/plane/docs/acro-mode.html says: 

> In the current implementation the controller won’t use rudder while the plane is on its side to hold pitch, which means horizontal rolls won’t be as smooth as a good manual pilot, but that should be fixed in a future release. This also means that it won’t hold knife-edge flight.

Is this still accurate as of 4.3?

**Comment by Hwurzburg** [comment]
yes its true unless YAW_RATE_ENABLE is enabled and the axis properly tuned...unless acro locking is also enabled, only the rate controller is active and attitude drift in body-frame yaw can still occur...

**Comment by Hwurzburg** [comment]
see #4791
