### ISSUE TITLE
APM Planner 2 windows download link is broken

### ISSUE THREAD

**Issue by WickedShell** [ArduPilot/ardupilot_wiki#479]
http://ardupilot.com/planner2/docs/install-windows.html

(I actually can't find the current download link or I'd try to submit a fix)

**Comment by hamishwillee** [comment]
Fixed in https://github.com/ArduPilot/ardupilot_wiki/commit/137c11b268e23bdbdc7289ae9ecd407c1dafb1b5

SOmeone moved the "latest" builds under a latest folder.
