### ISSUE TITLE
how to enable wind estimation?

### ISSUE THREAD

**Issue by Rand0409** [ArduPilot/ardupilot_wiki#4814]
Should I Calculate the Propeller Drag Coefficient to enable wind estimation, or just update the Arducoptor firmware to 4.3+?  
I don't see any change with Mission Planner status' wind section.

**Comment by Hwurzburg** [comment]
ask on discuss.ardupilot.org....its a support question not a documentation issue as far as I can see

**Comment by rmackay9** [comment]
In case it helps, the setup for the wind speed estimation is detailed here https://ardupilot.org/copter/docs/airspeed-estimation.html .  I suspect you've already seen this though.  As Henry says, questions should really go in [the forums](https://discuss.ardupilot.org/c/arducopter/copter43/167) first.
