### ISSUE TITLE
SIYI ZR10 and A8 Gimbals

### ISSUE THREAD

**Issue by Lorisdem** [ArduPilot/ardupilot_wiki#4815]
[SIYI ZR10 and A8 Gimbals](https://ardupilot.org/copter/docs/common-siyi-zr10-gimbal.html) - Add expo on RC_TILT and RC_Yaw chanells needed for smooth operation of ZR10.

**Comment by rmackay9** [comment]
This is really a flight code enhancement so I've created an issue over on the other issues list (linked above).  Thanks for the report.
