### ISSUE TITLE
Archive OpenKai page

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#4817]
We should archive this page and remove it from the Non-GPS navigation landing page
https://ardupilot.org/rover/docs/common-zed.html

It worked many years ago (at least for me) but I've never actually seen another person successfully use it since so I don't think we should present it as a valid option in on Non-GPS section because it is more likely to mislead users rather than help them achieve their goals.

**Comment by Hwurzburg** [comment]
done #4819

**Comment by rmackay9** [comment]
@Hwurzburg Thanks very much!
