### ISSUE TITLE
QGC ON IPHONE & IPAD NOT CONNECTING RELIABLY TO CUBE BLACK WITH WIFI

### ISSUE THREAD

**Issue by PilotCommander** [ArduPilot/ardupilot_wiki#4818]
[Search](https://ardupilot.org/copter/search.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by PilotCommander** [comment]
ANY SETUP (CONFIGURATION) SUGGESTIONS HERE PLEASE? 
MACBOOK (IOS VENTURA) CONNECTS EVERY TIME WITHOUT PROBLEM TO BOTH Q GROUND CONTROL AND MP USING THE COPTER'S WIFI CONNECTION BUT NOT MY NEW IPHONE OR IPAD, EVERY NOW AND THEN THEY DO CONNECT, BUT WHEN YOU GO BACK THE NEXT TIME THEY JUST STAY DISCONNECTED
THANKS CHRIS

**Comment by Hwurzburg** [comment]
please post support questions in the support forum: discuss.ardupilot.org    this is not a documentation issue
