### ISSUE TITLE
SITL Parameters

### ISSUE THREAD

**Issue by sluvd** [ArduPilot/ardupilot_wiki#4825]
[SITL Parameters](https://ardupilot.org/dev/docs/sitl-parameters.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

In "https://ardupilot.org/dev/docs/sitl-parameters.html" there is a parameter called (SIM_WIND_DELAY) but I can't find in mission planner when simulating.

**Comment by Hwurzburg** [comment]
it was deleted in May...never used...

**Comment by Hwurzburg** [comment]
removed...there are probably others.. they get added and removed as sitl tests are reorganized over time...probably time to regenerate the table...with @peterbarker help
