### ISSUE TITLE
Robotis Servos

### ISSUE THREAD

**Issue by vidyaap97** [ArduPilot/ardupilot_wiki#4859]
[Robotis Servos](https://ardupilot.org/copter/docs/common-servo-robotis.html) - Is enough to make servo work with pixhawk 6C?
Dynamixel - XM430-W350-T connected Tx pin of pixhawk telem 2(serial2) port( Tried other serial ports also)
Baud rate of dynamixel -57600bps
ID - 11
Protocol 2
Pixhawk 6C( hexacopter X config, Firmware version - 4.3.2)
I checked the Tx pin output in oscilloscope, I can’t see any UART signal.

**Comment by rmackay9** [comment]
@vidyaap97,

The instructions on the [Robotis wiki page](https://ardupilot.org/copter/docs/common-servo-robotis.html) should be sufficient but we don't have a lot of users of this feature so it is possible that it may be broken.

This is actually our wiki to-do list so could you instead raise the issue as a new topic in the [Copter-4.3 category of discuss](https://discuss.ardupilot.org/c/arducopter/copter43/167)?  If possible it would be good if you could also attach an [onboard log](https://ardupilot.org/copter/docs/common-downloading-and-analyzing-data-logs-in-mission-planner.html).
