### ISSUE TITLE
EKF / DCM Check Failsafe not landing

### ISSUE THREAD

**Issue by Patnetpatnet** [ArduPilot/ardupilot_wiki#487]
[EKF / DCM Check Failsafe](http://ardupilot.org/copter/docs/ekf-inav-failsafe.html) EKF errors are tripped yet still allows me to go to PH from Stab and does not Failsafe and land. Loss of control.

**Comment by hamishwillee** [comment]
Best to raise this first in the discussion forums: http://discuss.ardupilot.org/c/arducopter
This is a place to report errors in the documentation.
