### ISSUE TITLE
problem in the microcontroller 

### ISSUE THREAD

**Issue by abdul828** [ArduPilot/ardupilot_wiki#4933]
![Uploading ٢٠٢٣٠٢٠٩_٠١١٩٤٦.jpg…]()
It flashed red and then it didn't work

**Comment by Hwurzburg** [comment]
this does not have enough information about what issue you are having.  and nothing is attached as an image..and support questions should be directed to discuss.ardupilot.org or the vehicle help area on the discord server....closing this
