### ISSUE TITLE
ROS with SITL in Gazebo

### ISSUE THREAD

**Issue by dtardiss** [ArduPilot/ardupilot_wiki#4938]
[ROS with SITL in Gazebo](https://ardupilot.org/dev/docs/ros-gazebo.html) - As a team we are preparing for Fixed-Wing UAV competition. We want to simulate our project with fixed-wing plane model in GAZEBO but we are getting problems and there is no up-to-date guide about it. I'm using Ubuntu 20.04,ROS Noetic distribution.

**Comment by Hwurzburg** [comment]
this has been updated in wiki  closing
