### ISSUE TITLE
Gremsy gimbal to autopilot connection digram should show 5V disconnected

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#4958]
The Gremsy wiki page's wiring diagram shows the 5V line connected between the gimbal and autopilot which is not a good idea.  We should update this diagram to remove that connection.

https://ardupilot.org/copter/docs/common-gremsy-pixyu-gimbal.html#connecting-to-the-autopilot-4-3-or-higher

**Comment by Hwurzburg** [comment]
@rmackay9 since I did not create that drawing, modifying it would require a complete re-draw....do you still have the raw drawing?

**Comment by Hwurzburg** [comment]
fixed by #5114
