### ISSUE TITLE
INS_ACC_IDx is marked readonly

### ISSUE THREAD

**Issue by lotsofone** [ArduPilot/ardupilot_wiki#4974]
[Parameter Reset](https://ardupilot.org/plane/docs/common-parameter-reset.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.
https://ardupilot.org/plane/docs/common-parameter-reset.html
This page tells us how to restore calibrations after resets. But when I try to write INS_ACC_ID parameter, the ground station shows "INS_ACC_ID" is marked readonly, and I cannot write it.

**Comment by Hwurzburg** [comment]
do it FULL PARAMETER TREE as the wiki shows
