### ISSUE TITLE
Complete Parameter List

### ISSUE THREAD

**Issue by heinduplessis** [ArduPilot/ardupilot_wiki#5009]
It’s mentioned here that the vehicle can only be rudder armed when in manual modes. However we’ve tested many times and one can arm the aircraft in auto mode, causing a very dangerous scenario.

https://ardupilot.org/plane/docs/parameters.html#arming-rudder-arming-with-rudder-enable-disable

**Comment by Hwurzburg** [comment]
being discussed at next devcall.... #23186 is being proposed to address...then the param description can be updated in another PR pending acceptance of that PR....even if rejected, I will do a PR to correct the param description

**Comment by Hwurzburg** [comment]
results of devcall....my PR added a safety feature to rudder arming in AUTO or MODE TAKEOFF was discussed and some modifications were proposed which I will work on....in the meantime, I will cubmit a PR to correct the param description...
