### ISSUE TITLE
Creating Tamperproof Firmware

### ISSUE THREAD

**Issue by Sathiyanarayanan18** [ArduPilot/ardupilot_wiki#5020]
[Creating Tamperproof Firmware](https://ardupilot.org/dev/docs/secure-firmware.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

tunga@tunga-desktop:~/ardupilot$ ./waf copter
Waf: Entering directory `/home/tunga/ardupilot/build/CubeOrange'
Checking for env.py
env added DEFAULT_PARAMETERS=/home/tunga/ardupilot/libraries/AP_HAL_ChibiOS/hwdef/CubeOrange/defaults.parm
env added APJ_BOARD_TYPE=STM32H743xx
env added USBID=0x2dae/0x1016
env added EXT_FLASH_RESERVE_START_KB=0
env added OPTIMIZE=-O2
env added BOOTLOADER_EMBED=1
env added ENABLE_DFU_BOOT=1
env added MAIN_STACK=0x600
env added BOARD_FLASH_SIZE=2048
env added APJ_BOARD_ID=140
env added CORTEX=cortex-m7
env added CHIBIOS_BUILD_FLAGS=USE_FATFS=yes MCU=cortex-m7 ENV_UDEFS=-DCHPRINTF_USE_FLOAT=1 CHIBIOS_PLATFORM_MK=os/hal/ports/STM32/STM32H7xx/platform.mk CHIBIOS_STARTUP_MK=os/common/startup/ARMCMx/compilers/GCC/mk/startup_stm32h7xx.mk
env appended CPU_FLAGS=['-mcpu=cortex-m7', '-mfpu=fpv5-d16', '-mfloat-abi=hard', '-DARM_MATH_CM7', '-u_printf_float']
env added PROCESS_STACK=0x1C00
env added HAL_NUM_CAN_IFACES=2
env added EXT_FLASH_SIZE_MB=0
env added HAS_EXTERNAL_FLASH_SECTIONS=0
env added FLASH_TOTAL=1966080
env added ENABLE_CRASHDUMP=1
env added IOMCU_FW=0
env added HAL_CANFD_SUPPORTED=8
env appended APP_RAM_START=None
env added BUILD_ABIN=True
env added FLASH_RESERVE_START_KB=128
env added PERIPH_FW=0
env added WITH_FATFS=1
Padded 16 bytes for bootloader.bin to 50144
Embedding file bootloader.bin:/home/tunga/ardupilot/Tools/bootloaders/CubeOrange_bl.bin
Embedding file hwdef.dat:/home/tunga/ardupilot/build/CubeOrange/hw.dat
Embedding file io_firmware.bin:Tools/IO_Firmware/iofirmware_highpolh.bin
[905/912] Linking build/CubeOrange/bin/arducopter
[906/912] apj_tool build/CubeOrange/bin/arducopter
Loaded binary file of length 4103156
Setting defaults from /home/tunga/ardupilot/libraries/AP_HAL_ChibiOS/hwdef/CubeOrange/defaults.parm
Saved binary of length 4103156
[907/912] Generating bin/arducopter.bin
[908/912] app_descriptor build/CubeOrange/bin/arducopter.bin
Waf: Leaving directory `/home/tunga/ardupilot/build/CubeOrange'
Build failed
Traceback (most recent call last):
  File "/home/tunga/ardupilot/modules/waf/waflib/Task.py", line 348, in process
    ret = self.run()
  File "Tools/ardupilotwaf/chibios.py", line 296, in run
    desc = struct.pack('<IIII76s', crc1, crc2, len(img), githash, sig)
error: argument for 's' must be a string
![Screenshot from 2023-03-14 18-38-16](https://user-images.githubusercontent.com/125279106/225010869-f009e6b7-90ae-47f1-917b-872fc22f71c6.png)

**Comment by Hwurzburg** [comment]
please post in a support area....discuss.ardupilot.org or general user help on the Ardupilot Discord server....
