### ISSUE TITLE
The docs show Mamba H743v4, is that correct?

### ISSUE THREAD

**Issue by jwarnergithub** [ArduPilot/ardupilot_wiki#5038]
I've been looking at getting a new FC and ran across the Mamba H743v4 in the docs, but I don't believe a v4 version exists for the public, if at all. Before I put in a PR to request the page change, I just want to make sure this wasn't a dev board sent to the team as a future release and it's not supposed to be the Mamba H743 MK4? 

The only current board I found is the Mamba H743 MK4 v2 [HERE](https://www.diatone.us/collections/flightcontroller/products/mamba-mk4-h743-v2-flight-control-30mm-m3), which looks like the newest version of this board.

**Comment by Hwurzburg** [comment]
the code should work with either version of the H743...it supports both the old and the new IMUs....Diatone's names continuously change a bit and are not consistent...but the pinout and features of the currently offered board seem to be the same as the one which we have code for...
