### ISSUE TITLE
Suggestions for "Adding Parameters" Dev Wiki Page

### ISSUE THREAD

**Issue by olliw42** [ArduPilot/ardupilot_wiki#504]

**Comment by hamishwillee** [comment]
Hi @olliw42 

Thanks very much for taking the time to post this. First thing, this is actually on the DEV wiki - the real URL is here: http://ardupilot.org/dev/docs/code-overview-adding-a-new-parameter.html
The reason you're seeing it on copter is that things get redirected in odd ways from the old ardupilot.com site to the new ardupilot.org site.

The instructions for making [edits/PRs are here](http://ardupilot.org/dev/docs/common-wiki_editing_guide.html) ... this appears on all wikis from the top menu "about" link. Would it be possible to "remake" your changes following these instructions? (you can probably just copy-paste what you have now into an edit window). That will make it much easier for me to review the differences.

Regards
Hamish

**Comment by olliw42** [comment]
ah ... I didn't realize that there are extra info for the wiki ... this is very well made, indeed very easy !! (when I read the info for PR to the code I passed out, but this could do LOL)
