### ISSUE TITLE
Download and Installation of MAVProxy on Raspberry Pi

### ISSUE THREAD

**Issue by ravagea1** [ArduPilot/ardupilot_wiki#5058]
[Download and Installation](https://ardupilot.org/mavproxy/docs/getting_started/download_and_installation.html) - Getting this error when trying to download mavproxy to a Raspberry Pi 2 Model B

"ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you                                                                                         have updated the package versions, please update the hashes. Otherwise, examine                                                                                         the package contents carefully; someone may have tampered with them.
    mavproxy from https://www.piwheels.org/simple/mavproxy/MAVProxy-1.8.59-py3-n"

This is the bit of command line output when it happens
```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting mavproxy
  Downloading https://www.piwheels.org/simple/mavproxy/MAVProxy-1.8.59-py3-none-                                                                                        any.whl (7.1 MB)
     |████████████████████████████▍   | 6.3 MB 4.8 kB/s eta 0:02:47
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you                                                                                         have updated the package versions, please update the hashes. Otherwise, examine                                                                                         the package contents carefully; someone may have tampered with them.
    mavproxy from https://www.piwheels.org/simple/mavproxy/MAVProxy-1.8.59-py3-n

```

I copy pasted the code (attached below) into the command line and hit enter and let the installation happen.
```
sudo apt-get install python3-dev python3-opencv python3-wxgtk4.0 python3-pip python3-matplotlib python3-lxml python3-pygame
pip3 install PyYAML mavproxy --user
echo 'export PATH="$PATH:$HOME/.local/bin"' >> ~/.bashrc
```

Any input on how I can fix this? Thanks in advance!

**Comment by Hwurzburg** [comment]
This really should be in the support group discuss.ardupilot.org.....you will get the appropriate people looking at it.....I will wait a day or two to close this while you have a chance to move it

**Comment by ravagea1** [comment]
Oops sorry about that! Will move it asap
