### ISSUE TITLE
4.5 Wiki (Should be in Upcoming features )

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot_wiki#5060]
- [x] 13760 VTOL fwd motor (@priseborough )
- [ ] 13961 IMUO serial protocol (@tridge)
- [x] 19517 Add OSD_TYPE2 (@yaapu )
- [x] 19687 Send gps over DroneCAN (@magicrub )
- [x] 20138 LD-06 Proximity(@Adithya-Patil )
- [x] 20356 Motor spool down time (@WickedShell )
- [x] 21439 SPRacing H7RF (@andyp1per )
- [x] 21805 Hirth ICE/EFI (@Lokesh-Carbonix)
- [ ] 22278 mavlink_parse.py (@ES-Alexander )
- [x] 22331 HiMark CAN servos (back port)(@tridge )
- [x] 22661 DDFP tail rotor linerization (@bnsgeyer )
- [ ] 22671 CubeRED board (@bugobliterator )
- [x] 23131 Yaw D Auttotune(@andypiper )
- [x] 23138 MAVLink2 gimbal commands (@rmackay9 )
- [x] 23170 Holybro KakuteH7-Wing (@Hwurzburg )
- [x] 23186 rudder neutral to arm in AUTO/TAKEOFF (@Hwurzburg )
- [x] 23189 dont trigger RC failsafe until RC seen (@IamPete1 )
- [x] 23191 PixSurveyA1-IND (@Cedric0489 )
- [x] 23223 TKOFF_THR_MAX (@lthall )
- [x] 23237 raw voltage for voltage compensation (@andyp1per )
- [x] 23238 KDECAN rewrite(@magicrub )
- [x] 23249 FlyWoo F745 v2 (@andyp1per )
- [x] 23292 FlyWoo F405 Pro (@andypiper )
- [x] 25330 rename common.py to vehicle_test_suite.py(@peterbarker )
- [x] 23333 AFS switch to AUTO on GCS FS (@eppravitra)
- [x] 23378 new Buzzer sounds (@Hwurzburg )
- [x] 23325 new longFS action (@WickedShell )
- [x] 23425 LOG_DISARMED (moved to 4.4) (@tridge )
- [x] 23428 SpeedyBeeF405WING (@Hwurzburg )
- [x] 23450 Mount POI scripting applet (@rmackay9 )
- [x] 23627 Point Mount at circle center(@khanasif786 )
- [ ] 23640 Image tracking(@rmackay9 )
- [x] FS in Mode Takeoff (@Hwurzburg )
- [x] 23652 JFB-100 board (@rmackay9 )
- [x] 23659 Add support for Ubuntu23.04 (@peterbarker )
- [x] 23706 CAN Compass auto replace option (@IamPete1 )
- [x] 23718 Foxeer H743 GA board (@andyp1per )
- [x] 23728 Mode Takeoff improvement(@Hwurzburg )
- [ ] 23730 CAN mirror in periph(@WickedShell )
- [x] 23737 Gimbal Manager (@rmackay9 )
- [x] 23745 blackbox autoarm(@tridge )
- [x] 23749 RPLidarA1(@peterbarker )
- [x] 23787 Notch fltr tracking(@peterbarker )
- [x] 23805 DroneCAN RC (@peterbarker )
- [x] 23809 Aerofox F9P GPS(@Aerofoxtech )
- [x] 23818 INAxx max amps(@tridge )
- [x] 23824 Winch controlaux switch(@rmackay9 )
- [x] 23832 GCS FS Brake action(@tatsuy )
- [x] 23836 Mount follow mode (@khanasif786 )
- [x] 23847 Cube pinout update(@tridge )
- [x] 23888 USB passthru (@tridge )
- [x] 23890 Rover circle and loiter-turns modes (@rmackay9 )
- [ ] 23892 OpenDroneID storage of UAS-ID (@bugobliterator )
- [x] 23895 Brd safety description backported(@tridge )
- [x] 23918 Extended DShot Telem (@andyp1per )
- [x] 24934 osd horizon option (@Hwurzburg )
- [x] 23940 Nooploop RF (@rishabsingh3003 )
- [x] 23948 RADIX2HD board (@mluessi)
- [x] 23960 SD card formatting (@tridge )
- [x] 23973 Dshot for IOMCU(@andypiper )
- [x] 23981 Rover LUA quick tune (@rmackay9 )
- [x] 23985 iFlight Blitz 754 AIO board (@andyp1per )
- [x] 24017 Mode block mask (@IamPete1 )
- [x] 24032 Remove bootloader on DFU (@tridge )
- [x] 24036 FS trim on passthru (@Hwurzburg )
- [x] 24097 TOFsenseP driver (@rishabsingh3003 )
- [x] 24108 Pixhawk6X BDShot (@andyp1per )
- [ ] 24111 UDP Multicast CYGWIn (@tridge )
- [x] 24118 Here4 GPS (@tridge )
- [ ] 24135 EKF3 Option (@priseborough )
- [x] 24138 Serial over DroneCAN (@tridge )
- [x] 24147 MAVLink EFI backend (@Max-001)
- [x] 24164 HeeWing F405 VTOL (@andyp1per )
- [x] JFB-110 biard (@jfbblue0922)
- [x] 24192 Revert param lua applet (@tridge )
- [x] 24193 CAMx_OPTION (@khanasif786 )
- [x] 24196 Batt status MSP in BLHeli (@andyp1per )
- [ ] 24207 FF scalling (@andypiper )
- [x] 24214 Ethernet (@magicrub )
- [x] 24251 Add HobbyWing DroneCan ESC (@bugobliterator )
- [x] 24253 Add bdshot to Matek765-SE (@Hwurzburg )
- [x] 24281 Allow notch freq logging at loop (@andyp1per )
- [x] 24301 HewWingF405 V2 (@andyp1per)
- [x] 24309 expand filter harmonics(@IamPete1 )
- [x] 24311 Gyro filter logging @IamPete1 )
- [x] 24326 CM4Pilot autopilot (@robinloujl)
- [ ] 24327 ACNS-F405AIO autopilot (@robinloujl)
- [x] 24355 Autotune filter option (@andypiper )
- [x] 24357 time based cam trigger(@khanasif786 )
- [x] 24376 Fence type metadata change (@peterbarker )
- [x] 24379 Union of inclusion areas (@tridge )
- [x] 24386 Dronecan raw ESC command (@iq-fred)
- [x] 24398 Camera ID (@khanasif786 )
- [x] 24409 Blimp modes and enhancements (@MichelleRos )
- [ ] 24411 PID Notches (@andypiper )
- [x] 24427 Bat SOC Lua script (@tridge )
- [x] 24450 Remove SLCAN from all bds except CubeBlack/Orange (@tridge )
- [x] 24462 Airspeed temp sensing(@magicrub )
- [x] 24485 add UART7 to RADIX2HD (@mluessi)
- [x] 24501 Mag Field pre-arm check (@rmackay9 )
- [x] 24505 BDshot for mRoControlH7 (@andypiper )
- [x] 24547 YJUAV-A6E board (@yunjiuav)
- [ ] 24578 VScode extension (@Ryanf55 )
- [x] 24625 BETAFPV-F405 (@andypiper )
- [x] 24634 DLA EFI (@tridge )
- [x] 24640 SVFFI Generator (@tridge )
- [x] 24656 Baroless EKF3 fix (@andypiper )
- [x] 24658 Forward Batt info to ESC telem (@magicrub )
- [x] 24660 Expand BattMon to 16 instances (@magicrub )
- [x] 24687 More CAN SITL types (@tridge )
- [x] 24714 KakuteF7-Wing bdshot expansion (@andypiper )
- [x] 24773 BATT_HIDE_MASK (@magicrub )
- [ ] 24779 CAN multicast and socketcan in SITL (@tridge )
- [x] 24830 SpeedyBee F405 Mini (@andypiper )
- [x] 24867 PrecLand fast descent (@rishabsingh3003 )
- [x] 24868 TSYS03 temp sensor (@peterbarker )
- [x] 24871 SITL on HW relay option (@joshanne )
- [x] 24906 YJUAV A6SE backport (@yunjiuav)
- [x] 24928 TKOFF mode taildrag hold-down(@Hwurzburg )
- [x] 24961 GSC FS timeout (@eppravitra)
- [x] 25003 MambaF405 V2 fixes (@andypiper )
- [x] 25023 GPS_DRV_OPTION ellipsoidal hgt (@tridge ) (4.4)
- [x] 25053 ICE option to disable disarmed start (@WickedShell )
- [x] 25065 Max # log files (@khancyr )
- [x] 25091 INF_inject EFI driver (@tridge )
- [x] 25093 Winch options (@rmackay9 )
- [x] 25108 New Relay Functions (@WickedShell )
- [x] 25111 PixPilot-C3 (@Cedric0489 )
- [x] 25138 ICE start while disarmed option (@WickedShell )
- [x] 25140 Neopixel GRB (@andypiper )
- [x] 25144 Pixhawk 6X bootloader (@peterbarker )
- [x] 25155 Tail rotor yaw trim (@Gone4Dirt )
- [x] 25160 Diawa winch protection (@rmackay9 )
- [x] 25185 CubeOrangePlus flash from SD (@peterbarker )
- [x] 25191 Batt shunt param (@tridge )
- [x] 25192 add vtx control to SpeedyBeeF405-Wing(@Hwurzburg )
- [x] 25197 IOMCU Bdshot (@andypiper )
- [x] 25219 Add params to Analog Fuel Level batt mon (@Jono453)
- [x] 25255 SpeedybeeF405v4 (@andypiper )
- [ ] 25268 TOFSense F I2C (@rishabsingh3003 )
- [x] 25318 LoiterAltQLand loiter point (@magicrub )
- [x] 25345 Arming send text surpression (@WickedShell )
- [ ] 25354 Airvolute-DCS2 (@vrsanskytom)
- [x] 25358 Batt_Monitor AuxInfo split (@tridge )
- [ ] 25403 Read defaults from ROMFS (@peterbarker )
- [x] 25428 Hobbywing lua driver(@tridge)
- [x] 25479 GSOF comm port param (@Ryanf55 )
- [x] 25495 JRE-30 Radar(@rmackay9 )
- [x] 25521 Scripting checksum (@IamPete1 )
- [x] 25536 Add IS31FL3195  LED (@peterbarker )
- [x] 25577 CAN Serial Ports (@tridge )
- [x] 25579 MicroStrain7 (@Ryanf55 )
- [x] 25591 JFB110 defaults (@jfbblue0922 )
- [x] 25595 Enet to Serial (@magicrub )
- [x] 25601 SBF gps-for-yaw (@rmackay9 )
- [x] 25617 2nd CAN protocol (@tridge)
- [x] 25634 TCP/UDP Inet servers (@tridge )
- [x] 25636 Rover circle mode aux switch support (@rmackay9 )
- [x] 25648 AocodaH743Dual board (@Hwurzburg )
- [x] 25660 RTL_CLIMB_MIN in cone (@lthall )
- [x] 25674 IntialLabs EAHRS (@tridge )
- [x] 25676 AHRS_OPTIONS (@tridge )
- [x] 25687 Scripting WebServer (@tridge )
- [ ] 25720 Here4 Autopilot (@bugobliterator )
- [x] 25741 PPP Support (@tridge )
- [x] 25793 Dykstras fast waypoints (@rmackay9 )
- [x] 25798 ICE starter delay (@IamPete1 )
- [ ] 25805 Serail Options in AP_Perip(@tridge )
- [ ] 25818 IRC Ghost RC protocol (@andypiper )
- [x] 25836 ARKV6X uart6 (@AlexKlimaj )
- [x] 25862 AP_Periph remote hardpoint (@IamPete1 )
- [x] 25873 Fractional Loiter Turns(@jrbronkar)
- [x] 25876 Throw Mode Altitude params @JanMaciuk)
- [x] 25914 Flywoo GOKU F745 AIO new pinout (@mbuzdalov)
- [x] 25927 Mount switching to RC_TARGETING(@rmackay9 )

updated thru 2/1 and the branching of 4.5...list closed

**Comment by andypiper** [comment]
Could you correct this issue to refer to @andyp1per against 24301 - I keep getting pinged against any changes here and i'm afraid I can't help :-)

**Comment by IamPete1** [comment]
> Could you correct this issue to refer to @andyp1per against 24301 - I keep getting pinged against any changes here and i'm afraid I can't help :-)

Done, you welcome to give it a try tho, dev wiki is here, https://ardupilot.org/dev/index.html flying things is fun, ;)

**Comment by mbuzdalov** [comment]
It's interesting how the wiki for Flywoo F745 had the pictures for v1.2 for months, whereas the hwdef had only v1.0 until recently. 
I wonder how exactly to fix the wiki in this case...

**Comment by Hwurzburg** [comment]
> It's interesting how the wiki for Flywoo F745 had the pictures for v1.2 for months, whereas the hwdef had only v1.0 until recently. I wonder how exactly to fix the wiki in this case...

I have not looked at what might be required, I scan commits in the code each day and add the label if something in the wiki might be affected or needed, Then weekly add them to this list so as to track them. As time permits, I look in detail and either ask the commit author for info needed to modify the wiki, or just do it if I understand what is required.. for boards, once a wiki page is created the code README.md is much less important...its to help me make a wiki page or for devs using the board before a wiki page gets created.

**Comment by mbuzdalov** [comment]
> for boards, once a wiki page is created the code README.md is much less important...its to help me make a wiki page or for devs using the board before a wiki page gets created.

My sense of beauty tells me that these should probably kept in sync, as, for the sake of developers and users that need advanced knowledge like which ports have DMA enabled, we don't want to have an up-to-date hwdef and an outdated picture of the board at the same place. But hopefully there are not so many places like this one where things may diverge.
