### ISSUE TITLE
Archive ToshibaCAN ESCs wiki page

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#5090]
We should archive https://ardupilot.org/copter/docs/common-toshiba-can-escs.html because we removed support in this PR https://github.com/ArduPilot/ardupilot/pull/20935.  Support was dropped in Copter-4.3.  e.g. 4.2 was the last version to support these ESCs.

I don't think there are any active users so we don't need to worry to much

**Comment by Hwurzburg** [comment]
done

**Comment by rmackay9** [comment]
Thanks!
