### ISSUE TITLE
Archive Tart 2D gimbal page

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#5106]
We can archive the Tarot 2D gimbal page (https://ardupilot.org/copter/docs/common-tarot-gimbal.html) now that we've got the [BrushlessPWM page](https://ardupilot.org/copter/docs/common-brushless-pwm-gimbal.html) and 4.3 is out.

**Comment by Hwurzburg** [comment]
closed by #5107

**Comment by rmackay9** [comment]
Thanks!
