### ISSUE TITLE
wiki error - main/aux/out

### ISSUE THREAD

**Issue by joe-stroup** [ArduPilot/ardupilot_wiki#5127]
I noticed that this page of the wiki isn't up to date regarding the function of the main and aux ports.  In particular, the ability of main ports (iomcu) to function as output GPIO.

https://ardupilot.org/copter/docs/common-flight-controller-io.html
![wiki update](https://github.com/ArduPilot/ardupilot_wiki/assets/91474707/2653f70e-d122-4bd5-85ec-9bc0109ac591)

**Comment by Hwurzburg** [comment]
nice catch....the PR that added this function was not tagged for wiki needed....its limited functionality as a GPIO...ie only for relay use...will update the wiki...thanks

**Comment by Hwurzburg** [comment]
wiki updated
