### ISSUE TITLE
Lightware SF02 Rangefinder URL wrong

### ISSUE THREAD

**Issue by zlite** [ArduPilot/ardupilot_wiki#513]
[Lightware SF02 Rangefinder](http://ardupilot.org/copter/docs/common-rangefinder-sf02.html) 

The URL for this product has changed. New URL is here: 
http://www.lightware.co.za/shop/en/drone-altimeters/7-sf02f.html

**Comment by hamishwillee** [comment]
Thanks very much. I've patched this - the link should be updated in about 5 minutes.
