### ISSUE TITLE
Flywoo GOKU GN 745 AIO with 40A ESC/ Nano

### ISSUE THREAD

**Issue by hyperion11** [ArduPilot/ardupilot_wiki#5136]
[Flywoo GOKU GN 745 AIO with 40A ESC/ Nano](https://ardupilot.org/copter/docs/common-flywoo-f745.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.
typo in documentation
must be [BATT_VOLT_PIN](https://ardupilot.org/copter/docs/parameters.html#batt-volt-pin) = 13
[BATT_CURR_PIN](https://ardupilot.org/copter/docs/parameters.html#batt-curr-pin) = 12

**Comment by Hwurzburg** [comment]
thanks...fixed
