### ISSUE TITLE
Tailsitter VTOL Tuning

### ISSUE THREAD

**Issue by nwinston7** [ArduPilot/ardupilot_wiki#5141]
[Tailsitter VTOL Tuning](https://ardupilot.org/plane/docs/tailsitter-tuning-guide.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

Error in the expression for yaw axis feed forward analysis (X*PIQP.ACT instead of X*PIQY.ACT). Easy to miss in copy and paste

Currently Reads:
PIQY.FF+PIQY.P+PIQY.D
X * (PIQ**P**.Act) , where X is 0.2 to start

Should be:
PIQY.FF+PIQY.P+PIQY.D
X * (PIQ**Y**.Act) , where X is 0.2 to start

**Comment by Hwurzburg** [comment]
fixed...thanks
