### ISSUE TITLE
adding NAMED_VALUE_FLOAT in MissionPlanner

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot_wiki#5146]
with more people using scripting to send NAMED_VALUE_FLOAT and the 2nd airspeed currently as "AS2" we should have some docs on how to display those on MissionPlanner
I recently captured these to help a user:
![image](https://github.com/ArduPilot/ardupilot_wiki/assets/831867/07b2fefe-48ab-4b4a-b3c5-0bd9c1135829)
![image](https://github.com/ArduPilot/ardupilot_wiki/assets/831867/1a100ee2-e6ac-4e00-bc46-bf34cefbe5b8)
![image](https://github.com/ArduPilot/ardupilot_wiki/assets/831867/b6007515-fdd2-4fbf-b9ff-e07b8656d170)
![image](https://github.com/ArduPilot/ardupilot_wiki/assets/831867/2fab6f8d-8592-41e6-9ba2-4415f80ac573)

**Comment by Hwurzburg** [comment]
how is named float displayed?

**Comment by Hwurzburg** [comment]
Added to MP wiki dealing with USER item display
