### ISSUE TITLE
Tuning for Autonomous Aerobatics --- Document error and a question

### ISSUE THREAD

**Issue by normkawakami** [ArduPilot/ardupilot_wiki#5161]
1) The "Veryfing the Rate Capabilities" says,
"The [ACRO_PITCH_RATE](https://ardupilot.org/plane/docs/parameters.html#acro-pitch-rate), [ACRO_ROLL_RATE](https://ardupilot.org/plane/docs/parameters.html#acro-roll-rate), and [ACRO_YAW_RATE](https://ardupilot.org/plane/docs/parameters.html#acro-yaw-rate) must be set to less than what the airframe is capable of doing. Values of 360, 180, and 90 degress per second, respectively,"

I believe "360, 180, and 90 degrees" is incorrect and it should be "180, 360 and 90 degrees". 

2) The "Confirming Test Flight" says,
"After verifying and modifying the PIDS, fly again, being ready to resume MANUAL control if unstable. "

My question is in what flight mode should I fly again?

**Comment by Hwurzburg** [comment]
the numbers are rates...degrees per second...and the wording is correct

after tuning fly in any stablized mode to check tune

**Comment by normkawakami** [comment]
Hwurzburg, Thank you for your response.
I know 360,180 and 90 are rates and expressed in degrees per second.
I still think the pitch rate should be 180 and the roll rates 360, as usually roll is more responsible than pitcth as the graph in the same page shows.

**Comment by Hwurzburg** [comment]
True....will  change

**Comment by Hwurzburg** [comment]
fixed
