### ISSUE TITLE
Optical flow page should clarify vehicle won't climb over rangefinder alt

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#5163]
We should add a note to the [optical flow page](https://ardupilot.org/copter/docs/common-optical-flow-sensor-setup.html) to warn users that when copters have an optical flow sensor enabled (along with a rangefinder) and it is specified as the only horizontal position source (e.g. EK3_SRCx_VELXY=OpticalFlow, EK3_SRCx_POSXY=None) and the vehicle is flying in a pilot controlled mode requiring a position estimate (which is only Loiter and PosHold I believe) the vehicle will not climb above the rangefinder's maximum altitude specified in RNGFNDx_MAX_CM.  This is a safety mechanism because otherwise the EKF failsafe would trigger as the vehicle flew out of rangefinder range.

By the way, there are some odd characters on the optical flow page like "/site".

This issue comes from [this discussion](https://discuss.ardupilot.org/t/ekf3-optical-flow-and-gps-behavior/95996/16).

**Comment by Hwurzburg** [comment]
added note, fixed formatting
