### ISSUE TITLE
Update | SpeedybeeF405 Wing WiFi + MP

### ISSUE THREAD

**Issue by jlpoltrack** [ArduPilot/ardupilot_wiki#5174]
Was able to connect Mission Planner to the SpeedybeeF405 Wing FC using the following settings:

- Tx/Rx pads bridged on the top FC board (this is default)
- Serial6 set to 2 (MAVLink2), baudrate 115
- Switch to WiFi AP using boot button (white LED)
- Connect to Wifi AP
- Launch Mission Planner, will use UDP for connection
![image](https://github.com/ArduPilot/ardupilot_wiki/assets/41841496/6961ae05-10f0-4983-9dbf-41be16c4ccea)
![image](https://github.com/ArduPilot/ardupilot_wiki/assets/41841496/818c4a6f-ccf3-4566-bbac-4d63055e7313)
![image](https://github.com/ArduPilot/ardupilot_wiki/assets/41841496/0dad39c0-f4cc-4403-91a0-7e30bc4b7604)

**Comment by Hwurzburg** [comment]
the wiki already referred to the speedybee manual on how to set this up, but I added a brief note
