### ISSUE TITLE
Question about choosing an Antenna

### ISSUE THREAD

**Issue by Shivam-Kataria** [ArduPilot/ardupilot_wiki#5182]
Hi, I am relatively new to choosing antennas so I would appreciate some guidance on it. In this post, I have laid out my knowledge and questions/concerns I have. Thanks and any help would be greatly appreciated!

So, I have RFD900 modules which currently don't perform great at all, I get maybe a kilometer range with them (I have tried playing around with the settings but nothing is reliably working well with range). Changing the antenna could potentially fix this. I was thinking of purchasing a directional high gain antenna. The current system I have has a gain of about 2-3dbi. The new ones I am looking to purchase have a gain of around 15-17.5 dbi. For an example of the type of antennas I am looking at, here's one: [Kp Performance 17.5dBi 900MHz Single Pol. Yagi Antenna (5-Pack) (ispsupplies.com)](https://www.ispsupplies.com/KP-Performance-YA17KPPD). 

My concerns start with the fact that some of these antennas have input/max power rating which is much higher than the output power of the rfd900 module - about 1W output power for rfd900, but the antennas I found with high gain are input/max rated for anywhere between 50W (the link above) to I found some with 500W. Ardupilot's guide, however (screenshot, the links no longer work), mentions some of the similar spec antennas (their doc is using a 433 mhz module).
![image|690x168](upload://j6BJhvRIYGKvOmuAoJb2wYywZOT.png)
 
Since those antennas are such high power, are they compatible with the rfd900 modules I am using? I'm worried that the telemetry modules won't be able to make use of the larger antennas because of it's input/max power output. I'm not convinced that the 1W RFD 900's can be effective with those 50 to hundreds of Watts antennas. I know 100W is "rated" and you can use them at a lower wattage. What I am worried about is the RFD 900 not being able to make use of the huge antenna or barely being able to "saturate" it with enough juice to actually get a usable signal out of them, let alone improve range. But then Ardupilot's guide recommending those antennas makes me question otherwise as well. So that's where I am stuck.

Thanks!

**Comment by Hwurzburg** [comment]
in the future you should post questions on discuss.ardupilot.org.... this is for issues/corrections/additions to the documentation....

that said, yes you can use that antenna...the power rating is only so you do not melt the coax or connectors when using a massive amp..

you might also want to try a smaller antenna in the 9bd gain range....1/4 the price and wider beam width(which allows not as exact pointing of the antenna to the plane)...distance is not only determined by gain....multipath reflections can be the limiting distance factor also....
