### ISSUE TITLE
Using-flaps docs is out of date

### ISSUE THREAD

**Issue by CraigElder** [ArduPilot/ardupilot_wiki#520]
In [Automatic Flaps#Using flaps](http://ardupilot.org/plane/docs/automatic-flaps.html#using-flaps):

> To use flaps they must be configured on channel 5, 6, 7 or 8. If you wish to have manual control of the flaps then they must be on 5, 6, or 7.

Is out of date.  Flaps can be on any channel

**Comment by hamishwillee** [comment]
Hi @CraigElder 
So should the line just change to:

> Flaps can be used on any channel.

Ie there is no channel for configuration, and no special subset for manual control? 

Is there a version that this changed in? AP 3.? say

**Comment by CraigElder** [comment]
>>>Ie there is no channel for configuration, and no special subset for manual control?
That is correct
>>>Is there a version that this changed in? AP 3.? say
I don't remember. This changed nearly a year ago

I would also like to suggest that we add a recommended procedure for testing the auto flap function.

Remove the prop
Arm the vehicle
Select Loiter Mode
Set the airspeed to a speed to a value below the FLAP_1_SPEED and the flaps should deploy.

**Comment by hamishwillee** [comment]
I did the quick fix for initial problem [here](https://github.com/ArduPilot/ardupilot_wiki/commit/e2c161e188f876b04573703c17802cfcf0c6577b?w=1). 

Can you add the testing section as a PR?

**Comment by brunoolivieri** [comment]
There was some time since this issue opening and some updates.

Is this issue still actual and need to be followed, or we could close it?

**Comment by Hwurzburg** [comment]
flaps/flaperons recently updated....closing
