### ISSUE TITLE
Add fleet management links

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#5204]
ArduPilot is supported by multiple external fleet management systems so we should consider adding a page somewhere that links to them.

- Autrik https://www.autrik.com/ <-- new partner
- AVCRM https://avcrm.net/aerodromes/ <-- only Australia and New Zealand
- Drone LogBook https://www.dronelogbook.com/hp/1/index.html
- flyfreely https://flyfreely.io/

**Comment by Hwurzburg** [comment]
Added to commercial support page
