### ISSUE TITLE
Pymavlink Unable to control boat using RC channel

### ISSUE THREAD

**Issue by Larkye** [ArduPilot/ardupilot_wiki#5214]
I made an unmanned ship, flashed the rover firmware, and used the official demo control through the RC channel, why didn't it work.

**Comment by rmackay9** [comment]
Hi @Larkye,

It is probably best to ask these questions in the ArduPilot rover forum here. https://discuss.ardupilot.org/c/ardurover/rover-44/170

This is the wiki to-do list so I'll go ahead and close this.  Sorry to be strict but if we're not then our to-do list turns into another support forum and we lose track of our to-dos.
