### ISSUE TITLE
Arming and Disarming

### ISSUE THREAD

**Issue by vetonn29** [ArduPilot/ardupilot_wiki#5237]
[Arming and Disarming](https://ardupilot.org/mavproxy/docs/uav_configuration/arming.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

Hello, when I connect my raspberry pi with FMUK66 when I type the command arm check and want to check the all option it doesnt work. It just shows: ERROR in command ['check', 'all']: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

can somebody help me. Thanks in advance!

**Comment by Hwurzburg** [comment]
please post support questions in discuss.ardupilot.org....thanks
