### ISSUE TITLE
Link for MAX31865 is for a local document

### ISSUE THREAD

**Issue by jlpoltrack** [ArduPilot/ardupilot_wiki#5238]
On the Temperature Sensor page, the link for MAX31865 is a local PDF: https://ardupilot.org/plane/docs/common-temperature-sensor.html

<img width="1327" alt="image" src="https://github.com/ArduPilot/ardupilot_wiki/assets/41841496/d020b90b-8484-4f06-b462-cc4bb4a4d9c2">

Link to datasheet on AD website: https://www.analog.com/media/en/technical-documentation/data-sheets/MAX31865.pdf

**Comment by Hwurzburg** [comment]
thanks...fixed
