### ISSUE TITLE
Documentation of serialx_options don't match options in Mission Planner

### ISSUE THREAD

**Issue by fpvironman** [ArduPilot/ardupilot_wiki#5244]
The Ardupilot (copter and plane) pages » [Advanced Configuration](https://ardupilot.org/plane/docs/common-advanced-configuration.html) » Serial Port Configuration Options have the following list of serialx_options that don't match the list in Mission Planner.

Bitmask Options
if bit 0 is set, then RX data received is inverted internally.
if bit 1 is set, the TX data is inverted before outputting.
if bit 2 is set, then HalfDuplex operation using the TX pin is implemented.
if bit 3 is set, then the TX and RX pins are effectively swapped internally.
if bit 4 is set, then the RX pin has a weak pull down resistor activated.
if bit 5 is set, then the TX pin has a weak pull down resistor activated.
if bit 6 is set, then the RX pin has a weak pull up resistor activated.
if bit 7 is set, then the TX pin has a weak pull up resistor activated.
if bit 8 is set, then the RX has no DMA activated (assuming DMA is available on this UART)
if bit 9 is set, then the TX has no DMA activated (assuming DMA is available on this UART)
if bit 10 is set, then MAVLink forwarding will not be active on this UART port.

The options in Mission Planner 1.3.80 are:
![image](https://github.com/ArduPilot/ardupilot_wiki/assets/37737502/6aa605d4-2ca7-41be-863c-1f7ed4ce6f89)

Which one is correct?
Can the incorrect one please be updated?

Thanks
Oliver

**Comment by Hwurzburg** [comment]
thanks...fixed wiki page
