### ISSUE TITLE
Sensor Position Offset Compensation documentation is confusing

### ISSUE THREAD

**Issue by paulr4** [ArduPilot/ardupilot_wiki#5304]
The [Sensor Position Offset Compensation](https://ardupilot.org/copter/docs/common-sensor-offset-compensation.html#common-sensor-offset-compensation) page gives some useful detail, but uses IMU position and centre-of-gravity interchangeably.

For example:

"[GPS_POS1_X](https://ardupilot.org/copter/docs/parameters.html#gps-pos1-x), [GPS_POS1_Y](https://ardupilot.org/copter/docs/parameters.html#gps-pos1-y), [GPS_POS1_Z](https://ardupilot.org/copter/docs/parameters.html#gps-pos1-z) the first GPS’s position from the vehicle’s IMU or center-of-gravity"

Earlier the document states that if the C of G and IMU are not co-located, the other sensor’s position offsets can be specified from the vehicle’s center of gravity. So presumably the offset is intended to be measured from C of G, not the IMU?

It's also not clear if the offsets are applied before or after the AHRS_ORIENTATION parameter. For example if AHRS_ORIENTATION is set to 180deg roll, are the Y and Z offsets inverted?

**Comment by rmackay9** [comment]
Yes indeed, it's a little unclear.  I think that the X, Y, Z offsets are relative to the IMU if the user hasn't set the INS_POS_XYZ parameters... but relative to the vehicle's COG if INS_POS_XYZ have been set.  This is what @priseborough told me (I think).

**Comment by Hwurzburg** [comment]
when @priseborough confirms as correct, @rmackay9 , I will update the wiki page

**Comment by priseborough** [comment]
That is correct. If the IMU position is left at 0,0,0 then by default it is at the body frame origin and everything else can be measured wrt the IMU

**Comment by Hwurzburg** [comment]
added note
