### ISSUE TITLE
Table of Contents

### ISSUE THREAD

**Issue by CraigElder** [ArduPilot/ardupilot_wiki#531]
[Table of Contents](http://ardupilot.org/plane/docs/common-table-of-contents.html) - 
TOC is broken all of the subsections and all of the parameters are showing up in the TOC

**Comment by hamishwillee** [comment]
The full table of contents is only properly generated if you put it on the top/home page - like this one: http://ardupilot.org/planner/index.html

If you generate it on another page using the various options you get a flat list. This is something to do with sphinx that I have not tried to debug. I am sure it is a sphinx issue and not a "use of the tool" issue.

One option is to remove the page (arguably we don't need it). Alternatively add the full index in the top page.

**Comment by gmorph** [comment]
I'd just close this issue and assume its a limitation of the tool.  Probably not worth our time to investigate and fix.

**Comment by hamishwillee** [comment]
Well, one option is to remove the TOC page - we don't really need it when you have the sidebar. I just didn't want to do that unilaterally.

**Comment by gmorph** [comment]
I'm not fussed either way.  Does anyone ever load the TOC and then search it via the browser for a keyword?  Anyway as I said remove the TOC page or don't - I'm fine either way.
Thanks, Grant.

**Comment by Hwurzburg** [comment]
I think TOCs are okay now on all the sites....closing
