### ISSUE TITLE
Add link to plot.ardupilot.org to UAVLogView page

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#5310]
Our [UAVLogView page](https://ardupilot.org/copter/docs/common-uavlogviewer.html#) should get a link right at the top to https://plot.ardupilot.org/#/

**Comment by rmackay9** [comment]
Ah, I guess it does actually have one it's just a little small 'cuz it's linked from "here".

**Comment by Hwurzburg** [comment]
added some emphasis.

**Comment by rmackay9** [comment]
@Hwurzburg cool, thanks very much1
