### ISSUE TITLE
Installing Mission Planner

### ISSUE THREAD

**Issue by Xtremeflight** [ArduPilot/ardupilot_wiki#5376]
[Installing Mission Planner](https://ardupilot.org/planner/docs/mission-planner-installation.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.
1. Finish download and tried open Mission Planner
2. Mission Planner window and black DOS screen (command prompt window) pop up togather
3. DOS screen never turned off, it keep scrolling forever
4. Uninstall Mission Planner and reinstall, same thing happen
5. Uninstall Mission Planner again and restore windows (Windows 11) to the 3 month ago point
6. Reinstall Mission Planner but same thing happen

**Comment by Hwurzburg** [comment]
Please move this to discuss.ardupilot.com...not a doc issue...it's a support issue
