### ISSUE TITLE
Building ArduPilot for Pixhawk/PX4 on Windows with Make

### ISSUE THREAD

**Issue by Metello** [ArduPilot/ardupilot_wiki#538]
[Building ArduPilot for Pixhawk/PX4 on Windows with Make](http://ardupilot.org/dev/docs/building-px4-with-make.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

When I built the code  ,I got this :
 fatal: Not a git repository: f:/MyRepository/3.3/ardupilot/modules/../../.git/modules/modules/PX4Firmware
Failed to get px4 hash
fatal: Not a git repository: f:/MyRepository/3.3/ardupilot/modules/PX4NuttX/nuttx//../../.git/modules/modules/PX4NuttX
Failed to get nuttx hash
PX4 ArduCopter Firmware is in ArduCopter-v2.px4

Does it matter？Did I need resovle this? How?  
Thank you very much!!

**Comment by magicrub** [comment]
That is normal and we should note that in the wiki that as long as you get "Firmware is.." then a final firmware was created and you're good to go.

**Comment by magicrub** [comment]
@Metello I've updated the wiki. Thanks for the comment!

**Comment by Metello** [comment]
Thankyou very much!!

**Comment by louise1983** [comment]
Hello ... i have gotten "git clone ardupilot"by git bash , and still trying to built it by eclipse and px4toolchain ....i got some error:
make[1]: *** [/c/git1/ardupilot/modules/PX4Firmware/Archives/px4fmu-v2.export] Error 7
make: *** [/c/git1/ardupilot/modules/PX4Firmware/Archives/px4fmu-v2.export] Error 2
make[1]: Leaving directory `/c/git1/ardupilot/modules/PX4Firmware'

anyone help me?
