### ISSUE TITLE
add Holybro DroneCAN ESCs to DroneCANESC page

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#5392]
We've got this DroneCAN ESC page https://ardupilot.org/copter/docs/common-uavcan-escs.html and we've recently added Hobbywing DroneCAN ESC support so it should be added to this page.

**Comment by Hwurzburg** [comment]
Its on the 4.5 wiki list

**Comment by rmackay9** [comment]
@Hwurzburg ok great.  It seems we've backported it to 4.4 so we will need a page.  I've actually just received one ESC from my main sponsor so I hope to give it a try in the next day or two.  I'm happy to write a wiki page based on that.

**Comment by Hwurzburg** [comment]
@rmackay9 super...thanks..

**Comment by Hwurzburg** [comment]
done
