### ISSUE TITLE
olld and new issue.

### ISSUE THREAD

**Issue by larrypatterson** [ArduPilot/ardupilot_wiki#5433]
This is my first experience with pixhawk.  I bought two of the 145 dollar 2.4.8 units.    I have spent several weeks trying to get one of the pixhawk to give me a out put to servos.
I have tried putting 5 volts servo panel.
I read thru the BRD safety mast several times that I was directed me to.   AT 75 years old i am just not very sharp anymore. I have gotten pretty good about downloading stuff.
There use to be an airplane which flew around the simulator.  Lost that plane.  Do you know how I could get the simulator plane back?   I have tried deleting everything several times, and reloading.
Didnt help.
  I do appreciate your help.!

**Comment by Hwurzburg** [comment]
not the place for support requests...  discuss.ardupilot.org....  that said I can try to interactively help you.....email me your phone number and times when I can call...hwurzburg@yahoo.com
