### ISSUE TITLE
Speedy Bee F4 V3

### ISSUE THREAD

**Issue by AM8240** [ArduPilot/ardupilot_wiki#5459]
I'm Unable to find any supported firmware for [Speedy Bee F4 V3](https://ardupilot.org/copter/docs/common-speedybeef4-v3.html). Can anyone help me to find correct firmware for Speedy Bee f405 V3 flight controller. (Multirotor Firmware)

**Comment by Hwurzburg** [comment]
https://firmware.ardupilot.org/Copter/latest/speedybeef4v3/
