### ISSUE TITLE
Choosing a Flight Controller APM firmware err?

### ISSUE THREAD

**Issue by cala2** [ArduPilot/ardupilot_wiki#547]
I read that instructions says that 3.3 is the latest firm for APM boards here: http://ardupilot.org/plane/docs/common-choosing-a-flight-controller.html
and 3.4 release announcement says that is 3.4 here: http://diydrones.com/profiles/blogs/apm-plane-3-4-0-released

**Comment by magicrub** [comment]
Thanks, we'll get that cleared up as soon as we figure out the correct
answer :)
