### ISSUE TITLE
what does the 'RATE'in the 'DataFlash Logs'mean?

### ISSUE THREAD

**Issue by Metello** [ArduPilot/ardupilot_wiki#551]
hi gays!
        I use the ArduPilot to do some test, now I wonder the rotate speed of the plane .Does the "R",'P',"Y"in the "RATE"of the 'DataFlash Logs'meas that?if that what does the unit of it?centidegree/s?or some others?
      thank you for your help!!

**Comment by billbonney** [comment]
Great question to ask in the forum. http://discuss.ardupilot.org This issue list is for things that need fixing in the wiki. If this reference a page in the wiki posts link. that would be most helpful or even post a update to the wiki 👍

**Comment by magicrub** [comment]
Closing per Bill's suggestion
