### ISSUE TITLE
APM Planner install on linux ubuntu14 - dpkg dependency problem libflite1, libqt5core5a, libqt5gui5-gles, libstdc++6

### ISSUE THREAD

**Issue by jhenry5** [ArduPilot/ardupilot_wiki#552]
I am trying install APM planner on linux 14.04. I have some dependency issues and not sure how to update the prerequisite files. I am installing APM planner using  instructions from : http://ardupilot.org/planner2/docs/installation-for-linux.html

When I run the first command :  sudo dpkg -i apmplanner*.deb I get the following print out.
![screenshot from 2016-09-17 21 07 17](https://cloud.githubusercontent.com/assets/5570690/18612009/cfa8b7dc-7d1a-11e6-8113-e966557b9bb8.png)

**Is there a way to update all these prerequisite files at once?**

Error print out below

jh@jh-Lenovo-Ideapad-Z50-70:~$ sudo dpkg -i apmplanner*.deb
Selecting previously unselected package apmplanner2.
(Reading database ... 224404 files and directories currently installed.)
Preparing to unpack apmplanner2.deb ...
Unpacking apmplanner2 (2.0.20) ...
dpkg: dependency problems prevent configuration of apmplanner2:
 apmplanner2 depends on libflite1 (>= 1.4-release-9~); however:
  Version of libflite1:amd64 on system is 1.4-release-8ubuntu0.1.
 apmplanner2 depends on libqt5core5a (>= 5.4.0); however:
  Version of libqt5core5a:amd64 on system is 5.2.1+dfsg-1ubuntu14.3.
 apmplanner2 depends on libqt5gui5 (>= 5.3.0) | libqt5gui5-gles (>= 5.3.0); however:
  Version of libqt5gui5:amd64 on system is 5.2.1+dfsg-1ubuntu14.3.
  Package libqt5gui5-gles is not installed.
 apmplanner2 depends on libstdc++6 (>= 5.2); however:
  Version of libstdc++6:amd64 on system is 4.8.4-2ubuntu1~14.04.3.

dpkg: error processing package apmplanner2 (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu1) ...
Processing triggers for bamfdaemon (0.5.1+14.04.20140409-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.54ubuntu1.1) ...
Errors were encountered while processing:
 apmplanner2

**Comment by billbonney** [comment]
These issues should be checked/raised on the http://discuss.ardupilot.org as well, since that's where there are probably answers to the docs being out of date. Thx

I created a #553 PR to address this one.
