### ISSUE TITLE
Setting up SITL on Linux

### ISSUE THREAD

**Issue by lv2eof** [ArduPilot/ardupilot_wiki#554]
Hi,
Is not the first time I run this. The others sometimes went almost well others not so well.
So I'm running again.
I follow "http://ardupilot.org/dev/docs/setting-up-sitl-on-linux.html#setting-up-sitl-on-linux".
1-Download ardupilot
Should be done in "~/"?
2-Install some required packages
sudo pip install pymavlink MAVProxy
Well, I have a lot of pip's :) Not a lot but at least pip2, pip2.7, pip3, pip3.4 and pip...
Well, some must point to the same place, but I'm not sure.
I think that the results will be different if I use:
"sudo pip2 install pymavlink MAVProxy" or "sudo pip3 install pymavlink MAVProxy", isn't it?
Which one should I use?
If I write: "pip -V" I got "pip 8.1.2 from /usr/local/lib/python3.4/dist-packages (python 3.4)".
Ok. Thanks in advance.
Luis

**Comment by billbonney** [comment]
You need to use pip that is compatible with Python 2.7. MAVProxy does not work with Python 3.x at this time

**Comment by billbonney** [comment]
NOTE: These questions should be asked here http://discuss.ardupilot.org/c/ground-control-software/mavproxy

Issue here should be like 'Update wiki to setup Python 2.7 environment' its not really for support questions

Hope that helps :)

**Comment by lv2eof** [comment]
Hi,
Thanks a lot for your answer.
It seems to me that Python2 and Python3 only share the name :)
If I write:
"python --version" I get "Python 2.7.6"
"python2 --version" I get "Python 2.7.6"
"python3 --version" I get "Python 3.4.3"
The reason for opening an issue was because I think that is of some interest to point that we should use "pip2", because "pip" only can point to Python2 or to Python3 (I think).
Anyway, thanks for the advice.
Cheers,
Luis
