### ISSUE TITLE
DroneKit Tutorial - video link broken

### ISSUE THREAD

**Issue by bturnbau** [ArduPilot/ardupilot_wiki#5561]
[DroneKit Tutorial](https://ardupilot.org/dev/docs/droneapi-tutorial.html) - Link to tutorial video broken. See screenshot. 
<img width="753" alt="Screenshot 2023-11-13 at 6 28 17 PM" src="https://github.com/ArduPilot/ardupilot_wiki/assets/42814695/9d87b6d3-9d93-4bc4-8bd6-61c16e1d0e5f">

**Comment by Hwurzburg** [comment]
changed to another tutorial
