### ISSUE TITLE
Control a Camera

### ISSUE THREAD

**Issue by Invictus-lab** [ArduPilot/ardupilot_wiki#5563]
[Control a Camera](https://ardupilot.org/dev/docs/mavlink-camera.html) - where will I get camera information after sending request in mavproxy command .

**Comment by Hwurzburg** [comment]
see https://mavlink.io/en/messages/common.html#CAMERA_SETTINGS

**Comment by rmackay9** [comment]
@Invictus-lab,

We've got these two wiki pages as well:

- https://ardupilot.org/dev/docs/mavlink-camera.html
- https://ardupilot.org/dev/docs/mavlink-gimbal-mount.html

BTW, if you're trying to integrate AP camera and gimbal controls and having troubles feel free to contact me.  [Discuss](https://discuss.ardupilot.org/c/arducopter/copter-44/169) or discord is probably best.
