### ISSUE TITLE
Are grammatical tweaks welcome 

### ISSUE THREAD

**Issue by SukritSethi** [ArduPilot/ardupilot_wiki#5572]
I have been recently exploring Mission Planner and I feel like there are some minute grammatical errors. Seeing that the project is opensource, I am curious to know if such minute updates/suggestions are welcome or not.
I shall go through some more documentation and compile a collection of my suggestions and raise a review if the maintainers give me a green signal.

**Comment by Hwurzburg** [comment]
please contributions welcomed! If you setup and use the wiki editing environment (https://ardupilot.org/dev/docs/common-wiki_editing_guide.html) to make suggested changes, that is best...but you can use the edit button on each individual page also
