### ISSUE TITLE
Optitrack for Non-GPS Navigation

### ISSUE THREAD

**Issue by Samrj12** [ArduPilot/ardupilot_wiki#5580]
[Optitrack for Non-GPS Navigation](https://ardupilot.org/copter/docs/common-optitrack.html) - 

Hi,

I am using Motive for my research on autonomous drones in an indoor setting. I am trying to stream the data from Motive to my GCS mission planner through MAVProxy however, it's failing to connect to my drone and outputs 'failed to connect to COM3 : Permission Denied'. I am using Telemetry for my drone connection.

**Comment by Hwurzburg** [comment]
since this is for documentation corrections/additions, you wont get much help on a support issue like this...try submitting it on discuss.ardupilot.org
