### ISSUE TITLE
Building Mission Planner with Visual Studio

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/ardupilot_wiki#559]
[Building Mission Planner with Visual Studio](http://ardupilot.org/dev/docs/buildin-mission-planner.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

Apparently there is an error here with use of VS2013 - see https://groups.google.com/forum/#!msg/drones-discuss/-4N6b1G0TZk/svzXHZZOHwAJ

**Comment by OXINARF** [comment]
Mission Planner was updated to VS2015 not long ago. @meee1 should have more info.

**Comment by hamishwillee** [comment]
This is fixed by #560
