### ISSUE TITLE
Do-Change-Speed types are incorrect

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#5593]
I'm afraid that I made a mistake when I update the [Copter Command List page's do-change-speed](https://ardupilot.org/copter/docs/mission-command-list.html#do-change-speed) to include the Up and Down types.

The correct values are shown [here](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L2958) and I've confirmed that in the code we also use these values.

0. AirSpeed (interpreted as ground speed by Copter)
1. GroundSpeed (treated same as Airspeed by Copter)
2. Climb
3. Descent

Sorry!  I will fix this.

**Comment by Hwurzburg** [comment]
fixed
