### ISSUE TITLE
SERIALx_PROTOCOL missing many values in SERIAL2_PROTOCOL

### ISSUE THREAD

**Issue by Ryanf55** [ArduPilot/ardupilot_wiki#5604]
This list is outdated for many protocols.
https://ardupilot.org/copter/docs/common-serial-options.html#serialx-protocol

This list is up to date. For example, DDS XRCE is mentioned in the param list.
https://ardupilot.org/copter/docs/parameters.html#serial2-protocol-telemetry-2-protocol-selection

If the first link is not maintained, perhaps the documentation should be combined. 

Is there an easy way to avoid the duplication and fix the mismatch?

**Comment by Hwurzburg** [comment]
no that list should be maintained.....but its obviously been missed for the last additions...the param list is autogenerated but cant show the links to the relevant topics....I will update that page

**Comment by Ryanf55** [comment]
Got it. Can we cross-links the pages?

**Comment by Hwurzburg** [comment]
not sure what you mean...updated page
