### ISSUE TITLE
Installing APM Planner for Linux - first download link is dead

### ISSUE THREAD

**Issue by ncarrier** [ArduPilot/ardupilot_wiki#564]
[Installing APM Planner for Linux](http://ardupilot.org/planner2/docs/installation-for-linux.html) - 
Hello,
Everything is in the title, in the Download section of the "installation for linux" instructions page for APM Planner 2, 2 links are given and the first one sends the user to a page saying "Oops! That page doesn’t exist or is private.".

**Comment by GregoireH** [comment]
same for windows

**Comment by billbonney** [comment]
Thanks for the comments. it's easy to update the page as well using the edit button, which would also be awesome and very helpful for info you have discovered. 👍 Thanks again

![screen shot 2016-10-04 at 9 00 33 am](https://cloud.githubusercontent.com/assets/959994/19081994/2d6961b6-8a11-11e6-88f6-cd1c8b1841a1.png)

**Comment by GregoireH** [comment]
true, thanks

**Comment by ncarrier** [comment]
I'd like to do it, but I'm reading this page because I don't know what is
the correct link 😊

Le 4 oct. 2016 18:06, "Bill Bonney" <notifications@github.com> a écrit :

Thanks for the comments. it's easy to update the page as well using the
edit button, which would also be awesome and very helpful for info you have
discovered. 👍 Thanks again

[image: screen shot 2016-10-04 at 9 00 33 am]
<https://cloud.githubusercontent.com/assets/959994/19081994/2d6961b6-8a11-11e6-88f6-cd1c8b1841a1.png>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ArduPilot/ardupilot_wiki/issues/564#issuecomment-251433839>,
or mute the thread

**Comment by GregoireH** [comment]
is this the corresponding link for windows ?
http://firmware.eu.ardupilot.org/Tools/APMPlanner/apm_planner_2.0.20_win.exe

That's how I got it at least

**Comment by billbonney** [comment]
@GregoireH there should be 2.0.24 available now... 

I updated the links to refer to the download locations  for each platform.

I was pointing out the edit button for other issue you may see, and you can help. I realize the download locations for AP2 is really for me to update. Thx 👍

**Comment by ncarrier** [comment]
For the Linux part it seems good.
Thank you.

**Comment by magicrub** [comment]
Is this ready to be closed?

**Comment by billbonney** [comment]
@magicrub Yep, closed
