### ISSUE TITLE
The issue with Mission Planner on a 2014 MacBook Pro 15-inch laptop running Ubuntu 22.04 system.

### ISSUE THREAD

**Issue by swj735245824** [ArduPilot/ardupilot_wiki#5657]
Hello everyone, I'm using the Ubuntu 22.04 system on my 2014 MacBook Pro 15-inch laptop. I installed Mono by following the steps on the official website for the 20.04 system. After installation, I can open Mission Planner normally, but the page layout is very chaotic. Some components even overlap with others and labels, making it almost unusable. I feel that this issue is quite complex, and I don't know how to fix it. Has anyone else encountered this problem?
![image](https://github.com/ArduPilot/ardupilot_wiki/assets/12065843/934040bc-56d2-4973-92d1-6efadf0e390b)

![image](https://github.com/ArduPilot/ardupilot_wiki/assets/12065843/25bccc31-5ebf-409c-bd1f-f0a218ace111)

![image](https://github.com/ArduPilot/ardupilot_wiki/assets/12065843/9af16923-1e91-4958-9189-d20f1d801d69)

![image](https://github.com/ArduPilot/ardupilot_wiki/assets/12065843/cfc95332-1f53-42a9-a515-e099e2570b1c)

![image](https://github.com/ArduPilot/ardupilot_wiki/assets/12065843/874a41af-cdc2-4f11-bfa3-09a234222501)

![image](https://github.com/ArduPilot/ardupilot_wiki/assets/12065843/55c37dc9-ddc6-4283-9ffb-7f26cea9b711)

**Comment by Hwurzburg** [comment]
This is a Mission Planner issue not wiki...please raise the issue there: https://github.com/ArduPilot/MissionPlanner/issues
