### ISSUE TITLE
Lua Scripts: no mention of mount: commands?

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/ardupilot_wiki#5658]
[Lua Scripts](https://ardupilot.org/copter/docs/common-lua-scripts.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

Please add information about those.

**Comment by Hwurzburg** [comment]
![image](https://github.com/ArduPilot/ardupilot_wiki/assets/6076534/f010964d-83ce-4d14-a83e-245753e37929)
no way to list them all...if you read the intro it links to the auto-updated documentation
