### ISSUE TITLE
Mission Planner GPS-based Antenna Tracking

### ISSUE THREAD

**Issue by rspandolfi** [ArduPilot/ardupilot_wiki#568]
Has Mission Planner GPS-based Antenna Tracking been removed from the current version of Mission Planner? I had to roll back to version 3.9 to access the Tracker.

**Comment by billbonney** [comment]
Support questions here first http://discuss.ardupilot.org/c/ground-control-software/mission-planner

This issue list is for issue wiith the wiki docs themselves and not the programs they describe. Thx 👍
