### ISSUE TITLE
RPLidar A2 360 degree lidar

### ISSUE THREAD

**Issue by 175zora** [ArduPilot/ardupilot_wiki#5689]
[RPLidar A2 360 degree lidar](https://ardupilot.org/copter/docs/common-rplidar-a2.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.我用RPlidar A2 M12激光雷达按照上面的步骤连接到雷迅v5+飞控的TELEM1串口上，在地面站上看不到数据并报错
![45206807237ef7e2dd49d115f67b866](https://github.com/ArduPilot/ardupilot_wiki/assets/118435736/0ab5ac00-e697-4841-8576-fa10345147dc)PreArm：PRX1：no Data，该怎么办？我用的是最新的固件

**Comment by Hwurzburg** [comment]
this should be postedd in discuss.ardupilot.org support forum...and in any case there is not enough information provided for anyone to assist you...please open an issue in that forum with more details about the setup and problem
