### ISSUE TITLE
Add known working RPM sensors to Heli RPM sensor wiki

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#5696]
We should add this RPM sensor to the [RPM sensor wiki page](https://ardupilot.org/copter/docs/common-rpm.html) as a known working model https://www.controlhobbies.com/Telemetry-magnetic-sensor-to-measure-RPM-33616.html

**Comment by Hwurzburg** [comment]
are there any others @bnsgeyer @Gone4Dirt ?

**Comment by rmackay9** [comment]
This seems to be the only other one that we know about.  I asked on the trad-heli discord channel..
https://www.sm-modellbau.de/magnetischer-Drehzahlsensor-fuer-UniTest-2-UniLog-1-2

**Comment by Gone4Dirt** [comment]
Sorry for being slow.  
I know that this works:
https://modelhelicopters.co.uk/products/align-beastx-governor-sensor-hegbp002t?variant=42819003220168
Requires a pull up resistor (between 5V and signal).

**Comment by Hwurzburg** [comment]
done
