### ISSUE TITLE
SkyController 1 Mision Planner

### ISSUE THREAD

**Issue by tatria** [ArduPilot/ardupilot_wiki#5708]
Hi, has anyone got the alternative firmware to use skycontroller 1 on mission planner?
Many thanks, my email: tatria@gmail.com

**Comment by rmackay9** [comment]
Hello, thanks for using AP.  Questions should really go in the support forums https://discuss.ardupilot.org/c/arducopter/copter-44/169

Sorry to be strict but I'll close this now so that we can keep our wiki to-do list clear.
