### ISSUE TITLE
While Implementating the crazyflie.wbt as per the documentation in webots

### ISSUE THREAD

**Issue by sairaghavamunagala2001** [ArduPilot/ardupilot_wiki#5734]
[Setting up the Build Environment (Linux/Ubuntu)](https://ardupilot.org/dev/docs/building-setup-linux.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.
- while I am implementing the following command as per documentation
```bash
ardupilot/Tools/autotest/sim_vehicle.py -v ArduCopter -w --model webots-python --add-param-file=ardupilot/libraries/SITL/examples/Webots_Python/params/crazyflie.parm -n 2
```
I am getting following window.
![image](https://github.com/ArduPilot/ardupilot_wiki/assets/130888313/dcfc88ed-2661-45ec-8bde-a01cb0fd3129)

**Comment by Hwurzburg** [comment]
first this has nothing to do with the page you raise the issue about....this is about SITL Webots...
second, you do not have "/path/to/ardupilot/libraries" specified correctly for your directory structure to locate the param file...most likely the command should be: Tools/autotest/sim_vehicle.py -v ArduCopter -w --model webots-python --add-param-file=libraries/SITL/examples/Webots_Python/params/crazyflie.parm

thirdly, you specify two sim instances when you are trying to sim only a single vehicle
if you still have issues ask in the support forum discuss.ardupilot.org or the discourse servers simulation topic
