### ISSUE TITLE
Communicating with Raspberry Pi via MAVLink

### ISSUE THREAD

**Issue by qoo23502004** [ArduPilot/ardupilot_wiki#575]
[Communicating with Raspberry Pi via MAVLink](http://ardupilot.org/dev/docs/raspberry-pi-via-mavlink.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

The pymavlink newest version have some problem.
When I typing "param show ARMING_CHECK",it no any response.Other command was no response too.
But I downgrade it version, it can work now.

**Comment by gmorph** [comment]
This isn't a wiki issue as what it describes works fine.  It should be an issue raised on the ArduPilot code if there is actually a bug.  We would also need more details with what versions of code were being used where and what output was showing a failure.
Thanks, Grant.
