### ISSUE TITLE
4.6 Wiki (should be in Upcoming features)

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot_wiki#5759]
commits after 1/28 that need wiki:
- [x] 22513 Param controller applet (@Hwurzburg )
- [ ] 23056 RDSS02UF Rangefinder (@zebulon86) need to verify this is obtainable by users and how
- [x] 24645 Allow more rpm instanes(@magicrub )
- [ ] 24801System ID-Pos Cntrlr(@bnsgeyer )
- [x] 24899 GPS Jamming (@tridge )
- [x] 25273 MatekF765-SE bdshot (@FOGYamato)
- [x] 25442 harmonic notch rework (@tridge )
- [x] 25844 CRSF Extended RF reports (@rmaia3d )*
- [x] 25940 LR-D1rangefinder (@jkronk)
- [x] 25993 Temp sense from AP_Periph (@IamPete1 )
- [x] 26021 AnyleafH7 board (@David-OConnor )*
- [x] 25621 EKF filtering (@andyp1per )
- [x] 25714 PixFlamingoF767 (@subashchandar)*
- [x] 25801 MR72CAN(@rishabsingh3003 )*
- [x] 26030 YJUAVA6Ultra(yunjiuav) *
- [x] 26057 default param extract utility(@amilcarlucas )
- [x] 26129 Chute option(python36)
- [x] 26131 MicroStrain7 orientation (@Ryanf55 )
- [x] 26139 RadiolinkPIX6*
- [x] 26172 Mavlink camera source (@rmackay9 )
- [x] 26197 STAMPH743(@andyp1per )
- [x] 26212 Hi-speed VTOL fixes (@priseborough )
- [x] 26245 Improve AUTOTUNE (@lthall )
- [x] 26260 VTOL takeoff FS (@CallanDaniel )
- [x] 26272 Fence on SD(@tridge )*
- [x] 26265 low drag TECS option (@priseborough )
- [x] 26321DShot V2 telem (@mbuzdalov)
- [x] 26463 ControlZero H7 OWM RevG (@TOTON95)*
- [x] 26568 Relay invert(@LaneaLucy)
- [x] 26317 GPS_DRV_OPTION for full parsing (@tridge )*
- [x] 26345 Heli inverted flight (@IamPete1 )
- [x] 26356 MAVLink RC (@olliw42 )
- [x] 26368 MicoAir405V2 (@Minderring)*
- [x] 26379 PLDP_RNG_MAX (@lthall )
- [x] 26415 PWM_TYPE_ANGLE (@IamPete1 )
- [x] 26435 Heli inverted added to additional modes (@bnsgeyer )
- [x] 26436 precision QLOITER(@tridge )
- [x] 26449 RTL_ALT_MIN(@tatsuy )
- [x] 26464 DroneCAN hires compass option(@tridge )
- [x] 26465 INA239 params(@tridge )
- [x] 26484 RPLidar C1 (@rmackay9 )
- [x] 26497 New Tool (@peterbarker )
- [x] 26516 Viewpro rf enable(@rmackay9 )
- [x] 26542 Orca F405 pro (@andyp1per )*
- [x] 26562 NET_ENABLED name change(@timtuxworth )
- [x] 26571 FoxeerF405V2 (@andyp1per )*
- [x] 26576 Remove GPS blending from small bds (@peterbarker )
- [x] 26623 Persistent IMU params (@joshanne )
- [x] 26637 M icoAir405Mini (@Hwurzburg )*
- [x] 26639 NxtPX4v2 (@Minderring)
- [ ] 26646 Speektreworks boom ESC bds (@WickedShell )
- [x] 26667 CSKY405 bd (@AlexandrShipovsky )
- [x] 26674 per motor Thr-based notch (@andyp1per )
- [x] 26707 ARSPD_OPTION for GCS cal offset report (@Hwurzburg )
- [x] 26710 Crash dump prearm (@peterbarker )
- [ ] 26722 Heli autotune improvements (@bnsgeyer )
- [x] 26748 Auto/Guided Pause/Resume (@peterbarker )
- [x] 26762 No compass learn with GPS yaw (@tridge )
- [x] 26763 Flight Blitz H743Pro(@andyp1per )*
- [x] 26788 JHEMCU GF30H743 HD (@SCRainbow)
- [x] 26789 Flight Blitz F745 Mini(@andyp1per )*
- [x] 26793 Correct GPS on MambaH743v4(@andyp1per )
- [x] 26812 Aocoda-RC H743Dual motor 5-8 mis-labeled issue(@lida2003 )*
- [x] 26854 MicoAir743 (@Minderring)
- [x] 26886 MLX96014 Temp Sensor (@rahulOCR)
- [x] 26935 SDMODELH7V2(@andyp1per )*
- [x] 26940 ARKV6X mods(@dakejhal)
- [x] 26967 BLITZ H743Wing (@andyp )*
- [x] 26971 Copter brake script(@tridge )
- [x] 26982 BF frame preconfig(@Hwurzburg )
- [x] 27009 LongBowF405WING (@HiRCbro)
- [x] 27030 BATMON ESC mask (@IamPete1 )
- [x] 27036 FlywooF405 HD AIO v2 (@rotorman )
- [x] 27040 ROMFS flags (@IamPete1 )
- [x] 27053 Topotek Gibal (@rmackay9 )
- [x] 27076 TCA9554 crank dir (@loki077)
- [ ] 27091 Add QURT HAL (@tridge )
- [x] 27155 FoxeerF405 update (@andyp1per )
- [x] 27166 iFlight Thunder H7 (@andyp1per )*
- [x] 27174 TECS airspeed during takeoff (@Georacer )
- [x] 27219 Serial device scripting support (@tpwrules )
- [x] 27298 eeprom full prearm (@tridge )*
- [x] 27335 Kakute F4 Wing (@andyp1per )
- [x] 27341 Ground resonance (@lthall )
- [x] 27352 Mount2 retract (@muramura )
- [x] 27365 Add cmd_int accessor to Scripting (@tridge )
- [x] 27367 Copter flight option for position before arm (@peterbarker )
- [x] 27385 Require position in addition to GPS on RGB Noitfy LED flashing (@peterbarker )
- [x] 27399 Update Q_OPTION 22 info (@IamPete1 )
- [x] 27406 ESC_RATE param (@tpwrules )
- [x] 27433 NEMA2000 EFI driver(@tridge )
- [x] 27438 CUAV-7-Nano (@cuav-chen2)*
- [x] 27487 Option to align extnav to optiflow (@rmackay9 )
- [x] 27491 GEPRC745BTHD (@YI-BOYANG)
- [x] 27551 Add Mecanum wheeled omni (@srmainwaring )
- [x] 27533 I LED Notify (@peterbarker)
- [x] 27588 MFT-EMA100 board (@EternAlmox)*
- [x] 27442 Stall speed param @WickedShell )
- [x] 27649 ZeroOneX6(@ZeroOne-Aero)*
- [x] 27651 Rename iFlight Thunder H743(@andyp1per )
- [x] 27675 Temp sensor logging(@IamPete1 )
- [x] 27686 ReaperF475 AIO update (@ericjohnson97)
- [x] 27695 iBus Telem (@nicole-ashley)
- [x] 27745 ICE endpoints (@IamPete1 )
- [x] 27754 Autotune test AUX switch (@IamPete1 )
- [x] 27758 Plane takeoff improvements (@Georacer )
- [x] 27768 TmotorH7 (@andyp1per )*
- [x] 27770 TKOFF_THR_MIN (@Georacer )
- [x] 27785 FlywooH743 Pro (@andyp1per )
- [x] 27840  Septrino gps type (@peterbarker )
- [x] 27852  EKF2 options (@tridge)
- [x] 27860  TECS tuning revert script (@tridge )
- [x] 27918  Jamming sim (@peterbarker )
- [x] 27926 ICE crank limit(@loki077)
- [x] 27930 Update CUAV-7 Nano (@cuav-chen2)
- [x] 27931 1LED improvements (@Hwurzburg )
- [x] 27973 BotBlox ENET adapter (@tridge )
- [x] 27980 Update MicoAir F405s (@Minderring)
- [x] 27983 Rover circle mode (@stephendade )
- [x] 27985 Glider pullup (@tridge )
- [x] 28014 Different plane RF orientations (@tridge )
- [x] 28015 Update ARKV6x (@dakejahl)
- [x] 28039 waf custom build options (@tridge )
- [x] 28072 Q_APPROACH_DIST (@tridge )
- [ ] 28098 Experimental topics (@Ryanf55 )
- [x] 28117 Rename EK3_POS_SRC  AUX sw(@peterbarker )
- [x] 28122 Remove Bionic support (@Ryanf55 )
- [x] 28160 X-MAV-AP-H743v2 (@Tompsontan)
- [ ] 28203 DDS params for ping (@srmainwaring )
- [x] 28227 Sum batt min voltage report (@robertlong13 )
- [x] 28257 EKF option to disable airspeed check (@tridge )
- [x] 28387 Update ZeroOneX6 (@ZeroOne-Aero)
- [ ] 28282 SITL Flightaxis improvements (@robertlong13 )
- [ ] 28434 DDS configurable rates (@Ryanf55 )
- [ ] 28469 KakuteH7Mini IMU(@peterbarker )
- [ ] 28222 MUPilot (@Hwurzburg )

*backported
last updated 11/06/2024 ....no further additions, 4.7 has been branched

**Comment by David-OConnor** [comment]
LMK if there's anything I can do to help, or if this is something you generally handle.

**Comment by Hwurzburg** [comment]
I got it...thanks

**Comment by Ryanf55** [comment]
26131 will be backported to 4.5 FYI.

**Comment by LaneaLucy** [comment]
For 26568 Relay invert there is some explanation on discord

**Comment by mbuzdalov** [comment]
26321 is addressed here: https://github.com/ArduPilot/ardupilot_wiki/pull/5994

It covers the EDTv2 contribution, but also explains the basic extended DShot telemetry, because I could not find it anywhere.

**Comment by Hwurzburg** [comment]
@mbuzdalov thanks

**Comment by joshanne** [comment]
@Hwurzburg 26623 was a source documentation update to reflect what was actually already occurring in code.

The improved text around the text was included in the wiki PR: https://github.com/ArduPilot/ardupilot_wiki/pull/5841

**Comment by Hwurzburg** [comment]
> @Hwurzburg 26623 was a source documentation update to reflect what was actually already occurring in code.
> 
> The improved wiki documentation around the bitmask was included in the wiki PR: #5841
great...then done

**Comment by lida2003** [comment]
26812 Aocoda-RC H743Dual motor 5-8 mis-labeled issue(@lida2003 ) #6010

**Comment by rahulOCR** [comment]
[26886](https://github.com/ArduPilot/ardupilot/pull/26886) MLX96014 Temp Sensor #6286
