### ISSUE TITLE
Copter: add warning to AutoTune page that crashes may occur

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#5760]
We quite regularly see crashes from users attempting [AutoTune](https://ardupilot.org/copter/docs/autotune.html).  [Here's a recent example from 4.5.0-beta1 testing](https://discuss.ardupilot.org/t/copter-4-5-0-beta1-available-for-beta-testing/112504/11).

We should add a warning about ESC desync risks to the page and point them towards the Lua script.

**Comment by Hwurzburg** [comment]
Proposed wording?

**Comment by Hwurzburg** [comment]
di this a few weeks ago
