### ISSUE TITLE
pixhawk 2.4.8  firmware io error

### ISSUE THREAD

**Issue by Revanthreva003** [ArduPilot/ardupilot_wiki#5796]
[Copter Introduction](https://ardupilot.org/copter/docs/copter-introduction.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.
I recently purchased a Pixhawk 2.4.8, and it operated smoothly for a few weeks when connected to Mission Planner. However, it has now started displaying an error message: "Please fix error and restart firmware, IO error." Despite my attempts to resolve the issue by formatting the SD card, the error persists. I'm seeking assistance in resolving this sudden problem.\

**Comment by Hwurzburg** [comment]
try moving this to the support forum: discuss.ardupilot.com...this is for doc issues only...you are more likely to get help...but fyi,I would try re-loading the "latest (dev)" firmware using the mission planner firmware tab "All Options" button
