### ISSUE TITLE
What are Ecode ERR-0 and ERR23-1 in mission planner logs

### ISSUE THREAD

**Issue by OAPpilot** [ArduPilot/ardupilot_wiki#580]

**Comment by magicrub** [comment]
This is a help question, not a proposed change/bug to the wiki. Please post help questions to discuss.ardupilot.org

if the Wiki is missing info, please reopen this or start a new issue and link to the page that needs changes. Also include what changes are needed. You can also make the edits yourself and make a pull-request. 

thanks!
