### ISSUE TITLE
GPS Error 1.0

### ISSUE THREAD

**Issue by MJBeaubien** [ArduPilot/ardupilot_wiki#581]
[](http://ardupilot.org/copter/search.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

What does GPS error 1.0 mean?

**Comment by magicrub** [comment]
Gps status 1 means it detected hardware but has no lock. I'm not sure what error 1 means. Did you see it on this wiki?

This issue tracker is for bug reporting and feature requests. For howTo or help questions please go to discuss.ardupilot.org

Closing this.
