### ISSUE TITLE
GUIDED%20Mode

### ISSUE THREAD

**Issue by eldhogk7** [ArduPilot/ardupilot_wiki#5814]
[GUIDED%20Mode](https://ardupilot.org/plane/docs/guided-mode.html)%20-%20Describe%20the%20issue/suggestion%20and%20improve%20the%20title.%20Please%20keep%20a%20link%20to%20the%20original%20article%20if%20relevant.

**Comment by eldhogk7** [comment]
need to know guid mode mavilink commands

**Comment by rmackay9** [comment]
Hi @eldhogk7,

Here are the wiki pages we have for this:

- Copter https://ardupilot.org/dev/docs/copter-commands-in-guided-mode.html
- Rover https://ardupilot.org/dev/docs/mavlink-rover-commands.html
- Plane https://ardupilot.org/dev/docs/plane-commands-in-guided-mode.html

I'll go ahead and close this but I'll still see responses.
