### ISSUE TITLE
 Config Error: INS: unable to initialise driver

### ISSUE THREAD

**Issue by Cirocirotondo** [ArduPilot/ardupilot_wiki#5818]
Hi, I have a Pixhawk 6x from Holybro.
My board used to connect without any problem to Mission Planner. 
However, today I was trying to reconnect the board with Mission Planner, but it gave me a problem: the data window was stuck, and there was an error: "Config Error: INS: unable to initialise driver".

What happened? How could I solve the problem?

**Comment by Hwurzburg** [comment]
this should be posted in a support forum...discuss.ardupilot.org...not a wiki issue

**Comment by Cirocirotondo** [comment]
Sorry, I didn't know it. I deleted the topic.
Best Regards,

SC

Il giorno sab 9 mar 2024 alle ore 17:44 Henry Wurzburg <
***@***.***> ha scritto:
