### ISSUE TITLE
Transitions - Airspeed Parameter Change.

### ISSUE THREAD

**Issue by alta-lyster** [ArduPilot/ardupilot_wiki#5832]
[Transitions](https://ardupilot.org/plane/docs/quadplane-transitions.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

I think the paramter AIRSPEED_MIN needs to be changed to ARSPD_FBW_MIN on this page.

**Comment by Hwurzburg** [comment]
no ARSPD_FBW_MIN was renamed to AIRSPEED_MIN in 4.5
