### ISSUE TITLE
Add SidePilot GCS to the common-choosing-a-ground-station page

### ISSUE THREAD

**Issue by tommy-b-10** [ArduPilot/ardupilot_wiki#584]
Add the SidePilot GCS to the common-choosing-a-ground-station page in the doc. 

```

SidePilot
---------

ArduCopter and Px4 compatible GCS for iOS Devices.

See support forum for how-to on how connect it to your autopilot

-  **Platform**: iPhone, iPad
-  **Licence**: Proprietary

.. image:: ../../../images/sidepilot.jpg
    :target: ../_images/sidepilot.jpg

-  `Release announcement Blog & Discussion <http://diydrones.com/profiles/blogs/sidepilot-app-version-1-1-formerly-imavlink>`__
-  `Support Forum <http://sidepilot.net/forum>`__
-  `iTunes Store link <https://itunes.apple.com/us/app/sidepilot/id1138193193?ls=1&mt=8>`__
```

Image to show:

![sidepilot](https://cloud.githubusercontent.com/assets/7692933/19670778/9faafbd0-9ab1-11e6-8472-001db3423cae.jpg)

**Comment by magicrub** [comment]
Hi @tommy-b-10 it looks like you wrote a pull request inside an issue. Have you tried just passing this code into the wiki directly? If you visit the page you want to edit, at the top right you can "edit in github" and edit then preview right there! If you still need help then we can look at doing that for you

**Comment by tommy-b-10** [comment]
Thanks, I was going to do a pull request however I cannot seem to add the image

**Comment by davidbuzz** [comment]
Before we add SidePilot to the wiki, and encourage user/s to use it, etc... What sort of feature set does  it have ..?      I don't have the software ( it requires payment ), so I'd appreciate anyone who does have it could go to this document and describe some/all of it's features..?   https://docs.google.com/spreadsheets/d/1PyuViV9NfwAKZbIXa9GBftLn05cTQTtGgdhJ0CjOyXA/edit#gid=2144438540

**Comment by tommy-b-10** [comment]
If you would like to test out the software and have a wifi connection to your quad, I'd be happy to give you a promo code for a free version, just chuck me an email. I will update that doc later today when I'm free.

Thanks!

On 15 Nov. 2016, at 12:17 pm, Buzz <notifications@github.com<mailto:notifications@github.com>> wrote:


Before we add SidePilot to the wiki, and encourage user/s to use it, etc... What sort of feature set does it have ..? I don't have the software ( it requires payment ), so I'd appreciate anyone who does have it could go to this document and describe some/all of it's features..? https://docs.google.com/spreadsheets/d/1PyuViV9NfwAKZbIXa9GBftLn05cTQTtGgdhJ0CjOyXA/edit#gid=2144438540

-

**Comment by auturgy** [comment]
reviewing http://ardupilot.org/copter/docs/common-choosing-a-ground-station.html reveals that sidepilot is listed, with the links, image etc.  Closing.
