### ISSUE TITLE
About the website  Documentation issue 

### ISSUE THREAD

**Issue by A10-vtol** [ArduPilot/ardupilot_wiki#5840]
https://ardupilot.org/plane/docs/common-install-sdcard.html

in this page , I  find a wrong word.

which woukkd upload on the next boot of the vehicle.

maybe  the word  "would " is   original .
![image](https://github.com/ArduPilot/ardupilot_wiki/assets/164890489/4f09c1ee-bbc0-4345-b2c8-fbbb30154f6d)

**Comment by Hwurzburg** [comment]
fixed
