### ISSUE TITLE
SpeedyBee F405 WING. RCInput ELRS in AP Wiki NOT correct.

### ISSUE THREAD

**Issue by nostromo123** [ArduPilot/ardupilot_wiki#5861]
In the AP Wiki page SpeedyBee F405 WING the RCInput chapter should be overlooked and corrected. In case of CRSF and ELRS according to the SppedyBee manual TX1/RX1 is the correct port, but NOT TX2/RX2. 
![446da4e1a0b0d25c34ef3d628958d2ae32fb83e8](https://github.com/ArduPilot/ardupilot_wiki/assets/17964433/4db0251b-5ac6-42e2-9a81-40da39fc22a2)

This is especially annoying in case of F405 Wing mini, as the kit is shipped by SpeedyBee without the necessary GH1.25 cable to access TX2/RX2.

Enough for today. 
br Kalle

**Comment by Hwurzburg** [comment]
https://github.com/ArduPilot/ardupilot_wiki/pull/5862...will merge once CI passes
btw Uart2 can be used as currently documented...wiki page was created before Speedybee had created their recommended wiring diagram and they had reviewed and approved the wiki page
