### ISSUE TITLE
arducopter autotune fail

### ISSUE THREAD

**Issue by Danielsvf** [ArduPilot/ardupilot_wiki#5866]
[Search](https://ardupilot.org/copter/search.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by Danielsvf** [comment]
Good afternoon Srs
Im trying to do as usual the AUTOTUNE in my brand new quadcopter, its built with the pixhawk 2.4.8, but when I lift the dron in Althold flygth mode then I switch the aux chanel to AUTOTUNE the dron do nothing in the teoreticaly movements of itsself, it stays stop while the little air push the drone in the space more and more far..., without any movement of itself..., I keep the control then to bring the dron to my place again, like that continuously and the dron only do by itself some roll movement, about 3 time in 13 minutes, then the dron do itself a RTL because Battery fail safe then land then I disarm, then switch of the AUTOTUNE mode aux, but the PID neither is recording.

Please, can anyone to say me some lights of why this could be happening? can be the PixHawk defective? 

Thanks alot in advance by your help of anyone.

Waiting yours anxiously

Daniel

**Comment by Hwurzburg** [comment]
this is a support question, not a wiki issue....please move it to discuss.ardupilot.org or the Discord copper help thread...
but anytime you move the sticks while in Autotune it will stop for about 2 seconds...if you were continuously re-positioning to compensate for wind drift, it would probably never complete the tune....read https://ardupilot.org/copter/docs/autotune.html instructions carefully

**Comment by Danielsvf** [comment]
How to move it?

please explain me how

Thanks in advance

Daniel



Saludos cordiales
Best regards




*Daniel Vega Frias*
*Telf / *0034 673567151

*         Web* / www.summum-brothers.com
*FaceBook* / https://www.facebook.com/daniel.vegafrias
*FaceBook* / https://www.facebook.com/Escuela.de.Pilotos.de.RC
*FaceBook* / https://www.facebook.com/SummumBrothers

*e-mail* / ***@***.***






*This e-mail may contain confidential and/or privileged information.If you
are not the intended recipient (or have received this e-mail in
error),please notify the sender immediately and destroy this e-mail. Any
unauthorized copying, disclosure or distribution of the material in this
e-mail is strictly forbidden.*

**Comment by Hwurzburg** [comment]
just copy and paste into this discord thread (you may have to join t he ArduPilot Discord thread) https://discord.com/channels/674039678562861068/998765214398939247

**Comment by rmackay9** [comment]
@Danielsvf,

As a side note, if you're new to ArduPilot I would recommend using QuikTune before the full blown AutoTune.  It's here on the wiki https://ardupilot.org/copter/docs/quiktune.html
