### ISSUE TITLE
Consolidate Dynamic Harmonic Notch setup instructions

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#5878]
There appear to be three wiki pages that covers portions of the harmonic notch setup some of which can surely be consolidated.  I think the 3rd item above is just for collecting data so perhaps it is the first two that really need to be consolidated.

- [Managing Gyro Noise with the Dynamic Harmonic Notch Filters](https://ardupilot.org/copter/docs/common-imu-notch-filtering.html)
- [Throttle Based Dynamic Notch Setup](https://ardupilot.org/copter/docs/common-throttle-based-notch.html)
- [Raw IMU Logging for FFT Analysis](https://ardupilot.org/copter/docs/common-raw-imu-logging.html)

In particular it is odd that [the top link](https://ardupilot.org/copter/docs/common-imu-notch-filtering.html) talks about these parameters:

- INS_HNTCH_ENABLE
- INS_HNTCH_MODE
- INS_HNTCH_HMNCS
- INS_HNTCH_OPTS

.. but misses out on these:

- INS_HNTCH_FREQ
- INS_HNTCH_BW
- INS_HNTCH_ATT
- INS_HNTCH_REF
- INS_HNTCH_FM_RAT

Then then 2nd link talks about these parameters:

- INS_HNTCH_ENABLE <-- the mention of this parameter should probably be moved up one line
- INS_HNTCH_MODE
- INS_HNTCH_FREQ
- INS_HNTCH_BW
- INS_HNTCH_REF
- INS_HNTCH_FM_RAT

.. but misses out on these:

- INS_HNTCH_HMNCS
- INS_HNTCH_OPTS
- INS_HNTCH_ATT

I understand this area is complicated and evolving but we must try and imagine how a new user would try to navigate this. They need a single set of instructions to follow from top to bottom.  They don't need to understand how everything works but they do need to understand how to set it up.

Also not having good instructions adds to the support load both because of the avoidable user support question but also because the support engineer also needs to spend time figuring it out if they're not intimately involved in this area.

FYI @andyp1per

**Comment by Hwurzburg** [comment]
@rmackay9 Notch filtering is complicated indeed...originallty, the info was structured just as you suggest and was an impossibly long read. It was intentionally restructured to avoid this by separating the center freq control methods into separate pages, Throttle based being only 1 of the four modes having their own page to avoid readers having to wade thru other methods of non-interest.
Those pages have the params needed for each control mode that need to be set. The main page having the advanced common notch params. 
And the last page , while needed data for notch setup, can be used independently and should be a separate page.
Perhaps a very simple overview page that describes the setup flow with links to each page(s) would make it clearer? I can attempt that, but I disagree the current hierarchy needs collapsing....a step backwards in my opinion
