### ISSUE TITLE
Landing Gear

### ISSUE THREAD

**Issue by skule1** [ArduPilot/ardupilot_wiki#588]
[Landing Gear](http://ardupilot.org/copter/docs/landing-gear.html) - 
The Pixhawk controller is retracting the landing gear when the power is applied to the drone staying at ground level. I have to rectract and then deploy the landing gear manually with the switch on the transmitter in order to deploy the landing gear. After that manual tracting/deploying of the landing gear works correctly. It is a problem that the landing gear is not staying in deployed position at the ground level and retracts after the power is activated.  What is wrong?

**Comment by magicrub** [comment]
This sounds like a help or howto question but you've  posted it on the wiki documentation change area. Please repost at the forums at discuss.ardupilot.org
