### ISSUE TITLE
Link not found on APM2

### ISSUE THREAD

**Issue by butchalline** [ArduPilot/ardupilot_wiki#590]
On this page:

http://ardupilot.org/planner2/index.html

clicking a link produces this: The requested URL /planner2/_images/planner2_install_firmware_large.jpg was not found on this server.

**Comment by hamishwillee** [comment]
@billbonney I think this one is for you, though I don't understand it.

**Comment by billbonney** [comment]
@hamishwillee The image links where wrong... fixed with 64094f28699688340137e1783c5f3b068c24a85a
