### ISSUE TITLE
Add MTF-01 flow sensor setup instructions

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#5916]
This comes from this discussion in the Copter-4.5 forum where a user couldn't get it working.  This is the 2nd report and the issue is that the sensor ships with a sysid=1, compid=1 which conflicts with the autopilot's default mavlink sysid/compid and in 4.5 we throw away these messages.

We should add a wiki page so that people can at least find the solution.  The sensor also has a narrow field of view (6deg) and a build in 8m lidar so it's a decent choice I think.

**Comment by Hwurzburg** [comment]
Done #5922 awaiting your review
