### ISSUE TITLE
SITL Simulator with ROS on Raspberry Pi

### ISSUE THREAD

**Issue by carlson-fpv** [ArduPilot/ardupilot_wiki#5947]
[SITL Simulator (Software in the Loop)](https://ardupilot.org/dev/docs/sitl-simulator-software-in-the-loop.html) 
Good afternoon everybody!
I'm trying to connect Ardupilot SITL (running on PC with Ubuntu 20.04) with ROS (running in Raspberry). Raspberry works as AP, it's own IP is 192.168.12.1 and PC's IP is 192.168.12.101. I'm trying >roslaunch apm.launch with <arg name="fcu_url" default="udp://@192.168.12.101:14580" />, and add output 192.168.12.1:14580 in simulator terminal, but no connection establishes. 
If I'm trying same way launch jmavsim everything works fine. What am I doing wrong?

**Comment by Hwurzburg** [comment]
can you please move this to a support venue: discuss.ardupilot.com or the simulation thread in discord....this is for doc issues only...tghanks
