### ISSUE TITLE
Connecting AntennaTracker with GCS

### ISSUE THREAD

**Issue by catasbox** [ArduPilot/ardupilot_wiki#5955]
[Connecting with GCS](https://ardupilot.org/antennatracker/docs/connecting-with-gcs.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

How can I send the data to the autopilot running AntennaTracker controlling the antenna if my RADIO connection with the UAV is TCP/IP and connects directly to the GCS computer. Looks like if I connect by USB to the antenna autopilot using another instance of MP there is no option...

**Comment by Hwurzburg** [comment]
please move this to discuss.ardupilot.org...this is for documentation errors or enhancements, not support questions...thanks
