### ISSUE TITLE
RTL Mode  RTL_ALTITUDE typo

### ISSUE THREAD

**Issue by AndreyAgafonov** [ArduPilot/ardupilot_wiki#6003]
Different units of length are used in various places in the documentation.

https://github.com/ArduPilot/ardupilot_wiki/blob/master/plane/source/docs/rtl-mode.rst?plain=1#L13 
The target altitude for RTL mode is set using the :ref:`RTL_ALTITUDE <RTL_ALTITUDE>` parameter in centimeters

and:

https://ardupilot.org/plane/docs/parameters.html#rtl-altitude

Units
--
meters

Where is the correct unit of measurement?

**Comment by Hwurzburg** [comment]
as of 4.5 its now in meters...it will be converted automatically if migrating from a version prior to 4.5...have updated wiki...thanks
