### ISSUE TITLE
Loading Firmware

### ISSUE THREAD

**Issue by Onkar86** [ArduPilot/ardupilot_wiki#6075]
[Loading Firmware](https://ardupilot.org/copter/docs/common-loading-firmware-onto-pixhawk.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.
![image](https://github.com/ArduPilot/ardupilot_wiki/assets/104762148/bae06b13-99e4-4e11-bf87-1999c7d10d74)
![image](https://github.com/ArduPilot/ardupilot_wiki/assets/104762148/0313557a-f1d1-4d98-bd1c-9773fbcd3734)

**Comment by Hwurzburg** [comment]
see comments on the other issue you opened
