### ISSUE TITLE
help me on this i'm completly check all this thinks but they was complety always give me error

### ISSUE THREAD

**Issue by Onkar86** [ArduPilot/ardupilot_wiki#6076]
![image](https://github.com/ArduPilot/ardupilot_wiki/assets/104762148/2cd1ffaf-32c2-41e9-8b2a-a1e0c6127850)

![image](https://github.com/ArduPilot/ardupilot_wiki/assets/104762148/a6e53705-7ab9-4004-a873-a10ac23cbab4)

![image](https://github.com/ArduPilot/ardupilot_wiki/assets/104762148/debca541-ee67-499e-8e3f-5c8165eae420)

**Comment by Hwurzburg** [comment]
1. this is probably a support issue and should not be raised here, but rather on the discuss.ardupilot.org site
2. It appears you are having an problem connecting to Mp...but you do not say what autopilot or what firmware you are using
please move this to a support forum
