### ISSUE TITLE
V-Tail Planes

### ISSUE THREAD

**Issue by HDPilot** [ArduPilot/ardupilot_wiki#6094]
[V-Tail Planes](https://ardupilot.org/plane/docs/guide-vtail-plane.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

Are the control description correct? The description for pitch and roll seems to be reversed. 
On a V-tail , to pitch the nose up, shouldn't the ruddervators pitch up? In to pitch the nose down, shouldn't the ruddervators pitch down?
And to roll, should the ruddervators deflect in the direction of the roll. Such as roll right, ruddervators deflect to the right, ad to roll left, the ruddervators deflect to the left?

This is the table from the ArduPilot Plane docs.
![Screenshot 2024-07-04 110643](https://github.com/ArduPilot/ardupilot_wiki/assets/174736493/03792b87-b9b9-4ae1-ac23-fc196a3d3544)

It was explained to me as an example.

![vtail-fig3-elevator](https://github.com/ArduPilot/ardupilot_wiki/assets/174736493/2ceab353-b679-423e-8528-936ebdff7e05)

![vtail-fig4-rudder](https://github.com/ArduPilot/ardupilot_wiki/assets/174736493/ca1fb3e7-702c-478a-9dd3-7c7467d830f3)

**Comment by Hwurzburg** [comment]
you did not carefully read the preceeding paragraph above the table...the table illustrates the autopilot's FBWA _reactions_ to the movement of the plane....you roll the plane left, it tries to roll it back right

**Comment by HDPilot** [comment]
Thank you
