### ISSUE TITLE
make -j4 -l4 failed

### ISSUE THREAD

**Issue by wenxin615** [ArduPilot/ardupilot_wiki#612]
[Using ROS/Gazebo Simulator with SITL](http://ardupilot.org/dev/docs/using-rosgazebo-simulator-with-sitl.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by magicrub** [comment]
Content of email was pertinent supposed to include:

make -j4 -l4 failed

More info will help. Audi, of this is not a documentation thing then please post in the other forum.
