### ISSUE TITLE
how to control the angle of the bldc/servo motor with the pixhawk qube orange plus and drone transmitter switch like SWC

### ISSUE THREAD

**Issue by Arhat9844** [ArduPilot/ardupilot_wiki#6123]
I have watched a video this is the video link -- https://www.youtube.com/watch?v=exr54pDj86U
then tell me how it is working and what type of motor I need to use for this and how can I it with the aux channel of pixhawk qube orange plus and drone transmitter 's any three-way switch switch like switch c  i want to drop 6 ball like this then tell me how can i do it with Ard copter firmware any what parameters I need to set for this.
thank you

**Comment by Hwurzburg** [comment]
This issues list is not for support questions...please ask in Discord copter help thread or discuss.ardupilot.org
