### ISSUE TITLE
Splined WPs removed/not working

### ISSUE THREAD

**Issue by billjow** [ArduPilot/ardupilot_wiki#6171]
I have Arduplane 4.5.5 installed on a F405 flight controller in a Fimi Manta VTOL. In an effort to smooth out a mission, I tried to use Spline WPs. If I load an existing mission into the Plan section of Mission Planner, the waypoints show up as Unknown and cannot be dragged around (see attached screeenshot ![Existing mission with Splined waypoints](https://github.com/user-attachments/assets/24f4c674-2299-45c4-93a3-ebf5b4754d3a)). If I am creating a new mission, I can insert a Spline WP after a numbered waypoint, but have to manually edit the coords for it to show. It only shows up as a Waypoint in Mission Planner. Please could the previous Spline WP functionality be reinstated. Thanks!
![New mission with Spline WP inserted WP 2](https://github.com/user-attachments/assets/73839c72-2496-4336-a391-a45ae6a95174)

**Comment by Hwurzburg** [comment]
this is not a wiki issue, its a support question(should be posted on discuss.ardupilot.org or discord plane-help)....
but fyi...plane(and quadplane) has never supported spline waypoints (or Scurves)....MP creates missions that are vehicle agnostic...but the vehicle code determines what MAV commands are implemented for that vehicle

**Comment by billjow** [comment]
Understood and thanks for the information. Kind Regards, Bill Sent from my iPhoneOn 8 Aug 2024, at 18:04, Henry Wurzburg ***@***.***> wrote:﻿
this is not a wiki issue, its a support question(should be posted on discuss.ardupilot.org or discord plane-help)....
but fyi...plane(and quadplane) has never supported spline waypoints (or Scurves)....MP creates missions that are vehicle agnostic...but the vehicle code determines what MAV commands are implemented for that vehicle
