### ISSUE TITLE
Incorrect april tag bundle labelling

### ISSUE THREAD

**Issue by chewdonovan** [ArduPilot/ardupilot_wiki#6201]
[Indoor autonomous flight with ArduCopter, ROS and AprilTag Detection](https://ardupilot.org/dev/docs/ros-apriltag-detection.html)

![image](https://github.com/user-attachments/assets/ebf630f6-588f-41df-ba37-f7aed1d30e08)

The provided april tag bundle is labeled from 0-5 and 7-12, where it should be 0-11.

As can be seen the tag labelled "7" is actually the number 6 tag.

![image](https://github.com/user-attachments/assets/29609cc6-fb40-40a6-ad03-179b31ae7d0a)

@thomas-matthews-chironix

**Comment by rmackay9** [comment]
Indeed, the number has missed "6"!  Thanks for the report!

**Comment by Hwurzburg** [comment]
I dont know of anyone that can fix this, to assign it to

**Comment by chewdonovan** [comment]
@Hwurzburg

Just in case you find someone

![fixed-bundle](https://github.com/user-attachments/assets/1ca3813a-0c60-41fe-8315-6992e6f00645)

**Comment by Hwurzburg** [comment]
I can replace with those...thanks

**Comment by Hwurzburg** [comment]
replaced https://github.com/ArduPilot/ardupilot_wiki/pull/6203
