### ISSUE TITLE
PPM Encoder page links to no-longer existent file

### ISSUE THREAD

**Issue by Patronics** [ArduPilot/ardupilot_wiki#6202]
[PPM Encoder](https://ardupilot.org/copter/docs/common-ppm-encoder.html) - Specifically, the link [to Tools/ArduPPM](Tools/ArduPPM) no longer exists.

It was available in older versions, as well as archived on archive.org. [Here's the version from the commit that archive.org archived in 2017](https://github.com/ArduPilot/ardupilot/tree/1062aed91e49e07cd0ae916e07c05ae31052691d/Tools/ArduPPM). I don't know if there's a newer version of these files before they were deleted or moved.

**Comment by Hwurzburg** [comment]
links on archived pages are not maintained since the entire page is obsoleted
