### ISSUE TITLE
Discourse server is incredibly slow

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#621]
It takes me 6 minutes to load the discourse servers: http://discuss.ardupilot.org/

For me this makes it nearly usable.

**Comment by gmorph** [comment]
I have the same issue.  I think its the network routing.  See the picture below showing massive packet loss.
![route-packetloss-screenshot_2016-11-28_14-35-41](https://cloud.githubusercontent.com/assets/1016642/20819377/ffe38b0e-b887-11e6-880b-62d7a3cb8989.png)

**Comment by OXINARF** [comment]
@gmorph Are you always routed through there with that packet loss?

**Comment by rmackay9** [comment]
For me, the biggest improvement came from clearing up the IP address conflict of my home's two routers (one wifi, one non-wifi) which I had connected in parallel.
Performance for me is now back to about 15seconds to load discourse.  It can take a couple of minutes now and then but mostly it's far better.
There's a plan to move to AWS (or similar) servers.
