### ISSUE TITLE
Error in speedybeef405-mini-wiring.jpg

### ISSUE THREAD

**Issue by geofrancis** [ArduPilot/ardupilot_wiki#6210]
the file https://github.com/ArduPilot/ardupilot_wiki/blob/master/images/speedybeef405-mini-wiring.jpg shows a PPM recevier connected, this is an error as its only possible with betaflight. the ppm recevier should be edited out.

![speedybeef405-mini-wiring](https://github.com/user-attachments/assets/bc0b8c18-ec5c-489d-ac40-733d95669b10)

![speedybeef405-mini-wiring](https://github.com/user-attachments/assets/d4bd4d15-3e90-4765-b2bc-c5c539ad7f97)

**Comment by Hwurzburg** [comment]
done
