### ISSUE TITLE
Mission Planner Overview

### ISSUE THREAD

**Issue by zhangyihangceshi1hao** [ArduPilot/ardupilot_wiki#6223]
"Click the designer of the file named FlightData.cs"  
Void SvgNet.SvgGdi.GdiGraphics..ctor(System.Drawing.Graphics
![f7982d7c1826ddcf36137c5b5dc0296](https://github.com/user-attachments/assets/03a15cba-9b63-4880-a6c2-32ca5560c0b7)
![f7982d7c1826ddcf36137c5b5dc0296](https://github.com/user-attachments/assets/e6a36bc4-0230-4a60-84d1-dc437fcd5b82)

**Comment by Hwurzburg** [comment]
not reader of Chinese,I have no  idea what this issue is about

**Comment by rmackay9** [comment]
Through the wonders of ChatGPT, it seems to be a mission planner compile issue.  @zhangyihangceshi1hao could you please raise this over in the [Mission Planner's issues list](https://github.com/ArduPilot/MissionPlanner)?  

Main Error Message: To use the designer, the following errors must be resolved:

2 errors

Could not find type: "Void SvgNet.SvgGdi.GdiGraphics..ctor(System.Drawing.Graphics)".

Error Details:

This error occurred in the following instance (1): Hidden Call Stack
at MissionPlanner.Controls.HUD..ctor()

Relevant Error Help: No help associated with this error was found. Check Windows Desktop Development Troubleshooting List.

Related Error Forum Threads: Search MSDN forums for threads related to this error.

Variable 'hud1' is declared but never assigned.
