### ISSUE TITLE
Remove reference to MP's Automatic Log Analysis

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#6236]
We've removed support for the Automatic log analysis recently because it has fallen out of date with changes to the log file format.

[This discussion](https://discuss.ardupilot.org/t/octocopter-violent-crash/122977/17) is from a user who was led astray but [this section of the wiki](https://ardupilot.org/copter/docs/common-downloading-and-analyzing-data-logs-in-mission-planner.html#automatic-analysis-of-logs).  We should remove this or perhaps provide a link to the [ArduPilot Web Tool's hardware report](https://firmware.ardupilot.org/Tools/WebTools/) which provides an overview at least.

**Comment by Hwurzburg** [comment]
removed...adding analysis tools links

**Comment by rmackay9** [comment]
Thanks very much!
