### ISSUE TITLE
IFlight Blitz Whoop F7 AIO Connector Pinout Incorrect

### ISSUE THREAD

**Issue by klay2000** [ArduPilot/ardupilot_wiki#6243]
On [this](https://ardupilot.org/plane/docs/common-iflight-blitzf7AIO.html) page between ``BAT`` and ``T1`` there is a missing ``GND`` pin.
![image](https://github.com/user-attachments/assets/80d20ba8-2ec3-455a-a1e2-36aa068f8abd)

**Comment by Hwurzburg** [comment]
fixed
