### ISSUE TITLE
Alt-F -> Ctrl-F in documentation for advanced settings?

### ISSUE THREAD

**Issue by ideasrule** [ArduPilot/ardupilot_wiki#6270]
In the documentation here:

https://github.com/ArduPilot/ardupilot_wiki/blob/master/common/source/docs/common-parameter-reset.rst

Should "Press ALT+F to get to advanced commands" instead be "Press Ctrl+F to get to advanced commands"?  The latter worked for me while the former didn't.

**Comment by Hwurzburg** [comment]
what operating system? on Windows its ctrl-f

**Comment by Hwurzburg** [comment]
can you give more info?. if not I will close this

**Comment by ideasrule** [comment]
It is on Windows.  I am not asking for help, just pointing out an error in the documentation that left me confused for a while

**Comment by Hwurzburg** [comment]
you are correct...dyslexically read your comment...wiki updated...thanks
