### ISSUE TITLE
ROS 2: microxrceddsgen version: null

### ISSUE THREAD

**Issue by AssaX0** [ArduPilot/ardupilot_wiki#6311]
Hello,

currently I am trying to get a Pixhawk6C to raspberrypi4B connection Working.
I am using Ubuntu 22.04 with ROS2 Humble and try to follow the Tutorial:
[ROS 2](https://ardupilot.org/dev/docs/ros2.html) 
I followed everything (twice - removed everything and tried again after it did not work) up to the point where you are supposed to check the
"microxrceddsgen -version"
wich returns
"microxrceddsgenversion: null"
I tried fixing it myself, but I am no Linux Main so I asked chat gpt who found a probable typo (?) in:
nano /home/pi/ardu_ws/Micro-XRCE-DDS-Gen/scripts/microxrceddsgen
one Line says
"if ! hash ${jave_exec}; then" what should probably be a:
"if ! hash ${java_exec}; then" ... but after fixing I stil got a 
"microxrceddsgen version: null" and chatgpt is not helpfull anymore.

I hope someone can help me fixing this!

**Comment by BasharAmeen** [comment]
+1

**Comment by Ryanf55** [comment]
Ignore the version. We can't do a formal release.

Use `microxrceddsgen -h` to check it works.

**Comment by AssaX0** [comment]
Well i guess it doesnt?
![image](https://github.com/user-attachments/assets/248ec8d2-0c6a-45a3-832c-241738bb9861)

And If I would like to continue the dds tests start to fail... I guess thats the consequence?
![image](https://github.com/user-attachments/assets/19fd149c-a2c4-4624-92d3-555f0b6627cc)

**Comment by Ryanf55** [comment]
> Well i guess it doesnt? ![image](https://private-user-images.githubusercontent.com/82667429/377888516-248ec8d2-0c6a-45a3-832c-241738bb9861.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyOTY5ODEsIm5iZiI6MTcyOTI5NjY4MSwicGF0aCI6Ii84MjY2NzQyOS8zNzc4ODg1MTYtMjQ4ZWM4ZDItMGM2YS00NWEzLTgzMmMtMjQxNzM4YmI5ODYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDAwMTEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5NGUyNzRkNzkzNjcyMTdmMTVhMjg3NmRlYTQ3ZTZhNmUxOTdkZTZlNTJkYjM0NWMwYjgxNGRkNTg0YWFmOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mU8h5nl7FpuGWeyzLclXIootDklPlsxnA-9XmP6ewG4)
> 
> And If I would like to continue the dds tests start to fail... I guess thats the consequence? ![image](https://private-user-images.githubusercontent.com/82667429/377888130-19fd149c-a2c4-4624-92d3-555f0b6627cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyOTY5ODEsIm5iZiI6MTcyOTI5NjY4MSwicGF0aCI6Ii84MjY2NzQyOS8zNzc4ODgxMzAtMTlmZDE0OWMtYTJjNC00NjI0LTkyZDMtNTU1ZjBiNjYyN2NjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDAwMTEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0N2NlMWIyMmM0YmQ3N2FkMTQ3Mjk1ZDVmMDhmMDE0MjU5NzYxZTRiMWZkZDJiM2FlYmI4ZGNjNjc1NDQzNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PDSnVbbeokaJ6KnttdtVhm5qzRWTAUcnZMpCsqZw5zE)

I put a PR up to solve the version printout. Please give it a try if you can and provide a review.

As far as why your tests are failing, please ask on discuss on one of the ROS threads. I'll need to to run it with more verbosity and attach logs. The ardupilot wiki issues is for discussing issues with docs, not user support.

**Comment by Ryanf55** [comment]
@Hwurzburg Please close this when convenient. It's complete.
