### ISSUE TITLE
Add link to methodic configurator

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#6313]
After a discussion with @amilcarlucas I think we should try and increase the visibility of the methodic configurator.

In particular I think on the [Mandatory Hardware Configuration page](https://ardupilot.org/copter/docs/configuring-hardware.html) we should add a section at the bottom which says something like:

**For users looking to ensure their vehicles are completely and correctly configured we recommend the [Methodic Configurator](https://github.com/ArduPilot/MethodicConfigurator/blob/master/QUICKSTART.md)**

**Comment by Hwurzburg** [comment]
done-
