### ISSUE TITLE
Foxeer Reaper F745 AIO V3 getting error INS: unable to initialize driver

### ISSUE THREAD

**Issue by bulganbaev** [ArduPilot/ardupilot_wiki#6327]
[Foxeer Reaper F745 AIO](https://ardupilot.org/copter/docs/common-foxeerf745aio.html) 

I have tried all firmwares from 4.4.0 to the latest. Tried all beta, stable and official.

Still getting this error. 

My assumptions that ICM-42688 used on V3

**Comment by Hwurzburg** [comment]
this is not a wiki issue, its a code issue and should be raised here: https://github.com/ArduPilot/ardupilot/issues

but the hwdef supports V1/V2/V3 with either BMI270,MPU6000, orICM42688....so it should work.... @andyp1per?
