### ISSUE TITLE
The Cube Black

### ISSUE THREAD

**Issue by myxxmikeyxx** [ArduPilot/ardupilot_wiki#6354]
[The Cube Black](https://ardupilot.org/copter/docs/common-thecube-overview.html) - The link at the bottom for where to buy does not work anymore. It just keeps loading and loading but then fails. 
I used the way back machine to get it.  [Link here](https://web.archive.org/web/20210803112248/http://www.proficnc.com/stores)

**Comment by Hwurzburg** [comment]
links on page updated...thanks
