### ISSUE TITLE
Using SITL with Gazebo, I get the following message in Ubuntu: "Warning, time moved backwards. Restaring timer."

### ISSUE THREAD

**Issue by SJ99-BIT** [ArduPilot/ardupilot_wiki#6360]
[Using SITL with Gazebo, Problem:"Warning, time moved backwards. Restaring timer."](https://ardupilot.org/dev/docs/sitl-with-gazebo.html)  - Hi, every time I run STIL in the simulation in the Ubuntu window I get the following message: "Warning, time moved backwards. Restaring timer."
How can I solve this problem?
![STIL Problem](https://github.com/user-attachments/assets/637bc335-7126-4619-8ed2-dccd4debb88b)

**Comment by Hwurzburg** [comment]
should post this in a support forum (discuss.ardupilot.org)
this is for pure documentation issues
