### ISSUE TITLE
Object Avoidance

### ISSUE THREAD

**Issue by MianIdrees** [ArduPilot/ardupilot_wiki#6388]
[Object Avoidance](https://ardupilot.org/plane/docs/common-object-avoidance-landing-page.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

hello everyone i wanted to that weather ardupilot support object avoidance from all 360 degrees
actully i am using RPlidar C1 360 which is working totally fine i have interfaced it using telemetery 1 port serially 
and i am able to see that  it is detecting objects in all 360 degrees using Proximity viewer window 

but i am unable to configure it as an object avoidance

**Comment by Hwurzburg** [comment]
please post support questions on discuss.ardupilot.org.....this list is for documentation errors or additions...

be sure to follow https://ardupilot.org/copter/docs/common-object-avoidance-landing-page.html and make sure that your autopilot firmware includes the Object Avoidance feature (https://ardupilot.org/copter/docs/common-limited-firmware.html)
