### ISSUE TITLE
Building for Bebop 2

### ISSUE THREAD

**Issue by Skorkmaz88** [ArduPilot/ardupilot_wiki#645]
[Building for Bebop 2](http://ardupilot.org/dev/docs/building-for-bebop-2.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

 You are skipping step of adb shell before kk command in the wiki.

**Comment by auturgy** [comment]
This seems to be resolved.

**Comment by rmackay9** [comment]
@auturgy, thanks for doing this review!
