### ISSUE TITLE
Radio Control Calibration, Bad Channel 1 Input Canceling

### ISSUE THREAD

**Issue by Lansel0t** [ArduPilot/ardupilot_wiki#6454]
[Radio Control Calibration](https://ardupilot.org/copter/docs/common-radio-control-calibration.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

Good morning.  This is my first build, and I need help calibrating an internal ELRS TX12 RadioMaster with a quad zero 3DR quadcopter using an H7 based autopilot in Mission Planner.  I can go through the Mission Planner mandatory hardware calibration steps until I reach radio control calibration, and then I get nothing.  No green bars.  Sometimes it flashes green at the very beginning for less than a second, and then goes away .  

Ways I've tried, and failed to solve the issue:  
- Checking the radio setup.
- Making sure that the transmitter and the receiver bind and that I have a solid light on the receiver.
- Checking the connection between the quad and the laptop.  
- Checking the channel mapping on the TX12.  
- Checking for similar errors on Drone Racing League simulator.  It works fine on the sim, no problems with connecting.
- Making sure I can see the channels moving on the TX12 on the monitor.  They look fine.  
- Resetting the parameters and starting from scratch. 
- Switching ports
- Plugging in the TX12 in via USB along with having the quad plugged in.  
- Looking at DIY drone forums, Reddit and Google.  
- Trying to follow the Mission Planner guide. 
- Asking 3DR for help.  

Sometimes, but not always, I get an error that reads, "bad channel 1 input, canceling" but I don't know what that error code means.  When I look it up it gives me a reference to PPM.  Which I'm not sure is relevant or leading me down a rabbit hole.  

Help appreciated.  
Please advise.

**Comment by Hwurzburg** [comment]
first, this should be posted in a support forum like discuss.ardupilot.org....this is for doc issues only and few dev/users ever look at these besides myself...so there is your best chance for support
second, that error message is not originating from ArduPilot code, but within Mission Planner, so I would post the above the the discuss forums Mission Planner section...
