### ISSUE TITLE
Servo not working with mavsdk

### ISSUE THREAD

**Issue by Momofaiz** [ArduPilot/ardupilot_wiki#6464]
[Move a Servo](https://ardupilot.org/dev/docs/mavlink-move-servo.html) 

Hello,

I have a problem when I try to move servo9 of the simulated drone ArduCopter.

When I send a COMMAND LONG DO_SET_SERVO so I can move it, it moves when the command is sent with mavproxy or ArduCopter directly.

![Capture d'écran 2024-12-17 103818](https://github.com/user-attachments/assets/2533d748-d2a4-46d7-8e20-61d323da5376)

We can see that the command is sent and we have a response from the autopilot.

But when i try to send the same message with a mavsdk c++ code :

![MAVSDK Code](https://github.com/user-attachments/assets/2b4ecc0f-68c0-4777-88e7-b39ad211b63c)

Autopilot Response : 

![Autopilot Response](https://github.com/user-attachments/assets/d404d6ee-e41e-424e-b566-fc7428c80994)

the message is sent to the autopilot, but with no response.

I am using :

* Raspberry Pi 4B, Ubuntu 20.04;
* Mavsdk v0.39.0;
* Ardupilot 4.6.0;

Here is Servo parameters :

* SERVO9_FUNCTION 0
* SERVO9_MAX 1900
* SERVO9_MIN 1100
* SERVO9_REVERSED 0
* SERVO9_TRIM 1500

**Comment by Hwurzburg** [comment]
This is a support question, not documentation issue....please move to a support forum: discuss.ardupilot.org.....thanks
