### ISSUE TITLE
Continuing a Mission After Landing (RTL updates)

### ISSUE THREAD

**Issue by prathamEndu** [ArduPilot/ardupilot_wiki#6490]
In the video it is told that while continuing, you can also set RTL, but if you do, it will just go back to the position where last arming was done.

[Continuing a Mission After Landing](https://ardupilot.org/copter/docs/common-continue-mission.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by rmackay9** [comment]
Hi @prathamEndu,

Thanks for the note.  If the user sets the home position then the home position won't be reset when the vehicle disarms and re-arms so we probably need to add a comment on the page explaining this if it's not already explained in the video
