### ISSUE TITLE
Connect Mission Planner to AutoPilot

### ISSUE THREAD

**Issue by huanmeimei** [ArduPilot/ardupilot_wiki#6493]
[Connect Mission Planner to AutoPilot](https://ardupilot.org/planner/docs/common-connect-mission-planner-autopilot.html) - 

I encountered this connection error when using a CUAV WiFlyLink.

“通常每个套接字地址(协议/网络地址/端口)只允许使用一次。

   在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Bind(EndPoint localEP)
   在 MissionPlanner.Comms.UdpSerial.Open() 位置 C:\Users\mich1\Desktop\CubePilot\MissionPlanner\ExtLibs\Comms\CommsUdpSerial.cs:行号 130
   在 MissionPlanner.MAVLinkInterface.OpenBg(IProgressReporterDialogue PRsender, Boolean getparams) 位置 C:\Users\mich1\Desktop\CubePilot\MissionPlanner\ExtLibs\ArduPilot\Mavlink\MAVLinkInterface.cs:行号 886
   在 MissionPlanner.Controls.ProgressReporterDialogue.RunBackgroundOperation(Object o) 位置 C:\Users\mich1\Desktop\CubePilot\MissionPlanner\ExtLibs\Controls\ProgressReporterDialogue.cs:行号 111”
![image](https://github.com/user-attachments/assets/b692bf3d-6f47-4bf2-8acc-967ee598932d)

It was functioning properly two days ago, but now it's not working. I guess it's because port 14550 has been used once and can't be used again. It suggests that I use another port number, such as 14551 or 14552.

![image](https://github.com/user-attachments/assets/286f8d3d-5c24-4d82-ba36-f18ab48b883d)

**Comment by Hwurzburg** [comment]
sorry but this apparently is a support issue, not a wiki issue....virtually no one except myself and a few others pay attention to wiki issues....move this information over toa post on discuss.ardupilot.org, the official support issued forum, and it will be visible to a lot more devs and users....closing this here...
