### ISSUE TITLE
Add how to get involved page

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#652]
add a "how to get involved" page which outlines the broad areas that people can get involved in including software development, wiki updating, beta testing, administration (i.e. taking meeting notes) and PR (i.e. blogging about ardupilot)

**Comment by brunoolivieri** [comment]
I did a brief draft in PR #2020

**Comment by Hwurzburg** [comment]
Closing since 202 is about to be merged once bruno does the  PR changes discussed in our wiki call
