### ISSUE TITLE
Proposal: External LEDs update

### ISSUE THREAD

**Issue by sgofferj** [ArduPilot/ardupilot_wiki#656]
I wrote a small Arduino sketch to use Adafruit Neopixel strips as external LEDs via I²C. They decode the existing LED control messages.
Would somebody (maybe with some graphical talent for making a connection diagram) be interested to include this into http://ardupilot.org/copter/docs/common-external-leds.html ?
All infos here: http://stefan.gofferje.net/uav/219-neopixel-leds-as-status-leds-for-ardupilot

**Comment by Hwurzburg** [comment]
this is now a standard feature and is in the wiki....closing
