### ISSUE TITLE
Mission Planner Language Translations pt-BR

### ISSUE THREAD

**Issue by ryokochang** [ArduPilot/ardupilot_wiki#657]
[Mission Planner Language Translations](http://ardupilot.org/planner/docs/mission-planner-language-translations.html) - here is the link with the tranlation folder, i hope you guys like it.

[Translation pt-BR link](https://drive.google.com/open?id=0B5TB8NkHjF1pVWY3Tlhrb2pXd00)

**Comment by narew** [comment]
Hello, probably You should move issue to mission planner repository just like we did
https://github.com/ArduPilot/ardupilot_wiki/issues/721

**Comment by auturgy** [comment]
moved to https://github.com/ArduPilot/MissionPlanner/issues/1909
