### ISSUE TITLE
Copter Commands in Guided Mode page needs updating

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#662]
http://ardupilot.org/dev/docs/copter-commands-in-guided-mode.html

in particular it says landing-target is accepted in GUIDED mode but it's actually accepted in LAND mode

**Comment by rmackay9** [comment]
There is also at least one messed up link on the page.

**Comment by Hwurzburg** [comment]
@rmackay9 this can be closed now, right?

**Comment by Hwurzburg** [comment]
closing
