### ISSUE TITLE
Ardupilot.org: Add pictures to front slider

### ISSUE THREAD

**Issue by OlivierJB** [ArduPilot/ardupilot_wiki#664]
Add quality pictures giving a good idea of breadth and depth of Ardupilot.
Make them clickable with link to source and credit, and more information about specific vehicle if available. Point to use cases when applicable.

**Comment by OlivierJB** [comment]
Went ahead and uploaded a first batch of new images, and those are now linked to corresponding pages with information on click (except first slide/mosaic). Acquired e-mail permissions for all images found on external commercial websites,  and corresponding pages point to source. For a very few non –commercial (e.g images from individuals on  facebook or from youtube videos) I was not able to get a response from owner and went ahead, will follow-up anyways. 

All images were “verified” to show vehicles specifically running Ardupilot. Pages are still minimal but more info will be added. Another batch of good images is coming hopefully soon, as permissions come in. Still missing Ardusubs in particular. 

Comments, yeahs/nays and suggestions more than welcome of course.

**Comment by OlivierJB** [comment]
Removed this image from front page slider: 
![bg1](https://cloud.githubusercontent.com/assets/24396967/21946915/baff22f8-d99f-11e6-88f2-0ea87309aa28.jpg)

It's a nice image but reverse image search shows same background without copter as stock image, so looks like it is a composite, and no way to verify source, actual copter, FC.

**Comment by magicrub** [comment]
do we know where this image came from? maybe someone we know made it

**Comment by billbonney** [comment]
It's a composite made by Jani AFAIU. I don't think removing it is a bad idea.

**Comment by OlivierJB** [comment]
Oops, could've asked before, I hope Jani won't mind ...  A guess is he had enough work already what with setting up the site in the first place, and not too many pics to choose from. Anyways, can always put it back if there is an outcry,  although I really think composites should be avoided.

**Comment by Hwurzburg** [comment]
I think this is completed....closing
