### ISSUE TITLE
Ardupilot.org: Improve front page layout

### ISSUE THREAD

**Issue by OlivierJB** [ArduPilot/ardupilot_wiki#666]
- Remove buttons "Check the drones", "Use cases", "Team" (redundant) as they take unnecessary vertical space (done)
- Reduce unnecessary  spacing between top of blogs block and bottom of sliders (done)
- Reduce height of top (black) menu bar, bring it in line with discourse forum and wiki page top bar?
- Aligning adjustments

**Comment by Hwurzburg** [comment]
This has been done right? if so close it please...

**Comment by OlivierJB** [comment]
Yes.
