### ISSUE TITLE
ardupilot_wiki/common/source/docs/common-rc-transmitter-flight-mode-configuration.rst

### ISSUE THREAD

**Issue by lvale** [ArduPilot/ardupilot_wiki#673]
Some of the links that point to diydrones are pointing to wrong articles

**Comment by larsks** [comment]
@lvale can you update this issue with the specific links (and, ideally, with the corrected links as well)? Thanks!

**Comment by lvale** [comment]
https://github.com/ArduPilot/ardupilot_wiki/pull/875
