### ISSUE TITLE
srxl RC setup pages unreachable?

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#674]
I can't actually see how a user can get to this srxl page.
http://ardupilot.org/copter/docs/common-srxl-receivers.html

I think it should be linked in from this page's, "Tutorials for specific RC hardware".
http://ardupilot.org/copter/docs/common-rc-transmitter-flight-mode-configuration.html

**Comment by Hwurzburg** [comment]
Seems to be linked correctly now...closing
