### ISSUE TITLE
Document tank mode on rover with skid steer in & out ==1

### ISSUE THREAD

**Issue by khancyr** [ArduPilot/ardupilot_wiki#683]
see https://github.com/ArduPilot/ardupilot/pull/5540

**Comment by hamishwillee** [comment]
@khancyr Were you planning on making this documentation change?

**Comment by khancyr** [comment]
@hamishwillee Yes, it is in my todo ... If someone make it before I will be happy too ^^

**Comment by hamishwillee** [comment]
Thank you!

**Comment by khancyr** [comment]
Closed as already well explain. A good addition could be to add a video about the controle mode...
