### ISSUE TITLE
Ardupilot.org: Create page promoting safety with links to regulations

### ISSUE THREAD

**Issue by OlivierJB** [ArduPilot/ardupilot_wiki#692]
- Portugal  (PT) legislation site : http://www.voanaboa.pt
- France : http://www.developpement-durable.gouv.fr/Drones-civils-loisir-activite
- Australia: https://www.casa.gov.au/aircraft/landing-page/flying-drones-australia
- UK: http://dronesafe.uk/drone-code/
...

**Comment by hamishwillee** [comment]
Probably a good idea. We have some regulations related to radio use that we might cross link http://ardupilot.org/copter/docs/common-telemetry-radio-regional-regulations.html. 

The page should probably live here: http://ardupilot.org/copter/docs/flying-arducopter.html and be linked from our checklists.

**Comment by khancyr** [comment]
It should be add to plane too !
For rover and boat, I don't know if their are laws in France . But it cost nothing to link it too since some are are about privacy when using camera!

**Comment by OlivierJB** [comment]
CH, Switzerland: https://www.bazl.admin.ch/bazl/de/home/gutzuwissen/drohnen-und-flugmodelle.html
PL, Poland: http://www.ulc.gov.pl/en/270-english/current-information/3806-safe-sky-regulations-on-flying-drones-in-poland
DE, Germany: https://www.bundesregierung.de/Content/DE/Artikel/2017/01/2017-01-18-drohnen-verordnung.html
IE, Ireland: https://www.iaa.ie/general-aviation/drones
HR, Croatia: http://www.crocontrol.hr/default.aspx?id=3505
ES, Spain: http://www.seguridadaerea.gob.es/lang_castellano/cias_empresas/trabajos/rpas/default.aspx
IT, Italy: http://www.enac.gov.it/La_Normativa/Normativa_Enac/Regolamenti/Regolamenti_ad_hoc/info-122671512.html
AT, Austria: http://www.ris.bka.gv.at/Dokumente/BgblAuth/BGBLA_2013_I_108/BGBLA_2013_I_108.html
PE, Peru: https://www.mtc.gob.pe/transportes/aeronautica_civil/prepublicaciones/documentos/NTC%20Requisitos%20Operaciones%20de%20RPAS.pdf

AR, Argentina: http://www.arpasa.com.ar/2016/09/07/ref-0001-perfil-operador-rpas-remotely-piloted-aircraft-systems/

BR: Brazil: https://www.anac.gov.br/assuntos/paginas-tematicas/drones
CO: Columbia: 
http://www.aerocivil.gov.co/autoridad-de-la-aviacion-civil/reglamentacion/Documents/CR-5100-082-002.pdf#search=rpas

UY: Uruguay: http://www.dinacia.gub.uy/comunidad-aeronautica/seguridad-de-vuelos-y-navegacion-aerea/operaciones-dsv.html

CL Chile:  http://www.dgac.gob.cl/portalweb/rest-portalweb/jcr/repository/collaboration/sites%20content/live/dgac/categories/normativas/normasDAN/documents/DAN_151-20150413.pdf

**Comment by OlivierJB** [comment]
Just found this: https://droneregulations.info/

Could be that  a link to it  is the better way  to go given how dynamic  the regulation landscape is  (with many countries no having any, yet  on their way),  so any list will be difficult to maintain.  Crowd funded,  nice clickable map, appears very comprehensive but need to look into it some more.

**Comment by Hwurzburg** [comment]
just put this in my todo soon list...

**Comment by Hwurzburg** [comment]
#2195 addresses this
