### ISSUE TITLE
bas gps health

### ISSUE THREAD

**Issue by lucky1868** [ArduPilot/ardupilot_wiki#702]
[](http://ardupilot.org/plane/search.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by magicrub** [comment]
Do you have an issue on the wiki to report?

**Comment by rmackay9** [comment]
@lucky1868, you probably meant to raise a support issue?  best to raise these in the support forums.  http://discuss.ardupilot.org/c/arducopter

**Comment by lucky1868** [comment]
I have a problem about Bad GPS Health with apm 2.6 arduplane.but it dosent have such problem with arducopter firmware What can I for it?

**Comment by magicrub** [comment]
APM 2.6 was depreciated many years ago because there is only do much an 8 it controller can do, no code changes for a long time. Please upgrade to a modern pixhawk.

**Comment by lucky1868** [comment]
apm is good enough for me
