### ISSUE TITLE
Loading Firmware onto Pixhawk/APM2.x/PX4

### ISSUE THREAD

**Issue by Geni0815** [ArduPilot/ardupilot_wiki#704]
[Loading Firmware onto Pixhawk/APM2.x/PX4](http://ardupilot.org/rover/docs/common-loading-firmware-onto-pixhawk.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by magicrub** [comment]
Hi @Geni0815 is there an issue you'd like to report?

**Comment by Geni0815** [comment]
Hi Tom,
No was a mistaked click, sorry.
Regards Geni


Am 06.02.2017 um 17:25 schrieb Tom Pittenger:
