### ISSUE TITLE
Trouble running sim_vehicle.py on Windows 7

### ISSUE THREAD

**Issue by sfisher49** [ArduPilot/ardupilot_wiki#705]
Trying to setup the sitl per ardupilot.org.  Was able to resolve the PATH issue per earlier comments, but now everytime I run sim_vehicle.py I get the following message:

$ sim_vehicle.py -j4 -L KSFO
SIM_VEHICLE: Start
SIM_VEHICLE: ** Is (arducopter) really your vehicle type?  Try  -v VEHICLETYPE  if not, or be in the e.g. ArduCopter subdirectory
Traceback (most recent call last):
  File "/home/SFisher/ardupilot/Tools/autotest/sim_vehicle.py", line 829, in <module>
    cmd_opts.frame = default_frame_for_vehicle[cmd_opts.vehicle]
KeyError: 'arducopter'
SIM_VEHICLE: Killing tasks

Ideas???

**Comment by OXINARF** [comment]
In what directory are you in? From the message looks to be `arducopter`, which should be actually named `ArduCopter`.

**Comment by sfisher49** [comment]
That worked.  thanks.
