### ISSUE TITLE
Rover wiki improvements

### ISSUE THREAD

**Issue by khancyr** [ArduPilot/ardupilot_wiki#714]
@gmorph 
rover/source/docs/gettit.rst#L26 link is broken , any other suggestion for a rover base ?
http://ardupilot.org/rover/docs/gettit.html#lipo-batteries-and-charger#L86 link is broken
rover/docs/project-news.html is a little outdated, should we keep it ?

**Comment by gmorph** [comment]
Fixed!  Thanks khancyr for finding the missing links.
