### ISSUE TITLE
Gazebo Installation Outdated

### ISSUE THREAD

**Issue by SwiftGust** [ArduPilot/ardupilot_wiki#735]
Hello,
I tried Gazebo Installation on my new laptop with Ubuntu 14.04 LTS 
followed as document here : http://ardupilot.org/dev/docs/using-gazebo-simulator-with-sitl.html#using-gazebo-simulator-with-sitl

Major Number of packages are missing so it's not possible to build from source/ pre-build installation
which does not work is as follows
Build from Source:
Ignition msgs/SD Format/Gazebo and dependency packages

Install from Pre-built :
Number of ROS-Kinetic Related Packages

are missing / does not work

**Comment by SwiftGust** [comment]
![image](https://cloud.githubusercontent.com/assets/13569579/23992376/f5e2c5c6-0a7f-11e7-8490-8ecb861b28e4.png)
It looks like this as I refer here https://github.com/osrf/uctf/tree/master/doc/install_binary

**Comment by SwiftGust** [comment]
![image](https://cloud.githubusercontent.com/assets/13569579/24033121/b1f4ba5e-0b2e-11e7-8275-16ae0ba7a446.png)
in case of ignition msgs, cmake compiling is fine but, 
compiling error comes up when type in make -j4
seems like code missing few things

**Comment by welkerCode** [comment]
Has this issue been solved?  I am trying to do the same exact thing on Ubuntu 16.04, and after trying to make (cmake ../ from the tutorial) Gazebo, it gives the following build errors:


-- BUILD WARNINGS
-- 	DART not found, for dart physics engine option, please install libdart-core4-dev.
-- 	libavdevice not found. Recording to a video device will be disabled.
-- 	Player not found, gazebo plugin for player will not be built.
-- 	Oculus Rift support will be disabled.
-- 	ronn not found, manpages won't be generated
-- 	Missing: Ignition Transport (libignition-transport-dev or libignition-transport2-dev)
-- 	OpenSource Virtual Reality (OSVR) support will be disabled.
-- END BUILD WARNINGS

-- BUILD ERRORS: These must be resolved before compiling.
-- 	Missing: SDF version >=4.1.0. Required for reading and writing SDF files.
-- 	Missing: Ignition math2 library.
-- END BUILD ERRORS

CMake Error at CMakeLists.txt:297 (message):
  Errors encountered in build.  Please see the BUILD ERRORS above.

I followed the example of making SDF on the tutorial, but that says that SDF might be outdated and broken.  Have you posted a fix somewhere in the past?

**Comment by SwiftGust** [comment]
@welkerCode new tutorial is available https://github.com/SwiftGust/ardupilot_gazebo
