### ISSUE TITLE
inconsistant compasses

### ISSUE THREAD

**Issue by aerialactionsports10** [ArduPilot/ardupilot_wiki#752]
[](http://ardupilot.org/copter/search.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by magicrub** [comment]
You've posted "inconsistant compasses" on the wiki page TODO list. I assume thats a mistake. Please post help questions http://discuss.ardupilot.org

**Comment by aerialactionsports10** [comment]
Correct! My apologies... not even sure how this happened.

Doug
