### ISSUE TITLE
After using cs.sendRC(), how could I make the drone controlled by RC again

### ISSUE THREAD

**Issue by LazyBusyYang** [ArduPilot/ardupilot_wiki#757]
[Using Python Scripts in Mission Planner](http://ardupilot.org/planner/docs/using-python-scripts-in-mission-planner.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.
I am using MP with a python script, which can control the drone to fly forward or to other direction, by function "cs.sendRC()". After this command having been sent to drone(e.g. sendRC(3,1500,true)), the chosen channel(e.g. channel 3) will be locked at the value of arguement(e.g. 1500), and input from Radio Control will be blocked. When this happens, never can I change the channel except rebooting PIX.
Is there a way or a function transmitting the control right back to Radio Control?

**Comment by rmackay9** [comment]
@LazyBusyYang,
Questions like this should go to the forums.  http://discuss.ardupilot.org/

In any case, I think if you send all zeros "rc overrides" (as it's called) will be disengaged and control will return to the pilot.  I think if you also simply stop sending updates for a couple of seconds control will revert to the pilot.  Although it really depends a bit on how MP is handling this.
