### ISSUE TITLE
Mission Planner copter simulation 

### ISSUE THREAD

**Issue by ElefLee** [ArduPilot/ardupilot_wiki#768]
I'm trying to simulate a copter mission in MP. The python script that I'm writing must check for the existence of a file in some specific directory. This file is a QGC formated (.waypoints) file including the waypoints to follow and some other actions. In case of such file existence, the MP must make its pre-arming checks, then to arm the vehicle, to take off in "GUIDED" mode and afterthat to follow the trajectory described in QGC format in the  "trajectory.waypoints" file. The final command inluded in the above file will be an RTL command.
Can someone please indicate to me where to look for the MP commands for the above actions or alternatively any related examples?

**Comment by OXINARF** [comment]
This question is about Mission Planner, not exactly related to some wiki issue.

You should post in the [forum](http://discuss.ardupilot.org/c/ground-control-software/mission-planner), which I think you already did - you now need to wait for someone that knows the answer.
