### ISSUE TITLE
LightWare SF40c for Object Avoidance (Incorrect connection instruction)

### ISSUE THREAD

**Issue by horiuchi4dn** [ArduPilot/ardupilot_wiki#769]
[LightWare SF40c for Object Avoidance](http://ardupilot.org/copter/docs/common-lightware-sf40c-objectavoidance.html)

Figure of "Connecting to the Pixhawk" indicates connecting Pixhawk's TX(# 2) to SF40c's TX (yellow cable).
It should be Pixhawk's TX to SF40c's RX (orange cable).

**Comment by rmackay9** [comment]
Oh my, thanks for finding this, fixed! (it might take 20min after this posting to see the change)
