### ISSUE TITLE
compass not healthy

### ISSUE THREAD

**Issue by yvanpeeters** [ArduPilot/ardupilot_wiki#783]
[](http://ardupilot.org/planner2/search.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by hamishwillee** [comment]
Can you provide more information about your problem?

**Comment by rmackay9** [comment]
support questions should go into the discuss forums: http://discuss.ardupilot.org/c/arducopter
.. so if there are no objections, I think I'll close this.
