### ISSUE TITLE
Documentation (building arducopter)

### ISSUE THREAD

**Issue by promistrio** [ArduPilot/ardupilot_wiki#791]
Pixhawk toolchain in this article(http://ardupilot.org/dev/docs/building-px4-with-make.html#building-px4-with-make) don't build an arducopter. 

https://dev.px4.io/en/setup/dev_env_windows.html  - this toolchain is working

**Comment by OXINARF** [comment]
@promistrio Then you aren't in master. Toolchain v14 certainly doesn't build master and the latest version mentioned in our wiki should work for all versions. @rmackay9 uses it everyday so it certainly works.

What errors do you get?

**Comment by OXINARF** [comment]
No answer after four months, closing.
