### ISSUE TITLE
SITL Simulator (Software in the Loop)

### ISSUE THREAD

**Issue by karthikpakala** [ArduPilot/ardupilot_wiki#792]
Hi, 
I have been using the SITL on mission planner with xplane since some time now, I had some issues which can be described as follows,
1)
the total frame rate
![badgyro](https://cloud.githubusercontent.com/assets/17682594/25784087/83496502-332d-11e7-8a57-c12197f54572.png)
 of the communication between the SITL and the xplane was too low until recently, a temporary fix is being applied to this. But a premanent solution is much appreciated
My Rig-(MSI GT62VR-gtx 1070, 32gig RAM, I7 processor.
2)
There is a new issue popping up now, Whenever i am trying to run the simulation 'Bad Gyro,'Bad Accel' warnings are coming on the mission planner and even when i try to fly at a decent frame rate its unflyable. 
please help me out with this.
Thank You

**Comment by larsks** [comment]
This is for issues related to the documentation. Issues concerning the ardupilot code should be filed at https://github.com/ardupilot/ardupilot/issues. You probably want to close this issue and open a new one there.
