### ISSUE TITLE
"MAVPROXY" ignores command

### ISSUE THREAD

**Issue by abhijeet2096** [ArduPilot/ardupilot_wiki#810]
---------------------------------------Problem-------------------------------------------------------------------
I have set up a Raspberry Pi 3 to communicate with the APM2.8 via MAVProxy .
[http://ardupilot.org/dev/docs/making-a-mavlink-wifi-bridge-using-the-raspberry-pi.html](url)
 It works great with mission planner but when try to command it with "mavproxy" commands are not accepted .In background i have a hotspot and pi and my remote laptop are connected as client 
 ----------------------------------------OUTPUT-----------------------------------------------------------------------
like when i type >> mode it gives output of different modes but when i type >>mode STABILISE it do not change the mode,Also if try to change mode though our RC connections all logs are displayed and mode gets changed.
-------------------------------------HARDWARE CONNECTION---------------------------------------------------
on my copter i have connected my APM 2.8 board with a raspberry pi (on board) through USB 
[http://www.amazon.in/APM2-8-Controller-Multicopter-Quadcopter-ARDUPILOT/dp/B01MY55UQ8?tag=googinhydr18418-21&tag=googinkenshoo-21&ascsubtag=6cbb02f4-3cae-489b-a30d-7dbe1838c88f](url)   i have connected pi and remote laptop both through same wifi as client and a wifi router as server
------------------------------------Initiate connection------------------------------------------------------------------------
I initiate connection on remote laptop through `mavproxy.py –master=udpout:xxx.xxx.xxx.xxx:14550` 
and in mavgateway it `DAEMON_ARGS="--master=/dev/ttyACM0,115200 --out=udpin:0.0.0.0:14550 --daemon" `
----------------------------------Ultimate Goal -------------------------------------------------------------------------------
we are making a person following drone we have used struck algorithm for object tracking and want to control our quadcopter through   remote laptop .As this algorithm requires high resource we will be doing our object tracking on remote laptop and send data to apm through wifi bridge but apm is not taking our commands

**Comment by davidbuzz** [comment]
not an issue with the website.    please goto http://discuss.ardupilot.org/  for community assistance with your problems.
