### ISSUE TITLE
Vagrantfile points to wrong repo for theme

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/ardupilot_wiki#815]
The line here: https://github.com/ArduPilot/ardupilot_wiki/blob/master/Vagrantfile#L22 should be pointing to the ardupilot version of the theme here https://github.com/ArduPilot/sphinx_rtd_theme#read-the-docs-sphinx-theme (not the one in my repo)

**Comment by rmackay9** [comment]
ok, fixed!
