### ISSUE TITLE
AC: ATC_RAT_*  is appear twice in documentation, with different range

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/ardupilot_wiki#829]
see http://ardupilot.org/copter/docs/parameters.html#atc-rat-rll-filt-roll-axis-rate-controller-input-frequency-in-hz

within the page, search for: "ATC_RAT_RLL_FILT"
observe that there are four occurrences, two different range.

**Comment by auturgy** [comment]
This is the result of https://github.com/ArduPilot/ardupilot/issues/6164 where heli and multi param lists are both generated and published as the Copter list. Suggest close one of these issues and link to the other.

**Comment by magicrub** [comment]
As @auturgy said, the problem shows up on the wiki but the fix is on the ardupilot scripts. I'll go ahead and close this in favor of https://github.com/ArduPilot/ardupilot/issues/6164
