### ISSUE TITLE
ADS-B Receiver

### ISSUE THREAD

**Issue by pmshopUSMC** [ArduPilot/ardupilot_wiki#837]
[ADS-B Receiver](http://ardupilot.org/copter/docs/common-ads-b-receiver.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

USA link to product is to the pingUSB ADS-B receiver. 
Not the device with the DF-13 connector
Link provided here:
https://www.unmannedsystemssource.com/shop/atc-devices/pingrx-ads-b-receiver/

**Comment by magicrub** [comment]
Thanks for the note! Btw, next time you can do it yourself if you'd like. At the top right click "Edit on Github" and you can edit right there!

**Comment by magicrub** [comment]
closed, link updated.
