### ISSUE TITLE
ERROR: the following packages/stacks could not have their rosdep keys resolved to system dependencies

### ISSUE THREAD

**Issue by ELSHAIKHI** [ArduPilot/ardupilot_wiki#852]
Hello ,
I am trying to download the Additional Baxter packages for MoveIt, written entirely in C++ (pick and place tutorial) , I stuck with this error could you please update me how to fix it ?

https://github.com/davetcoleman/baxter_cpp

ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
baxter_moveit_scripts: Cannot locate rosdep definition for [baxter_control]
baxter_pick_place: Cannot locate rosdep definition for [baxter_control]

Regards
Thanks in advanced
Hamied ELSHAIKHI

**Comment by Georacer** [comment]
I believe you are asking at the wrong bug tracker. This is the bug tracker for the ArduPilot autopilot firmware, not a Gazebo-generic site.

**Comment by ELSHAIKHI** [comment]
Many thanks for alerting me :)

**Comment by auturgy** [comment]
Closing as per George’s comment. Not directly an ArduPilot issue.
