### ISSUE TITLE
FrSky Telemetry

### ISSUE THREAD

**Issue by kojderek** [ArduPilot/ardupilot_wiki#856]
[FrSky Telemetry](http://ardupilot.org/copter/docs/common-frsky-telemetry.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

Why DIY telemetry cable is connected to Telemetry_2 and CraftTheory Cable is connected to Serial4/5. 
Is there any difference?

**Comment by tomlauzon** [comment]
As you can see  in the table [here](http://ardupilot.org/copter/docs/common-frsky-telemetry.html#frsky-telemetry-configuration-in-mission-planner) FrSky telemetry is available on serials 1-4. It's a matter of user preference. It makes no difference. Having the pics show different options is good in my opinion.

**Comment by tomlauzon** [comment]
Please close the issue if resolved. Thanks

**Comment by OXINARF** [comment]
I think @tomlauzon answered the question and I agree that showing different options is the best - also there are pictures of the C&T cable connected to Telem2 too.
