### ISSUE TITLE
Downloading and Analyzing Data Logs in Mission Planner

### ISSUE THREAD

**Issue by rajputgaurav51** [ArduPilot/ardupilot_wiki#859]
[Downloading and Analyzing Data Logs in Mission Planner](http://ardupilot.org/copter/docs/common-downloading-and-analyzing-data-logs-in-mission-planner.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by hamishwillee** [comment]
Looks like this has been created in error. Closing.
