### ISSUE TITLE
Setting up SITL in Windows

### ISSUE THREAD

**Issue by KedarT** [ArduPilot/ardupilot_wiki#863]
When I try to run a sim_vehicle I am getting this error, can you please help me with the same?
Thank You.

$ python sim_vehicle.py -w -v ArduCopter

  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
SIM_VEHICLE: Killing tasks

**Comment by OXINARF** [comment]
This issues list is to report problems in the wiki. For development questions please post in the forum (http://discuss.ardupilot.org) or ask in Gitter chat (http://gitter.im/ArduPilot/ardupilot). You'll have to provide more information than that, like what OS are you in, if you are following any guide, etc.
