### ISSUE TITLE
Building ArduPilot for Pixhawk/PX4 on Windows with Make

### ISSUE THREAD

**Issue by Imam24** [ArduPilot/ardupilot_wiki#864]
[Building ArduPilot for Pixhawk/PX4 on Windows with Make](http://ardupilot.org/dev/docs/building-px4-with-make.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

Whenever I use the Make command to compile, I keep getting "make' is not recognized as an internal or external command". Any help is appreciated.

Thanks.

**Comment by OXINARF** [comment]
Then you are missing some step, make is definitely included in the Pixhawk Toolchain. Try re-installing it.

**Comment by OXINARF** [comment]
No answer after two months and make is definitely in toolchain, so I'm closing this. Feel free to comment if you still have an issue.
