### ISSUE TITLE
Document usage of first (zero-ith) waypoint as home position

### ISSUE THREAD

**Issue by akorb** [ArduPilot/ardupilot_wiki#867]
The first mission item will be used (and overwritten) as a waypoint containing the home position.

This is a common pitfall, see https://groups.google.com/forum/#!topic/mavlink/SL0oTUJx1fE and https://github.com/ArduPilot/ardupilot/issues/1379 .
To avoid this, this should be mentioned in the documentation. Probably here: http://ardupilot.org/copter/docs/common-planning-a-mission-with-waypoints-and-events.html (Planning a Mission with Waypoints and Events).

This might lead to huge problems. Imagine your first mission item is a takeoff specifying the safe height. You start and instead of rising vertically, it will fly straight to the waypoint given afterwards and there might be an obstacle.

**Comment by magicrub** [comment]
This was fixed via https://github.com/ArduPilot/MissionPlanner/commit/97bdafb3c570fa93bf5aa189b81343a08b7798d9
