### ISSUE TITLE
Update SITL instructions to point to new VM

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/ardupilot_wiki#88]
Update [Setting up SITL using Vagrant](http://dev.ardupilot.com/wiki/simulation-2/sitl-simulator-software-in-the-loop/setting-up-sitl-using-vagrant/) instructions to provide option to use the pre-built image: 

`vagrant init 3drobotics/ardupilot-sitl`

This is much simpler than the ardupilot SITL, but not so useful for developers of ArduPilot itself as does not currently contain provision for updating and rebuilding the environment if this ends up being needed - ideal for DroneKit users though.

**Comment by peterbarker** [comment]
@hamishwillee Pretty sure we don't want to reference this pre-built Vagrant image any more.

Feel free to reopen if I'm wrong :-P
