### ISSUE TITLE
Using SITL for ArduPilot Testing

### ISSUE THREAD

**Issue by HumamHelfawiOptecks** [ArduPilot/ardupilot_wiki#898]
[Using SITL for ArduPilot Testing](http://ardupilot.org/dev/docs/using-sitl-for-ardupilot-testing.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

The link is broken https://raw.githubusercontent.com/ArduPilot/ardupilot/master/Tools/autotest/win_sitl/InstallCygwinAPM.ps1

**Comment by magicrub** [comment]
I don't see that link on that page and the links all look OK on the page they should be on http://ardupilot.org/dev/docs/sitl-native-on-windows.html#sitl-native-on-windows

please specify the URL and surrounding text so we can identify it

**Comment by HumamHelfawiOptecks** [comment]
http://ardupilot.org/dev/docs/sitl-native-on-windows.html#installation-steps

**Comment by OXINARF** [comment]
Fixed by #904
