### ISSUE TITLE
Document MAVLink2 setup

### ISSUE THREAD

**Issue by WickedShell** [ArduPilot/ardupilot_wiki#909]
MAVLink2 setup should be better documented in the wiki, particularly should explain when MAVLink2 is used vs MAVLink1, and document how to setup/clear signing key's with at least MP.

Issue prompted by: https://discuss.ardupilot.org/t/pixhawk-2-1-mavlink2/19904

**Comment by rmackay9** [comment]
I've added a tiny little bit on [Mavlink1 vs Mavlink2 here on the developer wiki](http://ardupilot.org/dev/docs/mavlink-basics.html#mavlink1-vs-mavlink2).

**Comment by Hwurzburg** [comment]
done closoing
