### ISSUE TITLE
Weird text on plane - MAV_CMD_NAV_LOITER_TO_ALT

### ISSUE THREAD

**Issue by juvinski** [ArduPilot/ardupilot_wiki#917]
Hi,

at 
http://ardupilot.org/plane/docs/common-mavlink-mission-command-messages-mav_cmd.html?highlight=mav_cmd_nav_loiter_to_alt#mav-cmd-nav-loiter-to-alt

There is a text I'm thinking is wrong:
Plane
This command enables auto-tuning on Plane.

I think this should be removed.

**Comment by Hwurzburg** [comment]
#2209 fixes
