### ISSUE TITLE
First time setup 

### ISSUE THREAD

**Issue by vinodph123** [ArduPilot/ardupilot_wiki#920]
Hi,

     It is better if you put First time setup like px4 firmware setup they have given the steps for installation of px4.

Regards
Vinod

**Comment by OXINARF** [comment]
@vinodph123 Can you explain better what you want? I don't understand what First Time setup you are referring to, is it installing firmware to a board or installing a dev environment?

**Comment by vinodph123** [comment]
It is about installing a dev environment in host system like in px4 firmware they have provided jmavsim for checking the operations

**Comment by OXINARF** [comment]
We have an extensive developer wiki (http://ardupilot.org/dev/index.html), including guides to build the code in several operating systems. Have you looked at it?

**Comment by peterbarker** [comment]
On Wed, 23 Aug 2017, vinodph123 wrote:

> It is about installing a dev environment in host system like in px4 firmware they have provided jmavsim for checking the operations

We supply a Vagrant virtual machine to get people started quickly.

We have extensive simulation support - look for "sim_vehicle.py" and 
"SITL"

**Comment by OXINARF** [comment]
I'm closing this as I believe we have enough documentation and options for the first time setup.

@vinodph123 If there is something specific you think we can improve, please comment here and we'll try to look at it.
