### ISSUE TITLE
ESC Calibration - Step missing

### ISSUE THREAD

**Issue by fabianpedd** [ArduPilot/ardupilot_wiki#924]
Hi, 

I think there ist one step in the "Typical ESC Calibration" section missing. Instead of:

`The steps for calibration are:`

`- start with the autopilot powered, but with the motor unpowered or propeller removed`
`- switch to MANUAL flight mode`
`- disable the safety switch (if fitted)`
`- move the throttle stick on your transmitter to maximum`
`- add power to the motor`

it should be something along the lines of:

`The steps for calibration are:`

`- start with the autopilot powered, but with the motor unpowered or propeller removed`
`- switch to MANUAL flight mode`
`- disable the safety switch (if fitted)`
**- arm ESC by moving the throttle stick to the lower right corner**
`- move the throttle stick on your transmitter to maximum`
`- add power to the motor`

Otherwise, at least for me, ESC calibration does not work, since there is no PWM output to the ESC. (Using KISS 18A ESC)

Cheers,
Fabian

[ESC Calibration](http://ardupilot.org/plane/docs/guide-esc-calibration.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by auturgy** [comment]
Suggest close.  Arming is relevant to the FC, not the ESC, and isn't required for ESC calibration.  There may be another issue interacting with KISS ESC's (I don't have any to test), but this should not be a general change.
