### ISSUE TITLE
Maxbotic I2C Sonar Rangefinder

### ISSUE THREAD

**Issue by chris669** [ArduPilot/ardupilot_wiki#942]
[Maxbotic I2C Sonar Rangefinder](http://ardupilot.org/copter/docs/common-rangefinder-maxbotixi2c.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

I have a problem with this. When I select 4 in RNGFND_TYPE = “4” (PX4-MaxbotixI2C sonar)
 Maxbotix I2C the value I have selected in the configuration Range Finder page disappear. So where is the right place to select the Sensor type? Seems confusing for me.

**Comment by OXINARF** [comment]
The correct value is 2, thanks for the report.

**Comment by chris669** [comment]
happy to help
