### ISSUE TITLE
SITL Simulator (Software in the Loop)

### ISSUE THREAD

**Issue by FranciscoFabra** [ArduPilot/ardupilot_wiki#953]
[SITL Simulator (Software in the Loop) - heading issue](http://ardupilot.org/dev/docs/sitl-simulator-software-in-the-loop.html) -Possible bug with 90 degrees starting heading.

I am developing multi-UAV simulator based on SITL, and I have detected that, when the initial heading is set to 90 degrees, the UAV is unable to take off after arming motors. The arducopter flight controller refuses to accept the command_long message (result = 4). The simulation progress without issues when using any other value.
Anybody with the same issue?

Using MAVLink v1 msg_command_long:
command = MAV_CMD.MAV_CMD_NAV_TAKEOFF
param7 = altitude (meters)
Message sent when the engines are already armed (ACK result = 0, everything ok).

**Comment by OXINARF** [comment]
This issues list is for problems in the wiki. What you are reporting would be a problem in code, not documentation. For development questions, please post in the forum (http://discuss.ardupilot.org) or ask in Gitter chat (http://gitter.im/ArduPilot/ardupilot) - I'll say that we'll need a list of reproducible steps to check what is happening.
