### ISSUE TITLE
Indoor Flying Guidelines

### ISSUE THREAD

**Issue by chris669** [ArduPilot/ardupilot_wiki#954]
[Indoor Flying Guidelines](http://ardupilot.org/copter/docs/indoor-flying.html) - Possible to implement an INDOOR Flight Mode? Easier than each time disabling GPS, failsafe, etc. thanks. Chris

**Comment by magicrub** [comment]
You've asked for a new feature of the flight code from the wiki page issue tracker. Please post it in the flight code github issue area instead.

https://github.com/ArduPilot/ardupilot/issues/new
