### ISSUE TITLE
Antenna Tracker Wiki needs project information

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/ardupilot_wiki#96]
The wiki needs more material about the project. Minimally this should include an update to the Project News wiki page and some general information about the project roadmap, members, and how you can join.

I can put this together, but we need to discuss first. Assigned to you Randy

**Comment by hamishwillee** [comment]
@rmackay9 Is "additional project information" ever going to happen, or should I just shut this item?

**Comment by gmorph** [comment]
There is no roadmap for AntennaTracker nor specific AntennaTracker members or any need to join anything.  I have added a couple of sentences to where uses can find the link to the support forums and where developers can find the link to the gitter channel on the AntennaTracker landing page.
Thanks, Grant.

**Comment by hamishwillee** [comment]
Works for me :-)
