### ISSUE TITLE
Broken links: Supported AutoPilot Controller Boards

### ISSUE THREAD

**Issue by DawoodTaii** [ArduPilot/ardupilot_wiki#964]
[Supported AutoPilot Controller Boards](http://ardupilot.org/dev/docs/supported-autopilot-controller-boards.html) -

A lot of links on this page is broken specially all links under 
http://firmware.ardupilot.org/downloads/wiki/pdf_guides/

I couldn't find alternative links for them. I think maybe pdf_guides directory is dropped by mistake or server error, may be it can be recovered?

**Comment by DawoodTaii** [comment]
Also all links under auav.com is broken, the whole old website is taken down.

**Comment by auturgy** [comment]
Thanks for letting us know!  Could you have a go at fixing these, and putting a comment linking a pull request in here?  You'll find an "edit on github" button near the top right had side of the page.

**Comment by hamishwillee** [comment]
@auturgy The PDF guides were hosted on the firmware server. When uploaded those links work, so has the firmware server been moved. @jpkh should know.

**Comment by auturgy** [comment]
@hamishwillee the links to the pdf guides themselves are broken, as are almost every hyperlink within the pdf's.  Would be great if @DawoodTaii could have a go at fixing!

**Comment by OXINARF** [comment]
The correct link would be http://download.ardupilot.org/downloads/wiki/pdf_guides/ but even there a lot of PDFs are missing.

Like many pages in the dev section, this one also needs to be redone.

**Comment by hamishwillee** [comment]
@OXINARF @auturgy Just FYI, it is possible to use sphinx to build with a link checker option. Might be worth doing that soon and doing a global attempt to chase broken links. The last time this was done was early last year.

**Comment by Hwurzburg** [comment]
pdfs have been removed...closing
