### ISSUE TITLE
RC Input and Output

### ISSUE THREAD

**Issue by auturgy** [ArduPilot/ardupilot_wiki#965]
[RC Input and Output](http://ardupilot.org/dev/docs/learning-ardupilot-rc-input-output.html)
Just a note to flag that we need to update this.

**Comment by auturgy** [comment]
Also https://github.com/ArduPilot/ardupilot_wiki/issues/1064

**Comment by Hwurzburg** [comment]
addressed by #2068

**Comment by Hwurzburg** [comment]
closing
