### ISSUE TITLE
OUTPUT 1 constantly fluctuating for tank type rover configuration. PX4v2 0046001C 3136510A 34313630, PX4: 56c0c696 NuttX: be6ff61a, APM:Rover v3.1.2 (0fa522b8)

### ISSUE THREAD

**Issue by deepparikh** [ArduPilot/ardupilot_wiki#968]
[Skid Steer Parameter Tuning](http://ardupilot.org/rover/docs/skid-steer-parameter-tuning.html) - OUTPUT 3 is following the Input 3 but OUTPUT 1 is constantly fluctuating between INPUT 1 and 1000.
SKID_STEER_IN - 1 
SKID_STEER_OUT-0

**Comment by magicrub** [comment]
Hi @deepparikh . Seems you've posted a help question in the Wiki edit list so I'm closing. Please re-post in the forums at http://discuss.ardupilot.org
