### ISSUE TITLE
License (GPLv3)

### ISSUE THREAD

**Issue by auturgy** [ArduPilot/ardupilot_wiki#974]
[License (GPLv3)](http://ardupilot.org/dev/docs/license-gplv3.html) - Fix contact email (note to remind me).

**Comment by magicrub** [comment]
Nice catch, we'll find a new contact and update it. Thank you!

**Comment by auturgy** [comment]
@CraigElder suggestions? Should this link to the contacts page, or is there a particular email address we can use?
I'd prefer email (as would people/companies wanting to contact us in this regard), but you'd probably be the one at the end of it, so your call I think.

**Comment by CraigElder** [comment]
I have been meaning to fix this too

![image](https://user-images.githubusercontent.com/1746862/31688839-d25ab9dc-b34a-11e7-9cd7-867af9c8a7df.png)

**Comment by CraigElder** [comment]
Updated https://github.com/ArduPilot/ardupilot_wiki/commit/9f2dd346cd8b7c47c2a23afb72c084ca97f29d05
