### ISSUE TITLE
Submitting Patches Back to Master - Out of date link to mailing list

### ISSUE THREAD

**Issue by legonigel** [ArduPilot/ardupilot_wiki#976]
[Submitting Patches Back to Master](http://ardupilot.org/dev/docs/submitting-patches-back-to-master.html#Submitting-pull-requests) - At the end of the page, step 7 of Submitting pull requests, it says to post on the mailing list drones-discuss. It should now point developers to the correct area of the discuss and how to post a pull request on discuss.ardupilot.org

**Comment by auturgy** [comment]
Devs are notified of PR's via email automatically, so I removed the email link.  Most discussion re PR's occurs in github itself, as comments on the PR, which I think is fine.

**Comment by legonigel** [comment]
That sounds better. Thanks for updating that.
