### ISSUE TITLE
Plane: Note that downgrading from 3.8 to a previous version will lose any RC changes that were done

### ISSUE THREAD

**Issue by WickedShell** [ArduPilot/ardupilot_wiki#999]
http://ardupilot.org/plane/docs/plane-3-7-to-3-8-migration.html should note that if you downgrade from Plane 3.8 to an earlier version of plane then any changes that were made to the RC_* parameters will be lost in the earlier version, and that upgrading back to 3.8 will not copy over any param changes that happened in the earlier version. This is only an issue if the user decides to downgrade. See https://github.com/ArduPilot/ardupilot/issues/6522

**Comment by marcmerlin** [comment]
further improved the warning, PR sent.
